### PR TITLE
clang-tidy: convert loops to range based

### PR DESCRIPTION
**Pull request by neheb**
Found with modernize-loop-convert

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Manually converted several C arrays to std::array to get the various methods.

A lot of the changes are dominated by git clang-format.

### CODE REVIEW

**Comment by piponazo** [comment]
Thanks @neheb again for this contribution. 

Up to now, I have been accepting your PRs without much thinking because most of the changes were done automatically by clang-tidy. I know by experience that the tool works very well and you can almost trust in those changes blindly (if the build & tests pass).

However, I noticed that there are some manual changes that would require a more careful review.

Would it be too much work to separate the changes in 2 commits (one with the clang-tidy changes  and other with the manual ones) ?

**Comment by neheb** [comment]
Split into two commits.

**Comment by neheb** [comment]
All green. nice.

**Comment by neheb** [comment]
No longer green after the last commit :(.

**Review by piponazo — APPROVED** [review]
Really good contribution, thank you! 👏 

I am really surprised by some of the automatic transformations done by clang-tidy ... I looks like it is more intelligent now than when I tried out few years ago 😉 .

Do not worry about the red CI jobs, they were random failures in the step of installing dependencies. Probably due to some flaw in network

**Comment by neheb** [comment]
I used both clang-tidy 8 and 10. 8 seems more intelligent. Both of them found similar loops. Yet they do miss a fair amount. Note the manual ones I did that it did not find. I'm sure there are more.

**Pull request merged**
