### PR TITLE
Complete DNG 1.4 spec support (0.27 -> master)

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
These tags are missing, first commit here to see how things work.

### CODE REVIEW

**Comment by clanmills** [comment]
Thank You for the PR.  This looks OK to me.  Do you have test images which we can add to the test suite?  I'll add the tests for you to save you a chore if you provide test images.  I extract the metadata with the command `$ exiv2 -ea --force --verbose image` and only add the `.exv` file to the test suite to save space in the repos.

Your timing is perfect.  I'm working on Exiv2 v0.27.3 at the moment.  RC1 is on-track to ship on schedule on 2020-04-30 and GM is scheduled for 2020-06-30.

**Comment by clanmills** [comment]
Thanks for sending Leica-Q2-pr1161.exv.  Two comments:

1) The tags Adding DefaultUserCrop and BaselineExposureOffset are not in the .exv file.  There must be some DNG specific magic that causes those tags to be respected.  So, `Leica-Q2-pr1161.exv ` is useless.  Please remove it from the PR.  However, I want to see this working before I add it to the code base.  Can you send me a DNG please.  Don't put it in the PR, simply attach it, or put it on a file sharing service such as dropbox.

I've run exiftool on the .exv and he doesn't see anything concerning Crop or Offset:
```
$ exiftool ../test/data/Leica-Q2-pr1161.exv | grep -i -e offset -i -e crop
Offset Time                     : +01:00
Offset Time Original            : +01:00
Offset Time Digitized           : +01:00
Warning                         : [minor] Possibly incorrect maker notes offsets (fix by -1534?)
$ 
```

I hope we're not heading into a major investigation here into DNG metadata.  I didn't write Exiv2, so this kind of investigation can be very time consuming.  I wouldn't delay RC1 to investigate this issue.

2) Please remove the blank line.

**Comment by boardhead** [comment]
The DefaultUserCrop tag in a Q2 DNG is in the SubIFD, so it probably wouldn't make it to the EXV file.  My Q2 sample doesn't contain BaseLineExposureOffset.

But it would make sense to update to the current DNG specification rather than adding just two of the new tags.

**Comment by clanmills** [comment]
Thanks @boardhead I suspected something like that and I've never been into that code.  It's probably nothing amazing, however perhaps it's not as simple as @jenshannoschwalm believes.  A test file with those tags is essential to investigate further.

I'm going well on Exiv2 v0.27.3.  RC1 will be ready by 2020-04-30.  I'm working hard and enjoying it.  For sure, I won't delay RC1 to include this PR.

**Comment by jenshannoschwalm** [comment]
I am absolutely new in this field so i tried with something "simple" to get an idea how this repo works.
 The tags this pr tackles are just missing from those implemented for 1.4 specs - and i have an example.

https://drive.google.com/file/d/1raSrURkvu5z2S1TdEt9npAcsSPF7pi8a/view?usp=sharing

For 1.5 i have no examples yet, standard is pretty new ...

**Comment by boardhead** [comment]
I think you will find it difficult to find samples for all of the possible DNG tags, so for simple tags like this I would suggest going ahead and implementing them based on the specification only.  (I suppose you use ExifTool to generate a sample with these tags, but this would be of questionable validity since I didn't have samples for many DNG tags when I added support for them to ExifTool.)

**Comment by jenshannoschwalm** [comment]
In fact i used only the specs. For the user crop i have been using this for long in darktable by searching for `Exif.SubImage1.0xc7b5` and it has been working perfectly (at leat no user complained about it)

I would add the 1.5 tags by specs in another pr?

Also - if i can get your advice? I know that Leica Makerstuff is sort of a mess and when reading exiftool sources this impression is supported.

Would the exiv2 maintainers accept just a minimal support like Exif.Subimage1.Leica8 or alike?

**Comment by clanmills** [comment]
I'm going to defer this for v0.27.4.

@jenshannoschwalm Thank for your your enthusiastic contribution to Exiv2.  If you'd like to participate in the Exiv2 v0.27.3 project, here are the remaining tasks.  If you'd like to volunteer for something, please let me know and I'll mentor you.  https://github.com/Exiv2/exiv2/milestone/5

Of, if you'd like to help with Exiv2 in general, again I will help if you indicate your interest and expertise.

**Comment by boardhead** [comment]
Yes, Leica maker notes are a problem: https://exiftool.org/idiosyncracies.html#Leica

But the DNG tags are better behaved.

**Comment by kmilos** [comment]
Yeah, I saw that earlier PR, but decided to not refer to it ATM - I kept this one purposefully contained to Chapter 3 "Restrictions and Extensions to Existing TIFF Tags" of the spec because of the low impact.

I guess we could create a separate Feature Request for completing DNG support where we can track all of these related PRs and discuss what test are needed for the suite? I suspect there might a few more tags missing, not just those two...

**Comment by kmilos** [comment]
Here's a list of missing DNG tags in general as of 0.27.3:

* DNG 1.2 is incomplete:

0xc6f5 ExtraCameraProfiles

* DNG 1.3 is complete

* DNG 1.4 is absent:

0xc791 OriginalDefaultFinalSize
0xc792 OriginalBestQualityFinalSize
0xc793 OriginalDefaultCropSize
0xc7a3 ProfileHueSatMapEncoding
0xc7a4 ProfileLookTableEncoding
0xc7a5 BaselineExposureOffset
0xc7a6 DefaultBlackRender
0xc7a7 NewRawImageDigest
0xc7a8 RawToPreviewGain
0xc7b5 DefaultUserCrop

* DNG 1.5 is absent:

0xc7e9 DepthFormat
0xc7ea DepthNear
0xc7eb DepthFar
0xc7ec DepthUnits
0xc7ed DepthMeasureType
0xc7ee EnhanceParams

**Comment by clanmills** [comment]
This seems fine to me.  Two questions:

1. Does this complete DNG 1.5, or are there tags to be done?
2. Phil says there a problem with some Leica tags:  https://exiftool.org/idiosyncracies.html#Leica

**Comment by kmilos** [comment]
This is a first step to complete 1.4 level support only that @jenshannoschwalm started. I was planning separate PR for 1.5 if somebody else doesn't beat me to it. ;) 

I don't think the Leica Makernote idiosyncracies impact this PR (or the DNG 1.5 level), we're just implementing the spec to the letter here...

**Review by clanmills — APPROVED** [review]
Thank You to both @jenshannoschwalm and @kmilos for working on this.  Please merge when the CI goes green.  I've successfully built/tested this on macOS.

**Comment by clanmills** [comment]
I believe that completes your list for **DNG 1.4**.

BaselineExposureOffset
DefaultBlackRender
DefaultUserCrop
NewRawImageDigest
OriginalBestQualityFinalSize
OriginalDefaultCropSize
OriginalDefaultFinalSize
ProfileHueSatMapEncoding
ProfileLookTableEncoding
RawToPreviewGain

We can deal with the following **DNG 1.5** in future:

0xc7e9 DepthFormat
0xc7ea DepthNear
0xc7eb DepthFar
0xc7ec DepthUnits
0xc7ed DepthMeasureType
0xc7ee EnhanceParams

From **DNG 1.2** we still have Camera Profile IFD parsing to be done.  I'm currently working on #1402 which involves parsing a tiffIfd array (tag type 13).  The solution to #1402 will work for both FujiRAF and DNG 1.2 Camera Profile IFDs.  A very challenging extension to the architecture of TiffVisitor.  The code tvisitor.cpp (in my book) achieve this and I'm working to find out how to achieve this in Exiv2/TiffVisitor.

tiff

**Review by kmilos — APPROVED** [review]

**Pull request merged**
