### PR TITLE
Update CI actions

### PR DESCRIPTION
**Pull request by kmilos**
Most updated to node16 as node 12 is going EOL in April

### CODE REVIEW

**Review by piponazo — APPROVED** [review]
LGTM! Thanks

**Comment by kmilos** [comment]
Thanks for the quick reviews!

**Comment by postscript-dev** [comment]
@kmilos:
I noticed that the [Exiv2 nightly releases](https://github.com/Exiv2/exiv2/releases) stopped being published after this PR was merged. The [release workflow](https://github.com/Exiv2/exiv2/actions/runs/2406877884) shows that there are problems in the `Build Linux Release` and `Build Windows Release` sections but the `Build macOS Release` works well.

I think that the changes made in this PR are justified but perhaps there is an unintended side-effect to them?

**Comment by kmilos** [comment]
No idea if these are indeed related. From the list, it doesn't look like those releases are/were regular/scheduled, and certainly not "nightly"...

**Comment by postscript-dev** [comment]
@kmilos:
Thanks for looking at this, GitHub actions are not my area of expertise. I suggested the link between the problems and the PR, only because the dates matched. The real cause could be something else.

**Pull request merged**
