### PR TITLE
Fix/add exceptions for BMFF based files

### PR DESCRIPTION
**Pull request by postscript-dev**

### CODE REVIEW

**Review by piponazo — DISMISSED** [review]
Fine for me to change the exception type 👍

**Comment by postscript-dev** [comment]
@piponazo 
I have also added exceptions when setting `ExifData`, `IptcData` and `XmpData` as we don't support this in BMFF files. Do I need to add tests to demonstrate this or are you satisfied that the PR is simple enough to approve?

**Review by kmilos — APPROVED** [review]
LGTM

**Comment by kmilos** [comment]
Please backport to 0.27-maintenance as well.

**Comment by 1div0** [comment]
Gr8! Thank You so much.

**Pull request merged**
