### PR TITLE
v0.27.2

### PR DESCRIPTION
**Pull request by clanmills**
Essential (documentation) changes for v0.27.2

### CODE REVIEW

**Comment by D4N** [comment]
LGTM, are you planning on adding additional changes @clanmills?

**Comment by clanmills** [comment]
I hope to have no further changes.  However  let's leave this as WIP for another week to see what appears.Robinhttps://clanmills.comOn 4 Jul 2019 23:05, D4N <notifications@github.com> wrote:LGTM, are you planning on adding additional changes @clanmills?

**Comment by clanmills** [comment]
I've spoken to @kevinbackhouse and he'd like to see a couple of security fixes added to v0.27.2.

So, I propose that we have 0.27.2.3 (0.27.2 RC3) which I'll create on Sunday evening (2019-07-14).

The additions for v0.27.2.3 are:
#944 and #946. 
#938 is a low-risk change (however, I'll also have to update README.md)
#922 (cross-compiling) is pure documentation

If you have other changes, please merge them onto 0.27-maintenance by Sunday afternoon and set the issue target = 0.27.2.

I haven't studied the libFuzzer code.  It smells great.  Let's hold that back for 0.27.3 (scheduled 2019-09-30).

**Comment by D4N** [comment]
Robin Mills <notifications@github.com> writes:

> I've spoken to @kevinbackhouse and he'd like to see a couple of security fixes added to v0.27.2.
>
> So, I propose that we have 0.27.2.3 (0.27.2 RC3) which I'll create on Sunday evening (2019-07-14).
>
> The additions for v0.27.2.3 are:
> #944 and #946. 
> #938 is a low-risk change (however, I'll also have to update README.md)
> #922 (cross-compiling) is pure documentation
>
> If you have other changes, please merge them onto 0.27-maintenance by Sunday afternoon and set the issue target = 0.27.2.
>
> I haven't studied the libFuzzer code.  It smells great.  Let's hold
> that back for 0.27.3 (scheduled 2019-09-30).

The libfuzzer code should go into master only.

**Comment by clanmills** [comment]
I'll reopen this PR and update it for v0.27.2.  Still WIP.  I'll ask for review/merge next week.

**Comment by clanmills** [comment]
@piponazo  I think this is v0.27.2 (I hope it is 0.27.2).  Can you review/approve/merge, please?  I hope to publish this tomorrow (2019-07-29).

I'm not too sure why it's conflicted.  I want the versions in this PR in the release.

**Review by piponazo — DISMISSED** [review]

**Review by piponazo — APPROVED** [review]

**Comment by clanmills** [comment]
Thanks for dealing with this, Luis.  I'm doing to builds now and expect to release 0.27.2 this evening.

**Pull request merged**
