### PR TITLE
optimize toString slightly

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
Hmmm after talking with ChatGPT, this is a bad idea on C++11. Wonder if we should remove if constexpr from public headers.

**Review by kmilos — DISMISSED** [review]

**Review by kevinbackhouse — DISMISSED** [review]

**Comment by neheb** [comment]
Updated to remove if constexpr.

@kmilos I remember you saying there was some issue. Is it still present?

**Comment by kmilos** [comment]
> Updated to remove if constexpr.
> 
> @kmilos I remember you saying there was some issue. Is it still present?

I'll check. You still have it in types.hpp though...

**Comment by neheb** [comment]
Needs some work to compile properly. I'll check later.

The remaining one is in a big function. Doesn't make much sense to get rid of it there.

**Comment by neheb** [comment]
ping @kmilos

**Review by kmilos — APPROVED** [review]

**Comment by neheb** [comment]
@kmilos the headers should be kept C++11 compatible in any case. As mentioned earlier, the if constexpr stuff should also be removed.

**Comment by neheb** [comment]
@Mergifyio backport 0.28.x

**Pull request merged**
