### PR TITLE
Sony2010e support

### PR DESCRIPTION
**Pull request by sridharb1**

### CODE REVIEW

**Review by clanmills — COMMENTED** [review]
This looks good @sridharb1 We've done it.  (clap on the back).

A couple of comments:
1) I am surprised by the EXV_USE_SSH and EXV_USE_CURL changes.  We will deprecate SSH support in v0.28.  For sure if `#ifdef` and `#if foo == 1` are an issue, the CI or the build server will get into trouble.  So, I'll accept your code.

2) You'll remember we had to tweak `sony2010eSelector()` as Clang/macOS doesn't accept initialisers on `const std::set<std::string> s2010eModels;`
```
		const char* models[] = { "SLT-A58", "SLT-A99", "ILCE-3000", "ILCE-3500", "NEX-3N", "NEX-5R", "NEX-5T", "NEX-6", "VG30E", "VG900",
 			"DSC-RX100", "DSC-RX1", "DSC-RX1R", "DSC-HX300", "DSC-HX50V", "DSC-TX30", "DSC-WX60", "DSC-WX200", "DSC-WX300" };
 		std::set<std::string> s2010eModels;
 		for (size_t i = 0; i < EXV_COUNTOF(models); i++) {
 			s2010eModels.insert(models[i]);
 		}
 		std::string model = getExifModel(pRoot);
 		int idx = -1;
 		if (s2010eModels.find(model) != s2010eModels.end()) {
 			idx = 0;
 		}
 		return idx;
```

I'm going out for a run.  Can you modify the PR and I'll approve/pull/merge it when you're done.

**Comment by clanmills** [comment]
One more comment @sridharb1

If you work directly in the Exiv2 repos, I can modify your PR.  So in this case, I would have *tweaked* `sony2010eSelector()` in your branch, committed it, tested, merged, tested and done!

**Comment by sridharb1** [comment]
Thanks, indeed, I had forgotten about the clang problem. Possibly a newer version of the compiler supports the syntax. But, that can be done another day.

I have not been able to create a new pull request with these changes for some reason, sorry. Please go ahead with this change in this file.

**Comment by clanmills** [comment]
@sridharb1 You should be able to edit the file, commit the change and push.  Maybe you have to set the tracking branch or some other git magic.  I'll open a new PR with your changes.  One of Team Exiv2's GitHub guru's can "tweak it" to ensure you get the credit.

I'm surprised that clang doesn't support this yet.  My laptop is kept up to date by Apple.
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.29)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E266
$ 
```

You'll notice the OS name according to `sw_vers` is **Mac OS X**.  Nobody's told Apple Engineering that the product's now called **macOS**.  I updated all our documentation and website for v0.27.3 about that yesterday.  #1117 (a software engineer's work is never done).

**Pull request closed without merging**
