### PR TITLE
Correct the output of exiv2-test

### PR DESCRIPTION
**Pull request by LeoHsiao1**
The PR is to solve issue #1357 .

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
Excellent work, Mr Lion @LeoHsiao1

**Comment by clanmills** [comment]
One comment.  Can you work directly in GitHub.com/exiv2/exiv2 in future.  It more convenient for everybody.

**Comment by LeoHsiao1** [comment]
I just gave it a try. I found that I do not have write permission for 0.27-maintenance, so I can only use the following method:
- Create a temporary branch `A` in GitHub.com/exiv2/exiv2, then merge it to 0.27-Maintenance. But then I have to delete branch `A`.
- Create a a temporary branch `A` in my repository, then merge it to 0.27-Maintenance.
I prefer the second method. Otherwise I sometimes inadvertently commit the wrong commit, contaminating GitHub.com/exiv2/exiv2.

**Comment by clanmills** [comment]
Here's my total knowledge of git:

GitIdiotCard

You have write permission.  Would you like to screen share on Zoom and we'll get this fixed.

**Comment by clanmills** [comment]
https://us02web.zoom.us/j/83835287420?pwd=bDJKUVh1Z25LSTZzZ2F4eVo5aGg5QT09

**Comment by LeoHsiao1** [comment]
I think the more important problem is that directly writing `0.27-maintenance` is easy to make mistakes. I worry about my carelessness.
For example, in this PR, I committed the wrong content and then recommitted it by `git push -f`.
```
LeoHsiao1 force-pushed the LeoHsiao1:0.27-maintenance branch from 65a2c24 to 068a80c 2 hours ago
```

**Comment by clanmills** [comment]
You can't write directly into 0.27-maintenance.  You can only write into a branch and submit a PR.  You won't make mistakes.  The system does allow you.  Luis has checked the "must review" option.  So, a PR can only been merged when it has been approved.  You can't approve your own PR.

Never use `git push -f` on exiv2.  Just don't!  If you're in trouble, let me help.  Never force push.

**Comment by clanmills** [comment]
I use SmartGit gui for most of the stuff I do.  I use that little card when I'm ready to submit a PR.

I work all the time in 0.27-maintenance.  When I'm ready to create a PR, I stash the changes, create the branch, apply the stash, commit, `push origin` and create the PR in the browser.  Then I set the tracked branch in the GUI.  If I need to change the PR, I update it and commit the change.

I checkout 0.27-maintenance to continue with the next task.  I only work in a branch if I intend to modify an open PR.

I never work in 'master'.

**Pull request merged**
