### PR TITLE
samples/xmpprint.cpp: Fix typos

### PR DESCRIPTION
**Pull request by lemniscati**
Fix typos in comments.

### CODE REVIEW

**Comment by clanmills** [comment]
Thanks for this PR.  I maintain the 0.27-maintenance branch and I will happy to approve/merge this into 0.27-maintenance.  Can you update the base, or submit a new PR on 0.27-maintenance.

**Comment by lemniscati** [comment]
@clanmills I've submitted a new PR #1444 on  Exiv2:0.27-maintenance :).
Thank you for maintaining.

**Comment by piponazo** [comment]
Since the changes were merge in 0.27-maintenance with PR #1444 , I'll close this PR.

In the future we will branch out from 0-27-maintenance.

**Comment by clanmills** [comment]
Thanks, Luis.  I was really delighted that you attended the meeting last weekend.  Exiv2 is in the news.  Maybe a new maintainer will volunteer.  Maybe Exiv2 will join KDE.  We'll see.  https://www.phoronix.com/scan.php?page=news_item&px=Exiv2-Looks-To-KDE

I hope folks involved with Exiv2 will have a weekend together in Bavaria in September.  I hope you can join us.  It's pointless to make plans with the C-19 situation.  I'll let you know when we get serious about planning this.

**Pull request closed without merging**
