### PR TITLE
Include HEIC type explicitly

### PR DESCRIPTION
**Pull request by kmilos**
HEIC has a dedicated MIME type, see https://www.iana.org/assignments/media-types/media-types.xhtml#image

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
I'm happy with this, Milos.

Can you set Milestone v0.27.4 on new issues.  I monitor the milestone as I push towards RC1.  Almost missed this one.

**Comment by clanmills** [comment]
@1div0 Do you have an opinion about the mime-type (or anything else in this PR)?

I think I'd like to add a test for the mime type.  

```bash
557 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 ../test/data/*.heic 2>/dev/null | grep -i mime
../test/data/2021-02-13-1929.heic MIME type       : image/heif
../test/data/IMG_3578.heic MIME type       : image/heif
../test/data/Stonehenge.heic MIME type       : image/heif
../test/data/heic.heic MIME type       : image/generic
558 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 ../test/data/*.HIF 2>/dev/null | grep -i mime
../test/data/Canon.HIF MIME type       : image/generic
../test/data/Sony.HIF MIME type       : image/generic
559 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 ../test/data/*.avif 2>/dev/null | grep -i mime
../test/data/avif.avif MIME type       : image/avif
../test/data/avif_exif_xmp.avif MIME type       : image/avif
../test/data/avif_metadata2.avif MIME type       : image/avif
560 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

**Comment by clanmills** [comment]
Here's another oddity.  Some files have 'Image size' 0 x 0.  Could be correct of course.

```bash
566 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 ../test/data/*.avif 2>/dev/null | grep 'Image size'
../test/data/avif.avif Image size      : 0 x 0
../test/data/avif_exif_xmp.avif Image size      : 0 x 0
../test/data/avif_metadata2.avif Image size      : 0 x 0
567 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 ../test/data/*.HIF 2>/dev/null | grep 'Image size'
../test/data/Canon.HIF Image size      : 2400 x 1600
../test/data/Sony.HIF Image size      : 8640 x 5760
568 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 ../test/data/*.heic 2>/dev/null | grep 'Image size'
../test/data/2021-02-13-1929.heic Image size      : 4032 x 3024
../test/data/IMG_3578.heic Image size      : 4032 x 3024
../test/data/Stonehenge.heic Image size      : 6000 x 4000
../test/data/heic.heic Image size      : 0 x 0
569 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

**Comment by kmilos** [comment]
> I think I'd like to add a test for the mime type.

This is IMHO some way off as it seems there's still some future work to be done on `ftyp` parsing, [it doesn't look like using just the major brand is enough](https://github.com/strukturag/libheif/issues/83).

The three files that return `image/generic` above have e.g. `mif1` (w/ `heic` as minor version) or `heix` (10-bit heic), and should be identified as image/heic... Then we have all the sequence variants as well...

**Comment by clanmills** [comment]
I'm not sure I have understood your message.  Can you fix this and I will update the test suite?

```
575 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ tvisitor -pR ../test/data/Canon.HIF ../test/data/Stonehenge.heic ../test/data/avif.avif | grep ftyp
       0 |       32 | ftyp |      | heix____mif1heixmiaf 104 101 105 120 0 0 0 0 109 105 102 49 104 101 105 120 109 105 97 102
       0 |       24 | ftyp |      | heic____heicmif1 104 101 105 99 0 0 0 0 104 101 105 99 109 105 102 49
       0 |       32 | ftyp |      | avif____mif1avifmiaf 97 118 105 102 0 0 0 0 109 105 102 49 97 118 105 102 109 105 97 102
576 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

I suspect that the output of the command `$ exiv2 foo.ext` is something that Andreas put in the code at the start of the project.  It's a chaotic mix of stuff, most of which has nothing to do with Exiv2/IPTC/XMP/ICC.  For example, it has file size and mime/type.  Why?  Nobody knows.  However, if we say "we're getting out of mime matters", somebody will report a bug.

```bash
569 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ exiv2 ../test/data/Canon.HIF
File name       : ../test/data/Canon.HIF
File size       : 1253392 Bytes
MIME type       : image/generic
Image size      : 2400 x 1600
Thumbnail       : None
Camera make     : Canon
Camera model    : Canon EOS R5
Image timestamp : 2021:02:18 19:54:47
File number     : 
Exposure time   : 1/1000 s
Aperture        : F4
Exposure bias   : 0 EV
Flash           : No flash
Flash bias      : 0 EV
Focal length    : 24.0 mm
Subject distance: 0 m
ISO speed       : 100
Exposure mode   : Manual
Metering mode   : Multi-segment
Macro mode      : Off
Image quality   : Fine
White balance   : Auto
Copyright       : 
Exif comment    : 

570 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

**Comment by kmilos** [comment]
> Can you fix this and I will update the test suite?

I'd rather we merged this and open a separate issue for overall bmff mime parsing improvement.

**Comment by clanmills** [comment]
I agree.  Let's not get stuck down the mine shaft.  It's a fringe feature that should have never been added.

**Pull request merged**
