### PR TITLE
libINIReader depends on libinih, the order is important when these libraries are static libraries

### LINKED ISSUE #2965: cmake出错了
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: ../lib/libexiv2.so.0.28.2: undefined reference to `ini_parse_string'
/opt/aarch64/KPGCC/gcc-10.3.1-2023.12-aarch64-linux/bin/../lib64/gcc/aarch64-linux-gnu/10.3.1/../../../../aarch64-linux-gnu/bin/ld: ../lib/libexiv2.so.0.28.2: undefined reference to `ini_parse'

cmake 3.25.0

### PR DESCRIPTION
**Pull request by leleliu008**
close #2965

### CODE REVIEW

**Comment by leleliu008** [comment]
> Thanks. Have you maybe tried linking just w/ libINIReader?

No. just linking `libINIReader` would arise undefiend symbol when libINIReader is `libINIReader.a`

**Comment by leleliu008** [comment]
> inih



> I meant just `inih::inireader`... That target should already imply the `inih::libinih` one, so we don't need both, no? Then the problem of ordering simply goes away...

No. please read https://github.com/Exiv2/exiv2/blob/main/cmake/Findinih.cmake

**Comment by leleliu008** [comment]
https://github.com/benhoyt/inih use meson build system. It doesn't install cmake module file but install .pc files.

**Comment by neheb** [comment]
Right.

/me doesn't understand cmake files. Or any advantages over pkgconfig.

**Review by kmilos — APPROVED** [review]
Let's maybe merge this tweak for now, and handle Findinih.cmake later eventually. Thanks.

**Pull request merged**
