### PR TITLE
0.27 fix620

### PR DESCRIPTION
**Pull request by clanmills**

### CODE REVIEW

**Comment by clanmills** [comment]
@D4N. Dan, @cryptomilk has helped me to submit this.  It's a simple change - we're removing the dead tree `contrib/organise/work`.

**Comment by piponazo** [comment]
I was taking right now a look into the directory to cleanup things and I reached that folder too. Are the rest of files in that folder used at all ? It looks like we could throw away the full folder ...

**Comment by clanmills** [comment]
The contrib/organize/work tree should never have been there.

Let's keep the files in contrib/organize/.  I dealt with a query on Redmine concerning organize about 3 years ago.  Somebody might use it.  It's not in samples because it requires boost and we didn't want to add boost to the build prerequisites.

**Comment by piponazo** [comment]
Thanks for telling us the history about these files.

Now my question is: why do you want to remove just one file from that folder, which actually contains most of the code of the sample. IMHO the two possible actions to take here are:

1. Delete the full folder. That code has not been compiled in a while and it would take an effort to make it compile. Anyways, it is still available in old branches of Exiv2 (0.26, 0.27.0). 
2. Do not delete only one file. If we do that, we move to even a worse situation. We would have a sample application without its main function ...

**Comment by clanmills** [comment]
There seems to a mis-understanding. Here's what I see:
```
725 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ find . -name "organ*.cpp" -exec ls -l {} \;
-rw-r--r--+ 1 rmills  staff  29751  1 Mar 16:38 ./contrib/organize/organize.cpp
-rw-r--r--+ 1 rmills  staff  0  1 Mar 16:38 ./contrib/organize/work/exiv2/contrib/organize/organize.cpp
726 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $
```
To code is in contrib/organize/organize.cpp and I intended to keep it.

There's a erroneous/dead tree contrib/organize/work/exiv2/contrib/organize/organize.cpp that I intended to remove.  That tree contains a single file of zero length and shouldn't be there.

However, if you prefer to remove contrib/organize, I'm fine with that.

**Comment by piponazo** [comment]
Ohhhh! I see now. Sorry for the noise. 

We can discuss in the future about removing the other folder or not 😉

**Review by piponazo — APPROVED** [review]

**Review by D4N — APPROVED** [review]
LGTM!

Thanks for this change @clanmills

**Comment by D4N** [comment]
Ok, there's something really odd with this PR, Travis hasn't received the correct payload and won't run the build. Same apparently with appveyor. @piponazo Can we force merge this? This PR doesn't imho need a CI run.

**Comment by piponazo** [comment]
Sure, I will take care of it.

**Pull request merged**
