### PR TITLE
Fix out of buffer access in #1530

### PR DESCRIPTION
**Pull request by pydera**

### CODE REVIEW

**Review by clanmills — COMMENTED** [review]
That's interesting matter about 
```
// FIXME. Special case. the real box size is given in another place.
```
I know that bmffimage.cpp (which Peter and I wrote) deals with that correctly.  When I saw that, I opened this:  #1522.  I think I know who wrote jp2image.cpp.  All of that guys code is loose.  You can't ignore a feature like that in the standard.

I'll review your changes after dinner.

**Comment by clanmills** [comment]
@pydera.  I'm going to grant you write-access to exiv2/exiv2.git, because it's much easier for me to see what's been changed (and I can modify the PR if necessary).

Can you submit a different PR for each issue - again it's easier to work that way.

**jp2image.cpp2**

If you encounter box.length == 1 (in readMetadata()), I think you should `throw Error(kerCorruptedMetadata);` as we cannot safely navigate that file without reading the length (which I think is the next uint64_t) in the file.  I know we handle that correctly in bmffimage.cpp because it was used in a test file.  If readMetadata() throws, you can never arrive in writeMetadata(), but it's probably sensible to throw there also.

There's a function `printStructure()` that might may require similar treatment.

`box.length < 8` should never occur.  We should throw.

jp2
 
**crwimage.cpp**

Your proposal looks fine to me.  I'm surprised by this.  I thought Andreas wrote that code and his code is generally very solid and safe.

A part of my book that is not complete is to finish dealing with the CRW Format (both the text and associated code in tvisitor.cpp).  Phil Harvey (or ExifTool) has written excellent documentation about CRW and it's on his web site.

About submitting PRs.  Here's my total knowledge of git:

GitIdiotCard

**Review by clanmills — COMMENTED** [review]
A comment about size_t, uint32_t, uint64_t and class BasicIo.  That code was written for 32 bit linux.  When we started to support 64 bit builds, it was "kind of" converted to 64 bit.  It's not good.  We need to test Exiv2 with HUGE files.  This matter is discussed in my book.

One of the issues for v1.00 is BigTiff (64 bit Tiff).  BigTiff doesn't require HUGE files.  However, we should test that BasicIo does handle HUGE files correctly and that HUGE BitTiff files work.

Imperial College want to use Exiv2 for 90GByte BigTiff files from medical imaging systems.  This also requires multi-page Tiff support which might make v1.00.  Those medical body scanners generate multi-page files as they "slice" your body.

**Comment by tester0077** [comment]
variable with type size_t have caused me a lot of grief and work in 
converting my own projects to compile & run in their 64-bit version. In 
my case, all apps run only under Win, hence I did not have to contend 
with cross-OS issues.

**Comment by pydera** [comment]
new pull request is: #1535

**Pull request closed without merging**
