### PR TITLE
changes comma to dot for aperture (2,8 to 2.8) to match the other exif entries

### PR DESCRIPTION
**Pull request by codingdave**
With #743 I made the mistake to add the exif information for my lens with "F2,8" ~~instead of the common "f/2.8"~~. 

This PR shall fix that.

### CODE REVIEW

**Comment by codingdave** [comment]
Well, after looking at the code another time I see that there are various different ways to write the Aperture. I see F, F/ and f/: 

    {0x26,0x40,0x37,0x5C,0x2C,0x3C,0x1C,0x02,0x00,0x00,0x00, "Sigma", "", "24-70mm F3.5-5.6 Aspherical HF"},
    {0x00,0x47,0x25,0x25,0x24,0x24,0x00,0x02,0x00,0x00,0x00, "Tamron", "69E", "SP AF 14mm F/2.8 Aspherical (IF)"},
    {0xA0,0x40,0x2D,0x53,0x2C,0x3C,0xCA,0x8E,0x01,0x00,0x03, "Nikon", "JAA826DA", "AF-P DX Nikkor 18-55mm f/3.5-5.6G VR"},

However, I do not find a single other entry that uses a comma. So I change my PR to replace the comma by a dot.

**Comment by codingdave** [comment]
Just in case you wonder why this is important: In the darktable project there exists a function that separates the data into maker and model using the comma as a separator.
Do you know of any database entries that are in the fashion "<maker><comma><lens description>"?

**Review by D4N — APPROVED** [review]
Thanks for fixing this, I was not aware of this issue.

**Comment by codingdave** [comment]
Thank you!

D4N <notifications@github.com> schrieb am Mo., 11. Nov. 2019, 23:04:

**Pull request merged**
