### PR TITLE
ES translations

### PR DESCRIPTION
**Pull request by criadoperez**
Added ES translations

### CODE REVIEW

**Comment by criadoperez** [comment]
The coverage was increased to 73%. I don't know why codecov doesn't display this.

**Comment by clanmills** [comment]
Thanks for working on this.  Luis (@piponazo) is Spanish and I'll leave him to review/approve this.  Perhaps you could also submit a PR to the 0.27-maintenance.  It's probably identical as I don't believe the ES localisation has been modified since we split off the 0.27-maintenance branch in 2018.

I don't know what some of those CI checks like CodeCov (and others) actually do.

Thank You for working on this.  It is appreciated.

**Comment by criadoperez** [comment]
@clanmills I tried to submit a PR to the 0.27-maintenance branch but it says automatic merging is not possible. I forked and made changes from the master branch which seems to be different to the 0.27-maintenance-branch.
In which of the branches to you store the latest translations? Still want to to submit a PR to the 0.27-maintenance branch?
Thanks.

**Comment by clanmills** [comment]
That message occurs when your branches are mixed up.  Be sure to use 0.27-maintenance as the base when you create the PR.  You shouldn't need to fork.  I hardly know anything about Git.  My total knowledge is on this card:

GitIdiotCard

The funny little brown marks were added by Lizzie (our cat).  She doesn't think much of git.

**Comment by criadoperez** [comment]
I love your card @clanmills ! That clears things out. You are working on the 0.27 maintenance and not on the main branch. Ok, I can pull from that branch from now on.

**Pull request closed without merging**
