### PR TITLE
Issue 350

### PR DESCRIPTION
**Pull request by clanmills**

### CODE REVIEW

**Comment by clanmills** [comment]
This is wrong.  I have no idea how changes to src/CMakeLists.txt ended up here.  Git is a monster.

**Comment by D4N** [comment]
@clanmills I have removed the commit that got dragged in from this branch. If you switch to it, please do as follows:
```
$ git fetch origin
$ git checkout Issue-350
$ git reset origin/Issue-350 # this will do a soft reset, so your current changes will stay
```

**Comment by piponazo** [comment]
So, is this branch in a state to be reviewed now?

**Comment by clanmills** [comment]
The file "README-CONAN.md" is ready to be reviewed and committed.

**Review by piponazo — APPROVED** [review]

**Comment by D4N** [comment]
Does this make #350 obsolete and should it be closed?

**Comment by clanmills** [comment]
Gentlemen:  I've closed #350.  I see this is already closed.  I suspect we will have future updates to README-CONAN.md, however for the moment, this is complete.

When servicing the discussion about Extended XMP, I was unable to build on Linux due to issues with OpenSSL on the Ubunutu VM on my laptop.  I removed *`self.requires('libcurl/7.60.0@bincrafters/stable')` from conanfile.py and it built.  We should consider making webready an option in conanfile.py and updating the documentation appropriately.  I intend to work on Exiv2 v0.27 RC1 in September and I'll revisit README-CONAN.md at that time.

**Pull request merged**
