### PR TITLE
Use PROJECT_SOURCE_DIR

### PR DESCRIPTION
**Pull request by henryborchers**
Using PROJECT_SOURCE_DIR instead of CMAKE_SOURCE_DIR is exactly the same for locating include folders during a standard build. However, using PROJECT_SOURCE_DIR instead allows the Exiv2 to be built as a subproject of other projects using CMake's FetchContent and ExternalProject_Add.

### CODE REVIEW

**Review by D4N — DISMISSED** [review]
Git history must be cleaned up before merging.

**Comment by henryborchers** [comment]
Hi @D4N. Can you fix it for me this time?  I really need to learn how to clean up git logs.

**Comment by D4N** [comment]
@henryborchers Done. It was easier to create a new branch based on master, cherry pick the commit with the change and force push it to your branch.

Some additional stuff concerning git:
- I have force pushed to UIUCLibrary/master, if you do a git pull next time, you'll get a humongous merge and/or a lot of conflicts. Instead only do a git fetch and reset --hard your local copy.
- You can avoid the merges by always performing a `pull --rebase origin/master`. Thereby your local commits will be rebased on top of master and you'll never have to clean up merges again (but a failed rebase is harder to clean up than a merge).

**Review by piponazo — APPROVED** [review]
The changes look good for me. If this helps to consume the project in external ones and it does not affect to exiv2, let's merge it.

**Pull request merged**
