### PR TITLE
Add back localtime.c implementation for MinGW

### PR DESCRIPTION
**Pull request by piponazo**
This change add backs the localtime.c implementation when using MinGW. It should solve the problem described in #473 when cross-compiling from linux to windows using MinGW 32 bits. 

@cgilles I would appreciate if you could validate this change in your environment.

### CODE REVIEW

**Review by clanmills — COMMENTED** [review]
@piponazo Thanks for working on this.  I'm working on MSYS2 32 bit at the moment.  I hope to work on localtime.c/timegm.h and approved this later today.

**Comment by cgilles** [comment]
localtime.c and timegm.h must be reverted to 0.26 version, as i provided in my patch.

**Comment by D4N** [comment]
Just a quick note: the problem with conversions.sh could be a timezone
issue like we have seen when porting some exiv2json test cases from the
bash tests to the python test suite. I haven't looked at the code
though, so it's just a wild guess.

**Comment by clanmills** [comment]
@piponazo I discovered MSYS the painful way.  It's not a guess.

32bit MinGW/msys2 wasn't linking psapi.lib which provides EnumProcessHandles() for src/version.cpp.  I read the following article about printing all the variables in CMake:https://stackoverflow.com/questions/9298278/cmake-print-out-all-accessible-variables-in-a-script  And it suggested:

```
get_cmake_property(_variableNames VARIABLES)
list (SORT _variableNames)
foreach (_variableName ${_variableNames})
    message(STATUS "${_variableName}=${${_variableName}}")
endforeach()
```

I then modified src/CMakeLists.txt to link psaspi:
```
    if (CYGWIN OR MINGW OR MSYS OR MSYS2)
        target_link_libraries( exiv2lib PRIVATE  psapi ws2_32 )
    endif()
```

I invented MSYS2 (just being cautious).

The puzzle with conversions.sh and TZ is documented in #473.  It hasn't been recorded as a different issue because I suspected that it was being caused by the removal of localtime.c.  I'll record this as new issue for investigation later.

@D4N test/conversions.sh is "pure bash", so I don't believe any python is involved.

**Pull request merged**
