### PR TITLE
fix_conan_ci

### PR DESCRIPTION
**Pull request by clanmills**
https://github.com/Exiv2/exiv2/issues/2012#issuecomment-986705652

### CODE REVIEW

**Comment by clanmills** [comment]
Rat bags.  cmake doeen't find gtest.  So it's not curl/webready.  It's not finding dependencies that conan built.  It's working on my desktop (both macOS and Ubuntu).  Of course I have the dependencies built and installed (from source, or from the platform package manager).  Ummmm.  That's odd that cmake cannot find the dependences that conan built. 

Good News is that it builds fine on the desktop.  And this has been working for a long time.   Tomorrow's another day.

**Comment by kevinbackhouse** [comment]
We could just drop conan from the Linux builds. It builds fine without it. I think we already stopped using conan on macOS

**Comment by clanmills** [comment]
Good idea.  The whole point of conan is to build and install dependencies.  I haven't install curl on my M1/Linux VM.  Same issue, cmake cannot find curl.  Tomorrow, I'll see if we can build on Linux.

conan has greatly simplified building with Visual Studio and in #2012, the user was saying that the msvc build was broken.  I got it to work by upgrading conan and deleting the conan cache.

**Comment by clanmills** [comment]
Big improvement in the Linux builds.

Some windows builds are failing because conan-center has not set conan remote and still using bincrafters.  So we should do:

```
conan remote clean # remove all remote servers
conan remote add conan-center https://center.conan.io
```

Some windows builds are failing to find ZLIB.  How strange.  It seems that the way in which conan interacts with CMake is to write files such as FindZLIB.cmake and then the cmake `find_package` instruction will use the locally generated FindXXXX.cmake files to discover the dependency that conan built.

**Comment by clanmills** [comment]
I'm close to giving up on this.  There are several issues:

1.  We must set conan-center to https://center.conan.io in `conan remote`
The v0.27.5 builds were successfully achieved with the 'bincrafters' recipes.

I've fixed this.

2.  We were not setting CMAKE_MODULE_PATH correctly.
It should be a semicolon separated PATH style variable.

I've fixed this.

When we set it correctly, the FindXXX.cmake generated by conan are used by the compiler and linker to the code compiles.  When this was not being set, we were falling back on the CMake provided FindXXX.cmake files.  If the dependencies were installed by the package manager, those usually work.

3.  We need to add `${GTest_INCLUDE_DIRS}` the include path in unitTests

This was working in v0.27.5 because we hadn't fixed the CMAKE_MODULE_PATH.  The compiler found gtest.h in a standard location.

I've fixed this.

4. We should default to CMAKE_CXX_STANDARD 98 and gtest/1.8.1

I've fix this.

4. There is something wrong when linking GTest.

It fails to link all platforms.   This issue was masked by issues 1,2 and 3.

For the moment, the only way to submit this PR is to ignore unit tests.  If it makes the build stable, that will do and we can ask Luis to look at the GTest linking issue.

**Comment by piponazo** [comment]
Hi guys, I'm sorry to arrive late to the party. Today it's a public holiday where I live and the day is horrible, I'll spend some time on this issue and try to help :innocent:

**Comment by clanmills** [comment]
@piponazo Good to hear from you.  Bright/cold day here (2C at sunrise).  I'm going to run this morning.  We'll finish putting up the Christmas lights after lunch.

This PR is about the 0.27-maintenance/CI.  The focus is conan+gtest.  I can build with "pure cmake" when I've built/installed gtest 1.8 in /usr/local/  If you find other stuff which has nothing to do with conan+GTest, please report it and I'll deal with it.

There's something wrong with conan+gtest.  Thousands of linking errors (macOS, Linux, msvc = everywhere) such as `unsatisfied testing::Testing::TearDown()`.   It was working on msvc when the remote was bincrafters.  I am now using conan-center == https://center.conan.io and conan 1.43.0.

I was interested in your comment:
```
GTest::GTest once we upgrade the minimum CMake version required
```

I tried the cmake code, something like:
```cmake
include("GtestSomething")
enable_testing()
find_package(GTest REQUIRED)
```

One other "heads up".  I think msvc might be case sensitive and prefer `GTest_INCLUDE_DIRS` in the following:

```cmake
target_include_directories(unit_tests
    PRIVATE
        ${GTEST_INCLUDE_DIRS}
        ${CMAKE_SOURCE_DIR}/src
)
```

**Comment by piponazo** [comment]
Hi @clanmills thanks for the summary. I saw that you did a great work and grasped most of the conan issues correctly. Few weeks/months ago they deprecated the previous conan-center server and started to use a new one. Somehow we had the code renewed in the `main` branch, but not in the `0.27-maintenance`.

Since it has been a long time since I do not contribute in Exiv2, I thought it would be better to just start a new branch (I named it `fix_conan_ci_luis`) and do some trial & error there (instead of messing around with your branch).

I'll create a DRAFT PR soon with the changes I think are needed to fix the CI, without having to disable the unit tests. Then we can discuss if we want to merge this branch or the other.

**Comment by clanmills** [comment]
@piponazo  That's perfect.  A very good way to move forward.

**Comment by piponazo** [comment]
@clanmills @kevinbackhouse It looks like the PR #2018 fixes the CI. I added there a description with the changes introduced.

**Comment by clanmills** [comment]
Superseded by #2018.

**Pull request closed without merging**
