### PR TITLE
Display Repology packaging status

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by piponazo** [comment]
Could you give more details about this PR?

**Comment by tbeu** [comment]
This is another badge to display the number of Linux distros where exiv2 is used and which version it is.

**Review by piponazo — DISMISSED** [review]

**Comment by piponazo** [comment]
For some reason which I do not understand travis did not triggered a job here 😩 . If you want I can disable temporarily the Github checks, merge the PR, and enable them back.

**Comment by tbeu** [comment]
> For some reason which I do not understand travis did not triggered a job here weary . If you want I can disable temporarily the Github checks, merge the PR, and enable them back.

That was on purpose, since I used `[ci skip]` in the commit message.

**Comment by piponazo** [comment]
> That was on purpose, since I used `[ci skip]` in the commit message.

I learn new things every day with you guys ... 

The problem with that approach is that it conflicts with the CI checkers that we have. By doing that, we need to do additional manual work ... 😢

**Comment by tbeu** [comment]
The idea is, that dummy changes (like this one in a Readme file) should not require any CI.

**Comment by piponazo** [comment]
I know that this was your intention and I agree in which that would be ideal. What I am trying to say is that now the Merge button is disabled because travis did not run:

```
**continuous-integration/travis-ci ** Expected — Waiting for status to be reported
```

Note that in https://github.com/Exiv2/exiv2/settings/branches we have some CI checks which are requiring that Travis and Appveyor pass for every PR.

**Review by D4N — DISMISSED** [review]

**Comment by D4N** [comment]
Let's maybe not use the CI skip feature. While it would make sense here, turning of the required checks every time is annoying. @tbeu can you change the commit message so that it does not include the `[ci skip]`?

**Comment by tbeu** [comment]
OK.

**Review by piponazo — APPROVED** [review]

**Pull request merged**
