### PR TITLE
endian check from runtime to compile time

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
We're not on C++20 yet, are we? It's a shame we can't use [`std::endian::native`](https://en.cppreference.com/w/cpp/types/endian).

**Review by kevinbackhouse — APPROVED** [review]

**Comment by neheb** [comment]
> We're not on C++20 yet, are we? It's a shame we can't use [`std::endian::native`](https://en.cppreference.com/w/cpp/types/endian).

std::endian requires the minimum compiler to be bumped. Exiv2 can still be compiled with gcc7.

**Comment by Ryanf55** [comment]
> gcc7

FYI the oldest non-EOL ubuntu version ships with `9.3.0`. https://packages.ubuntu.com/focal/devel/gcc

**Comment by kmilos** [comment]
Also, might be better to use compiler defined `__BYTE_ORDER__` and `__ORDER_BIG_ENDIAN__` macros rather than some header defined macros that are not standard?

**Comment by kmilos** [comment]
And Clang as well, at least.

Where does `__ORDER_BIG_ENDIAN` come from?

**Comment by neheb** [comment]
GCC and clang.

**Comment by kmilos** [comment]
My GCC and Clang have only the variants with two underscores at the end 🤷

**Pull request merged**
