### PR TITLE
Conan instructions

### PR DESCRIPTION
**Pull request by piponazo**
As promised, I wrote a short document trying to explain how to use conan to bring all the exiv2 dependencies. 

Please, try to follow the instructions to use conan and let me know if you have questions or suggestions.

### CODE REVIEW

**Comment by piponazo** [comment]
Note that this PR address an old issue: #100

**Comment by clanmills** [comment]
Thanks, I'm looking at this at the moment.  Fighting with Windows to get conan to work on Windows.  Usual windows environment/python/svn mismatch stuff.  What's svn got to do with this?  Don't ask!

**Comment by clanmills** [comment]
For now, I'm going to focus on Visual Studio 2015 and 2017 and not worry about MacOS-X, Linux or Cygwin.

The documentation in README-CONAN.md is correct as far as it goes.  For sure, everything seems to work as documented.
```
C:\Users\rmills\gnu\github\exiv2\exiv2>mkdir build
C:\Users\rmills\gnu\github\exiv2\exiv2>cd build
C:\Users\rmills\gnu\github\exiv2\exiv2\build>conan install ..
PROJECT: Installing C:\Users\rmills\gnu\github\exiv2\exiv2\conanfile.py
Requirements
    Expat/2.2.5@pix4d/stable from 'conan-center'
    OpenSSL/1.0.2n@conan/stable from 'conan-center'
    gtest/1.8.0@bincrafters/stable from 'conan-center'
    libcurl/7.56.1@bincrafters/stable from 'conan-center'
    zlib/1.2.11@conan/stable from 'conan-center'
Packages
    Expat/2.2.5@pix4d/stable:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7
    OpenSSL/1.0.2n@conan/stable:606fdb601e335c2001bdf31d478826b644747077
    gtest/1.8.0@bincrafters/stable:a35f8fa327837a5f1466eaf165e1b6347f6e1e51
    libcurl/7.56.1@bincrafters/stable:e37838f02fd790447943465f1c9317fd1c59b95c
    zlib/1.2.11@conan/stable:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7

Expat/2.2.5@pix4d/stable: Already installed!
gtest/1.8.0@bincrafters/stable: Already installed!
zlib/1.2.11@conan/stable: Already installed!
OpenSSL/1.0.2n@conan/stable: Already installed!
libcurl/7.56.1@bincrafters/stable: Already installed!
PROJECT: Generator cmake created conanbuildinfo.cmake
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt
PROJECT imports(): Copied 5 '.dll' files

C:\Users\rmills\gnu\github\exiv2\exiv2\build>cmake ..
...
-- Compiler info: MSVC (C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe) ; version: 19.11.25507.1
-- ------------------------------------------------------------------
-- exiv2 0.26 configure results        <http://www.exiv2.org>
-- Building shared library:            YES
-- Building PNG support:               YES
-- XMP metadata support:               YES
-- Native language support:            YES
-- Conversion of Windows XP tags:      YES
-- Nikon lens database:                YES
-- Commercial build:                   NO
-- Building video support:             NO
-- Building webready support:          NO
-- Dynamic runtime override:           NO
-- Unicode paths (wstring):            NO
-- Building exiv2 command:             YES
-- Building samples:                   YES
-- Building PO files:                  NO
-- Building unit tests:                NO
-- Using ccache:                       NO
-- ------------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/rmills/gnu/github/exiv2/exiv2/build

C:\Users\rmills\gnu\github\exiv2\exiv2\build>
```
Now, how to get it to build?

I tried:
```
C:\Users\rmills\gnu\github\exiv2\exiv2\build>cmake --build . --config Release --target install
.....
lots and lots of errors 
.....
  C:\cygwin64\usr\include\sys/_intsup.h(82): fatal error C1189: #error:  "Unable to determine type definition of intptr_t" (compiling sour
ce file C:\Users\rmills\gnu\github\exiv2\exiv2\xmpsdk\src\XMPUtils.cpp) [C:\Users\rmills\gnu\github\exiv2\exiv2\build\xmpsdk\xmp.vcxproj]

    686 Warning(s)
    2298 Error(s)

Time Elapsed 00:00:11.16
```

It building with Visual Studio 2017.  I tried to use 2015 by changing ~/.conan/profiles/default - however that doesn't seem to be effective.  For sure it's cacheing stuff.  I suspect it's building with a mix of 2017/2015 headers or something.

Good News:
The code and CMake files are ok.  I can successfully build with contrib/cmake/msvc/cmakeBuild.cmd
```
C:\Users\rmills\gnu\github\exiv2\exiv2\contrib\cmake\msvc\dist>2015\x64\dll\Release\bin\exiv2 -vV | grep -e version -e compiler -e date -e time
compiler=MSVC
version=13.00 (2015/x64)
date=Apr 10 2018
time=21:48:45
C:\Users\rmills\gnu\github\exiv2\exiv2\contrib\cmake\msvc\dist>2017\x64\dll\Release\bin\exiv2 -vV | grep -e version -e compiler -e date -e time
compiler=MSVC
version=13.11 (2017/x64)
date=Apr 10 2018
time=22:20:44
have_gmtime_r=0
have_timegm=0
xmlns=mediapro:http://ns.iview-multimedia.com/mediapro/1.0/
C:\Users\rmills\gnu\github\exiv2\exiv2\contrib\cmake\msvc\dist>
```

**Comment by piponazo** [comment]
I am suspecting that your problem could be about a mismatch in the architecture. Indeed I did not explain anything about that (I will fix it later).

Please, try the following:

1. Create a profile for your the compiler you want to use. If it is Visual studio 2017, create a file in `$HOME/.conan/profiles/msvc2017Release` with the content:

```
[settings]
arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
```

If you have several compilers in your machine, this is the best way to keep a configuration for each of them.

2.  Delete the content of the build folder, and run again conan install:

```
conan install .. --profile msvc2017Release
```
This bring packages of the dependencies for the configuration specified in the profile (Visual Studio 2017, Release mode, x64 architecture, runtime MD)

3. Now run CMake, and choose the Generator that matches your profile. Let's call CMake as we do it in AppVeyor:

```
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DEXIV2_ENABLE_XMP=ON -DEXIV2_ENABLE_NLS=OFF -DEXIV2_ENABLE_PNG=ON -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DCMAKE_INSTALL_PREFIX=install ..
```

4. Finally run the command:

```
cmake --build . --config Release --target install
```
This should install everything in the directory specified to CMake at configuration time (CMAKE_INSTALL_PREFIX). 

Of course, you can also open the solutions and projects generated inside the **build** folder directly with Visual Studio. Or use any other command you would use directly with VS solutions.

**Comment by clanmills** [comment]
Thanks very much.  That has worked.  The important difference is that you have entered the complete cmake command `cmake -G "......"`, whereas I used `cmake ..`.  The output of both cmake commands is similar, however yours works, although both claim to use same compiler (MSVC VS 2017).

This is _**wonderful**_ progress.

There's an issue with the build.  The binaries in build\bin are fine, however build\install\bin does not contain dependent dlls (libcurl.dll).  I'm also a little surprised not to find zlib and expat dlls, so presumably we've built and linked a static version of those libraries.

**Review by clanmills — APPROVED** [review]
I've very happy with the progress here.  I don't think we're finished, however this is very good "work-in-progress".

**Comment by clanmills** [comment]
This PR seems to have closed itself!  I don't agree that we are finished here.  You have merged the work-in-progress, however I'm sure this needs more review and revision.

For example, the cmake command is very complicated and requires the user to know about generators with compilicated names such as _**"Visual Studio 15 2017 Win64"**_.  This might make sense to the CMake Engineers, however it's total foreign to a Visual Studio User.  I've buried the complexity in contrib/cmake/msvc in the build command:
```
> cmd /c "vcvars 2015 64 && cmakeBuild --build"
```

**Comment by clanmills** [comment]
Luis:  I'm putting comments here to help me "explore the boundary" of conan/Visual Studio.  So, I will be editing this note in the next couple of days.  I'll let you know when I want you to review my comments.

1) Please say "Visual Studio Specific Notes"
2) contrib/cmake/msvc/cmakeBuild.cmd populates dist/ (see contrib/cmake/msvc/ReadMe.txt)
```
   The build is performed in  work_Config (for example work_Release)
   The output is generated in dist
                              dist\..mumble..\bin contains *.exe and *.dll files
                              dist\..mumble..\lib contains *.lib files
                              dist\..mumble..\include contains *.h and *.hpp files

   mumble identifies the compiler and build.
   Example C:\gnu\github\exiv2\contrib\cmake\msvc\dist\2013\x64\dll\Release\bin
   2013    = Visual Studio      Choices: 2005 | 2008 | 2010 | 2012 | 2013 | 2015 | 2017
   x64     = 64 bit build                Win32 | x64
   dll     = shared library              dll | static
   Release = configuration               Release | Debug | RelWithDebInfo | MinSizeRel
```
3) Explain how to build with static/shared zlib and expat
4) Does debug link a debug version of zlib and expat?
5) Is the command "cmake .. -G "Visual Studio 15 2017 Win64"  sufficient?
5) What happens if the -G generator conflicts to conan profile? 
6) How can you build with different versions of Visual Studio?
6) Which versions of Visual Studio do we support?
7) Can you clear the conan cache?  Where is it stored?  Does it store different versions of dependent libraries for different versions of Visual Studio?

Remarks (to you, not for the document)
1) Using cygwin to build Exiv2 works well and is essentially identical to Linux.
2) CMake/MinGW (msys/1.0) is a disaster.  I refuse to support that and  put notes in TODO-CMAKE about this.
3) _**darktable**_ build Exiv2 with Msys/2.0, although I couldn't get it to work: http://dev.exiv2.org/boards/3/topics/2913?r=2963

I think we should say that "_**Users have reported being able to build Exiv2 with MinGW & CMake on msys/2.0.  Team Exiv2 will not provide support for this configuration.  Users wishing to build Exiv2 for MinGW (both msys/1.0 and msys/2.0) should use autotools (./configure)**_."

**Comment by piponazo** [comment]
@clanmills I merged after you approved the PR, I would have not merged it without the approval :wink:. I agree in which we can continue improving the document, I am happy to continue working on these things until all of us are happy with the outcome. 

I understand your comment about the generators, but there is not much we can do about it, you need to specify a generator if you do not want to use the default one. We could always provide provide some super simple scripts for windows users to make the proper calls to conan & cmake.

I am also happy to explore a bit the integration of conan/cmake with MinGW and MSYS. I know that the conan guys did some work in that area.

**Comment by clanmills** [comment]
We can't change the horrible names of the Visual Studio generators, however we can hide them in scripts which is what I did in contrib/cmake/msvc.

If you could look at MinGW + msys/2.0 + CMake that would be  appreciated by Tobias.  I had to modify a Microsoft SDK header file to even get CMake to build about a year ago.  I don't think there's any reason to spend time on msys/1.0 as I believe it's obsolete.  However msys/2.0 is used by several applications and deserves more effort.  If you can get msys/2.0 + CMake + Exiv2 to build, that drives another nail into the coffin of autotools (./configure).

**Pull request merged**
