### PR TITLE
CI: improved in-progress job canceling

### PR DESCRIPTION
**Pull request by kmilos**
Only works on pull_request events as per https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value

### CODE REVIEW

**Review by piponazo — APPROVED** [review]
LGTM

**Comment by hassec** [comment]
@kmilos I think this merge broke our CI, so maybe we should revert this merge. 
Release build failed this morning and I see that the individual commits all had failing CI jobs... :roll_eyes: 

@piponazo any objections to revert?

**Comment by piponazo** [comment]
Ups. No objections at all, please @kmilos could you look at it?

**Comment by kmilos** [comment]
I don't think this should have broken anything? What is wrong exactly? I only see known failing Cygwin jobs...

**Comment by hassec** [comment]
I got a ping that the release workflow failed and looked into our CI and it looks like the last few commits all have failed CI jobs. 

Are you saying the CI has just been broken the before?

**Comment by piponazo** [comment]
Hum, I see that the Release job for windows fails:
https://github.com/Exiv2/exiv2/actions/runs/3442616233/jobs/5743368035

But I think it is totally unrelated to this change. This looks very similar to the issue we are currently having with the Cygwin jobs. Note that I reported the issue with the Cygwin jobs here:
https://github.com/egor-tensin/setup-cygwin/issues/9#issuecomment-1306329575

Many other projects are having similar issues which seem to be caused by **chocolatey**

**Comment by hassec** [comment]
Ah, thanks @piponazo, so I guess I was too quick to blame this PR, sorry @kmilos! :see_no_evil:

**Pull request merged**
