### PR TITLE
reduce nesting of operator

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
ping @mohamedchebbii

**Review by mohamedchebbii — APPROVED** [review]
Seems good to me ; 
If the goal is to reduce nesting of operator;
I suggest the following : 

 `bool AsfVideo::GUIDTag::operator<(const GUIDTag& other) const {
  if (data1_ != other.data1_)
    return data1_ < other.data1_;

  if (data2_ != other.data2_)
    return data2_ < other.data2_;

  if (data3_ != other.data3_)
    return data3_ < other.data3_;

  return std::lexicographical_compare(data4_.begin(), data4_.end(), other.data4_.begin(), other.data4_.end());
}
`

anyway I approuve uour solution

**Comment by neheb** [comment]
even shorter. nice.

**Review by mohamedchebbii — APPROVED** [review]

**Comment by neheb** [comment]
ping @kmilos

**Review by kmilos — APPROVED** [review]
LGTM

**Comment by kmilos** [comment]
@Mergifyio backport 0.28.x

**Pull request merged**
