### PR TITLE
bump_revision_27.5.2

### PR DESCRIPTION
**Pull request by clanmills**

### CODE REVIEW

**Comment by clanmills** [comment]
This is failing in conan because of missing registry.json.  I can't find this file (on macOS or Windows).  There's a mention of it here.  https://github.com/conan-io/docs/pull/990/files. 

I'm confident this is an infrastructure failure.  registry.json is documented here:  https://docs.conan.io/en/1.20/reference/config_files/registry.txt.html  and contains the following example:

```json
 {
     "remotes":[
         {
             "name":"conan-center",
             "url":"https://api.bintray.com/conan/conan/conan-center",
             "verify_ssl":true
         },
         {
             "name":"artifactory_local",
             "url":"http://192.168.43.191:8081/artifactory/api/conan/conan-local",
             "verify_ssl":true
         },
         {
             "name":"bincrafters",
             "url":"https://api.bintray.com/conan/bincrafters/public-conan",
             "verify_ssl":true
         }
     ],
     "references":{
         "nanomsg/1.1.2@bincrafters/stable":"bincrafters",
         "Poco/1.9.0@pocoproject/stable:09378ed7f51185386e9f04b212b79fe2d12d005c":"conan-center",
         "hello/1.0@user/channel:2bb76c9adac7b8cd7c5e3b377ac9f06934aba606":"artifactory_local"
     },
     "package_references":{
         "nanomsg/1.1.2@bincrafters/stable:26d575619895d584ff4fb07701901d53ff4cdd6b": "bincrafters",
         "Poco/1.9.0@pocoproject/stable:09378ed7f51185386e9f04b212b79fe2d12d005c":"conan-center",
         "hello/1.0@user/channel:2bb76c9adac7b8cd7c5e3b377ac9f06934aba606":"artifactory_local"
     }
 }
```

**Comment by clanmills** [comment]
Whoops.  Found a regstry.json on the MacMini build-server in Luis's directory: ` /Users/piponazo/.conan/registry.json`

```json
{
 "remotes": [
  {
   "url": "https://conan.bintray.com", 
   "verify_ssl": true, 
   "name": "conan-center"
  }, 
  {
   "url": "https://api.bintray.com/conan/piponazo/piponazo", 
   "verify_ssl": true, 
   "name": "conan-piponazo"
  }
 ], 
 "package_references": {
  "zlib/1.2.11@conan/stable:bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583": "conan-center", 
  "gtest/1.8.1@bincrafters/stable:b9a1cc8221294c735988f56e5527f8d2adc8e499": "conan-center", 
  "Expat/2.2.6@pix4d/stable:bad7dd1e4b5daf2b9ae8e3ca2e4397d55b8d3583": "conan-center", 
  "gtest/1.8.1@bincrafters/stable:fc3dbc4d97a08f0428de79c1307277c5be35249a": "conan-center", 
  "libcurl/7.61.1@bincrafters/stable:bdb25084f7fcc9d0690b41a8e12fc2fd958dfd6b": "conan-center"
 }, 
 "references": {
  "Expat/2.2.5@pix4d/stable": "conan-center", 
  "gtest/1.8.1@bincrafters/stable": "conan-center", 
  "libcurl/7.56.1@bincrafters/stable": "conan-center", 
  "Expat/2.2.6@pix4d/stable": "conan-center", 
  "gtest/1.8.0@bincrafters/stable": "conan-center", 
  "libcurl/7.61.1@bincrafters/stable": "conan-center", 
  "XmpSdk/2016.7@piponazo/stable": "conan-piponazo", 
  "libcurl/7.60.0@bincrafters/stable": "conan-center", 
  "zlib/1.2.11@conan/stable": "conan-center"
 }
}
```

**Comment by kevinbackhouse** [comment]
I think something has changed in conan, because the Windows build has stopped working without us changing anything. I just tried rerunning the checks on #1806, which is an older pull request (on the main branch) that previously passed all checks. The Windows build is failing now.

**Comment by kevinbackhouse** [comment]
It looks like the build started failing 2 days ago: https://github.com/Exiv2/exiv2/actions/runs/1208122648

**Comment by kevinbackhouse** [comment]
I think it must have something to do with [Conan version 1.40](https://github.com/conan-io/conan/releases/tag/1.40.0), which was release three days ago. I have been comparing the build logs between [the last passing release build](https://github.com/Exiv2/exiv2/actions/runs/1204710859) and [next one which failed](https://github.com/Exiv2/exiv2/actions/runs/1208122648). One of the differences is that the conan version changed from 1.39 to 1.40.

**Comment by kevinbackhouse** [comment]
I bet this change is to blame: https://github.com/conan-io/docs/pull/2212

**Comment by clanmills** [comment]
Not so fast with the close, @kevinbackhouse. The code is good.  We need:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c2467b3..96f94ec 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,7 +1,7 @@
 cmake_minimum_required( VERSION 3.3.2 )
 
 project(exiv2          # use TWEAK to categorize the build
-    VERSION 0.27.5.1   # 0.27.5.1  = RC1
+    VERSION 0.27.5.2   # 0.27.5.2  = RC2
                        # 0.27.4    = GM               (tagged and released)
                        # 0.27.4.9  = 27.4.9 Development
                        # 0.27.4.00 = GM Preview
```

**Review by kevinbackhouse — APPROVED** [review]
Let's merge this, because it clearly isn't causing the build failures. I think we need to fix the conan stuff before we create the RC2 release though.

**Comment by kevinbackhouse** [comment]
Oh, did I close this? That was an accident - sorry about that.

**Comment by clanmills** [comment]
I do the builds on the Mac mini and only use conan for Visual Studio.  So, I'm OK to update the pre-release site (which I polluted earlier).

I'm working on the include path issue and hope to get a rock-solid way to reproduce that.

Let's get conan and the include path fixed for RC2.

**Pull request merged**
