### PR TITLE
Serialize XMP packet in Image::xmpPacket()

### LINKED ISSUE #226: Exiv2::Image::xmpPacket() does not work for some tiff.
I'm using exiv2 on macOS (High Sierra), exiv2 0.26 001a00 (64 bit build), comes from macport.
First I prepare 2 images using ImagaMagick (6.9.9-26 Q16 x86_64), just do the following:
```
convert logo: logo.tif
convert logo: logo.jpg
```
then, add simple xmp with exiv2.
```
exiv2 -M"set Xmp.dc.rights foo" logo.tif 
exiv2 -M"set Xmp.dc.rights foo" logo.jpg
```
Here is the file after adding xmp:
[logo.zip](https://github.com/Exiv2/exiv2/files/1704875/logo.zip)

I confirmed the raw packet is there by using `exiv2 -pX`, so far it looks no problem.

Then I compile [`xmpdump.cpp`](https://github.com/Exiv2/exiv2/blob/0.26/src/xmpdump.cpp) found in your src directory, with gcc, and just execute.
For jpeg image, it outputs xpacket in the file, however for tiff, it returns error:
```Caught Exiv2 exception './logo.tif: No XMP packet found in the file'```
It looks it fails to find xpacket.

I think this should be worked for all supported image, but I am afraid i missed something - 
are there any way to explicitly specify the page, because tiff could have multiple images in one file.

---
PS
I checked with MSYS2 binaries (mingw-w64-x86_64-exiv2-0.26-3) on Windows 7 (64 bit), and the result are the same.

### PR DESCRIPTION
**Pull request by piponazo**
Pushing this commit on behalf of @clanmills . Let's see if CI is happy with the changes.

Fixes #226

### CODE REVIEW

**Comment by piponazo** [comment]
The CI job linux-clang is failing:

https://travis-ci.org/Exiv2/exiv2/jobs/452121962

This is running in a docker Ubuntu 14.04 image with clang-5.

I tried locally on my Ubuntu 18.04 + clang-6 and I cannot reproduce the issue. I'll try later usin clang-5 locally.

**Comment by piponazo** [comment]
I am really shock by the issue detected on the CI job. I cannot reproduce it locally on Ubuntu 16.04. It is impossible for me to research further this issue without being able to reproduce it locally.

**Review by clanmills — APPROVED** [review]
Well done, Luis.  Really great find.

Can you review all the CMakeLists.txt and see if there's any other places where we can avoid setting explicit compiler/linker flags.

**Comment by clanmills** [comment]
I really appreciate the value of Travis/Appveyor/CodeCoverage/GitLabs monitors that have been added during the v0.27 project.  

You might have noticed that a user reported packaging issues with FreeBSD (which is Unix, not Linux).  So, even with all of this effort, we can still be caught out!  Who says software is easy?

We are covering our code and platforms with much greater depth than ever before.  Thanks to @piponazo  and @D4N for making this happen.

**Comment by clanmills** [comment]
The buildservers/CI object to the fix. Robin to investigate.

**Comment by clanmills** [comment]
@piponazo Travis is failing in icc-test.sh with an ASAN build.  We saw this somewhere else and fixed it.  I think Travis is finding a rogue from elsewhere and we should "push" this change into the code base.

If Travis continues to find issues with icc-test.sh, we'll open a new issue and I will investigate.  However, I believe we have fixed the issue "Serialize XMP packet in Image::xmpPacket()".

**Comment by piponazo** [comment]
We cannot merge this since one of the CI jobs is failing, and the failure is consistent (I have rebased the branch in top of master few times and the errors is always there).

The idea of adding these checks is to keep master always in green state: "The project builds and run the tests properly in all the platforms". We need to find a fix in the branch (before merging it).

**Comment by clanmills** [comment]
OK.  Ubuntu 14.04 image with clang-5.  I'll investigate the Linux/ASAN/icc-test.sh puzzle.

**Comment by clanmills** [comment]
Good News:  I've reproduced this on Ubuntu 14.04 with Clang 5.0.  Next, I solve what's causing this.

**Comment by clanmills** [comment]
I'd like you to resubmit this PR on top of fresh code.  The fix is good in your branch **`fix226`**

```
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/fix226/build$ git status
On branch fix226
Your branch is up to date with 'origin/fix226'.

nothing to commit, working tree clean
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/fix226/build$ cp /Home/Downloads/logo.zip .
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/fix226/build$ ls -l logo.zip
-rw-r--r-- 1 rmills rmills 86798 Nov 30 07:29 logo.zip
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/fix226/build$ unzip logo -d logo
Archive:  logo.zip
  inflating: logo/logo.tif           
  inflating: logo/logo.jpg           
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/fix226/build$ bin/xmpdump logo/logo.tif
<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2"> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/"> <dc:rights> <rdf:Alt> <rdf:li xml:lang="x-default">foo</rdf:li> </rdf:Alt> </dc:rights> </rdf:Description> </rdf:RDF> </x:xmpmeta>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <?xpacket end="w"?>
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/fix226/build$ 
```

Here's how to reproduce and fix the issue in #226 on 0.27-RC3

```
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ cp /Home/Downloads/logo.zip .
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ ls -l logo.zip
-rw-rw-r-- 1 rmills rmills 86798 Nov 30 07:38 logo.zip
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ unzip logo -d logo
Archive:  logo.zip
  inflating: logo/logo.tif           
  inflating: logo/logo.jpg           
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ bin/xmpdump logo/logo.tif
Caught Exiv2 exception 'logo/logo.tif: No XMP packet found in the file'
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ cp ~/temp/image.cpp ../src
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ git diff
diff --git a/src/image.cpp b/src/image.cpp
index 75991f7d..5dac5bc3 100644
--- a/src/image.cpp
+++ b/src/image.cpp
@@ -565,9 +565,15 @@ namespace Exiv2 {
 
     std::string& Image::xmpPacket()
     {
+        // Serialize the current XMP
+        if (xmpData_.count() > 0 && !writeXmpFromPacket()) {
+            XmpParser::encode(xmpPacket_, xmpData_,
+                              XmpParser::useCompactFormat |
+                              XmpParser::omitAllFormatting);
+        }
         return xmpPacket_;
     }
-
+     
     void Image::setMetadata(const Image& image)
     {
         if (checkMode(mdExif) & amWrite) {
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ make 2> /dev/null >/dev/null
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ bin/xmpdump logo/logo.tif
<?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2"> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/"> <dc:rights> <rdf:Alt> <rdf:li xml:lang="x-default">foo</rdf:li> </rdf:Alt> </dc:rights> </rdf:Description> </rdf:RDF> </x:xmpmeta>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <?xpacket end="w"?>
rmills@rmillsmm-ubuntu14:~/gnu/github/exiv2/exiv2/build$ 
```

I have reproduced the test harness failures in icc-test.sh and webp-test.sh in your branch `**fix226**`.  I know I've seen those before.  I spent a few minutes with kdiff3 to see if I could quickly massage fix226.  I just don't remember how we solved those puzzles.

**Comment by piponazo** [comment]
I rabased this branch in top of 0.27-RC3 and the problem is still present. I am not sure I am following your explanations ...

**Comment by clanmills** [comment]
@piponazo I don't know what's wrong with your branch 'fix226'.  However, I believe this issue is fixed in 0.27-RC3.  If Travis says 0.27-RC3 builds successfully, we don't need to know what's wrong with your branch 'fix226'.  I committed  74a2223d

**Pull request closed without merging**
