### PR TITLE
Issue No. 1359 

### PR DESCRIPTION
**Pull request by jaehojung**
Hello, Regarding the 1359 issue I registered last time, I could not find the original file.
But I want to solve this issue, I ask for a different code review.
I would like to see this code to help me solve this problem.

### CODE REVIEW

**Comment by D4N** [comment]
@jaehojung please open an **issue** and explain there:
- Where do your files come from?
- Why is their metadata broken?
and preferably: why should we support broken files? (the sample that you provided violated the TIFF standard)

Please provide us with a few example files, so that we can take a closer look.

Concerning this patch: it completely breaks the testsuite, it has no tests and the commit log is a mess. I cannot accept that.

**Comment by D4N** [comment]
@jaehojung could you please address my questions?

**Comment by jaehojung** [comment]
Sorry for the late reply.
I do not know why the file was broken and where it came from.
I just want to solve this problem.

**Comment by clanmills** [comment]
What problem?  We've discussed this and analysed your file.  The file violates several parts of the tiff and ITPC standards.  There is no problem to be solved.

**Comment by jaehojung** [comment]
Yes, you are right.
The Problem that I think are problematic from my point of view, Of course not a problem.

**Pull request closed without merging**
