### PR TITLE
Support Sony DSC-RX100M5A

### PR DESCRIPTION
**Pull request by mikaelstaldal**

### CODE REVIEW

**Review by piponazo — CHANGES_REQUESTED** [review]
Hi @mikaelstaldal , thanks for your contribution! :smile: 

Could you please drop your second commit? It does not provide any change. 

I double checked the change you did with the image provided in #612 and I will merge the PR once you resubmit the branch without the 2nd commit.

**Comment by mikaelstaldal** [comment]
The reason for the empty second commit is to make GitHub automatically close the corresponding issue.

**Comment by piponazo** [comment]
> The reason for the empty second commit is to make GitHub automatically close the corresponding issue.

Yes, but we can achieve the same behaviour by just writing a comment in the PR:

https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/

I find that way much cleaner, since we do not need to pollute the git history with those commits.

**Comment by mikaelstaldal** [comment]
OK, the empty commit is removed now.

**Review by piponazo — APPROVED** [review]
Thanks a lot again :wink:

**Comment by piponazo** [comment]
This PR fixes #612

**Pull request merged**
