### PR TITLE
Fix_1368 Sigma 18-35mm f/1.8 DC HSM (0.27 only)

### LINKED ISSUE #1368: Sigma 18-35mm f/1.8 DC HSM misdetected after upgrading to firmware 2.03
**Describe the bug**
Sigma 18-35mm f/1.8 DC HSM on a Canon 70D body, after upgrading to firmware 2.03 via the Sigma USB mount, is misdetected. Apparently the new firmware changed `LensType` from `150` to `368`.

Firmware changelog: https://www.sigma-global.com/en/download/lenses/firmware/popups/a_18_35_18/
Analogous report to `exiftool`: https://exiftool.org/forum/index.php?topic=3833.msg63023#msg63023

**To Reproduce**
Steps to reproduce the behaviour:

1. Upgrade lens to latest firmware (2.03)
2. `exifv2 --version`: `0.27.3`
3. Lens has a new type and is misdetected (two RAW files, same lens and body, old and new firmware):
```
$ exiv2 -p v 20200921_1828.cr2 20201017_2113.cr2
20200921_1828.cr2  0x0016 CanonCs      LensType                    Short       1  150
20200921_1828.cr2  0x0017 CanonCs      Lens                        Short       3  35 18 1
20200921_1828.cr2  0x0095 Canon        LensModel                   Ascii      74  18-35mm
20200921_1828.cr2  0xa432 Photo        LensSpecification           Rational    4  18/1 35/1 0/1 0/1
20200921_1828.cr2  0xa434 Photo        LensModel                   Ascii       8  18-35mm
20200921_1828.cr2  0xa435 Photo        LensSerialNumber            Ascii      11  0000000000
20201017_2113.cr2  0x0016 CanonCs      LensType                    Short       1  368
20201017_2113.cr2  0x0017 CanonCs      Lens                        Short       3  35 18 1
20201017_2113.cr2  0x0095 Canon        LensModel                   Ascii      74  18-35mm F1.8 DC HSM | Art 013
20201017_2113.cr2  0xa432 Photo        LensSpecification           Rational    4  18/1 35/1 0/1 0/1
20201017_2113.cr2  0xa434 Photo        LensModel                   Ascii      30  18-35mm F1.8 DC HSM | Art 013
20201017_2113.cr2  0xa435 Photo        LensSerialNumber            Ascii      11  0000000000

$ exiv2 -p a 20200921_1828.cr2 20201017_2113.cr2
20200921_1828.cr2  Exif.CanonCs.LensType                        Short       1  Sigma 18-35mm f/1.8 DC HSM | A
20200921_1828.cr2  Exif.CanonCs.Lens                            Short       3  18.0 - 35.0 mm
20200921_1828.cr2  Exif.Canon.LensModel                         Ascii      74  18-35mm
20200921_1828.cr2  Exif.Photo.LensSpecification                 Rational    4  18/1 35/1 0/1 0/1
20200921_1828.cr2  Exif.Photo.LensModel                         Ascii       8  18-35mm
20200921_1828.cr2  Exif.Photo.LensSerialNumber                  Ascii      11  0000000000
20201017_2113.cr2  Exif.CanonCs.LensType                        Short       1  Sigma 14-24mm f/2.8 DG HSM | A
20201017_2113.cr2  Exif.CanonCs.Lens                            Short       3  18.0 - 35.0 mm
20201017_2113.cr2  Exif.Canon.LensModel                         Ascii      74  18-35mm F1.8 DC HSM | Art 013
20201017_2113.cr2  Exif.Photo.LensSpecification                 Rational    4  18/1 35/1 0/1 0/1
20201017_2113.cr2  Exif.Photo.LensModel                         Ascii      30  18-35mm F1.8 DC HSM | Art 013
20201017_2113.cr2  Exif.Photo.LensSerialNumber                  Ascii      11  0000000000
```
**Expected behavior**
Lens should be detected as `Sigma 18-35mm f/1.8 DC HSM | A` and not `Sigma 14-24mm f/2.8 DG HSM | A`.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
I hope this information is enough so I'm not attaching the RAW files here, but if needed I can attach them.

### PR DESCRIPTION
**Pull request by lbschenkel**
See #1368.  On Canon bodies and lens firmware 1.x, this lens identifies itself using
model number `150`. Starting with firmware 2.x, this lens now identifies
itself using model number `368`.

`Exiv2` was correctly identifying the former but not the latter.

This PR also fixes a pre-existing bug in which `exiv2` was not
correctly disambiguating lenses using model number `368`.

### CODE REVIEW

**Review by clanmills — DISMISSED** [review]
This looks good.  Thanks very much.

My only comment is to point out that can run exiv2 (or any command) more than once in a test.  Commands is an array, as are retval, stderr, stdout.  If you'd like to change it, I will merge later.  If you want to leave it "as is", I'll merge.

I will cut'n'paste my instructions to you about the test harness in to the book.  So, while helping you, the book has also developed.  I'll mention you on page 2.

If you'd like to do more work on Exiv2, I would be delighted to have your help.  In August, I recruited a young Chinese engineer @LeoHsiao1 who has done marvellous work on rewriting bash_tests in python.  So Leo meet Leonardo.  Leonardo meet Leo.

I've changed the title to match my naming style.

**Comment by clanmills** [comment]
Another comment about this.  I haven't really studied the issue here. If it's straight-forward to port this PR to master can you change the trailer of the title (0.27) to be (0.27->master) to be sure that the release engineer (probably me) deals with it.

If you intend to submit a different PR for 'master', please change the trailer to (0.27 only).

**Comment by lbschenkel** [comment]
> My only comment is to point out that can run exiv2 (or any command) more than once in a test. Commands is an array, as are retval, stderr, stdout. If you'd like to change it, I will merge later. If you want to leave it "as is", I'll merge.

No problem, I'll improve it.

> If you'd like to do more work on Exiv2, I would be delighted to have your help. 

I'm afraid that I won't be able to commit to that. I have a newborn at home and a number of other projects that I'm the maintainer for. :-) But I think I will be able to submit future fixes unassisted, if I ever encounter a similar issue.

> If you intend to submit a different PR for 'master', please change the trailer to (0.27 only).

Master does not have this particular bug, because in master this is the only lens with model 368. But I can submit the new tests if you like.

**Comment by lbschenkel** [comment]
Improved test case to avoid running multiple commands.

**Review by clanmills — APPROVED** [review]
Good Job.  Thanks very much.  Please submit a PR to master with an update to the test suite.

**Pull request merged**
