### PR TITLE
Add IDs for several Canon lenses

### PR DESCRIPTION
**Pull request by webmeister**

### CODE REVIEW

**Comment by clanmills** [comment]
Thank you for reporting this and providing a patch.  Can you provide test images that use those lenses.  We will use your test images to test your patch.  We also add your test images to the test suite to ensure future changes do not disturb your patch.

You can update your local installation of exiv2 v0.26 (and later) be adding lenses to the config file ~/.exiv2.  http://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/

**Comment by D4N** [comment]
@webmeister If you don't have the time to add test cases yourself, then feel free to just paste as many test images as you have access to directly here on github and I'll add tests for you (if you selected the option to allow edits from maintainers, it'll require no extra work from your side). If you want to add the tests yourself, take a look at some of the newer tests like `tests/bugfixes/github/test_issue_227.py`.

**Comment by clanmills** [comment]
This looks harmless.  I didn't pull this into v0.27 because we didn't have test files.  However, I'm OK about this being added to v0.27.1.

**Comment by piponazo** [comment]
Even without the test images? I know nothing about this part of the code, so if you think it is harmless I am happy to merge it.

**Review by clanmills — APPROVED** [review]
I have run the following command (on the build server) on the ExifTool test files with/without these changes.  No difference!  

```
$ exiv2 --pa --grep lens/i /Users/rmills/Jenkins/testfiles/Phils/Canon/*
```
Conclusions:

1) This change has not broken anything.
2) We don't have the test files that use those lenses.

Approved.  This change causes no harm.

**Pull request merged**
