### PR TITLE
Modernization C++ (replace auto_ptr with unique_ptr)

### PR DESCRIPTION
**Pull request by piponazo**
This PR brings the requirement of C++11 to the project and replaces the usage of `auto_ptr` with `unique_ptr`. 

Another change that I took from `old-master` was the removal of the EPS format (which was marked as deprecated in `0.27-maintenance`). I had to do it here to avoid doing useless work in those files.

Original PRs for `old-master`: 
https://github.com/Exiv2/exiv2/pull/257
https://github.com/Exiv2/exiv2/pull/601

### CODE REVIEW

**Comment by clanmills** [comment]
Wow, Luis.  @piponazo That's amazing that you've done this already.  When I got up today, I wrote this issue to deal with Modernisation. #1557.  You've done the code more quickly that I wrote the "requirement spec".

After breakfast, I'll build and look at the code.

**Comment by piponazo** [comment]
There are still some issues in some of the travis-ci jobs, I'll try to deal with them in the next days.

**Review by clanmills — DISMISSED** [review]
That's really impressive, @piponazo It builds and passes the test suite.

I'm happy if you merge.  Or you may wish the submit a new PR on exiv2/exiv2.  I find it much easier to review when it's there.

How do you feel about using gtest 2.0.  I investigated that last year.  I believe it works OK.

To resolve the conflict with the CI files, can you accept mine.  On Sunday I removed travis/Ubuntu-18.04 because it was using python2 to unsuccessfully run the test suite.

Thanks for removing the EPS code.  The ssh and video code is still present.  Perhaps you can submit a PR for that later.

I wrote some notes in #1555 to outline the scope of the "modernisation" project.  I've invited @neheb to join us on v1.00 and hope we can get his clang-tidy changes into v1.00.

This PR is a huge step forward and a precursor to using clang-tidy for code refinement.  Thanks very much.  Good Job!

**Comment by piponazo** [comment]
I will create next commits in the main repository (and not in my fork). I just did it this time on my personal fork to avoid confusion until the `main` branch was created. 

> How do you feel about using gtest 2.0. I investigated that last year. I believe it works OK.

GTest 2.0? I noticed sometime ago that GTest released something new but it is the version 1.10 (see tags in their repo
https://github.com/google/googletest). I do not know if they bring something new that could be interesting for us ... I'll try to take a look to determine if it would be convenient to use the latest version. 

> Thanks for removing the EPS code. The ssh and video code is still present. Perhaps you can submit a PR for that later.

Sure, I'll do it in different PRs. I prefer to have several smalls PRs rather than a huge one where is more difficult to review the changes.

There are still some issues I want to investigate in the travis-build:
https://travis-ci.org/github/Exiv2/exiv2/builds/767134177

I'll merge the PR once I solve them.

**Comment by clanmills** [comment]
I don't know what you've done to the PR, @piponazo.  It seems to be "frozen".  I noticed last night that travis/windows builds we failing.  I can't remember why.  But nothing to do with icc_test.

Thanks for isolating the commands to reproduce the jp2image error.  I'll debug that today on Linux.

**Review by clanmills — APPROVED** [review]

**Pull request merged**
