### PR TITLE
fix bad for range loop

### PR DESCRIPTION
**Pull request by neheb**
This loop is supposed to break when it encounters a match.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

I tried converting this to std::find_if. Didn't work.

### CODE REVIEW

**Comment by neheb** [comment]
Maybe the find is better.

**Comment by neheb** [comment]
find causes address sanitizer issues. Oh well.

**Review by piponazo — APPROVED** [review]
Great! It looks you have fixed the tests that were failing on Windows from time to time. It is interesting to see that those tests were not failing on Linux nor on Mac.

I can backport this change to the 0.27-maintenance.

Thanks!

**Comment by piponazo** [comment]
Ups ... weird, in the PR view all the checks look green, but when I go to the github actions page, I see that some of these flaky tests (on BMFF code) on windows are still failing:

https://github.com/Exiv2/exiv2/runs/2573006142?check_suite_focus=true

Just for clarification. Were you trying to fix some defect in Exiv2 that was already reported?

**Comment by piponazo** [comment]
I was not looking to the right github actions link ... that is the one were all the windows jobs are passing:
https://github.com/Exiv2/exiv2/actions/runs/837867978

What I do not understand is that the failing tests seemed to be on BMFF while your change is in the epsimage.cpp file.

**Comment by piponazo** [comment]
I tried to cherry-pick the change to include it in 0.27-maintenance, but we do not need it there

**Comment by neheb** [comment]
No this was a bad transformation on my part.

**Pull request merged**
