### PR TITLE
add missing commas

### PR DESCRIPTION
**Pull request by neheb**
Formats the structs properly.

### CODE REVIEW

**Comment by kmilos** [comment]
Perhaps roll https://github.com/Exiv2/exiv2/pull/2690 into this please?

**Comment by postscript-dev** [comment]
@neheb 
> Formats the structs properly.

Is it worth changing `.clang-format` to enforce this?

**Comment by neheb** [comment]
What clang-format option?

**Comment by neheb** [comment]
Apparently there's InsertTrailingCommas, but that requires BinPackArguments to be false. The latter looks horrible.

**Comment by postscript-dev** [comment]
@neheb 
>> What clang-format option?

> Apparently there's InsertTrailingCommas, but that requires BinPackArguments to be false. The latter looks horrible.

Thanks for checking. A future `clang-format` version may provide a better option.

**Comment by kmilos** [comment]
> So I tried locally with BinPackArguments and InsertTrailingCommas separately. Seems there are no further changes.

So should we commit this to `.clang-format` then so everyone can use it for future changes?

**Review by kmilos — APPROVED** [review]
LGTM

**Pull request merged**
