### PR TITLE
Remove 'using namespace' from public header

### PR DESCRIPTION
**Pull request by piponazo**
Just a minor improvement. I noticed there was an usage of `usign namespace` in one of the public headers, what it is known as a bad practice.

### CODE REVIEW

**Comment by D4N** [comment]
There's still plenty of `using namespace` in other places. Should we use this PR to get rid of those too?

Appveyor seems to have some problems:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ICONV_LIBRARY
    linked by target "cmTC_250f2" in directory C:/projects/exiv2-wutfp/build/CMakeFiles/CMakeTmp
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.11/Modules/CheckIncludeFile.cmake:60 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  config/generateConfigFile.cmake:35 (check_include_file)
  CMakeLists.txt:83 (include)
-- Configuring incomplete, errors occurred!
```
I think it complained about this too in #264, so it is quite surely unrelated to this PR.

**Comment by piponazo** [comment]
I confirm that I could reproduce the issue on Windows.

**Comment by clanmills** [comment]
I believe Google's coding conventions forbid the use of `using` under all circumstances.  Let's remove `using namespace` from library header files (asfvideo.hpp)

`using namespace Exiv2` is probably OK in library and samples.   If removing `using namespace Exiv2` causes **_many_** code changes, perhaps it should be retained.  **What is "many"?**  200 isn't "many", 1000 is "many".

In C++, "using namespace" is resolved at compile-time and I think that's OK.  In JavaScript "using" causes run-time resolution along the prototype chain and should never have entered the language.

```
538 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ grep 'using *namespace' include/exiv2/*pp src/*pp samples/*pp 
include/exiv2/asfvideo.hpp:using namespace Exiv2::Internal;

src/asfvideo.cpp:    using namespace Exiv2::Internal;
src/convert.cpp:    using namespace Exiv2;
src/cr2image.cpp:    using namespace Internal;
src/crwimage.cpp:    using namespace Internal;
src/easyaccess.cpp:    using namespace Exiv2;
src/epsimage.cpp:    using namespace Exiv2;
src/exif.cpp:    using namespace Internal;
src/image.cpp:    using namespace Exiv2;
src/ini.cpp:using namespace Exiv2;
src/matroskavideo.cpp:    using namespace Exiv2::Internal;
src/orfimage.cpp:    using namespace Internal;
src/pngimage.cpp:    using namespace Internal;
src/preview.cpp:    using namespace Exiv2;
src/properties.cpp:    using namespace Internal;
src/quicktimevideo.cpp:    using namespace Exiv2::Internal;
src/riffvideo.cpp:    using namespace Exiv2::Internal;
src/rw2image.cpp:    using namespace Internal;
src/tags.cpp:    using namespace Internal;
src/tiff-test.cpp:using namespace Exiv2;
src/tiffimage.cpp:    using namespace Internal;
src/tiffmn-test.cpp:using namespace Exiv2;
src/webpimage.cpp:    using namespace Exiv2::Internal;

samples/geotag.cpp:using namespace std;
samples/geotag.cpp:    using namespace Exiv2;
samples/geotag.cpp:    using namespace Exiv2;
samples/iptctest.cpp:using namespace Exiv2;
samples/key-test.cpp:using namespace Exiv2;
samples/mmap-test.cpp:using namespace Exiv2;
samples/taglist.cpp:using namespace Exiv2;
samples/tiff-test.cpp:using namespace Exiv2;
samples/tiffaddpath-test.cpp:using namespace Exiv2;
samples/write-test.cpp:using namespace Exiv2;
539 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```

**Comment by D4N** [comment]
Afaik we don't have an official style guide, do we?

I think we should definitely remove the using namespace from the public header. For the remaining ones we can probably keep them for now.

**Review by D4N — APPROVED** [review]
Once the CI is green we can safely merge this.

**Comment by clanmills** [comment]
Let's remove `using namespace` from asfvideo.hpp and do nothing about src and samples.

I'm making notes for our meeting in May.  http://dev.exiv2.org/projects/exiv2/news  I'll put this on the list for discussion concerning v0.27.  I'd also like to discuss removing the video code and EPS code in v0.28.

**Review by clanmills — APPROVED** [review]
Thanks for reporting and working on this.

**Pull request merged**
