### PR TITLE
Remove duplicate tag info entries fujifilm

### PR DESCRIPTION
**Pull request by norbertwg**
Refers to issue https://github.com/Exiv2/exiv2/issues/2409
The removed lines contained entries for 0x1022 and as "Unknown"; they are included in the other code with name.
Unknown tag 0x1200 removed (as recommended by @postscript-dev ).

### CODE REVIEW

**Comment by norbertwg** [comment]
Sorry, I need help. Some checks were not successful, and I do not know how to fix it.

https://github.com/Exiv2/exiv2/actions/runs/3392606863/jobs/5639001570#logs:
Test starts with `ctest --test-dir build --output-on-failure`
On my Windows 11 machine the command (with an additional `-C Release`) gave no error. 

https://github.com/Exiv2/exiv2/actions/runs/3392606863/jobs/5638995976#logs:
Here it stops already in step `Set up Cygwin`. I cannot image that this failure is caused by my code changes.

**Comment by piponazo** [comment]
Ey @norbertwg , I just retriggered the jobs. The Cygwin issue is something that is already happening on our `main` branch and that I am investigating. Even if it is failing, we could proceed to merge this PR.

The other error I am not sure why it is happening ... that needs to be investigated. Although it is weird that is only happening in one platform 🤔

**Comment by norbertwg** [comment]
@piponazo : thanks for the fast feedback.

I hope somebody else is able to bring some light into the problem with 
https://github.com/Exiv2/exiv2/actions/runs/3392606863/jobs/5639001570#logs

**Review by VJSchneid — COMMENTED** [review]
Hi @norbertwg, thanks for your pull request. I checked your changes in ``fujimn_int.cpp`` and everything looks good to me.

Unfortunately I also don't know what's causing the one MYSYS2 job to fail...
Maybe someone can test whether this job fails now on the ``main`` branch too.

**Comment by postscript-dev** [comment]
@VJSchneid 
> I checked your changes in fujimn_int.cpp and everything looks good to me.

> Unfortunately I also don't know what's causing the one MYSYS2 job to fail...
> Maybe someone can test whether this job fails now on the main branch too.

I have noticed the `MSYS2 UCRT64 - BuildType:Debug - SHARED:ON` fail intermittently on the `main` branch for the past few months. If you re-run the job (sometimes more than once) then it usually completes successfully. This might indicate a race condition in the [io_test](https://github.com/Exiv2/exiv2/blob/026cee3e6a6e5916b63f7c16dc74c773dc8839f8/tests/bash_tests/testcases.py#L566) but I can't replicate the error on my Windows computer. I am not a Python expert but there is a sleep after the [http server](https://github.com/Exiv2/exiv2/blob/026cee3e6a6e5916b63f7c16dc74c773dc8839f8/tests/bash_tests/utils.py#L329) starts, perhaps this needs to be increased.

@norbertwg 
I don't think that the MSYS UCRT64 failure is connected to your PR and if you re-run it then it is likely to pass. Once this occurs, @VJSchneid could review your PR and merge it.

**Comment by norbertwg** [comment]
@postscript-dev 
Thanks a lot for the investigation. Unfortunately I do not know how to re-run MSYS UCRT64. I found instructions saying that there will appear a button "Run workflows" in Actions tab, when the work flow is configured with `workflow_dispatch`. This is not done in the workflow, so should I do it in my fork? Or is there another way to start the workflow manually?

**Comment by postscript-dev** [comment]
> Unfortunately I do not know how to re-run MSYS UCRT64

In #2412, 
1. In the list of checks, scroll down the list to find the one that you are interested in (i.e., `Windows Matrix /MSYS2 UCRT64 - BuildType:Debug - SHARED:ON`) and click "Details".
2. At the top of the new page next to "Search logs", look for the two arrows in a circle and click. Alternatively, you can move your mouse over the the list of checks on the left hand side and the same circular arrow appears.

If you want to run multiple checks again, then use "Re-run jobs" at the top of the page.

**Comment by piponazo** [comment]
I just re-triggered the failing jobs and the MSYS2 passed now.

**Comment by norbertwg** [comment]
@piponazo 
Thanks for re-triggering.
@postscript-dev 
I followed your instructions, but for this PR I did not see the "Re-run jobs". As I found the button for some other jobs in my fork, I think it is a question of permissions. So now I know I how to do it.
@VJSchneid 
You had already a look at the PR, so could you now mark it as reviewed?

**Review by VJSchneid — APPROVED** [review]

**Comment by VJSchneid** [comment]
I have marked this PR as reviewed but unfortunately I do not have write access to this repo. It seems that someone else with write access (maybe @piponazo or @postscript-dev) has to review this PR too, to get this merged.

**Comment by postscript-dev** [comment]
@VJSchneid , @norbertwg 
Sorry, I didn't realise about the permissions. I will review the PR this afternoon.

**Review by postscript-dev — CHANGES_REQUESTED** [review]
Thanks @norbertwg ,your PR looks good. I noticed a typo in a different tag though which is trivial to fix. It would be helpful to include it. In `src/fujimn_int.cpp`, the tag:

```cpp
{0x1425, "SzeneRecognition", N_("Scene recognition"), N_("Scene recognition"), IfdId::fujiId, SectionId::makerTags,
```

should be changed from `"SzeneRecognition"` to `"SceneRecognition"`.

(The tag is only in the `main` branch.)

**Comment by norbertwg** [comment]
> I noticed a typo in a different tag 
Of course, is helpful to include it in this PR. Is done - and I am happy, that except for the known Cygwin all checks were successful.

**Review by postscript-dev — APPROVED** [review]
Thanks @norbertwg

**Pull request merged**
