### PR TITLE
Mingw cross 0.27

### PR DESCRIPTION
**Pull request by clanmills**
Gentlemen.  I'm not done on this.  I'll assign reviewers when ready for review.

### CODE REVIEW

**Comment by clanmills** [comment]
WTF.  There are 20 other submissions here.  Are you sure that git works?

**Comment by D4N** [comment]
Robin Mills <notifications@github.com> writes:

> WTF.  There are 20 other submissions here.  Are you sure that git works?

Yes. Which commits did you want to submit? Give me sha hashes and if
they are on github, I'll create a branch with them for you.

**Comment by D4N** [comment]
Done. 

Please submit a new PR from the same branch, I have dropped all the extra commits.

It looks like you didn't base your submission on the latest state of 0.27, which created the weird addition of commits. I fixed the situation via these commands:
```
git checkout mingw-cross-0.27
git reset --hard origin/0.27
git cherry-pick e2edcb4
git push --force-with-lease
```

**Comment by clanmills** [comment]
Thanks for doing this.  Git is very mysterious when you don't understand it.  Over the years, lots of folks have advocated that Exiv2 should use git.  I resisted because I was afraid of getting "locked out" and that's exactly what happened.  My other fear has been that Exiv2 would die if I didn't maintain it.

However by moving to GitHub, you and Luis have joined me and that's given the project new life.   I'm almost at the point where I can know enough git to maintain v0.27 while you and Luis move the code into the future.  So things are in good shape.

I hope we'll attract another couple of contributors as that would take pressure off you and Luis.  However if I maintain v0.27 for two years, that will ease the strain on you.

Thank You for your help.

**Pull request closed without merging**
