### PR TITLE
Add shutter mode and mechanical shutter count to nikon makernote 3

### PR DESCRIPTION
**Pull request by hassec**
These were easy enough to add, and I figured they might be useful.  

Added a quick test based on the Nikon z6 file (`CH0_0174.exv`) that is already in the repo to test the version 8 lens data.

### CODE REVIEW

**Comment by clanmills** [comment]
Thanks @hassec.  A couple of comments:

1.  Do we need print0x0034?  There's a macro to match values to string definitions for prettyPrinters.  I think expects the value to be an index.  However it would be nice to have a variant of that in which the value value is a key to a sparse vector of strings.  We might be able to use that to simplify lots of pretty printers.  What do you think?  

2. You can put more than one test into a python script.  Have a look at test_issue_981.py You can almost certainly add the test you're put into tests/bugfixes/github/test_pr_1444.py to the file tests/bugfixes/github/test_pr_1437.py.  And that makes sense because this PR is really a supplement to #1437.

**Review by clanmills — COMMENTED** [review]
Have a look at nikonFlashComp.  Its a TagDetails array, which is a sparse array of value/strings.  Can you use something similar to eliminate the need for print0x0034?

**Comment by hassec** [comment]
Thanks for the quick review @clanmills :)

I've moved the test into the one you suggested.  

Re `print0x0034`, I'm not sure what would be best. As you already said, the `EXV_PRINT_TAG` macro unfortunately won't work for this without modification. 
That's why I just went along with the style of the file and created another `printXYZ` function.  
I think for this particular case it makes for a compact PR that can't really break anything existing.  
If it was up to me I'd leave a larger refactoring of the overall printing functionality for a new PR that can target master and use C++11.  

But  I don't have a super strong opinion, am just a bit hesitant of moving too much code around in the maintenance branch as I don't want to break anything :D

**Comment by clanmills** [comment]
You're right.  We shouldn't do a big edit on working code.

However, if you can get things to work with a TagDetails array instead of print0x0034() I would much prefer this.

**Comment by hassec** [comment]
Thanks for the suggestion @clanmills! I updated my comment above, I had actually misunderstood the macro.  

Just adapted to code accordingly. It's now even shorter and thus nicer ;)

**Review by clanmills — APPROVED** [review]
Good Job.  Very nice job.

Very clever of you to add the extra -g shutter/i stuff to the existing test.  Less is always more in software.

**Comment by clanmills** [comment]
When the CI is green, please merge.

**Comment by hassec** [comment]
@clanmills I don't have the rights to merge

**Comment by clanmills** [comment]
Let me look at the permissions.  You obviously an good engineer and I'm happy for you to merge.

**Comment by clanmills** [comment]
I thought I added you last week.  Anyway, you should be in now.

When you want to submit a PR in future, can you create it in the exiv2/exiv2 repos.  Much easier work-flow.  Other team members can edit/update it.  And easier for me to sync/build/review.

**Comment by hassec** [comment]
Awesome! Thanks a lot, it's much appreciated :+1:

**Pull request merged**
