### PR TITLE
Remove occurrences of EXIV2_BUILDDIR and rely in EXIV2_BINDIR

### PR DESCRIPTION
**Pull request by piponazo**
As discussed, here I remove the usage of `EXIV2_BUILDDIR` to rely in `EXIV2_BINDIR`

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
Very good work, thank you.

I wonder if any of this works with MSVC.  I have a script test/testMSVC.sh  I'll have a look at that on Wednesday.  It tests msvc builds from Cygwin/bash.

Do you know if a DOS command such as 'c:\...\> cmake --target tests` can run the python test suite?

**Comment by D4N** [comment]
I believe I added this code in 653814afb0f67f23b7ee2a34409e9f1ae6232631 for a reason. If I recall correctly, then I added that to get the deploy stage on gitlab to work correctly. Could you submit this to a branch on Exiv2, too, so that the gitlab build will run now and not after it is merged?

**Comment by piponazo** [comment]
Sure, then I'll close this PR to not have two of them opened.

**Comment by clanmills** [comment]
Great Work, Guys.

**Pull request closed without merging**
