### PR TITLE
Exiv2 v0.28.0

### PR DESCRIPTION
**Pull request by nehaljwani**
It is time to cut a release 🙂

xref: https://github.com/Exiv2/exiv2/issues/2406

### CODE REVIEW

**Comment by neheb** [comment]
I'd also make the necessary changes to the meson.build file.

**Comment by neheb** [comment]
Maybe also undo https://github.com/Exiv2/exiv2/commit/dd48bb13ee1ee0dd8943913e73b3d820eda468a8

Was needed when version was 1.0.0

**Comment by neheb** [comment]
So the soversion is automatic when version is specified. That commit is an override.

**Comment by nehaljwani** [comment]
According to the [manual](https://mesonbuild.com/Reference-manual_functions.html#arguments10), it seems to default to the project major:
> For example, if version is 3.6.0 and soversion is not defined, it is set to 3.

But we have been setting it to the minor version (before 1.0.0), so the override is required.

**Review by neheb — APPROVED** [review]

**Pull request merged**
