### PR TITLE
#199 Fix for getopt().  Replace libc/getopt() with src/getopt_win32

### PR DESCRIPTION
**Pull request by clanmills**
I hope this is has been correctly submitted.

### CODE REVIEW

**Comment by piponazo** [comment]
The changes look good and the CI checks are passing in both platforms. I think this is good to go!

**Review by piponazo — APPROVED** [review]

**Comment by clanmills** [comment]
That's great.  Thanks @piponazo 

Can you do the merge (or whatever is required) to move this into 'master'.

**Comment by D4N** [comment]
Robin, could you do a `git pull --rebase exiv2_upstream/master` (replace the `exiv2_upstream` with the name of the Exiv2 remote), then we can merge this.

**Comment by clanmills** [comment]
```
$ cd ~/gnu/github/clanmills/exiv2
$ git remote add exiv2_upstream https://github.com/Exiv2/exiv2.git
$ git remote -v
exiv2_upstream	https://github.com/Exiv2/exiv2.git (fetch)
exiv2_upstream	https://github.com/Exiv2/exiv2.git (push)
origin	http://github.com/clanmills/exiv2 (fetch)
origin	http://github.com/clanmills/exiv2 (push)
$ git pull exiv2_upstream/master
fatal: 'exiv2_upstream/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
$ 
```

**Comment by D4N** [comment]
I had a typo in the original message, it should be:
$ git pull --rebase exiv2_upstream master

Please don't omit the --rebase.

You'll have to then do a:
$ git push --force

**Comment by piponazo** [comment]
Hi guys. For this case it was easier to just press the button "Rebase and merge" that does the rebase-magic without needing to type in the command line. 

You can find more information about the different merging strategies used by Github in this link:

https://help.github.com/articles/about-pull-request-merges/

**Pull request merged**
