### PR TITLE
meson CI: update to GCC 14

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
hrm.

So meson on macOS fails with address sanitizer on test_slice. Other CI with CMake fails on test_basicio. Probably they all fail. I assume GTest bug on arm64.

**Comment by neheb** [comment]
Aaaand works when I use the wrap instead of the brew package.

**Review by kmilos — APPROVED** [review]
The changes LGTM, but any idea why the Mac CI still fails? I think unrelated to this change - switch to arm4 runner by default?

**Comment by neheb** [comment]
arm64 is default. It’s probably a brew issue.

**Pull request merged**
