### PR TITLE
various clang fixes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Review by kmilos — APPROVED** [review]
LGTM

**Comment by kmilos** [comment]
Hm, didn't seem to do it for CLANG64 still:
```
C:/msys64/home/kmilos/exiv2/samples/easyaccess-test.cpp:15:3: error: constexpr variable 'easyAcces
s' must be initialized by a constant expression
} easyAccess[] = {
  ^              ~
1 error generated.
```

No idea what's going on...

**Comment by neheb** [comment]
No they're pointers. Using & results in a const pointer unless you const_cast.

Maybe one of those functions is missing for some reason.

**Comment by neheb** [comment]
According to ChatGPT: 

```
The error you're seeing is caused by the fact that the Exiv2::ExifData::const_iterator type is not a literal type, which means it cannot be used in a constexpr context.
```

**Pull request merged**
