### PR TITLE
change print of Exif.Canon.SerialNumber

### PR DESCRIPTION
**Pull request by norbertwg**
reference: #2792
In general serial number is just printed as decimal. Exception for EOS D30, where higher bytes are printed as hex, lower bytes as decimal, the format, which was used for all Canon devices before this change.
Output is now aligned with Canon Photo Digital Professional 4 (except leading zeros). A few exceptions, where the images have two entries in Exif.Canon.SerialNumber (which looks strange): then Canon Photo Digital Professional shows only one number.
As print0x000c was also used for 0x000a, new function print0x000a as copy from old print0x000c.

### CODE REVIEW

**Comment by neheb** [comment]
rebase to main

**Comment by norbertwg** [comment]
I did a rebase.

**Comment by norbertwg** [comment]
This pull request is waiting for approving review since 5 months. Are there reasons not to approve this request or was it just lost out of sight?

**Comment by norbertwg** [comment]
CodeQL warnings are fixed, but "On PRs - Mac Special Builds / macOS - XCode - Release+Sanitizers (pull_request)" fails. From job output I have no idea, what is the reason for that.

**Review by kmilos — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
