### PR TITLE
Add Exif Gamma tag

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Review by clanmills — DISMISSED** [review]
Several comments:

1.  Do you have a test file and python script?
2.  Are there other missing Exif Tags from Table 7 of https://fotomagazin.hu/wp-content/uploads/2020/05/CIPA_DC_008_EXIF_2019.pdf
3. What do you think about adding the tags in #1397 to this PR?
4. Is printFloat() the correct prettyPrinter?  Do you know how ExifTool presents this data.?  I think it's between 0.0 and 1.0  If in doubt ask @alexvanderberkel because he knows about Photography.

**Comment by clanmills** [comment]
I see this has died a horrible (and well deserved) death in the test suite.  You'll have to update that. For example:

```bash
/Users/travis/build/Exiv2/exiv2/test/data/exiv2-test.out: 8756 lines
863/Users/travis/build/Exiv2/exiv2/test/tmp/exiv2-test.out: 8756 lines
864The first mismatch is in line 979:
865< 20040329_224245.jpg   Exif.Photo.0xa500                            Rational    1  22/10
866> 20040329_224245.jpg   Exif.Photo.Gamma                             Rational    1  2.2
```

It's easy to fix.  You'll have to edit test/data/exiv2-test.out and replace \>0xa500\< with \>Gamma \<.  Watch out for the space following Gamma.

**Comment by clanmills** [comment]
When the test suite has been fixed, we don't need to bother adding anything to the python tests (in tests/bugfixes/github).  It's already tested by exiv2-test (which is in tests/bash_tests).  It's is called 'bash_tests' for historical reasons.  Leo rewrote them in python and that make them much easier to run on Visual Studio builds.

**Comment by clanmills** [comment]
Thanks.  I'm happy to see this merged.  The existing way (prior to the change) is:

```
632 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ exiv2 -g a500 --unknown test/data/exiv2-nikon-d70.jpg
Exif.Photo.0xa500                            Rational    1  22/10
633 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance $ 
```

It's so much nicer with your PR:

```bash
641 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ exiv2 -g gamma/i ../test/data/exiv2-nikon-d70.jpg
Exif.Photo.Gamma                             Rational    1  2.2
642 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ 
```

And that "rhymes" well with ExifTool:

```bash
642 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ exiftool ../test/data/exiv2-nikon-d70.jpg | grep -i gamma
Gamma                           : 2.2
643 rmills@rmillsm1:~/gnu/github/exiv2/main/build $ 
```


I'm not going to back-port it to 0.27-maintenance.  After RCfinal, I only want to change the revision number and update documentation.  I avoid C++ changes.  It's the same reason that I don't want to add Exiv2::enableBMFF() without EXV_ENABLE_BMFF.

If we must have an RC3 (for a security fix or darktable reports a bmff issue), I can back-port this PR to 0.27-maintenance.

**Review by clanmills — APPROVED** [review]
Good Job, @kmilos.  Thanks for dealing with this.

**Comment by kmilos** [comment]
Sure, that release policy makes sense.

Thanks.

**Pull request merged**
