### PR TITLE
[0.26] cmake backports from master

### PR DESCRIPTION
**Pull request by a17r**
I've been applying these downstream for some time.

### CODE REVIEW

**Review by piponazo — APPROVED** [review]

**Comment by piponazo** [comment]
Now that the travis changes are merged into 0.26 I think you can update this branch so it gets compiled on travis-ci

**Comment by D4N** [comment]
Please update your feature branch via `git pull --rebase` and force push so that we get a more linear history.

I'd also like to test this on my older machine later today before we merge this.

**Comment by a17r** [comment]
Rebase done already, just in case you did not get the force-push notification.

**Comment by a17r** [comment]
(of course this wouldn't be complete without https://github.com/Exiv2/exiv2/pull/122)

**Pull request merged**
