### PR TITLE
Use official Canon RF lens model names

### PR DESCRIPTION
**Pull request by cytrinox**
The new RF line is named F2.8L instead of f/2.8L (for example).

This patch makes the model names identically to the official
Canon lens names and the same names exiftool uses.

### CODE REVIEW

**Comment by cytrinox** [comment]
@hassec There is one little problem: **Canon RF 100-500mm F4.5-7.1L IS USM + RF2x** exists twice in current main. I assume one should be for 1.4 extender, but which one?

**Comment by hassec** [comment]
> @hassec There is one little problem: **Canon RF 100-500mm F4.5-7.1L IS USM + RF2x** exists twice in current main. I assume one should be for 1.4 extender, but which one?

The order of the array doesn't matter, only the number (here 61182) matters. 
As they all have the same one just pick one of the duplicates.

This change will require 2 more tiny changes to make the testing work. Do you mind if I just push them here?

Thanks a lot for taking the time to fix this!! :+1:

**Comment by cytrinox** [comment]
Yeah, go on.
-- 
Best regards / Mit freundlichen Grüßen
Daniel Vogelbacher

Am 21. Juni 2021 22:32:40 MESZ schrieb Christoph Hasse ***@***.***>:

**Comment by alexvanderberkel** [comment]
I noticed the bug as well and started to correct it inside the PR https://github.com/Exiv2/exiv2/pull/1628/files

**Comment by alexvanderberkel** [comment]
It is easier to identify the new RF lenses via the tag RFLensType. There we have a clear number that identifies the RF lenses, whereas lensmodel is ambiguous. Tag a look at https://exiftool.org/TagNames/Canon.html#LensType

**Comment by hassec** [comment]
> It is easier to identify the new RF lenses via the tag RFLensType. There we have a clear number that identifies the RF lenses, whereas lensmodel is ambiguous. Tag a look at https://exiftool.org/TagNames/Canon.html#LensType

@alexvanderberkel I think we should merge this PR as it's a clear improvement and then worry about the `RFLensType` improvements in your PR, as you already did the work there. WDYT?

**Comment by hassec** [comment]
@cytrinox I've also pushed the change to turn the duplicated `2x` version into the `1.4x` version.   

From my side this now looks ready, anything you still want to add?

**Comment by cytrinox** [comment]
@hassec looks good to me.

**Review by hassec — APPROVED** [review]
LGTM :heavy_check_mark: 

Thanks again @cytrinox for the PR! :+1:

**Pull request merged**
