### PR TITLE
LOCALEDIR is used by EXIV2_ENABLE_BUILD_PO so make sure it is defined

### PR DESCRIPTION
**Pull request by a17r**
Otherwise it is possible to install translations in `/` if `EXIV2_ENABLE_NLS=OFF`.

### CODE REVIEW

**Comment by a17r** [comment]
However, it might be worth checking if the variable incl win32 check can be dropped entirely for using gnuinstalldir path again. But I cannot test on Windows.

**Comment by a17r** [comment]
@piponazo I can squash both commits if you are in favor of it.

**Comment by clanmills** [comment]
@piponazo We discussed libintl and the library.  tags.cpp and exiv2.cpp use libintl.  tags.cpp is part of the library.  exiv2.cpp is main() for the the exiv2 command-line-program.  So, we need to link libintl with libexiv2.
```
581 rmills@rmillsmbp:~/gnu/github/exiv2 $ grep domain src/*.cpp
src/exiv2.cpp:    bindtextdomain(EXV_PACKAGE, EXV_LOCALEDIR);
src/exiv2.cpp:    textdomain(EXV_PACKAGE);
src/types.cpp:        bindtextdomain(EXV_PACKAGE, EXV_LOCALEDIR);
src/types.cpp:        bind_textdomain_codeset (EXV_PACKAGE, "UTF-8");
582 rmills@rmillsmbp:~/gnu/github/exiv2 $ 
```
Being a native English speaker, my brain isn't built to understand localisation.

**Comment by piponazo** [comment]
The changes look good, thanks @a17r ! 

the only thing I would try to check is to replace the `add_definitions( -DEXV_LOCALEDIR="${CMAKE_INSTALL_LOCALEDIR}" )` by : 

```
target_compile_definitions(exiv2lib PRIVATE EXV_LOCALEDIR="${CMAKE_INSTALL_LOCALEDIR}" )
target_compile_definitions(exiv2     PRIVATE EXV_LOCALEDIR="${CMAKE_INSTALL_LOCALEDIR}" )
```

In that way we do not add the definition to other things (the XMP static library, the sample applications, etc). 

Could you try that @a17r ? If it is too much work, I can merge this as it is and take care of what I just described.

**Comment by a17r** [comment]
Thanks, works fine for me.

**Comment by piponazo** [comment]
Thanks @a17r for taking care of the suggestion 👍 

I will merge once travis finishes its jobs :)

**Pull request merged**
