### PR TITLE
Remove obsolete SVN revision and EXIV2_RCSID

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by piponazo** [comment]
Hi @tbeu could you give describe why you are proposing to remove this "EXIV2_RCSID" thing ? Looking at the code I do not think it is something important, but I would like to know why this thing was in the project. Maybe @clanmills knows a bit more about the historial reasons.

**Comment by tbeu** [comment]
It simply is obsolete and was introduced when the repo was on svn. @ahuggel knows why it was needed at all.

https://github.com/Exiv2/exiv2/blob/06ce0d18b694a08d71948211a38fdb569b30adc9/src/rcsid_int.hpp#L49-L52

**Review by piponazo — APPROVED** [review]

**Review by D4N — APPROVED** [review]
I don't think we are going to need version information stored in each file, especially as git knows that anyway and is at it than us tracking it manually.

**Comment by D4N** [comment]
If I understand the `EXIV2_RCSID` macro, it simply creates version information inside each translation unit. Don't know why one would want that and the project from which Andreas took the idea (ACE) also dropped this feature. So I'll doubt we'll miss it.

**Comment by tbeu** [comment]
Yes, it simply is a legacy remainder from the svn days.

**Pull request merged**
