### PR TITLE
Fix lens name

### PR DESCRIPTION
**Pull request by greenbigfrog**
I recently noticed that the lens "Sigma 18-200mm f/3.5-6.3 II DC OS HSM" is named wrongly in exif2. The currently reported name is "Sigma 18-200mm f/3.5-6.3 DC OS HSM [II]" but it should be "Sigma 18-200mm f/3.5-6.3 II DC OS HSM".

Can't find a official sigma page on it anymore, since it's quite old by now. http://www.imaging-resource.com/lenses/sigma/18-200mm-f3.5-6.3-ii-dc-os-hsm/review/

```
$ exiv2 -pt FILE | grep -ai lens
Exif.CanonCs.LensType                        Short       1  Sigma 18-200mm f/3.5-6.3 DC OS HSM [II]
Exif.CanonCs.Lens                            Short       3  18.0 - 200.0 mm
Exif.Canon.LensModel                         Ascii      74  18-200mm
Exif.Photo.LensSpecification                 Rational    4  18/1 200/1 0/1 0/1
Exif.Photo.LensModel                         Ascii       9  18-200mm
Exif.Photo.LensSerialNumber                  Ascii      11  0000000000
```

### CODE REVIEW

**Comment by clanmills** [comment]
I'm happy to add your patch, however I always like to add a test file to our test suite for such a fix.  May I ask you for a test file?  We only add the metadata from your test file to the test suite, so you image will remain private.  I'll deal with the test suite, you only have to attach your test image to this PR.

A feature was added to Exiv2 v0.26 to enable you to add/modify lens recognition using the file ~/.exiv2.  This is discussed here:  http://dev.exiv2.org/boards/3/topics/2854?r=2861#message-2861

**Comment by greenbigfrog** [comment]
Took me a bit till I totally understood what you meant :smile: maybe add a page in the wiki, on how to add test images/data.

https://a.pomf.cat/chjxqo.cr2
is the above picture fine, or should I take a smaller/lower res one? (and is raw fine?)

**Comment by D4N** [comment]
I am currently in the process of rewriting the test suite, so if you
don't need this feature merged ASAP and are willing to wait a week or
two, I can ping you when I am finished. Then we could simply include the
file in the new test suite (which should be hopefully simpler to use).

**Comment by greenbigfrog** [comment]
I'm in no hurry so whatever works best for you. (Only need it locally right
now, and I can just install local)

On Oct 10, 2017 10:20, "D4N" <notifications@github.com> wrote:

I am currently in the process of rewriting the test suite, so if you
don't need this feature merged ASAP and are willing to wait a week or
two, I can ping you when I am finished. Then we could simply include the
file in the new test suite (which should be hopefully simpler to use).

Jonathan <notifications@github.com> writes:

> Took me a bit till I totally understood what you meant :smile: maybe add
a page in the wiki, on how to add test images/data.
>
> https://a.pomf.cat/chjxqo.cr2
> is the above picture fine, or should I take a smaller/lower res one? (and
is raw fine?)
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Exiv2/exiv2/pull/112#issuecomment-335208843

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Exiv2/exiv2/pull/112#issuecomment-335397800>, or mute
the thread

**Comment by clanmills** [comment]
Thanks for sending the test file.  I'm going to leave @D4N to integrate your file and code when he works on the test suite.

In the past, I've tried to avoid discussing the test suite with users and simply asked them to send a test file.  The reason is to save you time!  It's a five minute job to add a file to the test suite.  However, if you don't know the test suite, you have to read the scripts and figure out what to do.

**Review by clanmills — APPROVED** [review]

**Comment by clanmills** [comment]
I changed my mind and submitted the code and update to the test suite.

@D4N has accepted the challenge to refactor the script "test/bugfixes-test.sh" which has grown overtime into a monolith.   It's effective.  It'll be more modular in future.

**Comment by clanmills** [comment]
Closing this.  The request has been dealt with externally.

**Pull request closed without merging**
