### PR TITLE
Improve symbol visibility support

### PR DESCRIPTION
**Pull request by piponazo**
As described in #448 , in non-Windows platforms the compilers like gcc or clang tend to export all the symbols by default. In this PR I am changing this behaviour and hiding the symbols by default.

The code to handle how we export/import symbols has been replaced. Instead of using the code we had in the file `config.h` we use the GenerateExportHeader provided by CMake. 

The usage of `EXV_DLLLOCAL` has been removed (note that it was doing nothing on Windows).

Note that the number of exported symbols went down from 9489 to 6223.

### CODE REVIEW

**Comment by piponazo** [comment]
Note that clang with ASAN was detecting the following issue:
```
+./unit_tests
=================================================================
==15324==ERROR: AddressSanitizer: odr-violation (0x000000af9c80):
  [1] size=8 'Exiv2::ExifKey::Impl::familyName_' /home/travis/build/piponazo/exiv2/src/tags.cpp:3068:32
  [2] size=8 'Exiv2::ExifKey::Impl::familyName_' /home/travis/build/piponazo/exiv2/src/tags.cpp:3068:32
These globals were registered at these points:
  [1]:
    #0 0x49040e in __asan_register_globals /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_globals.cc:358:3
    #1 0x6d7aeb in asan.module_ctor (/home/travis/build/piponazo/exiv2/build/bin/unit_tests+0x6d7aeb)
  [2]:
    #0 0x49040e in __asan_register_globals /local/mnt/workspace/tmp/ubuntu_rel/llvm/utils/release/final/llvm.src/projects/compiler-rt/lib/asan/asan_globals.cc:358:3
    #1 0x7fe87bd207cb in asan.module_ctor (/home/travis/build/piponazo/exiv2/build/lib/libexiv2.so.0+0x70b7cb)
```
The reason is that the file `tags.cpp` is part of the target `exiv2lib_int` which is a CMake OBJECT library. That is just a collection of object files that is used for two things:

1. Obviously to build the **exiv2lib** library.
2. Then those object files are reused in the `unit_tests` target for being able to test the internals of the library. 

Since in `tags.cpp`we define a static const char*, the issue that ASAN is detecting is that such global is being defined twice in the unit tests. For the moment I think we can just skip such ODR issues (since this particular one is not relevant). However, at some point we should improve the overall design and enable the ODR detection again.

**Review by clanmills — APPROVED** [review]
@piponazo I'm going to approve this to ensure you're able to integrate this on Friday.  If I see something that needs to be changed, I'll raise an issue.

**Comment by piponazo** [comment]
After the latest changes, I could enable the ODR detection again, since now `tags.cpp` is not part of **exiv2lib_int**. Note that I will not squash the commits in this branch intentionally to show the steps I had to take to fix the visibility issues on the different platforms. It has been a painful process, but it finally works for all the platforms.

**Comment by D4N** [comment]
LGTM (can't approve, I'm on mobile).

A note concerning Clang's ODR detection: it can be annoying from time to time due to false positives. I had it for instance throw errors because two assertions used the same error message.

**Pull request merged**
