### PR TITLE
github CI: test clang-cl as well for meson

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
```
lld-link: warning: found both wmain and main; using latter
```

https://github.com/huangqinjin/wmain/commit/f9a818553e8b320c2941af4dd7032470acf770d6 is interesting. For meson, I just compile the cpp file as part of exiv2. Maybe I need to switch to doing a static lib...

**Comment by kmilos** [comment]
Can we save/eliminate some jobs somewhere else?

For example, it seems the nightly ones run on every PR/merge instead of once a day...

**Comment by neheb** [comment]
https://github.com/Exiv2/exiv2/blob/main/.github/workflows/on_PR_linux_matrix.yml can probably go away.

same with https://github.com/Exiv2/exiv2/blob/43ffc614f39f8069e121450c9a198650f217ca3c/.github/workflows/on_PR_windows_matrix.yml#L82C1-L82C9

https://github.com/Exiv2/exiv2/blob/main/.github/workflows/on_push_ExtraJobsForMain.yml is questionable.

**Review by kmilos — APPROVED** [review]
LGTM

**Pull request merged**
