### PR TITLE
C++11 compatibility for headers

### LINKED ISSUE #2255: Can we keep public headers C++11 compatible?
While we have moved to using C++17 internally, I think we should try to investigate how painful it would be to keep the public headers C++11 compatible. 

Some recent MRs for example introduced `std::string_view` into `basicio.hpp`.
https://github.com/Exiv2/exiv2/blob/7ebf2a184e28bf638a39aa30ed3784c5035b668a/include/exiv2/basicio.hpp#L698 

This is motivated by a report on the matrix channel by @aurelienpierre who stumbled over this when trying to compile darktable (C++11) with the latest master version of exiv2.   

cc @piponazo @kevinbackhouse @kmilos @neheb @alexvanderberkel

### PR DESCRIPTION
**Pull request by neheb**
I'll put this as a draft.

I tested compilation with darktable and it seems that compilation worked.

OTOH, when I look at some of the other stuff in the headers like std::remove_cv_t, that gets introduced in C++14. I need a way to test C++11 compilation of all the headers.

### CODE REVIEW

**Comment by neheb** [comment]
those C++14 changes are quite verbose...

**Comment by neheb** [comment]
That alert is not fixed as much as it is hidden honestly.

**Comment by piponazo** [comment]
Hi @neheb . Why are you proposing this change? Did the team recently have a discussion about using C++11 in our API? As far as I remember, in the team chat few people voted to choose C++17 for the development in main

**Comment by neheb** [comment]
@piponazo I tested with

```
c++ -DEXIV2API='' -std=c++11 *.hpp
```

and no more C++17 warnings.

```
[[noreturn]]
```

is interesting though. It gets introduced in C++17, that's true. But the C++ standard says that unknown attributes should not be an error. No idea if this should be handled.

**Review by piponazo — APPROVED** [review]
The changes look good to me. The only things missing is the automatic method to test. It would be nice to have a mechanism to detect automatically when somebody place new code in the headers which is not C++11 compliant. But we can take care of that in a different PR.

**Pull request merged**
