### PR TITLE
Fix long-running loop

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fix one of the problems mentioned here: https://github.com/Exiv2/exiv2/issues/2450#issuecomment-1453396653

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
@mohamedchebbii @benmccann

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
The meson failure is probably related to MSVC's /analyzer and memory usage.

I guess I should disable it...

**Comment by kevinbackhouse** [comment]
Thanks for reviewing, @neheb! Not sure what to say about the meson failures: does this always happen, or is this the first time?

**Comment by neheb** [comment]
Started happening recently

**Pull request merged**
