### PR TITLE
Update Nikon lens database.

### PR DESCRIPTION
**Pull request by FreddieWitherden**
This request updates the Nikon lens database through a careful merge with the database of Rottmerhusen.  Note that it looks as if we'll need to make a judgement call around how to handle the "S" and "C" suffixes on Sigma lenses.

### CODE REVIEW

**Comment by clanmills** [comment]
Thank you for submitting this PR.  I had a conversation recently with @frli8848 about this subject as he requested changes to that code.  I believe he contacted Mr Rottmerhusen.  I'll email @frli8848 (Fredrik) and ask him to comment on this.

I have a Nikon D5300 + Sigma 18-250mm Lens.  However I don't know what the "C" and "S" suffix is, so I'm not sure where to begin on a "judgement call".  Do you have advice to offer?

The most common bug report that arises in Exiv2 is to add recognition for new lenses.  For this reason, I added a feature to Exiv2 v0.26 enable users to define their own lens in the file ~/.exiv2 This is described in this document:  http://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/

Having the "config file" takes pressure off judgement calls.  If we choose a path that disturbs the recognition of an existing lens, the user has a possibility to restore the recognition.  However, in general, my judgement is to retain existing lens recognition and encourage users to add new lenses to the file ~/.exiv2.

**Comment by clanmills** [comment]
Conversation with @frli8848  is #227

**Comment by frli8848** [comment]
The S (Sports) and C (Contemporary) is only used in the latest generation of the Sigma lenses - there is also A (Art) lenses. Sigma has a list here:

https://www.sigma-global.com/en/lenses/

Previously the notation:
<pre>
| S
| C
| A
</pre> 
was used and not
<pre>
Sports
Contemporary
Art
</pre>
It looks like there is a mix of several different notations now. I think we should use the shorter  `| S/C/A` notation to avoid text truncation in some apps (like Darktable). Also, by a quick look it seems like the 120-300 2.8 | S lens I added is removed by this commit. 

Do we have any example images from these new lenses?

**Comment by FreddieWitherden** [comment]
Whilst `~/.exiv2` is a useful stopgap measure, it is not without its problems.  Firstly, for casual users requiring them to know the internal ID of their lens may be a barrier to entry.  Secondly, there are downstream projects (such as lensfun) which depend on the precise name of the lens.  Thus, if there is the possibility of users all giving different names to the same lens, it will break these projects.

For these reasons, wherever possible, my view is we should try and get support for lenses into exiv2.

**Comment by frli8848** [comment]
@clanmills how do you normally review new lens contributions? Should we check lens-by-lens and verify against the manufacturers data sheets etc. I guess we don't have lens data (jpg/exv files) for all these lenses.

**Comment by clanmills** [comment]
In the past, when I've added code to recognise a lens, I'll added a .exv to the test suite.  I only took on the maintenance of that code since around 2015, and I don't know what tests predate that time.

I don't see the ~/.exiv2 file as a "stop gap".  ~/.exiv2 is a way to enable the user to update the lens recognition without waiting for an exiv2/distro refresh (about 2 years).  Lens recognition is non-deterministic.  It requires interpretation of the metadata to deduce the lens in use.

About a couple of years ago, I discovered that exiftool has about 7000 test images and I downloaded them to our buildserver.  http://exiv2.dyndns.org:8080/userContent/testfiles/Phils/ and also the raw files from http://www.rawsamples.ch/index.php/en/ which were copied here:  http://exiv2.dyndns.org:8080/userContent/testfiles/raw/

There is an outstanding project to use these files to compare the output of Exiv2 with exiftool and also to provide more testing of Exiv2 with Raw images.  http://dev.exiv2.org/issues/992 

There are many outstanding ways in which we can enhance the infra-structure, test, build, lens recognition, localisation, security, XMPsdk support and other aspects of Exiv2.  As an unpaid volunteer, I have to prioritise.  I added the ~/.exiv2 feature to enable the user to avoid a long frustrating wait for a new release of Exiv2 when a lens is not recognised or incorrectly recognised.

The obvious way in which to do more with Exiv2 is to have more volunteers.  I'm delighted to say that, since the move to GitHub in April 2017, the project has more contributors.  There will be an "Exiv2 Developer's Meeting" at my home in England in May when I'm looking forward to enjoying time with Dan and Luis to discuss the project and prioritise the demands on the project.  https://github.com/Exiv2/exiv2/issues/225

**Comment by frli8848** [comment]
@clanmills Now I remember reading about the rawsamples.ch site on the Darktable blog. It looks like the site was hacked some time ago and is now not up-to-date. There is however a new site: 

https://raw.pixls.us

see:  https://www.darktable.org/2017/01/rawsamples-ch-replacement/

The data is CC0 licensed (=public domain) so we can use it to create exv files if we want! One can even download the whole repo as a zip-file so we can probably batch-convert all files to exv. 

https://raw.pixls.us/getfile.php/0/archive/raw_pixls_us_archive.zip

**Comment by FreddieWitherden** [comment]
@clanmills While I agree that there are edge cases in which lens determination is not necessarily deterministic, we should not let these get in the way of trying to support those lenses which can be resolved in a deterministic fashion.

The delay between us adding support upstream for a lens and it getting into the hands of users downstream is unfortunate.  Longer term one option might be to move all of the lens data out into text (JSON or XML) files.  We can then ship a utility with exiv2 to go and fetch the newest versions of these files from Git and put them in the users home directory.  This, however, would require a lot of development effort and so probably should not be a priority in the near term.

**Comment by clanmills** [comment]
The ~/.exiv2 file is a simple effort to move the lens recognition outside of the compiled Exiv2 code.  It was implemented in a morning!

I wrote compilers and interpreters for a living before I retired.  I could create a language interpreter to perform lens recognition.  We could add an option to exiv2 to say "update the lens recognition magic".  We could use a webservice (which would execute exiftool).  We could call exiftool if it's installed on the machine.  Lots of possibilities.  http://dev.exiv2.org/issues/1034

Please understand that Exiv2 has been mostly a one man project and I've never had sufficient time to do anything other than think about this.

I'm delighted to say that I have two excellent engineers working with me now and we're having a "Exiv2 Developer's Meeting" at my home in England on May 5/6.  Lens recognition is on the agenda for discussion:  http://dev.exiv2.org/news/3

**Comment by frli8848** [comment]
I have only looked at the Nikon F-mount code but that code is just a table which would not be that difficult to read from an external file. SQLite databases is another option that can be considered too perhaps.

**Comment by clanmills** [comment]
We can put that data into ~/.exiv2 and read it on demand.  Something like:

```
[nikon-f-mount]
abc-def=something
xyzzy-123=something else
...
```

The parser to read ~/.exiv2 is already in the code base (_**src/ini.cpp**_)  We can put a **`static std::map<something>* f_mount = NULL; `** in _**src/nikonmn_int.cpp*__.  When the data is needed, we can read it into memory.  The performance hit would be negligible.

As you know, we're having a team meeting on May 5/6 and lens recognition will be discussed.  http://dev.exiv2.org/news/3

**Comment by FreddieWitherden** [comment]
@frli8848 The Nikon code is relatively nice and easy to factor out into a table.  However, if you look at Canon things are much more involved.  My understanding is that each lens ID ambiguity is resolved by a dedicated function.  Thus, some more thought may be required here.

**Comment by clanmills** [comment]
I agree.  This can be done.  Now, where can I find a volunteer?

I had another thought about this.  Few users know about the ~/.exiv2 file.  If the f-mount data isn't in that file, we have to download it (from exiv2.org).  Good News.  We have the code to implement HTTP verbs, in this case _**GET**_ (in _**src/http.cpp**_).

Incidentally, I know everything about the PostScript language and wrote a "no thrills" PostScript Interpreter (about 200 lines of C++) long before I worked for Adobe.  I've thought about calling it Exiv2Script and it would perform arbitrary inspection of metadata for lens recognition.

This could be a real fun project.

**Comment by D4N** [comment]
Being able to update the lens data separately of the main binary would be nice to have. I would propose that we keep the lens data in text form and provide at least two different places for them to be installed: a system wide path (probably in /usr/share) and path in the user's directory (+maybe a script that updates them). That way packagers could split the exiv2 package into exiv2 & exiv2-lenses and update exiv2-lenses more frequently if they desire (but then the lens data must stay compatible). This could be also customized further inside the exiv2 library, so that downstream users (like kde, darktable, etc) could use their own lens data file.

Maybe to get back to topic: @clanmills do we want to merge this PR?

**Comment by clanmills** [comment]
I've misunderstood.  I thought this was a discussion and forgot there is something to be merged.  Exiv2 moved to git/GitHub in April 2017 when I released v0.26.  I don't understand git/GitHub.  So, I rely on others to merge code.

@frli8848 submitted a change to that code in in #227.  We have to be careful that your code doesn't conflict/negate the work by @frli8848

**Comment by frli8848** [comment]
I vote for (consistently) using the notation
<pre>
| S
| C
| A
</pre>
for the latest gen Sigma lenses and don't touch the Sigma 120-300/2.8 Sport lens code (which was already added). Besides that the code is most likely safe even though we have no test files for the new lenses.

**Comment by D4N** [comment]
This PR has been dormant now for a long time. Since I really cannot judge whether this is a good contribution: @clanmills can you please decide: merge/reject?

(There are currently file conflicts, but either me or @piponazo should be able to fix them.)

**Comment by clanmills** [comment]
@D4N .  If there isn't too much pain, could this be merged into the product please?

**Comment by piponazo** [comment]
As @D4N pointed out this has been dormant for some time. I'll try to take care of resolving the conflicts and merge it in the 0.27 branch.

**Comment by piponazo** [comment]
There is only one conflict to solve:

```
<<<<<<< HEAD
{0xE3,0x40,0x76,0xA6,0x38,0x40,0xDF,0x4E,0x00,0x00,0x00, "Tamron", "A022", "SP AF 150-600mm F/5-6.3 VC USD G2"},
=======
{0xE3,0x40,0x76,0xA6,0x38,0x40,0xDF,0x4E,0x00,0x00,0x00, "Tamron", "A022", "SP AF 150-600mm F/5-6.3 Di VC USD G2"},
>>>>>>> 97a79243400c552556a3473ada22c0cad98584de
```

But I cannot tell which line to keep. @frli8848 , @FreddieWitherden do you have any suggestion?

**Comment by FreddieWitherden** [comment]
I believe ```{0xE3,0x40,0x76,0xA6,0x38,0x40,0xDF,0x4E,0x00,0x00,0x00, "Tamron", "A022", "SP AF 150-600mm F/5-6.3 Di VC USD G2"},``` to be correct.

**Comment by piponazo** [comment]
The changes has been merged into 0.27 (#608) and will be merged also into master (#614). Thanks for the contribution!

**Pull request closed without merging**
