### PR TITLE
BigTiff Enhancements including fix for crash on BigTiffSamples/*.tif

### PR DESCRIPTION
**Pull request by Kicer86**

### CODE REVIEW

**Comment by clanmills** [comment]
Thanks for doing this, Michal.  I have changes to submit concerning Visual Studio.  I really want to get Luis' review of my CMake changes done on Monday or Tuesday.  I'm exhausted tonight and will look at your git recipes on Monday.  I'll update WORK-IN-PROGRESS about the Tiff Refactoring project.

**Comment by clanmills** [comment]
This is looking good.

Thanks for fixing I like the "STRUCTURE OF BIGTIFF ....".  Can you include the (II) or (MM) that's in the 32 bit version?

There are couple of things which are odd about this:
```
525 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pR ~/Downloads/BigTIFFSamples/BigTIFFSubIFD4.tif
STRUCTURE OF BIGTIFF FILE /Users/rmills/Downloads/BigTIFFSamples/BigTIFFSubIFD4.tif
 address |    tag                           |      type |    count |    offset | value
   15574 | 0x0100 ImageWidth                |     SHORT |        1 |           | 64
...
   15714 | 0x0117 StripByteCounts           |     SHORT |        1 |           | 12288
   15734 | 0x014a SubIFDs                   |       IFD |        1 |           | 
tag = 0x14a   <-- Is this a debugging relic?
  STRUCTURE OF BIGTIFF FILE /Users/rmills/Downloads/BigTIFFSamples/BigTIFFSubIFD4.tif
   address |    tag                           |      type |    count |    offset | value
...
  END /Users/rmills/Downloads/BigTIFFSamples/BigTIFFSubIFD4.tif
...
tag = 0x14a  <-- and this?
  STRUCTURE OF BIGTIFF FILE /Users/rmills/Downloads/BigTIFFSamples/BigTIFFSubIFD4.tif
   address |    tag                           |      type |    count |    offset | value
     18842 | 0x00fe NewSubfileType            |      LONG |        1 |           | 1
...
  END /Users/rmills/Downloads/BigTIFFSamples/BigTIFFSubIFD4.tif
END /Users/rmills/Downloads/BigTIFFSamples/BigTIFFSubIFD4.tif
526 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```
And this:
```
531 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pR ~/Downloads/BigTIFFSamples/BigTIFFLong8.tif
STRUCTURE OF BIGTIFF FILE /Users/rmills/Downloads/BigTIFFSamples/BigTIFFLong8.tif
 address |    tag                           |      type |    count |    offset | value
   12306 | 0x0100 ImageWidth                |     SHORT |        1 |           | 64
   12326 | 0x0101 ImageLength               |     SHORT |        1 |           | 64
   12346 | 0x0102 BitsPerSample             |     SHORT |        3 |           | 8 8 8
   12366 | 0x0106 PhotometricInterpretation |     SHORT |        1 |           | 2
   12386 | 0x0111 StripOffsets              |   unknown |        1 |           | 16 <-- unknown?
   12406 | 0x0115 SamplesPerPixel           |     SHORT |        1 |           | 3
   12426 | 0x0116 RowsPerStrip              |     SHORT |        1 |           | 64
   12446 | 0x0117 StripByteCounts           |   unknown |        1 |           | 12288 <-- unknown?
END /Users/rmills/Downloads/BigTIFFSamples/BigTIFFLong8.tif
532 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```
This a good time to add something to the test suite.  Let's get those test files (in BigTIFFSamples) into the Exiv2 test suite and write test-bigtiff.sh to read those files.  I'm happy to discuss the test suite on Slack.

**Comment by clanmills** [comment]
Another thought.  Let's update isBigTiffType() to detect a 32 bit tiff with the extension .bigtiff goes through your code and instead of the existing 32 bit isTiffType()

**Comment by Kicer86** [comment]
Ok I'll take care of it. :) Thank you

**Pull request merged**
