### PR TITLE
Fix 644 on master

### PR DESCRIPTION
**Pull request by clanmills**

### CODE REVIEW

**Comment by clanmills** [comment]
This broke the mdvc build on 0.27.  I will investigate.

**Comment by phako** [comment]
I think that MSVC's __declspec__(DLLEXPORT) is a bit more picky than the corresponding GCC attributes and that propbably needs the full revert, not just the single API attribute for the class.

**Comment by clanmills** [comment]
Thanks, @phako

I wrote the msvc __declspec code that was in Exiv2 for about 10 years without giving trouble.  However that was removed last year when the CMake code was rewritten.  I'll need to understand how CMake deals with this.  I was thinking I might leave this to @piponazo as he's our CMake expert.

I hope to get this fixed over the weekend because #644 is a "build breaker" for darktable and probably other folks who haven't been in touch yet!

**Comment by piponazo** [comment]
I think this weekend I will have some time to review the open PRs and I will try to fix few things reported recently 😉

**Comment by piponazo** [comment]
I'm taking the freedom of closing this, now that #652 have been merged.

**Pull request closed without merging**
