### PR TITLE
v0.27.4RC2

### PR DESCRIPTION
**Pull request by clanmills**
v0.27.4RC2

### CODE REVIEW

**Comment by kmilos** [comment]
Might be worth mentioning at least the recent CVE discovered and fixed in the changelog, or you're saving the changelog update for final release?

**Review by kmilos — APPROVED** [review]
Also builds and test pass with the new msys2/ucrt64 toolchain.

**Comment by clanmills** [comment]
Thanks for investigating the msys2 build compatibility.

I mention the CVE in the release notes.  It's given a low mention.  However it's not ignored.  I said

_8. One Security Fix.  18 months since last CVE.  Fixed in 24hrs.  Patch in 2 hrs._.

It's also categorised/detailed listing:

|  Group        | PR     |  Topic                                     | Issue  |
|:--------------|:-------|:-------------------------------------------|:-------|
| Bugs and Fixes | | | |
| ... | | | |
| Security      | #1483  | Define Security Policy                     | #1122  |
|               | #1523  | jp2image exiv2 asan issue                  | #1522  |
| Lens | ... | | |

**Comment by kmilos** [comment]
Congrats!

**Comment by clanmills** [comment]
A really fantastic team effort.  12 People to thank in the release notes.  Team Exiv2 really exists.  Well, it started to become a Team (and not just the cat and me) when Luis and Dan started working with me in 2017.   

Today was the first time that two contributors posted a PR for the same issue.  It's incredible.  I can't believe it.  Exiv2 v0.27.3 was more-or-less a solo effort.  I think the moment of rebirth of the team was when you showed up about August last year.  Talking about easyaccess and TIFF-EP and Exif 2.32.

Now, I want to get the book finished.

**Pull request merged**
