### PR TITLE
Add DNG 1.6 support (0.27->master)

### PR DESCRIPTION
**Pull request by kmilos**
A small Christmas present, just recently announced as part of [Apple's latest product updates](https://www.dpreview.com/news/4094896855/halide-developers-break-down-the-technology-powering-apple-s-new-proraw-image-format).

No spec in PDF form yet, just a [web page](https://helpx.adobe.com/photoshop/kb/dng-specification-tags.html).

Tested on a sample from [here](https://petapixel.com/2020/12/14/apple-proraw-review-the-best-way-to-shoot-raw-on-an-iphone/).

### CODE REVIEW

**Comment by kmilos** [comment]
Output excerpt:

```
Exif.SubImage1.NewSubfileType                Long        1  Primary image
Exif.SubImage1.ImageWidth                    Long        1  4032
Exif.SubImage1.ImageLength                   Long        1  3024
Exif.SubImage1.BitsPerSample                 Short       3  12 12 12
Exif.SubImage1.Compression                   Short       1  JPEG
Exif.SubImage1.PhotometricInterpretation     Short       1  Linear Raw
Exif.SubImage1.SamplesPerPixel               Short       1  3
Exif.SubImage1.PlanarConfiguration           Short       1  Chunky
Exif.SubImage1.TileWidth                     Long        1  504
Exif.SubImage1.TileLength                    Long        1  378
Exif.SubImage1.TileOffsets                   Long       64  2721756 3060354 3390846 3723747 4056475 4389531 ...
Exif.SubImage1.TileByteCounts                Long       64  338598 330492 332901 332728 333056 327286 328774 ...
Exif.SubImage1.LinearizationTable            Short     4096  0 1 1 2 3 4 4 5 6 7 7 8 9 9 10 11 12 12 13 14 15 ...
Exif.SubImage1.BlackLevel                    Short       3  0 0 0
Exif.SubImage1.WhiteLevel                    Short       3  65535 65535 65535
Exif.SubImage1.NoiseProfile                  Double      2  3e-05 3e-08
Exif.SubImage1.DefaultBlackRender            Long        1  None
Exif.SubImage1.ProfileGainTableMap           Undefined 49408  0 0 0 6 0 0 0 8 63 194 246 132 192 0 0 0 63 190 ...
Exif.SubImage2.NewSubfileType                Long        1  Primary image, Semantic mask
Exif.SubImage2.ImageWidth                    Long        1  2016
Exif.SubImage2.ImageLength                   Long        1  1512
Exif.SubImage2.BitsPerSample                 Short       1  8
Exif.SubImage2.Compression                   Short       1  JPEG (lossy)
Exif.SubImage2.PhotometricInterpretation     Short       1  Semantic Mask
Exif.SubImage2.StripOffsets                  Long        1  2365228
Exif.SubImage2.SamplesPerPixel               Short       1  1
Exif.SubImage2.RowsPerStrip                  Long        1  1512
Exif.SubImage2.StripByteCounts               Long        1  174080
Exif.SubImage2.XMLPacket                     Byte      640  60 120 58 120 109 112 109 101 116 97 32 120 109 ...
Exif.SubImage2.SemanticName                  Ascii      50  urn:com:apple:photo:2018:aux:portraiteffectsmatte
Exif.SubImage3.NewSubfileType                Long        1  Primary image, Semantic mask
Exif.SubImage3.ImageWidth                    Long        1  2016
Exif.SubImage3.ImageLength                   Long        1  1512
Exif.SubImage3.BitsPerSample                 Short       1  8
Exif.SubImage3.Compression                   Short       1  JPEG (lossy)
Exif.SubImage3.PhotometricInterpretation     Short       1  Semantic Mask
Exif.SubImage3.StripOffsets                  Long        1  2539308
Exif.SubImage3.SamplesPerPixel               Short       1  1
Exif.SubImage3.RowsPerStrip                  Long        1  1512
Exif.SubImage3.StripByteCounts               Long        1  182446
Exif.SubImage3.XMLPacket                     Byte      624  60 120 58 120 109 112 109 101 116 97 32 120 109 ...
Exif.SubImage3.SemanticName                  Ascii      47  urn:com:apple:photo:2019:aux:semanticskinmatte
```

**Comment by clanmills** [comment]
Thanks.  I'm on vacation and the laptop has died.  Will look after Chistmas.Can you test options -pp and -ep are working with the preview.  If DNG not too fat, try to add something to the test suite.  Might need latest Preview.app or PhotoShop to shrink the DNG and preserve metadata.  Good Luck.When I get home, I'll make you an admin on github.com/exiv2/exiv2 so you can push unreviewed PRs.Thanks for dealing with this.  I'm disappointed that the community haven't found somebody to maintain Exiv2. Robinhttps://clanmills.comOn 19 Dec 2020 22:14, Miloš Komarčević <notifications@github.com> wrote:A small Christmas present, just recently announced as part of Apple's latest product updates.
No spec in PDF form yet, just a web page.
Tested on a sample from here.



You can view, comment on, or merge this pull request online at:
  https://github.com/Exiv2/exiv2/pull/1436

Commit Summary
Add DNG 1.6 support

File Changes

    M
    src/tags_int.cpp
    (16)
  

Patch Links:
https://github.com/Exiv2/exiv2/pull/1436.patchhttps://github.com/Exiv2/exiv2/pull/1436.diff

**Review by clanmills — COMMENTED** [review]
Is it possible to add something to the test suite to cover this.  When I went through to the Apple web site, there are many images and I wasn't instantly sure which have this new metadata.  Can you find one and add it to the test suite (preferably as a .EXV to keep down the footprint).

You are now an "Admin" user of Exiv2 on GitHub and that gives you rights to merge unapproved PRs.  So, if I'm no around, please proceed to merge when you are confident that your changes are good.  I know you'll use your admin rights wisely.  You also have the rights to add/remove users.

**Comment by kmilos** [comment]
Sorry, I just couldn't find the time I thought I would during the holidays... I'll try to wrap up the tests soon.

**Comment by clanmills** [comment]
I am glad you had better things to do with your time.  Thank You for your contributions to Exiv2 this year.

Happy New Year.  I hope everything goes well and safely for everybody in 2021.

**Comment by kmilos** [comment]
Thanks, and same to you!

I need some help w/ creating this test though... I can't figue out how to extract all the metadata from a sample into an EXV file, I only get IFD0 (and Exif IFD and GPS IFD) with `exiv2 -ea ex`, no sign of SubIFDs where all this additional stuff lives, while I see everything when I do `exiv2 -pa pr`...

I wouldn't want to check in a 25MB DNG file (not to many samples around, and might be copyrighted as well), so going the EXV route is the still the best option.

**Comment by clanmills** [comment]
@kmilos There are lots of images on the web-page you have mentioned.  Can you identify the image (or images) you'd like to use in the test and I'll see what can be done.

The .exv file is effectively a JPG with no graphics.  So, it encounters the Exif < 64k limit.  Additionally, some IFDs are actually of type LONG and not IFD, so the .exv isn't valid.

Please let let me know which images you would like to use and I will investigate.

There are a couple of ways to handle large images:
- All versions of exiv2 support http (but not necessarily https), so we can read the image from the internet.
- I have stored images in svn://dev.exiv2.org/svn/testdata and downloaded them (with svn export) when necessary.

**Comment by kmilos** [comment]
For example the first IMG_4329.DNG from [here](https://onedrive.live.com/?authkey=%21ACHX4aioELhCdLY&id=AB370A8F9CEFFEA3%217748&cid=AB370A8F9CEFFEA3) (linked from the article above).

The 64kB limit might be a problem, there are quite a few large tables in there...

**Comment by clanmills** [comment]
Thanks.  I'll investigate.

I have researched the Adobe "ad hoc" standard to enable Exif > 64k in JPEG and documented it in the book and implemented it in tvisitor.cpp.   

When the test suite was rewritten in python two years ago, we did not retain the option to store test images on a server and download them on demand.

So many great things can be done when Exiv2 has more contributors.

**Comment by clanmills** [comment]
I've found a way to squeeze the file to 100k.

```
607 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ git status
On branch dng_1.6
Your branch is up to date with 'origin/dng_1.6'.

nothing to commit, working tree clean
608 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ build/bin/exiv2 -pa ~/Downloads/IMG_4329.DNG | wc
     118   57248  216119
609 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ dd bs=100000 count=1 if=~/Downloads/IMG_4329.DNG of=IMG_4329.DNG ; exiv2 -pa IMG_4329.DNG 2> /dev/null | wc
1+0 records in
1+0 records out
100000 bytes transferred in 0.000218 secs (458895405 bytes/sec)
     110     687    8570
610 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```

This is quite common.  The metadata is all at the front of the file followed by pixels, thumbnails and non-metadata.  Of course Exiv2 complains about loads of illegal offsets.  We ignore him.

I'll update your PR this afternoon with changes to the test suite.  And I'll review the code and find out what you've done!

This teamwork shit really works.  1+1=3 I don't know why nobody uses it in the office.

**Comment by kmilos** [comment]
Neat idea! (w/ some luck involved ;) )

It looks like keeping the first 64972 bytes ought to do it for this file?

```
Exif.Image.StripOffsets                      Long        1  64972
...
Exif.Image.SubIFDs                           Long        3  4930 63306 64150
```

There's only a handful of new tags/values to be tested for...

**Comment by kmilos** [comment]
Btw, I finally found a CC0 (public domain) sample at [RPU here](https://raw.pixls.us/data/Apple/iPhone%2012%20Pro/IMG_1361.DNG), so I think we better use that one just in case. The first 64104 bytes should do it.

**Comment by clanmills** [comment]
There's no luck here.  It's knowledge and understanding.  However it's good fortune that the metadata is near the start.

I think you're correct that extracting 64972 will be sufficient.
 
I've found another fix in which I write the Exif.Image.SubIFDs and the subIFDs.  With this change, Exiv2 passes the test suite.  However, I'm nervous about this as it could break something that isn't in our test suite, for example Multi-page tiff files (which we don't support).  Too big a risk for 0.27.4.

```
diff --git a/src/exif.cpp b/src/exif.cpp
index 493fd20b..13ee9d86 100644
--- a/src/exif.cpp
+++ b/src/exif.cpp
@@ -669,7 +669,7 @@ namespace Exiv2 {
             "Exif.Image.StripByteCounts",
             "Exif.Image.JPEGInterchangeFormat",
             "Exif.Image.JPEGInterchangeFormatLength",
-            "Exif.Image.SubIFDs",
+            // "Exif.Image.SubIFDs",
             // Issue 981.  Never allow manufactured data to be written
             "Exif.Canon.AFInfoSize",
             "Exif.Canon.AFAreaMode",
@@ -698,6 +698,7 @@ namespace Exiv2 {
         }
 
         // Delete IFDs which do not occur in JPEGs
+        /*
         static const IfdId filteredIfds[] = {
             subImage1Id,
             subImage2Id,
@@ -719,7 +720,7 @@ namespace Exiv2 {
 #endif
             eraseIfd(ed, filteredIfds[i]);
         }
-
+        */
         // IPTC and XMP are stored elsewhere, not in the Exif APP1 segment.
         IptcData emptyIptc;
         XmpData  emptyXmp;
```  

Can you update the test suite with your CC0 file and I will review/approve this change?  If you'd prefer that I modify the python stuff, please say so.

-------------

There's going to be Zoom meeting on Saturday with **darktable** to discuss ISOBMFF support.  I'd be delighted if you could attend (although I don't expect you to get involved with the code).  It's being discussed here:  

https://app.element.io/#/room/#exiv2-chat:matrix.org

------------

The Zoom meeting is:

Topic: Support for ISOBMFF Files (AVIF, HEIF, CR3)
Time: Jan 9, 2021 07:30 PM Amsterdam, Berlin, Rome, Stockholm, Vienna

Join Zoom Meeting
https://us05web.zoom.us/j/82168885673?pwd=K3pqRThERVNQK2JQR2ZweStwS2Nkdz09

Meeting ID: 821 6888 5673
Passcode: L1B3Hz_

**Comment by kmilos** [comment]
> There's no luck here.

I only meant that the metadata is conveniently packed at the beginning of the file ;)

Agreed, no need to introduce further source code changes since you found a good enough workaround. I think I can now finish the test in the coming days now, thanks.

Also thanks for the meeting invite and including me in the elite group, but unfortunately I won't be able to join.

**Comment by clanmills** [comment]
Right.  When you update the PR, I'll review/approve and you can merge.  Another issue closes quickly without too much effort.

Pity you can't join us on Saturday, however I believe we have the right folks in place to make **darktable** happy.  We'll get ISOBMFF (.CR3, .AVIF, and .HEIC) support into Exiv2 v0.27.4.  I hope to released it 2021-04-30 and after that, I will really will be retired.  All this stuff that you've done on DNG, TIFF-EP and EasyAccess will be in 0.27.4.

**Comment by kmilos** [comment]
Yep, 0.27.4 looks like a nice conclusion to your journey with rich features, and should serve the photo community for some time!

**Review by clanmills — APPROVED** [review]
This looks fine.  Good Job.  I've tidied up tests/README-TESTS.md and added it to the PR.

I've had a couple of thoughts about this:
1.  We could use the patch above to "preserve" the Exif.Image.SubIFDs and the subIFDs in a DNG.  That code is in exif.cpp and is used when writing .exv files.  We can detect "is this a DNG" by detecting Exif.Image.DNGVersion

2.  There's a LOT of output for Exif.SubImage1.ProfileGainTableMap           Undefined 49408 and so the test file is 172526 bytes.  Mind you, it compresses well.

```bash
553 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ finder test_pr_1436* $L
-rw-r--r--@ 1 rmills  staff  172526  6 Jan 14:27 ./tests/bugfixes/github/test_pr_1436.py
-rw-r--r--  1 rmills  staff  32644  6 Jan 15:55 ./tests/bugfixes/github/test_pr_1436.py.zip
554 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ 
```

It would be good to have a setting in the test suite such as `linemax=100` to chop stdout lines.  Having looked in tests/system_tests.py, it's not too obvious how to do that. 

However, let's not touch any of this.  It's OK as is.  Let's move on.

**Comment by kmilos** [comment]
Agreed, I'll merge as soon as the CI completes. Thanks for reviewing.

**Pull request merged**
