### PR TITLE
Default to /MD(d) even for STATIC builds.

### PR DESCRIPTION
**Pull request by piponazo**
This PR deals with the second issue described in #487.

We had issues to compile exiv2 on Windows and STATIC mode (`-DBUILD_SHARED_LIBS=OFF`) due to a undefined symbol referenced in expat.lib (Explained in #487):

```
  expat.lib(loadlibrary.obj) : error LNK2019: unresolved external symbol __imp__mbspbrk referenced in function _Expat_LoadLibrary [C:\Users\rmills\gnu\github\exiv2\exiv2\build\s
```

Static builds On Windows need to use **msvcrt.lib** where the missing symbol ("__imp__mbspbrk") is
defined Therefore, we need to use /MD instead of /MT even for the STATIC builds. To make the configuration simpler to developers, the new behaviour depending on the CMake options will be:

```
-DBUILD_SHARED_LIBS=ON --> Usage of /MD (Release) or /MDd (Debug) independently of EXIV2_ENABLE_DYNAMIC_RUNTIME
-DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_DYNAMIC_RUNTIME=ON --> Usage of /MD (Release) or /MDd
-DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_DYNAMIC_RUNTIME=OFF --> Usage of /MT (Release) or /MTd
```

The logic in `cmake/compilerFlags.cmake` has been simplified and some unnecessary code (lines 194-201) removed.

### CODE REVIEW

**Comment by D4N** [comment]
Could you add this explanation to one of the Readmes?
```
-DBUILD_SHARED_LIBS=ON --> Usage of /MD (Release) or /MDd (Debug) independently of EXIV2_ENABLE_DYNAMIC_RUNTIME
-DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_DYNAMIC_RUNTIME=ON --> Usage of /MD (Release) or /MDd
-DBUILD_SHARED_LIBS=ON -DEXIV2_ENABLE_DYNAMIC_RUNTIME=OFF --> Usage of /MT (Release) or /MTd
```
I think users would be interested, as they are probably not going to take a look at the available cmake options.

**Comment by piponazo** [comment]
I would do it with pleasure, but at this point any change in the README files would cause conflicts with the **RC1** branch (And I already had conflicts rebasing this branch in top of master). @clanmills It would be good to create a Pull-Request for RC1 soon to avoid these issues. You could still work on the RC1 after merging that branch.

**Comment by clanmills** [comment]
I don't know how to create a PR for anything.  Very very very frustrated with git.

**Review by clanmills — APPROVED** [review]
I support this with great enthusiasm.  I dislike the static run-time.  It's only suitable for small "hello world" applications.

*Another idea*:  Can we get CMake to run conan for us?  Then add an option -DEXIV2_BUILD_USE_CONAN=On and the build and dependencies would be built.

**Comment by piponazo** [comment]
I think there was some experimental "extensions" to run conan from within cmake, but it is something I really dislike.

Conan is a external tool from bringing dependencies. You can use conan, rely on system packages, or even build the external dependencies by your own. One should have freedom to choose whatever of the options he prefers. 

CMake is about configuring a project. It should know as less as possible about the dependencies. It only needs to find them (assuming that the dependencies have been brought already).

**Pull request merged**
