### PR TITLE
Update PACKAGE_URL and PROJECT_DESCRIPTION text

### PR DESCRIPTION
**Pull request by postscript-dev**

### CODE REVIEW

**Comment by postscript-dev** [comment]
Later last night after I logged off, I realised that I could have submitted the two PRs together. I haven't used git that much but now I know for next time.

**Comment by clanmills** [comment]
Thanks.  I'm just back from vacation and haven't looked at this yet.  I wondered if you'd like to also mention ICC Profiles, Image Previews and Image Comments.  I'll merge this to the 0.27-maintenance branch and leave 'master' for somebody else.  Will there be another maintainer for Exiv2?  Nobody has shown any interest.

**Comment by postscript-dev** [comment]
> I wondered if you'd like to also mention ICC Profiles, Image Previews and Image Comments.

I'm unsure what you are refering to.


I had another look at CMakeLists.txt and is 
```c
set( PACKAGE_URL "http://exiv2.dyndns.org" )
```
correct? The server isn't found.  Perhaps this should be ```"https://www.exiv2.org/"``` instead?
The description and URL appear in the pkgconfig file and look wrong?

> Will there be another maintainer for Exiv2? Nobody has shown any interest.

Personally I don't have the experience needed to do the job justice so this is beyond me. I hope you find somebody to continue the work.

**Comment by clanmills** [comment]
In principle, open-source is a community activity and many folks should contribute something.  The reality is different. 

You're right about exiv2.dyndns.org being obsolete.  The main web-site is as you say https://exiv2.org and the pre-release website is https://pre-release.exiv2.org

Exiv2 operates on 6 types of Metadata:

1.  Exif
2. IPTC
3. XMP
4. ICC Profiles
5. Image Previews
6. Image Comments

Exif, IPTC and XMP are "the big guys", however profiles and previews deserve mention.  Image Comments are only supported for JPEG and PNG and less deserving of mention.  I've just looked at https://exiv2.org and I don't mention either Previews or Comments:

_Exiv2 is a Cross-platform C++ library and a command line utility to manage image metadata. It provides fast and easy read and write access to the Exif, IPTC and XMP metadata and the ICC Profile embedded within digital images in various formats. Exiv2 is available as free software and is used in many projects including KDE and Gnome Desktops as well as many applications including GIMP, darktable, shotwell, GwenView and Luminance HDR._

**Comment by postscript-dev** [comment]
>You're right about exiv2.dyndns.org being obsolete. The main web-site is as you say https://exiv2.org and the pre-release website is https://pre-release.exiv2.org

So could change to
```c
set( PACKAGE_URL "https://exiv2.org" )
```

I didn't know about the pre-release website.  I tried it now and there are 2 API entries in the menu - one looks like it has a drop-down facility but it didn't work for me.  When I click on the API that does work then the API that I clicked on disappears and the non-functioning one is left.

>Exif, IPTC and XMP are "the big guys", however profiles and previews deserve mention.

I wasn't aware of the depth of the library.  We could use 
```c
set( PROJECT_DESCRIPTION "Exif, IPTC and Xmp metadata library and tools including ICC Profiles and Image Previews")
```
although this is may be a bit long (I don't know if there is an expected limit).
For something slightly shorter we could condense a little with
```c
set( PROJECT_DESCRIPTION "Exif/IPTC/Xmp metadata library and tools including ICC Profiles and Image Previews")
```
but I am happy to take you guidance on this.

**Comment by clanmills** [comment]
How about:

```
set( PROJECT_DESCRIPTION "Exif/IPTC/Xmp C++ metadata library and tools plus ICC Profiles, Previews and more.")
```

I think the **C++** is quite important as that is the BIG difference between Exiv2 and ExifTool.  We have a friendly working relationship with Phil Harvey.  Can you update the PR with this change _**and**_ the PACKAGE_URL.  

That's odd that you are experiencing UI issues on the pre-release web-site.  Can you look on the "main" web-site as that's the one that's important.  If there's something broken on 'main', I'll fix it.  If it's only broken on pre-release, let's let it be.  I am surprised as I don't recall touching that code during the last release cycle.

**Comment by postscript-dev** [comment]
>I think the C++ is quite important as that is the BIG difference between Exiv2 and ExifTool. 

I agree, I'll update the PROJECT_DESCRIPTION and the PACKAGE_URL for both master and maintenance.  This will have to wait until Boxing day though.

>That's odd that you are experiencing UI issues on the pre-release web-site

I tried both sites with Firefox, Edge, Opera and Chrome with cookies, without add ons and made sure that javascript was enabled.  I don't get an API dropdown box on the main site but do on the pre-release. Both sites have a non-dropdown API option that correctly links to the source code pages. Another thing, on both sites when you click on the "Examples" or "API" menu options, after the page loads the menu option does not go grey.  This is inconsistant with the other menu options although this is a small cosmetic problem.
I am happy to leave both of these observations.

As ususal, thanks for the help. Have a good Christmas.

**Review by clanmills — APPROVED** [review]

**Comment by clanmills** [comment]
Thanks.  Merged.

**Pull request merged**
