### PR TITLE
Fix 1278 nls test 0.27

### PR DESCRIPTION
**Pull request by clanmills**
Initial commit to see how the CI handles this.

### CODE REVIEW

**Review by piponazo — DISMISSED** [review]
Looks good to me! 👏

**Comment by clanmills** [comment]
@LeoHsiao1 I didn't add nls_test() to  tests/bash_test/testcases.py.  Can you add that to this PR before we merge, please.

I hope to get back to working on my book today.  I haven't work on it for 3 weeks.  Such a lot going on in Exiv2 at present.

**Review by clanmills — COMMENTED** [review]
This looks right.  The result should be:
if platform == Linux:
  env LC_ALL=fr_FR LANGUAGE=fr_FR exiv2
else:
  env LC_ALL=fr_FR LANG=fr_FR exiv2

Can't activate the "approve" button.

**Comment by clanmills** [comment]
Thanks for working on this, @LeoHsiao1 

I don't know why the GitHub UI would not let me select "Approve".  Change Looks good.  I'm going to merge.

**Comment by LeoHsiao1** [comment]
Maybe Github is checking the difficulty of merging.
It's my pleasure to make a contribution.

**Comment by clanmills** [comment]
We're not done yet.  There's a minor issue on centOS.  https://github.com/Exiv2/exiv2/issues/1278#issuecomment-708417651

Can you open a new PR and get nls_test() to skip in your code.  I'll update the PR to skip test/nls-test.sh in bash.

**Comment by LeoHsiao1** [comment]
I adopted your second idea and submitted PR #1359 .
Open source work is sometimes easy and sometimes difficult. Some days I'm busy, and some days I'm too idle to sleep.

**Comment by clanmills** [comment]
Thanks for dealing so quickly with this, @LeoHsiao1.  I'll look at #1359 this afternoon and update the test/nls-test.sh and test/data/nls-test.out appropriately.

I don't find any of this difficult.  However, there's quite a lot going on in 100,000 lines of code that runs on many different platforms.  Getting bash out of the test harness is wonderful simplification.  Of course, it comes at the cost of writing more python code.  The investment is worth-while.

I am proud of how quickly Exiv2 deals with issues.  Almost everything reported is acknowledged within hours and fixed in hours or days.  No commercial software company responds to users so quickly.

**Pull request merged**
