### PR TITLE
direct initialize some structs

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by piponazo** [comment]
Ey @neheb , in this PR you are mixing 2 different unrelated topics:
* Initialization of structures
* Remove constness from some variable members.

The 1st one I would approve without blinking my eyes. The 2nd one is a bit more controversial. What's your rationale to remove `const` from those variables? I guess the original authors of those pieces of code gave a lot of though to use `const` in there.

**Comment by neheb** [comment]
I can split up into separate PRs.

const removal is done by https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-const-or-ref-data-members.html

**Comment by piponazo** [comment]
> I can split up into separate PRs.
> 
> const removal is done by https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-const-or-ref-data-members.html

Sure, If you do that, I will approve quickly the 1st part :)

**Comment by neheb** [comment]
> > I can split up into separate PRs.
> > const removal is done by https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/avoid-const-or-ref-data-members.html
> 
> Sure, If you do that, I will approve quickly the 1st part :)

Done.

**Review by kmilos — APPROVED** [review]

**Pull request merged**
