### PR TITLE
IO read/write functions with size_t (3) 

### PR DESCRIPTION
**Pull request by piponazo**
This is a re-work of the changes done in #786 and #765 by @tbeu and me. 

I tried this time to be more careful about the changes done in each commit as requested by @D4N . 

I'll close the two previous PR so that we can focus on this one.

### CODE REVIEW

**Comment by piponazo** [comment]
Note that commit 829bdd8e735a0b97dd600988352d9e9a293aa899 is a bit longer than the rest, because it was when I switched from Linux to Windows to deal with the compilation issues on the 2nd platform.

**Review by D4N — APPROVED** [review]
Wow, impressive number of changes, thanks @piponazo and @tbeu!

**Comment by D4N** [comment]
@piponazo There are now some merge conflicts #807 and #805. I don't really feel comfortable rebasing this, as the changes due to #807 are non-trivial. Could you take a stab at that?

**Comment by piponazo** [comment]
Sadly, master has evolved so much since I created this PR that now it is really difficult to rebase or merge master into this branch. I will close the PR and try to apply the same changes from scratch

**Pull request closed without merging**
