### PR TITLE
Few characterisation tests for ImageFactory and ImageType as enum class

### PR DESCRIPTION
**Pull request by piponazo**
I started to analyse the core part of Exiv2 and I took the decision to start adding few characterisation tests (in form of Unit Tests) for the **ImageFactory** class. I soon realised about few things we could improve there and I prepared this Draft to discuss them.

First of all, I found bizarre that I had to include all the headers corresponding to the different Image Types to be able to create an instance of them. Normally, when using the Factory design pattern, the benefit of it is that you just need to know the Abstract Type (In this case **Image**) and you do not need to know the implementation details about each of the concrete implementations. I decided then to perform an experiment and replace the ImageType namespace that was populated in each image type header file, by a enum class type defined in a new file called `image_types.hpp`. The benefits from my point of view:

- We do not need to include all the Image Type headers to use the Factory.
- We have a unique place where the **ImageType** values are set. 

I also started to use the doxygen style `///`which I think make the documentation more readable and concise. 

The other interesting thing that I noticed thanks to the tests is that we do not support the creation of Image Metadata structures for most of the formats. Yes, we can read them, but not create them from scratch ... something that is not evident with the existing documentation. 

Note that I created this PR as a Draft to get your feedback about the first steps I am taking here. My idea is to create a PR with the **ImageFactory** fully tested. 

I would recommend you to take a look commit by commit, to see the decisions I took step by step.

### CODE REVIEW

**Review by tbeu — DISMISSED** [review]
I am in strong favour of introducing the type-safe enum class for the image types. But I would not have it mixed with the doxygen style changes. This should be a separate commit and considered similar as the clang-formatting changes.

**Comment by tbeu** [comment]
Are you sure 6c0e96fc6fd1b6604e49dcf5a927a7b5f6f1de63 and d3636d9fef47975d5cfb364658dacf3bf83c9811 belong here?

**Comment by piponazo** [comment]
> Are you sure 6c0e96f and d3636d9 belong here?

I agree that they do not belong here. Note that this is a Draft PR and I am just prototyping stuff. After I get feedback from you guys, I will create clean PRs trying to focus on just 1 topic each :wink:

**Comment by clanmills** [comment]
This all seems like a good idea to me.  I like the imageType symbols are defined in an enum instead of a const int xxx=value which has occasionally caused trouble in the past.  The "old" numbers in comments can be removed.

I'll approve this if you request me to do so.  From your comments, I think you're only asking for feedback and will provide a "solid" PR after your vacation.

**Comment by piponazo** [comment]
> I'll approve this if you request me to do so. From your comments, I think you're only asking for feedback and will provide a "solid" PR after your vacation.

Exactly. I just wanted to know if at least this seemed like a good idea to more than 1 person 😉 . I'll prepare a better PR soon.

**Pull request closed without merging**
