### PR TITLE
Update canonmn_int.cpp

### PR DESCRIPTION
**Pull request by czgnp**
Added Sigma 35mm/1.4 to lens id 368 and changed resolver to look at both focal length and aperture. Fixed canonEv so lenses with f/6.3 report as f/6.3 (they actually report f/6.2 to camera)

### CODE REVIEW

**Comment by czgnp** [comment]
Finally!
On 0.27-maintenance, updated cpp file, added Python test case with associated 6 images.

**Review by clanmills — COMMENTED** [review]
This looks good.  Thank You. 

A  comment about the **style of the python** test file.   What you've done works.  I don't think we usually use a different class for each test file.  You can do something like _(**caution:** my untested python could have syntax errors)_

```python
filename1="$data_path/Sigma_35mm_F1.4_DG_HSM_A_for_EOS.exv"
filename2="..."
...
commands=[ "exiv2 -pa --grep lensType/i $filename1",
"exiv2 .... $filename2",
];
# and fill in the arrays of stdout.
stderr = [""]*len(commands)
retval=[0]*len(commands)
```
I suspect that'll shorten your python from 77 lines of code to 30 or less. 

A comment about **printCsLensAndMaxAperture**.  I'm always nervous when I see cascading if statements.

```cpp
// convert 1/3 (0x0c) and 2/3 (0x14) codes
if (frac == 0x0c) {
    frac = 32.0f / 3;
}
else if (frac == 0x14) {
    frac = 64.0f / 3;
}
else if ((val == 160) && (frac == 0x08)) { // for Sigma f/6.3 lenses that report f/6.2 to camera
    frac = 30.0F / 3;
}
```
Those 10 lines can be more written more clearly as 4 lines:

```cpp
frac = frac == 0x0c                   ? 32.0f / 3 // Why?
     : frac == 0x14                   ? 64.0f / 3 // Why?
     :(frac == 0x08) && (val == 160)) ? 30.0F / 3 // for Sigma f/6.3 lenses that report f/6.2 to camera
     : frac;
```

_**Shorter**_ is almost always _**better**_. 

Do you agree?  If you don't want to change it, I will approve this.  If you'd like to change this, please update the PR.

**About Git**

I'm not to sure how you created this PR.  I suspect you did more work than necessary.  Here's my total knowledge of Git/GitHub.

GitIdiotCard

So, I would have started in your github/exiv2 directory
1. switched to 0.27-maintenance
2. git pull to get up-to-date. 
3. git checkout -b new_branch_name
-- performed the edits --
4. git commit
5. git push origin  
-- create PR using base: 0.27-maintenance--

Have created the PR, I would then use SmartGit to set the "Tracking Branch".  Once you've done that, you can edit/commit&push to update GitHub.  I don't know the terminal commands to set the tracking branch.  Git's mostly incompressible to a mere mortal such as me.  I recommend SmartGit as a nice GUI.  You can get a free 30 day license.  It's about $100/annum for license.  I think SmartGit is made in Germany.  It's a solid and reliable tool.

**Comment by czgnp** [comment]
Hi, I agree that short code - less to read - is easier to understand. In my profession (automotive software) readability is really important, but our thinking is that simple logic is easier for future maintainers so we strive to simple (boring) code even if not so elegant.
The Python testcase is really easy because each lens is a separate test - and once you get one of them, you understand the others to (and they are all copies of the 992 PR you refer to).
Same with if-else-if-else-if, it is simple (and that was the way it looked when I started). But I'm fond of ?: operator and think it is equally easy. (Though it is not allowed at my work, which mostly in C.) Also, I think porting/merging of changes in 0.27 branch into 0.28 will be easier if it is only addition of new code lines.
So, if OK, I would prefer to leave it as is, but if you don't merge within a few days I take that as a hint to update.
And thanks for the git hints. I'm OK with git, but github is new to me (and I did a lot more commands than needed).

**Comment by clanmills** [comment]
OK.  I have no desire to disagree with you about style.

I see that the CI is green, so I will approve and merge.

Thank You for your contribution.

**Review by clanmills — APPROVED** [review]

**Pull request merged**
