### PR TITLE
Windows: force UTF-8 code page for app and samples

### PR DESCRIPTION
**Pull request by kmilos**
See https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page

This should make Windows behaviour almost identical to *nix w.r.t UTF-8 everywhere, and simplifies/improves on the "wmain" wrapper solution.

NB: bumps minimum requirement to Windows 10 1903 (w/ 5th gen Broadwell HW cca 2015 and later), as well as building using UCRT only (default for MSVC for a while already; for MSYS2 this means UCRT64 or CLANG64 environments; cross-building from Ubuntu/Fedora is suspended due to missing UCRT toolchains).

Could be left in the backlog until these changed requirements are deemed to be acceptable.

(This doesn't address the missing wchar_t API in the library in any way - clients would expected to run in the UTF-8 code page as well.)

### CODE REVIEW

**Comment by kmilos** [comment]
Looks like we'll need equivalent changes for meson...

**Comment by neheb** [comment]
Heh, Windows 10 LTSC is on 1806.

Fedora has a UCRT toolchain. Pretty barebones though.

**Comment by kmilos** [comment]
> Heh, Windows 10 LTSC is on 1806.

_Active_ support ended for 1806 LTSC. I don't think it's reasonable to hold back (not only for this, but other possible Windows features) until 2029 when _security_ only support ends?

Mind you, this will not stop the app from working, it just won't have non-ASCII support. Then again, it doesn't have it today either since wchar_t was removed from the API...

**Comment by neheb** [comment]
Just noticed this was for the executable and not the library. Fine with me.

As far as the library goes, the removal of the wstring API ended up alienating many users as they build exiv2 with MinGW on Windows.

**Review by neheb — APPROVED** [review]

**Pull request merged**
