### PR TITLE
Translate exif.nikon af2.af area mode - enhanced

### PR DESCRIPTION
**Pull request by norbertwg**
As @kmilos pointed out in #2835, there may be more than one way for translation as documented in [https://exiftool.org/TagNames/Nikon.html#AFInfo2](https://exiftool.org/TagNames/Nikon.html#AFInfo2). Based on that information, translation now also depends on the value of Exif.NikonAf2.ContrastDetectAF.
The array with values and their translations is limited to those, which I could verify with Nikon NX Studio. The table from exiftool has additional values and I tried several of them, but Nikon NX Studio did not show the related texts. So I did not include them.

### CODE REVIEW

**Comment by kmilos** [comment]
Thanks. You'll need to rebase as the previous version was already merged.

**Comment by norbertwg** [comment]
@kmilos I did a rebase.

**Comment by kmilos** [comment]
> I did a rebase.

See the merge conflict messages below?

**Comment by norbertwg** [comment]
@kmilos the merge conflicts are gone now, but Commits tab shows four commits, which surprises me a little bit (I am still in a Git learning process). Checking the tab "Files changed" I see the changes i intended to do on top of #2835, so I think it is fine now.

**Comment by kmilos** [comment]
That's because you're _merging_ from the main branch into your PR branch, instead of _rebasing_ your PR branch on top of the main branch. Yeah, git takes some practice, you get there eventually 😉

**Comment by norbertwg** [comment]
Ok, do I still have a chance to fix it or would it be better create a new branch in my fork and make a new pull request?

**Comment by kmilos** [comment]
> Ok, do I still have a chance to fix it or would it be better create a new branch in my fork and make a new pull request?

No need, it'll work out.

**Review by kmilos — APPROVED** [review]

**Pull request merged**
