### PR TITLE
Fix #616 (master)

### PR DESCRIPTION
**Pull request by piponazo**
Applying patch provided by @clanmills in #631 into **master**.

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
Thank you for fixing this, Luis.  I was going to submit a PR (as you have done).  As always, I'm confused by Git..  I wanted to derive the patch from 'master' or 0.27 for each patch.  I couldn't figure out how.

This is patch deals with a very obscure matter.  There's nothing in the environment of GCC/musl to say "This is musl", and I believe this is a deliberate design choice.  Determining the return signature of `strerror_r()` is by sniffing the value of _GNU_SOURCE before and after `#include <string>`. 

A better fix is to put a test compile into the CMake code to determine `STRERROR_RETURNS_CHAR_PTR`, which should be called `EXV_STRERROR_RETURNS_CHAR_PTR` and be in `exv_conf.h`.

I'm happy to approve this as it stands.  I'll be interested to hear your thoughts about the CMake/test compile to set `STRERROR_RETURNS_CHAR_PTR`.

**Comment by D4N** [comment]
The fix won't work in the current form with libstdc++, as it requires _GNU_SOURCE to be defined.

**Comment by clanmills** [comment]
Thanks @D4N.  I see it's failing on some builders.  The patch worked OK on my laptop.

I think we'll have to go down the CMake/trial compile road to set **`EXV_STRERROR_RETURNS_CHAR_PTR`**  That's a much better road anyway.  It's explicit.  Relying on odd-ball **`#defines`** in the compiler environment is very fragile and could easily break on older/future releases of GCC.

@piponazo Do you have time to investigate CMake setting **`EXV_STRERROR_RETURNS_CHAR_PTR`**, or would you like me to work on that?

@D4N and @piponazo Delighted to say that conan does successfully cross-compile Linux->MinGW I'll update #610 about this later today.

**Comment by piponazo** [comment]
Interestingly the CI passes in the 0.27 branch (c++98) but  not in master (c++11 already). Sadly I do not have much spare time lately to research in depth these issues. But I am happy to help you with git whenever you need it (and I have few minutes to create the PRs).

**Comment by clanmills** [comment]
Yes, that's very curious.  I'll investigate adding something to set **`EXV_STRERROR_RETURNS_CHAR_PTR`** from cmake/something.cmake and you can help me get into the code base.

**Pull request closed without merging**
