### PR TITLE
github CI: use ilammy/msvc-dev-cmd

### PR DESCRIPTION
**Pull request by neheb**
Small simplification

### CODE REVIEW

**Comment by neheb** [comment]
Seems x86 builds are bugged:

```

======================================================================
ERROR: issue_1912_poc.jpg_test (test_regression_allfiles.TestAllFiles.issue_1912_poc.jpg_test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\exiv2\exiv2\tests\regression_tests\test_regression_allfiles.py", line 191, in test_func
    BT.reportTest(os.path.basename(filename), out)
  File "D:\a\exiv2\exiv2\tests\bash_tests\utils.py", line 567, in reportTest
    raise RuntimeError('\n' + log.to_str())
RuntimeError: 
Error:  The output of the testcase mismatch the reference
[INFO] The output has been saved to file D:\a\exiv2\exiv2\test\tmp\issue_1912_poc.jpg.out
[INFO] simply_diff:
D:\a\exiv2\exiv2\test/data\test_reference_files\issue_1912_poc.jpg.out: 53 lines
D:\a\exiv2\exiv2\test\tmp\issue_1912_poc.jpg.out: 53 lines
The first mismatch is in line 49:
< Exif.GPSInfo.GPSTimeStamp                    Rational    3  1131375984/1869505902 1950679091/1 18/1  05:20:00
> Exif.GPSInfo.GPSTimeStamp                    Rational    3  1131375984/1869505902 1950679091/1 18/1  05:20:18
```

**Comment by neheb** [comment]
@kevinbackhouse so the value up top is

```
07:36:50
```

on linux. Sounds like UB.

**Comment by kevinbackhouse** [comment]
> @kevinbackhouse so the value on the bottom is
> 
> ```
> 07:36:50
> ```
> 
> on linux. Sounds like UB.

@neheb: Is UB an abbreviation for undefined behavior? Is this test failing sporadically?

**Comment by neheb** [comment]
@kevinbackhouse added back 32-bit tests.

**Comment by neheb** [comment]
https://gist.github.com/neheb/d19b90a1a21214aa4e48ae7832bfcfe9

The failures are the same on x86 linux

**Comment by kevinbackhouse** [comment]
Speculating a bit here, because I'm debugging on 64-bit Linux, but most likely it's caused by a difference in floating point accuracy in this calculation:

https://github.com/Exiv2/exiv2/blob/79bf4d0b1e28f4f65d4f81b0cafc67126954c069/src/tags_int.cpp#L2615

**Comment by neheb** [comment]
partially.

So I tried fixing this by converting a bunch of doubles to floats. On 32-bit linux closest I got was 5:20:00.0

**Comment by kevinbackhouse** [comment]
> partially.
> 
> So I tried fixing this by converting a bunch of doubles to floats. On 32-bit linux closest I got was 5:20:00.0

I was wondering if the opposite would help: use double, not float. Experiment is here: #2520

**Comment by neheb** [comment]
Might want to add the second commit in this PR to that one.

**Comment by neheb** [comment]
remaining failures are CVE failures. Can you take a look?

**Comment by kevinbackhouse** [comment]
I looked at `test_CVE_2017_14864` first. On x86 it's throwing an exception in a `Safe::add<size_t>()` which obviously overflows more easily on 32-bit than on 64-bit. The result is just that it prints a different error message than the test is expecting, so that should be easy to fix in the test.

**Comment by kevinbackhouse** [comment]
#2522 will hopefully fix the remaining problems

**Comment by neheb** [comment]
Thanks to @kevinbackhouse , this passes now.

**Review by kevinbackhouse — APPROVED** [review]

**Pull request merged**
