### PR TITLE
Getopt changes

### PR DESCRIPTION
**Pull request by D4N**
Port of `getopt.c` to C++.

### CODE REVIEW

**Comment by piponazo** [comment]
I think the errors in the CI jobs:
```
[ 94%] Building CXX object samples/CMakeFiles/getopt-test.dir/getopt-test.cpp.o
/builds/D4N/exiv2/samples/getopt-test.cpp:86:22: error: #if with no expression
 #if EXV_HAVE_UNISTD_H
```
Could be fixed by adding `#include <exiv2/config.h>` in the getopt-test.cpp file.

**Comment by clanmills** [comment]
I think it should be:
```
#ifdef EXV_HAVE_UNISTD_H
```

**Comment by clanmills** [comment]
I've pushed the change into branch getopt-changes.  I can't appreciate the difference between a branch and a PR.

**Comment by clanmills** [comment]
Thanks.

**Comment by D4N** [comment]
clang + ASAN report a memory leak, I'll take a look what's causing this. I can reproduce the issue locally with clang 6.

**Review by clanmills — APPROVED** [review]
Good find.  Thanks.

**Review by piponazo — APPROVED** [review]

**Pull request merged**
