### PR TITLE
Update Catalan translation

### PR DESCRIPTION
**Pull request by bellaperez**
Last updates

### CODE REVIEW

**Comment by clanmills** [comment]
Thanks very much, Toni.  Is this update is to correct errors, or to deal with new messages which have appeared in the code base?  These changes will be released with Exiv2 v0.27.2 which is scheduled for 2019-06-30.  I'll assign @piponazo to review/approve this as he knows git very well.

Thanks very much for dealing with this.

**Comment by bellaperez** [comment]
I update new messages and always fix something.

**Comment by clanmills** [comment]
Thanks for the explanation.  And thank you for your contribution.

**Comment by D4N** [comment]
Do we know anyone that speaks Catalan (or something reasonably close) and could check this? Otherwise I'd suggest we just merge this as @bellaperez appears to be well versed in translations.

**Comment by clanmills** [comment]
When the lights go green, please merge.  And thanks for the back-port to 0.27-maintenance.

**Comment by bellaperez** [comment]
I am certainly very versed in the subject of translations (no writing in English, for now) and I like to ask the KDE Translation Team, to which I belong, and the association that coordinates (Softcatala.cat) all software Translation Teams in the Catalan language.

I'm very busy with Krita translations and I want to put everything up to date, but for holidays I will return it.

Your work is great! Thanks

**Comment by D4N** [comment]
> I am certainly very versed in the subject of translations (no writing in English, for now) and I like to ask the KDE Translation Team, to which I belong, and the association that coordinates (Softcatala.cat) all software Translation Teams in the Catalan language.

I don't think anyone is doubting that!

**Review by D4N — APPROVED** [review]

**Pull request merged**
