### PR TITLE
Add build switch to disable auto ccache

### PR DESCRIPTION
**Pull request by a17r**
Current usage of ccache leads to sandbox issues.
Be able to switch it off for package managers that already can make use of ccache for build.

### CODE REVIEW

**Comment by Kicer86** [comment]
I think we should actually remove any ccache references from cmakelists files. Users can easly setup it manually.

**Comment by clanmills** [comment]
@Kicer86 If you remove the ccache code, can you document how to set that up in README-CMAKE please.

**Comment by Kicer86** [comment]
@clanmills I'm not sure if it is necessary, if someone uses cmake, for sure knows how to do such things. Also there are more ccache-like tools (distcc for example) and I guess it's not handled in README nor by CMakeLists :) There are tons of examples in google too :)

**Comment by a17r** [comment]
In Gentoo we simply set `FEATURES="ccache"` ;)

**Comment by piponazo** [comment]
I was the one that added this feature and I think that it is useful because it makes super easy to anyone to use **ccache** without knowing much about it. One just need to have **ccache** installed in your system to be detected by CMake and used with Exiv2. 

According to the [ccache documentation](https://ccache.samba.org/manual.html#_run_modes) there are two ways to use it:

1. Prefix your compilation commands with ccache (What we do here)
2. Let ccache masquerade as the compiler by creating a symbolic link. This method would affect to the full system, and not only to the Exiv2 project.

I am happy to accept the changes introduced in this PR, even to disable the usage of ccache by default (so someone wanting to use ccache in the project, would need to turn on the option **BUILD_WITH_CCACHE**), but I would like to have this CCACHE feature in the CMake code. I think if it is disabled by default, it would not hurt anybody and help to some contributors :)

**Comment by Kicer86** [comment]
@piponazo I see your point, I just prefer keep things simple. I do not insist on any solution.

**Comment by D4N** [comment]
I think making ccache opt-in is the better choice here, as the default build should do things the most standard way (e.g. use the c/c++ compiler from `CC`/`CXX` env vars), especially if using it can cause issues. But having the option to use ccache is definitely a plus.

**Comment by a17r** [comment]
> I think making ccache opt-in is the better choice here
PR already changed accordingly

**Comment by D4N** [comment]
I saw that it is opt-in now. Looks good to me, so imo we can merge this.

**Review by clanmills — APPROVED** [review]
I'm good with this.  Good team-work everybody.

**Comment by piponazo** [comment]
@a17r would you mind to rebase your branch in top of master? Some other PRs have been merged lately and there are now some conflicts.

**Pull request merged**
