### PR TITLE
Add MinGW build to GitLab CI

### LINKED ISSUE #610: 0.27 : compilation is broken with NLS option enabled under MinGW
compilation trace : 

/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp: In function 'std::__cxx11::string Exiv2::getProcessPath()':
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:467:9: error: 'HANDLE' was not declared in this scope
         HANDLE processHandle = NULL;
         ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:468:9: error: 'processHandle' was not declared in this scope
         processHandle = OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, GetCurrentProcessId());
         ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:468:37: error: 'PROCESS_QUERY_INFORMATION' was not declared in this scope
         processHandle = OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, GetCurrentProcessId());
                                     ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:468:65: error: 'PROCESS_VM_READ' was not declared in this scope
         processHandle = OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, GetCurrentProcessId());
                                                                 ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:468:82: error: 'FALSE' was not declared in this scope
         processHandle = OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, GetCurrentProcessId());
                                                                                  ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:468:109: error: 'GetCurrentProcessId' was not declared in this scope
         processHandle = OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, GetCurrentProcessId());
                                                                                                             ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:468:110: error: 'OpenProcess' was not declared in this scope
         processHandle = OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, GetCurrentProcessId());
                                                                                                              ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:470:13: error: 'TCHAR' was not declared in this scope
             TCHAR filename[MAX_PATH];
             ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:471:58: error: 'filename' was not declared in this scope
             if (GetModuleFileNameEx(processHandle, NULL, filename, MAX_PATH) != 0) {
                                                          ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:471:68: error: 'MAX_PATH' was not declared in this scope
             if (GetModuleFileNameEx(processHandle, NULL, filename, MAX_PATH) != 0) {
                                                                    ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:471:76: error: 'GetModuleFileNameEx' was not declared in this scope
             if (GetModuleFileNameEx(processHandle, NULL, filename, MAX_PATH) != 0) {
                                                                            ^
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/futils.cpp:474:38: error: 'CloseHandle' was not declared in this scope
             CloseHandle(processHandle);
                                      ^
src/CMakeFiles/exiv2lib.dir/build.make:363 : la recette pour la cible « src/CMakeFiles/exiv2lib.dir/futils.cpp.obj » a échouée
gmake[6]: *** [src/CMakeFiles/exiv2lib.dir/futils.cpp.obj] Erreur 1
gmake[6]: *** Attente des tâches non terminées....
/mnt/devel/GIT/6.x/project/bundles/mxe/temp.build/ext_exiv2/ext_exiv2-prefix/src/ext_exiv2/src/convert.cpp:1510:10: warning: 'bool {anonymous}::convertStringCharsetWindows(std::__cxx11::string&, const char*, const char*)' defined but not used [-Wunused-function]
     bool convertStringCharsetWindows(std::string& str, const char* from, const char* to)
          ^
CMakeFiles/Makefile2:212 : la recette pour la cible « src/CMakeFiles/exiv2lib.dir/all » a échouée
gmake[5]: *** [src/CMakeFiles/exiv2lib.dir/all] Erreur 2
Makefile:129 : la recette pour la cible « all » a échouée
gmake[4]: *** [all] Erreur 2
ext_exiv2/CMakeFiles/ext_exiv2.dir/build.make:112 : la recette pour la cible « ext_exiv2/ext_exiv2-prefix/src/ext_exiv2-stamp/ext_exiv2-build » a échouée
gmake[3]: *** [ext_exiv2/ext_exiv2-prefix/src/ext_exiv2-stamp/ext_exiv2-build] Erreur 2
CMakeFiles/Makefile2:415 : la recette pour la cible « ext_exiv2/CMakeFiles/ext_exiv2.dir/all » a échouée
gmake[2]: *** [ext_exiv2/CMakeFiles/ext_exiv2.dir/all] Erreur 2
CMakeFiles/Makefile2:427 : la recette pour la cible « ext_exiv2/CMakeFiles/ext_exiv2.dir/rule » a échouée
gmake[1]: *** [ext_exiv2/CMakeFiles/ext_exiv2.dir/rule] Erreur 2
Makefile:196 : la recette pour la cible « ext_exiv2 » a échouée
gmake: *** [ext_exiv2] Erreur 2
FAILED COMMAND: ${MXE_BUILD_TARGETS}-cmake --build . --config RelWithDebInfo --target ext_exiv2 -- -j$CPU_CORES

[gilles@localhost mxe]$ 

In fact, in futils.cpp there are 2 problems in getProcessPath() : 

    std::string getProcessPath()
    {
        std::string ret("unknown");
    #if defined(WIN32)                                       <======= Must be _MSC_VER
        HANDLE processHandle = NULL;
        processHandle = OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, FALSE, GetCurrentProcessId());
        if (processHandle != NULL) {
            TCHAR filename[MAX_PATH];
            if (GetModuleFileNameEx(processHandle, NULL, filename, MAX_PATH) != 0) {
                ret = filename;
            }
            CloseHandle(processHandle);
        }
    #elif defined(__APPLE__)
        const int pid = getpid();
        char pathbuf[PROC_PIDPATHINFO_MAXSIZE];
        if (proc_pidpath (pid, pathbuf, sizeof(pathbuf)) > 0) {
            ret = pathbuf;
        }
    #elif defined(__linux__) || defined(__CYGWIN__) || defined(__MINGW__)
        // http://stackoverflow.com/questions/606041/how-do-i-get-the-path-of-a-process-in-unix-linux
        char proc[100];
        char path[500];
        sprintf(proc,"/proc/%d/exe", getpid());
        ssize_t l = readlink (proc, path,sizeof(path)-1);     << =========== Do not exists under Mingw
        if (l>0) {
            path[l]=0;
            ret = path;
        }
    #endif
    #if defined(WIN32)
        const size_t idxLastSeparator = ret.find_last_of('\\');
    #else
        const size_t idxLastSeparator = ret.find_last_of('/');
    #endif
        return ret.substr(0, idxLastSeparator);
    }

// ---------------------------------------

I take a look under Qt5 code which is fully portable and support very well MinGW, the readlink() call is wrapped with access()

Gilles Caulier

### PR DESCRIPTION
**Pull request by D4N**
This PR is split off of #645: it contains only the fixes to the source code and the addition of a GitLab build job of MinGW on Fedora.

The commit from @clanmills will automatically close #610, in case this does not fix the issue: @cgilles please object. 

I can reword the commit so that #610 stays open.

### CODE REVIEW

**Review by piponazo — APPROVED** [review]
Thanks for taking care about this!

If this fixes Gilles problem, we close #720

**Comment by cgilles** [comment]
I will verify all this patch with MXE when you will release a 0.27.1 beta, or when git/master will be ready to test.

We are in digiKam 6.1.0 stage to adjust for the next release. Let's me hear when i can test compilation with a code enough stable.

Gilles Caulier

**Comment by clanmills** [comment]
I'm about to start work on Exiv2 v0.27.1.  It's currently shown as 83% complete.  https://github.com/Exiv2/exiv2/milestone/3

I'm aiming for Exiv2 v0.27.1.1 (RC1) about 2019-03-15 and Exiv2 v0.27.1 (GM) by 2019-03-31.

I hope that RC1 == GM and anything discovered/surfacing after RC1 can be deferred for v0.27.2 (later in 2019).

**Comment by D4N** [comment]
@cgilles Since MXE is of such a big priority for you: if you have a docker container on dockerhub with MXE preinstalled, we can plug it into our CI on GitLab.

**Comment by cgilles** [comment]
i don' have a docker for MXE as i build whole cross compiled code on my native Linux host, but i can check the compilation using git/master code

**Pull request merged**
