### PR TITLE
Add cr3 tags

### PR DESCRIPTION
**Pull request by alexvanderberkel**

### CODE REVIEW

**Comment by clanmills** [comment]
Good Job, Alex.  It builds.

Lots of messages from the test suite causing the CI to be red.  We'll investigate and fix them.  Not a problem.  It's just work.

**Comment by alexvanderberkel** [comment]
There is still one tag to be done --> Categories. That I haven't been able today.

**Comment by alexvanderberkel** [comment]
A huge thanks goes out to @boardhead and @lclevy fore providing a lot of information around the new Canon tags. That was very helpful to get it to this level. Thanks for your work.

**Comment by clanmills** [comment]
I've looked at the differences in exiv2-test.sh, crw-test.sh, test_issue_445.py, test_issue_247.py which are disturbed by defining RecordMode in this PR.

```bash
520 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/test $ ../build/bin/taglist ALL | csv - | grep RecordMode
[CanonCs.RecordMode]	[9]	[0x0009]	[CanonCs]	[Exif.CanonCs.RecordMode]	[SShort]	[Record Mode]	
[Casio2.RecordMode]	[12288]	[0x3000]	[Casio2]	[Exif.Casio2.RecordMode]	[Short]	[Record Mode]	
521 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/test $ taglist ALL | csv - | grep RecordMode
[Casio2.RecordMode]	[12288]	[0x3000]	[Casio2]	[Exif.Casio2.RecordMode]	[Short]	[Record Mode]	
522 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/test $ 
```

test_issue_981.py reports Exif.Canon.AFConfig and Exif.CanonAFMicroAdj which has been defined.

So, this is looking really good.  When you've concluded your investigation concerning "Categories", I'll approve this.

**Comment by alexvanderberkel** [comment]
Haven't found any information around "Categories" online and within my EOS R. I would propose to skip searching for that tag and leave it be until further information reveals itself.

**Review by clanmills — APPROVED** [review]
Good Job, Alex.  As this PR has passed the CI, I will merge.  Thanks for your contribution.

**Pull request merged**
