### PR TITLE
fix_2044_add_tiff_tags

### LINKED ISSUE #2044: According to release notes of 0.27.5 #1765 was included but it's not
##### **Describe the bug**
The release notes of 0.27.5 state that PR #1765 was included in this release, however it was never committed to this branch.

##### **To Reproduce**
1. On Windows install GIMP 2.10.30 which includes exiv2 0.27.5 from MSYS2.
2. Open any TIFF image that includes Exif.Image.PageName, e.g. (sorry, can't add tif directly and even after zipping it, it still doesn't want to add it)
3. Open the metadata viewer and see that instead it still lists Exif.Image.0x011d as tag name (GIMP gets the literal name from exiv2).

##### **Expected behavior**
The metadata viewer should show the tag Exif.Image.PageName.

##### **Desktop (please complete the following information):**
- OS and version: Windows 10 Home, 64-bit  
- Compiler and version: The version used on the GIMP release build.  
- Compilation mode and/or compiler flags: -  

##### **Additional context**
When looking at [https://github.com/Exiv2/exiv2/blob/0.27-maintenance/src/tags_int.cpp#L599](https://github.com/Exiv2/exiv2/blob/0.27-maintenance/src/tags_int.cpp#L599) in the 0.27 maintenance branch I do not see this tag around line 599, while in the main branch I do see it at [line 605](https://github.com/Exiv2/exiv2/blob/main/src/tags_int.cpp#L605).

### PR DESCRIPTION
**Pull request by clanmills**
See #2044

### CODE REVIEW

**Comment by clanmills** [comment]
The Windows/CI is broken.  I think it needs conan 1.43.  I can't submit a change to the PR.  Something to do with OAuth.  @kmilos Can you submit this for me, please?

```diff
diff --git a/.github/workflows/on_PR_windows_matrix.yml b/.github/workflows/on_PR_windows_matrix.yml
index 05e88cd..20e38e5 100644
--- a/.github/workflows/on_PR_windows_matrix.yml
+++ b/.github/workflows/on_PR_windows_matrix.yml
@@ -46,7 +46,7 @@ jobs:
 
       - name: Install Conan & Common config
         run: |
-          pip.exe install "conan==1.39.0"
+          pip.exe install "conan==1.43.0"
           conan config install https://github.com/conan-io/conanclientcert.git
           conan profile new --detect default
           conan profile update settings.build_type=${{matrix.build_type}} default
```

**Comment by kmilos** [comment]
Will do as soon as I get a chance

**Review by kmilos — APPROVED** [review]
LGTM

**Comment by clanmills** [comment]
@kmilos Thanks for fixing this, Milo&scaron;.  I don't know why I can't update a PR that I created.  Grrrrr. Git.

Happy New Year.  Best Wishes for 2022.  This will be my last year of contributing to Exiv2.  I really hope to see the project moving smoothly into the future.  I've got to stop pushing, retire and leave it alone.  What will be will be.

**Comment by kmilos** [comment]
Same to you Robin, I hope you properly enjoy your retirement this year!

**Comment by clanmills** [comment]
Not only will I enjoy my retirement, I'm sure most of the team will be pleased when I am not snooping around.  It's time for me to let go.  And for sure, I cannot do anything that you guys cannot do.  @nehaljwani is doing some excellent release engineering work.

**Pull request merged**
