### PR TITLE
Fix pr#2053 for native Windows builds

### PR DESCRIPTION
**Pull request by postscript-dev**
Fixes:
1. Fix Windows native build error introduced in pr#2053. Correct problem of mismatched Windows/Linux newline characters.
2. Remove dependency on command line tools being available.

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
For future reference: this is a relatively new test, added in #2053.

**Comment by kevinbackhouse** [comment]
@postscript-dev: it looks like this test never caused a problem in our automated Windows tests. Do you have any idea what's different about the automated tests that stopped them from being affected?

**Comment by postscript-dev** [comment]
The only interesting thing I found on MSYS2/MinGW64 was that when using `diff`, the different newline characters were ignored by default. I didn't need the additional parameter but added it for compatibility with Linux/macOS.

**Comment by kevinbackhouse** [comment]
I was wondering if this could be caused by git auto-converting the line endings when you check the code out. Which file has the Windows line endings: `$filename_save` or `$filename_out`?

**Comment by clanmills** [comment]
@postscript-dev I'm surprised you're executing diff/cmp.  The usual workflow in the test suite is to store the "reference output" in the script (in the `stdout` array) and allow the script to output.  The framework will perform the diff for you.  By keep everything inside the Dan's excellent python framework, you avoid platform ugliness to ensure utilities such as diff/cmp are on the PATH.

**Comment by postscript-dev** [comment]
@kevinbackhouse: Sorry for the delay. In MSYS2/MinGW64, I deleted the `filename`, `filename_save` and `filename_out` files, then restored them using git and ran the Python test again. `filename` and `filename_save` both contained the Linux newlines (which is the same as in git) and `filename_out` (which was generated by the Python test) has the Windows newlines. Restoring the files using git didn't change the endings on my machine.

I don't have Visual Studio installed but in Windows 11, I installed Python3 and downloaded the latest official Windows nightly build ([exiv2-1.0.0.9-2019msvc64.zip](https://github.com/Exiv2/exiv2/releases/download/untagged-6965c8e2e7bb787530d5/exiv2-1.0.0.9-2019msvc64.zip)). When I ran *tests\bugfixes\github\test_issue_1959.py*, this behaved the same as the MSYS2/MinGW version. Both `filename_out` files have Windows newlines.

@clanmills: You are right about using the Python compare and I did consider that method. As I included a lot of tags in the file, the output is quite long and I was unsure about adding that much text to a Python test. Your comment about not having `cmp` or `diff` in the path, is interesting though. Do you think that I should change this to use the Python `stdout` array?

**Comment by clanmills** [comment]
@postscript-dev I think you should leave the test framework to do the comparison for you.

If the "reference output" is really long, you can probably read it into the test suite.  Typical test code is:

```python
         stdin  = [ "dkdkdkdkd","kekeke010101"]
        stderr  = [ "", ""]
```
Instead of having huge strings in the python code, you could read them from a file - something like this _(take care, my python's rusty and probably wrong)_ but you get the idea:

```python
         stdin  = [ "",""]
        stderr  = [ "", ""]
       stdin[0] = open('reference_1234_0.txt', 'rb').read()
       stdin[1] = open('reference_1234_1.txt', 'rb').read()
```

There are variables set from tests/suite.conf to identify directories.  For example: `data_path` is the path to the test/data.  You might need to use python's `os.path.join`.  I don't remember much about the test suite, however it is well designed.

**Comment by postscript-dev** [comment]
@clanmills: Thanks for explaining, I will change the test over to use the Python framework instead. This will be a job for next week sometime.

**Review by piponazo — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
