### PR TITLE
Nikon printApertureLd4 translate value 0 to n/a

### PR DESCRIPTION
**Pull request by norbertwg**
A value of 0 in Exif.NikonLd4.FNumber or Exif.NikonLd4.FNumber was translated to F0.5. In most cases 0 was entered, when no other lens data were available. When lens data were available, F0.5 did not match to them. So my conclusion: the value 0 stands for not defined or unknown.

### CODE REVIEW

**Comment by kmilos** [comment]
How about we do the same for FocalLength2 and FocusDistance2 as well? Looks like this group of  tags is reserved for real Z lenses (LensID not 0)...

**Comment by norbertwg** [comment]
I changed some more print functions to translate value 0 to n/a. Below a complete list of functions and affected tags. In theory many tags are affected, but so far I found only impact on the NikonLd4 tags. There I found a vanilla value of 0, whereas the other tags seem to have always a value greater than 0. As @kmilos already stated, it seems to be related to Z-lenses. 
One example: FocalLength was filled by a Nikon Z6 with Nikon AF-S Nikkor 500mm f/5.6E PF ED VR, whereas FocalLength2 was filled with 0. With a Nikkor Z 14-24mm f/2.8 S, FocalLength2 was filled whereas FocalLength was empty.

**printApertureLd4**
Exif.NikonLd4.FNumber
Exif.NikonLd4.MaxAperture

**printFocusDistance**
Exif.NikonLd2.FocusDistance
Exif.NikonLd3.FocusDistance
Exif.NikonLd4.FocusDistance

**printFocal**
Exif.NikonLd1.MinFocalLength
Exif.NikonLd1.MaxFocalLength
Exif.NikonLd2.FocalLength
Exif.NikonLd2.MinFocalLength
Exif.NikonLd2.MaxFocalLength
Exif.NikonLd3.FocalLength
Exif.NikonLd3.MinFocalLength
Exif.NikonLd3.MaxFocalLength
Exif.NikonLd4.FocalLength
Exif.NikonLd4.MinFocalLength
Exif.NikonLd4.MaxFocalLength

**printFocalLd4**
Exif.NikonLd4.FocalLength2

**printFocusDistanceLd4**
Exif.NikonLd4.FocusDistance2

**printAperture**
Exif.NikonLd1.MaxApertureAtMinFocal
Exif.NikonLd1.MaxApertureAtMaxFocal
Exif.NikonLd2.AFAperture
Exif.NikonLd2.MaxApertureAtMinFocal
Exif.NikonLd2.MaxApertureAtMaxFocal
Exif.NikonLd2.EffectiveMaxAperture
Exif.NikonLd3.AFAperture
Exif.NikonLd3.MaxApertureAtMinFocal
Exif.NikonLd3.MaxApertureAtMaxFocal
Exif.NikonLd3.EffectiveMaxAperture
Exif.NikonLd4.AFAperture
Exif.NikonLd4.MaxApertureAtMinFocal
Exif.NikonLd4.MaxApertureAtMaxFocal
Exif.NikonLd4.EffectiveMaxAperture

**Comment by kmilos** [comment]
TBH, I don't feel 100% comfortable with changes to all of the Nikon makernotes - the older generations have been around w/ this behaviour for a long while.

My comment was specifically about last introduced Ld4 (Z mount) only...

**Comment by kmilos** [comment]
Yes, and as I said, it was a concern specific to Ld4 - there we at least have some hard evidence (that you presented above as well) that either one set of values (for the Z native lens or the FTZ adapted lens) is filled in and the other set to zero (i.e. "n/a"), and that those two sets are mutually exclusive, and we can perhaps conclude that was Nikon's design intention.

I cannot say w/ the same certainty what was Nikon's intention way back for Ld1, Ld2, and Ld3 values, and if those are absolutely guaranteed to be backward compatible w/ the FTZ set of Ld4. We can suspect that is the case, but personally I can't say I am sure of it.

If someone else has more insight into Nikon lens metadata, they're very welcome to chime in.

**Comment by norbertwg** [comment]
After sleeping over it, I had an idea to get the missing samples. I took some images with a D80 resp. D7000 with a MF lens or no lens at all. Then the listed tags all have a value of 0. So I think the logic to translate 0 to n/a is valid for Ld2 and Ld3. Perhaps somebody has access to an elder Nikon to make the same test for Ld1.

**Comment by kmilos** [comment]
Thanks, that's a good confirmation then!

I'll check if some old Nikon samples on  https://raw.pixls.us/ are perhaps MF...

**Comment by kmilos** [comment]
It would seem [only the D100 had Ld1 (v1.00 info)](https://www.photonstophotos.net/NikonInfo/NEF_Version_Matrix.htm), and the one sample on RPU is unfortunately not MF.

Given the very rare corner case, I guess it is low risk to go ahead and adopt it for Ld1 as well then?

**Comment by kmilos** [comment]
Great.

Since we're touching/cleaning this file, would you mind adding the following related tweaks as well?
```diff
diff --git a/src/nikonmn_int.cpp b/src/nikonmn_int.cpp
index d191d3dd0..5ee14266c 100644
--- a/src/nikonmn_int.cpp
+++ b/src/nikonmn_int.cpp
@@ -1861,7 +1861,7 @@ std::ostream& Nikon3MakerNote::print0x0088(std::ostream& os, const Value& value,
       // But when actually in "Single area, Center" this can mean
       // that focus was not found (try this in AF-C mode)
       // TODO: handle the meaningful case (interacts with other fields)
-      os << "N/A";
+      os << _("n/a");
       return os;
     }
 
@@ -3839,16 +3839,16 @@ std::ostream& Nikon3MakerNote::printPictureControl(std::ostream& os, const Value
   oss.copyfmt(os);
   switch (pcval) {
     case 0:
-      os << "Normal";
+      os << _("Normal");
       break;
     case 127:
-      os << "n/a";
+      os << _("n/a");
       break;
     case -127:
-      os << "User";
+      os << _("User");
       break;
     case -128:
-      os << "Auto";
+      os << _("Auto");
       break;
     default:
       os << pcval;

```
TIA

**Review by kmilos — APPROVED** [review]

**Comment by kmilos** [comment]
@Mergifyio backport 0.28.x

**Comment by norbertwg** [comment]
I found somebody, who knows somebody, who has a Nikon D100. So I got an image with a manual lens, and the NikonLd1 tags are filled with 0. So our assumption finally is confirmed.

**Comment by kmilos** [comment]
@norbertwg Amazing effort, thanks for confirming!

**Pull request merged**
