### PR TITLE
Fix 981 Canon Auto Focus

### PR DESCRIPTION
**Pull request by clanmills**
WIP.  https://github.com/Exiv2/exiv2/issues/981#issuecomment-520755068

At the moment, this can read the first 8 fields of CanonAf (Mode, Width, Height etc)
```
858 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -pa --grep CanonAf ~/Downloads/IMG_7600.jpg 
Exif.CanonAf.AFInfoSize                      Short       1  96
Exif.CanonAf.AFMode                          Short       1  Single-point AF
Exif.CanonAf.AFNumPoints                     Short       1  9
Exif.CanonAf.AFNumValid                      Short       1  9
Exif.CanonAf.AFImageWidth                    Short       1  4752
Exif.CanonAf.AFImageHeight                   Short       1  3168
Exif.CanonAf.AFWidth                         Short       1  4272
Exif.CanonAf.AFHeight                        Short       1  2848
859 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

To be investigated and done:
1) Read the Points into arrays (Widths, Heights, X/Y Positions)
2) Read the data following the Points (AFPointsInFocus etc)
3) Investigate if we can retain the "old" Exif.Canon.AFInfo

### CODE REVIEW

**Comment by clanmills** [comment]
Good Progress.  

Puzzle 3 solved.  The "old" AfInfo has been restored to Exif.Canon.AFInfo.  AfInfo2 is reported as Exif.CanonAf2.AFxxx. 

Still to solve: Puzzles 1 and 2 (read the points, real trailer).

**Comment by clanmills** [comment]
This is now working OK when NumPoints == 9 and not correct otherwise.  Location for fix is documented in `src/tiffvisitor.cpp` and is probably difficult to implement.  We could fallback to modifying the selector to only decode AutoFocus2 which NumPoints == 9 , else treat as AutoFocus.
```
1027 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -pa -g CanonAf ~/Downloads/IMG_7600.jpg 
Exif.CanonAf2.InfoSize                       Short       1  96
Exif.CanonAf2.Mode                           Short       1  Single-point AF
Exif.CanonAf2.NumPoints                      Short       1  9
Exif.CanonAf2.NumValid                       Short       1  9
Exif.CanonAf2.ImageWidth                     Short       1  4752
Exif.CanonAf2.ImageHeight                    Short       1  3168
Exif.CanonAf2.Width                          Short       1  4272
Exif.CanonAf2.Height                         Short       1  2848
Exif.CanonAf2.AreaWidths                     SShort      9  115 115 115 162 200 162 115 115 115
Exif.CanonAf2.AreaHeights                    SShort      9  153 153 153 105 199 105 153 153 153
Exif.CanonAf2.AreaXPositions                 SShort      9  -1127 -674 -674 0 0 0 674 674 1127
Exif.CanonAf2.AreaYPositions                 SShort      9  0 321 -321 603 0 -603 321 -321 0
Exif.CanonAf2.PointsInFocus                  SShort      1  16
Exif.CanonAf2.PointsSelected                 Short       1  256
Exif.CanonAf2.PrimaryPoint                   Short       1  0
1028 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ bin/exiv2 -pa -g CanonAf ~/Downloads/IMG_7601.jpg 
Exif.CanonAf2.InfoSize                       Short       1  546
Exif.CanonAf2.Mode                           Short       1  Single-point AF
Exif.CanonAf2.NumPoints                      Short       1  63
Exif.CanonAf2.NumValid                       Short       1  61
Exif.CanonAf2.ImageWidth                     Short       1  6720
Exif.CanonAf2.ImageHeight                    Short       1  4480
Exif.CanonAf2.Width                          Short       1  6720
Exif.CanonAf2.Height                         Short       1  4480
Exif.CanonAf2.AreaWidths                     SShort      9  218 218 218 218 218 218 218 218 218
Exif.CanonAf2.AreaHeights                    SShort      9  218 218 218 218 218 218 218 218 218
Exif.CanonAf2.AreaXPositions                 SShort      9  218 218 218 218 218 218 218 218 218
Exif.CanonAf2.AreaYPositions                 SShort      9  218 218 218 218 218 218 218 218 218
Exif.CanonAf2.PointsInFocus                  SShort      1  218
Exif.CanonAf2.PointsSelected                 Short       1  218
Exif.CanonAf2.PrimaryPoint                   Short       1  218
1029 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ 
```

**Comment by derselbst** [comment]
>  We could fallback to modifying the selector to only decode AutoFocus2 which NumPoints == 9 , else treat as AutoFocus.

ATM, NumAFPoints may be 7, 9, 11, 19, 31, 45 or 61 , so the implementation could be hardcoded to those values. However I think a generic implementation is preferable to avoid that new camera models are handled incorrectly. Alternatively you could just treat it as raw blob as done before with `Exif.Canon.AFInfo`, but with correct signedness.

**Comment by clanmills** [comment]
@derselbst Thanks for your comments, Tom.

I'd like to invent/discover a way to dynamically configure this at run-time as we'll probably discover something similar in the future.

I thought of having different structures for NumPoints, however the architecture of Exiv2 will result in the keys having names such as Exif.CanonAF9.NumPoints, Exif.CanonAF11.NumPoints because every group requires a unique name.  This isn't nice.

So, I will investigate dynamically creating the structure at run time and the keys Exif.CanonAF2.Xxx and it will work with any number of points.

**Comment by clanmills** [comment]
I'm closing this.  I've thought of a much simpler way that does more with a LOT less code.

**Pull request closed without merging**
