### PR TITLE
Consistent debug definitions

### PR DESCRIPTION
**Pull request by piponazo**
This PR address the issue #272. You can find there the complete description of the problem and the proposed solution.

### CODE REVIEW

**Comment by D4N** [comment]
Uhm, this patch has one disadvantage: now you can no longer create a build without `DEBUG` and without `NDEBUG` (i.e. without the debug output and with assertions turned on). The issue with defining `DEBUG` is, that it breaks the test suite, since it spits out a lot of information to stderr. But during testing I don't want to turn off assertions yet I don't want to turn on the debug output, since it makes working with the test suite inconvenient.

**Comment by piponazo** [comment]
Good point, I did not think about that. One question, how were achieving such behaviour before on Linux? By default we were adding the `-DDEBUG` on Debug builds, see this commit:

https://github.com/Exiv2/exiv2/pull/273/commits/92a8dbe5359fba8843920b10ae8871ac30f70f5a

Were you removing the `DEBUG` definition manually ?

I guess, that then we should do something like this:

- Leave the code using `DEBUG` as it is.
- Remove `DEBUG` from the default compiler flags for Debug builds. 
- Add a way in CMake to add such DEBUG definition (or just tell users to define it if they are interested in that behavior).

**Comment by D4N** [comment]
I invoke cmake without a build type and add the flags myself via the CXXFLAGS environment variable.

I agree with your suggestion. I am adding DEBUG manually anyway.

**Comment by clanmills** [comment]
@D4N You can detect most of the build switches at run-time.
```
589 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 --verbose --version | grep debug
debug=0
590 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ 
```
It's reasonable that the test-suite is designed to run on release builds.  Maybe you could detect this in `tests/runner.py` report and terminate.

Incidentally, I often use the compiler -DDEBUG on a release build to get additional output without launching the debugger.  So, I edit a file and build with `$ env CXXFLAGS=-DDEBUG make` and I see the debug output strings from only the file in which I am interested.  I'm sure you have your own ingenious little tricks.

**Comment by clanmills** [comment]
Just thought of something else.  I think the `#ifdef DEBUG ... #endif` always outputs to `std::cerr`, so maybe that can be safely piped to /dev/null for both release and debug builds.

This is probably not a good idea as I suspect we have legitimate output written to `std:cerr` from the release build.

**Comment by piponazo** [comment]
I will restart the work from scratch after the comments made. I'm closing this PR.

**Pull request closed without merging**
