### PR TITLE
Rename resp. remove duplicate exif keys

### PR DESCRIPTION
**Pull request by norbertwg**
Duplicate key names with different tag are renamed. Following most of the existing entries, the key with higher tag number is renamed to ...2.

Exception: Canon.CustomFunctions, Olympus.ImageHeight, Olympus.ImageWidth. In the available images samples only the key with higher tag number is used, so changing the other has less impact on test data and also on users.

Canon.WhiteBalanceTable with tag 0x00a4 was listed twice, once with description "SharpnessTable". The entry with the deviating description is deleted.

### CODE REVIEW

**Review by kevinbackhouse — DISMISSED** [review]

**Comment by kmilos** [comment]
No idea why the CI fails, and if it's safe to merge...

**Comment by piponazo** [comment]
> No idea why the CI fails, and if it's safe to merge... Maybe rebase to include the CI switch to Ubuntu 22.04?

Yes, the CI issue was fixed already. Please rebase your branch in top of `main` and push again.

**Comment by norbertwg** [comment]
I updated my branch to reflect latest changes in main. Still one failed check:
Nightly - Linux distributions / distros (alpine:3.13, clang++, Release, OFF) (pull_request)
https://github.com/Exiv2/exiv2/actions/runs/3801758971/jobs/6466577419#logs 
at installing dependencies

**Comment by kmilos** [comment]
I've restarted the job, let's see...

Btw, for future reference, please rebase the PR branch on top of main, not merge main into it.

**Review by piponazo — APPROVED** [review]

**Pull request merged**
