### PR TITLE
Add Nikon F version of Tamron 17-35 mm F/2.8-4 Di OSD

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
I just got this lens and saw that exiftool has it, whereas exiv2 does not yet know about it, so I [used their lens tag values](https://github.com/exiftool/exiftool/blob/c6ca23d647608d16a702fce331a761e60d8708fe/lib/Image/ExifTool/Nikon.pm#L543) and the name from [the Tamron website](https://www.tamron.eu/lenses/17-35-mm-f28-4-di-osd/). Notably, despite being an autofocus lens it lacks the `AF` designator (both on the Tamron website and the barrel of the lens).

### CODE REVIEW

**Review by clanmills — COMMENTED** [review]
@Leonidas-from-XIV Thanks for sending this.

1) Can you put your change at the bottom or the table as I have done for other changes.  The data in that table was externally sourced and I would like our changes to be clearly identified to be sure they aren't lost if/when a new version of the table is available.
 
2) Can you provide a test image and (even better) update the test suite.  If you provide the test image, I will extract the metadata and update the test suite.

**Comment by Leonidas-from-XIV** [comment]
Okay, I've shuffled the line to the end of the table with a link to this PR.

I don't know yet how to update the test suite at the moment, but in the meantime I can provide a [test image raw](https://xivilization.net/~marek/binaries/tamron1735.nef) taken with that lens.

**Comment by clanmills** [comment]
@Leonidas-from-XIV Thanks for the change and the test image.  I'll update the test suite and merge this.  I'll be in Exiv2 v0.27.3 https://github.com/Exiv2/exiv2/issues/1018#issuecomment-604539346

**Comment by Leonidas-from-XIV** [comment]
Excellent, thank you!

**Comment by clanmills** [comment]
https://github.com/Exiv2/exiv2/pull/new/fix_1105_0.27

**Pull request closed without merging**
