### PR TITLE
Add nls_test() to PR #1341

### PR DESCRIPTION
**Pull request by LeoHsiao1**
@clanmills 
I have no right to push directly to the `fix_1278_nls_test_0.27` branch, so I present this PR first.
I still can't do a localized display, but this test case is easy to write.

### CODE REVIEW

**Review by clanmills — COMMENTED** [review]
This looks fine.  I'll fold your changes into #1341 tomorrow and test it on the supported platforms AND centOS.

I have a music teacher visiting tomorrow morning and staying for lunch.  I'll deal with this tomorrow afternoon.

I thought you had write access to the repos and could modify my PRs.  I'll look into that.

**Comment by clanmills** [comment]
Thanks for submitting a PR to the branch fix_1278_nls_test_0.27.  That's ingenious.

You have "write" access to the repos.  That's the same level of access as Luis, Dan and Rosen.  I don't know/understand git/github sufficiently to know what you can do.  I'm pretty sure that Luis and Dan have modified my PRs in the past when I couldn't understand git at all. 

This works well on macOS.  Questions (before I merge and test this on centOS).

1 Are you sure you are supporting all the environment strings in README.md:

| Variable        | Default | Platforms | Purpose |
|:--                 |:--        |:--     |:-- |
| EXIV2_BINDIR       | **\<exiv2dir\>/build/bin** | All Platforms | Path of built binaries (exiv2.exe) |
| EXIV2_PORT         | **12762**<br>**12671**<br>**12760**  | Cygwin<br>MinGW/msys2<br>Other Platforms | Test TCP/IP Port   |
| EXIV2_HTTP         | **http://localhost**  | All Platforms | Test http server   |
| EXIV2_ECHO         | _**not set**_ | All Platforms | For debugging Bash scripts |
| VALGRIND           | _**not set**_ | All Platforms | For debugging Bash scripts |
| VERBOSE            | _**not set**_ | All Platforms | Causes make to report its actions |
| PATH<br>DYLD\_LIBRARY\_PATH<br>LD\_LIBRARY\_PATH    | $EXIV2\_BINDIR/../lib | Windows<br>macOS<br>Other platforms | Path of dynamic libraries |

2.  Is there a typo in tests/bash_tests/testcases nls_test()

```python
        # variable LANG is unused
```

Perhaps it should be: 
```python
        # variable LANG is used as follows:
```

**Comment by LeoHsiao1** [comment]
- I forgot you gave me write permission for exIV2.Now I'm pushing directly to the `fix_1278_nls_test_0.27` branch.
- In my understanding, the variable Lang is not used:
    ```sh
    if [ "$platform"  == "platform=linux" ]; then
    	LANG=LANGUAGE
    else 
    	LANG=LANG
    fi
    ##
    # if necessary ditto /usr/local/share/locale -> build/share/locale
    share=${bin}../share
    if [ ! -e $share ]; then
    	mkdir -p $share
    fi
    usr=/usr/local/share/locale
    if [ -e "$usr" -a -e "$share" ]; then
    	cp -r "$usr" "$share"
    else 
    	echo "localisation files are not installed in $usr"
    	exit 0
    fi
    ##
    # test a couple of languages
	for l in fr_FR es_ES; do
		LC_ALL=$l LANG=$l ${bin}exiv2
    done
    ```

**Comment by clanmills** [comment]
It should be used.  My bug.  The command should be:
```bash
##
# test a couple of languages
for l in fr_FR es_ES; do
	LC_ALL=$l $LANG=$l ${bin}exiv2
done
```

**Comment by LeoHsiao1** [comment]
OK. This week I will support all environment variables. Today I found a strange British documentary, RIVER MONSTERS.

**Comment by clanmills** [comment]
Let's get to the end of nls_test.  I'll fix my bug in test/nls_test.sh and you should update tests/bash_test/test_cases.py appropriately.

You can deal with the environment variables in another PR.  Can you close this PR if it's not needed.

I've never heard about or seen River Monsters:  https://en.wikipedia.org/wiki/River_Monsters

**Pull request merged**
