### PR TITLE
cmake: Fix compiler flag support variables

### PR DESCRIPTION
**Pull request by jtojnar**
When working on https://github.com/Exiv2/exiv2/pull/1271, I noticed two issues in the original patch:

- the code mixes tabs for indentation with spaces, which does not fit into the rest of the code
- there is a mismatch in CMake variables representing compiler flag support

### CODE REVIEW

**Review by piponazo — APPROVED** [review]
Thanks for fixing this!

**Comment by piponazo** [comment]
I noticed that the clang builds are failing in some distros:

```
[  2%] Building CXX object src/CMakeFiles/exiv2lib_int.dir/canonmn_int.cpp.o
clang-10: error: unknown argument: '-fstack-clash-protection'
``` 

https://github.com/Exiv2/exiv2/pull/1272/checks?check_run_id=1070319141

Would you mind to also take a look to that issue?  Otherwise, it would be fine to merge this and fix things step by step.

**Comment by clanmills** [comment]
Head's up, @piponazo.  I've just discovered an issue with this on Solaris.  #1290

**Comment by piponazo** [comment]
@jtojnar I included your changes in #1292 while I was trying to fix all the CI jobs on master. I will close this PR therefore.

Thank you again for your contributions and efforts 😉

**Pull request closed without merging**
