### PR TITLE
Fix `exiv2`: verbose extract stdout mutli-file

### PR DESCRIPTION
**Pull request by postscript-dev**
When using `exiv2 --verbose`, `--extract` with stdout and multiple files, the output is concatenated together.

### CODE REVIEW

**Review by piponazo — COMMENTED** [review]
I do not use much of the functionality of the exiv2 command line application and I am not the best to judge if that "feature" might have been used by somebody. IMHO it looks like a reasonable thing to limit :+1: 

Do you really need to add a new .jpg image for the tests? Could you just reuse some other .jpg file from the `test/data`folder?

**Comment by postscript-dev** [comment]
@piponazo:
>I do not use much of the functionality of the exiv2 command line application and I am not the best to judge if that "feature" might have been used by somebody. IMHO it looks like a reasonable thing to limit 👍

Previously in the `exiv2` sample, I removed `--verbose` when using `--extract` with stdout. This prevented the filename from being prepended to the output, which would have corrupted the data. I realised afterward though that if multiple files were used, then all the output would be concatenated together and be corrupted.

> Do you really need to add a new .jpg image for the tests? Could you just reuse some other .jpg file from the test/datafolder?

As for image files, I had wondered the same thing. I wasn't sure if it was better for each test to be self contained or if reducing the number of files was better. I am happy to follow the Exiv2 policy.

**Comment by postscript-dev** [comment]
> I am not sure if we ever discussed about that ... I would say that it makes sense to add new files when it is the only way to check something new. If it is possible to check something with the existing test-data, I would not add more binaries into the repository.

OK, I will switch the file to an existing one. After this merges, I will try and add a comment somewhere in the documentation to explain the policy.

**Comment by clanmills** [comment]
@postscript-dev You are the expert in the exiv2 command-line program.  I'm sure everybody on Team Exiv2 agrees.

I thought there was something in `tests/suite.conf ` to massage paths in the diff comparison.  If all your input images are in $data_path, I believe the diff will succeed.  Or perhaps I haven't understood your situation.

I really like how you used setUp()/open/read to deal with the reference output in #2058.  Code can be beautiful.  Good Job.

**Comment by postscript-dev** [comment]
@clanmills:
> I thought there was something in tests/suite.conf to massage paths in the diff comparison. If all your input images are in $data_path, I believe the diff will succeed. Or perhaps I haven't understood your situation.

> I really like how you used setUp()/open/read to deal with the reference output in https://github.com/Exiv2/exiv2/pull/2058. Code can be beautiful. Good Job.

In both of your points, I had a problem with variables. I tried to use something like:
```
stdin = open("$filename", 'rb').read()
```
but it seems that `open()` is evaluated differently and the variables defined in the test suite and individual tests are not available. In the end, [tests/README-TESTS.md](https://github.com/Exiv2/exiv2/blob/main/tests/README-TESTS.md) was very helpful and provided the `setup()` answer. I don't know much about Python.

**Comment by clanmills** [comment]
I did work on README-TESTS.md.  It needs lots more work.  Dan's an amazing guy and engineer. For sure, he'll never win a Nobel prize for writing user documentation in English _(and neither will I)_.

If there are architecture/structure issues with the test suite and tests/suite.conf, it would good to address them.  @1div0  (Peter K) has offered to get more involved with testing.

**Review by piponazo — APPROVED** [review]

**Comment by clanmills** [comment]
@postscript-dev Here's the PR for the work that I started on tests/README-TESTS.md https://github.com/Exiv2/exiv2/pull/1553  I'm not asking you to finish this.  I know you are already over-loaded.  I'm amazed at the work involved in the Nikon/Flash business.

I suspect that the handling of environment variables in the test suite is hidden and should be exposed in the python API.  For example, a typical test is test_pr_pr_1409.py and has the following code:

```python
# -*- coding: utf-8 -*-

import system_tests

class FujiFilm_IFD_Tags_pr1409(metaclass=system_tests.CaseMeta):
    url = "https://github.com/Exiv2/exiv2/pull/1409"
    
    filename = "$data_path/exiv2-pr1409.exv"
    commands  = ["$exiv2 -g Fujifilm $filename"]
    stderr = [""]
    stdout = ["""Exif.Fujifilm.Version                        Undefined   4  48 49 51 48
Exif.Fujifilm.SerialNumber                   Ascii      48  FF0...
...
"""]
    retval = [0]
```

The variable `filename = "$data_path/exiv2-pr1409.exv"` is magically converted when the command `"$exiv2 -g Fujifilm $filename"` is executed by the framework.  How can you use `$data_path` directly in your code?  In your case you want to do something like:

```python
stdout[0] = open('$data_path/1234.out','r').read()
```
Python has a library function `os.path.expandvars()`.  The test suite should provide similar, so you can use:

```python
stdout[0] = open(system_tests.expandvars('$data_path/1234.out'),'r').read()
```
It might even have this.  I don't know.  If you do the following in the terminal:

```bash
1142 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance/tests $ python3
Python 3.8.2 (default, Sep 24 2020, 19:37:08) 
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import system_tests
>>> help(system_tests)
```
It reports an entry point `expand_variables` which is documented in README-TESTS.md as:

```python
class SomeName(metaclass=system_tests.CaseMeta):

	def setUp(self):
		self.commands = [self.expand_variables("$some_var/foo.txt")]
		self.stderr = [""]
		self.stdout = [self.expand_variables("$success_message")]
		self.retval = [0]
```

And I guess that's exactly what you used in #2058.

@1div0 and @hassec  Can you get involved with #1553  @postscript-dev has done a LOT of work in the last 12 months on the exiv2 man page and many other matters.  We can't expect him to take on support, maintenance and development of the test suite.

**Comment by 1div0** [comment]
@clanmills Yes, for sure I will take a 100k at #1553 and more as the time_t permits. But no ETA yet. Cheers. Best.

**Pull request merged**
