### PR TITLE
Remove duplicated source

### PR DESCRIPTION
**Pull request by piponazo**
I noticed that in `src/CMakeLists.txt` there was a duplicated source and I removed it. This was not causing any harm, but I took this opportunity to sort the files there alphabetically so we can easily see if there are any other duplicate in the future.

### CODE REVIEW

**Comment by clanmills** [comment]
@piponazo There are thousands of lines of duplicated code in src/tags.cpp and src/tags_int.cpp. 

There are file pairs foo.cpp and foo_int.cpp.  I suspect tags.cpp and tags_int.cpp are the only ones with duplicated code.
```
506 .../src $ for i in *int.cpp; do x=$(echo $i|cut -d_ -f 1) ; wc $x.cpp 2>/dev/null ; if [ $? == 0 ]; then wc $i; fi ; done
     231     670    7760 cr2image.cpp
      71     229    2135 cr2image_int.cpp
     223     717    7077 crwimage.cpp
    1213    4015   43619 crwimage_int.cpp
     241     718    8118 orfimage.cpp
      58     145    1483 orfimage_int.cpp
     275     806    9561 rw2image.cpp
      21      35     393 rw2image_int.cpp
    3283   19967  186181 tags.cpp
    2714   17823  161658 tags_int.cpp
     347    1131   12553 tiffimage.cpp
    1970    9089   94382 tiffimage_int.cpp
507 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/src $ 
```

**Comment by piponazo** [comment]
Hi @clanmills. I am not sure if I understood your message properly. How is that related with the modification I did in the CMake code? The main contribution on this PR is done in this commit:

https://github.com/Exiv2/exiv2/pull/268/commits/3ee9f093661e9f6666a536455fdf9c7a339b33da

That removes from the CMake list of sources two files that were duplicated.

**Comment by clanmills** [comment]
Oh, it's not related.  I've hi-jacked your title to say "there's duplicated C++ code".  I've got the tags.cpp/tags_int.cpp on the list for our meeting.  http://dev.exiv2.org/news/3

And, rats, I see exiv2.org is having another Denial of Service attack at the moment.  I'll go fix that now.

**Review by D4N — APPROVED** [review]
Good job!

**Pull request merged**
