### PR TITLE
Use more GNUInstallDirs

### PR DESCRIPTION
**Pull request by a17r**
Conveniently fixes multiarch install dir issues.

### CODE REVIEW

**Comment by clanmills** [comment]
Andreas.  Thanks for this contribution.  Luis (piponazo) is our CMake expert and will review your changes.

**Comment by piponazo** [comment]
Hi @a17r , thanks a lot for the contribution. 

I did not know about the **GNUInstallDirs **  module. I actually think that I might have removed something about it during the CMake refactoring it is taking place during the last weeks.

Could you please explain briefly what is your user case and why this is needed ? 

I have checked this and it works perfectly. However I left a comment about the usage of `CMAKE_SOURCE_INCLUDEDIR`. On Windows, the value of that variable is empty, and I could not find any reference to it on the web. Might it be a typo ?

**Comment by a17r** [comment]
Thanks for catching that one, fixed the bogus var.

Basically, everyone should use GNUInstallDirs with cmake - it is giving us sane defaults to work with, less re-invented wheels, and easy to override vars for different distro needs (Gentoo has libx32, lib32, lib64, other distributions may have more complicated multiarch names). With exiv2 as-is, a 32/64 bit multiarch build would simply install twice into /usr/lib/libexiv2.so, raising an error with strict checks. And instead of chasing libdir paths we now even get automatically correct /usr/lib{32,64}/pkgconfig files.

**Review by piponazo — APPROVED** [review]
The comment I made has been addressed. Now the PR only make changes related to the GNUInstallDirs

**Pull request merged**
