### PR TITLE
Fix 1508 enable bmff

### LINKED ISSUE #1508: Exiv2::enableBMFF() not in library built with -DEXIV2_ENABLE_BMFF=Off
See: https://github.com/Exiv2/exiv2/issues/1493#issuecomment-808063425

This entry point is required in the library for v0.27.4.

Fix is:
```
diff --git a/include/exiv2/exiv2.hpp b/include/exiv2/exiv2.hpp
index 5efd9d57..b4bb507b 100644
--- a/include/exiv2/exiv2.hpp
+++ b/include/exiv2/exiv2.hpp
@@ -45,9 +45,7 @@
 #include "exiv2/mrwimage.hpp"
 #include "exiv2/orfimage.hpp"
 #include "exiv2/pgfimage.hpp"
-#ifdef EXV_ENABLE_BMFF
 #include "bmffimage.hpp"
-#endif
 
 #ifdef EXV_HAVE_LIBZ
 #include "exiv2/pngimage.hpp"
764 rmills@rmillsm1:~/gnu/github/exiv2/0.27-maintenance/build $
```

The work around is to "double guard" the code as follows:

```cpp
#include <exiv2/exiv2.hpp>
....
#if EXIV2_TEST_VERSION(0,27,4)
#ifdef EXV_ENABLE_BMFF
    Exiv2::enableBMFF(true);
#endif
#endif
```

User code using "double guarding" will not require maintenance when this issue is fixed.

### PR DESCRIPTION
**Pull request by clanmills**
See #1508.

### CODE REVIEW

**Review by 1div0 — APPROVED** [review]
Yes, it this better this way.

**Comment by kmilos** [comment]
Not sure this PR is kosher: `EXIV2_ENABLE_BMFF` is a CMake option, don't we need to use the `EXV_ENABLE_BMFF` preprocessor macro instead?

**Comment by kmilos** [comment]
Also, should be `#ifdef` everywhere in `README.md`, not `#if`

**Comment by clanmills** [comment]
We should get rid of every mention of EXV in the code and documentation.  The file format .EXV must endure as it is supported by ExifTool.

Every option/pre-processor/#if should be EXIV2.  Why does cmake generate a file called exv_conf.h?  It should be named exiv2_conf.h 

@kmilos:  If you'd like to fix this mess for v0.27.4 RC2 (which I hope to ship on Tuesday), please post a PR. Or we defer this for v1.00.

**Comment by clanmills** [comment]
@kmilos I've investigated replacing EXV_ with EXIV2_.  Too brutal for v0.27.4 RC2.  I'll fix it on 'main'.  #1514.

**Comment by kmilos** [comment]
How is it different to this PR?

**Comment by kmilos** [comment]
The other way around, just fix this PR.

**Comment by clanmills** [comment]
Milos.  Can you submit the fix you have in mind.  It's easier if you show me, it's harder for me to guess!

**Comment by kmilos** [comment]
Ok, will do later this weekend.

**Comment by clanmills** [comment]
Thanks.  Happy Easter.  Watch out for the big rabbit!

**Comment by clanmills** [comment]
Fixed _(I hope)_.  PR: #1517

**Pull request merged**
