### PR TITLE
Canon cr3 previews

### LINKED ISSUE #1893: no preview for cr3 image
exiv2 0.27.5.1:

```
$ exiv2 -ep1 /path/to/my/image.cr3
/path/to/my/image.cr3: Image does not have preview 1
```

is it ok or am I missing something?

### PR DESCRIPTION
**Pull request by dhoulder**
Extract previews from Canon CR3 files.
Fixes https://github.com/Exiv2/exiv2/issues/1893

### CODE REVIEW

**Review by clanmills — COMMENTED** [review]
This looks good, @dhoulder.  It builds and passes the test suite.

Several comments:

1. I'd like somebody else to review and approve this as it will have to be approved on 0.27-maintenance after v0.27.5 ships next week.  I want out of the loop.

2.  Is using `import hashlib` part of the "standard" python3 installation?

3.  I added something to the test suite for dealing with temporary files.  See test_issue_1484.py  You might find that useful (or your might not).  I can't find the carcass of your _temporary_ extracted files.  The test suite on 'main' has a different user experience from 0.27-maintenance, so I'm not sure what it's doing.  I ran you test manually as follows:

```
$ 677 rmills@rmillsm1:~/gnu/github/exiv2/main/tests $ python3 runner.py --verbose bugfixes/github/test_issue_1893.py 
test_run (test_issue_1893.issue_1893_cr3_preview) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.033s

OK
678 rmills@rmillsm1:~/gnu/github/exiv2/main/tests $
```

4. I'm unclear if you've addressed the issue we discussed about needlessly allocating and reading the mdat box.

**Review by clanmills — COMMENTED** [review]
Well done, @dhoulder.  You've discovered that you can update the PR.  You have to set the tracked branch.  I use SmartGit to do that because I don't understand git.

**Review by kmilos — COMMENTED** [review]
Minor cosmetic changes while we're at it.

Looks good otherwise!

**Comment by kevinbackhouse** [comment]
@clanmills: It seems like the macOS `-fstack-clash-protection` issue is back. Do you think I should revert #1857?

**Comment by dhoulder** [comment]
@clanmills wrote:

> I added something to the test suite for dealing with temporary files. See test_issue_1484.py You might find that useful (or your might not)

Ah, yes that's probably a bit more succinct than my approach. Next time…

**Comment by clanmills** [comment]
@dhoulder Do nothing.  What you have works.

@kevinbackhouse Groan.  I'm surprised.  My MBP has the M1 chip and build David's code without issue.

There was another PR which used `check_linker_flag(-fcf-protection HAS_FCF_PROTECTION_LINK)`.  We should test that both check_compiler_flag() AND check_linker_flag() are successful.

When I attempted to use that for v0.27.5 RC3, it didn't deliver happiness although I didn't know why not.  What a miserable thing.  I'm on vacation at the moment.  I expect we'll revisit this next week before v0.27.5 gets safely out the door.

**Comment by dhoulder** [comment]
I see https://github.com/Exiv2/exiv2/pull/1962 is merged. Do I need to do something to rerun the checks?

**Comment by clanmills** [comment]
@dhoulder The builds on the MacBookPro/M1/Xcode13 and MacMini/Intelx64/Xcode12.1 are both good.

@kevinbackhouse I think David has to do a rebase merge or something to update the code base of this PR.  When he submits that change, the CI will run and pass.  Then we can approve and merge this branch.  How does David update the code base for this PR?



When I build v0.27.5 (probably Thursday 2021-10-21), I'll update cmake/compilerFlags.cmake from:
```
            # macOS M1 will set ARCHITECTURE == arm64
            EXECUTE_PROCESS( COMMAND uname -m COMMAND tr -d '\n' OUTPUT_VARIABLE ARCHITECTURE )
            if ( NOT ${ARCHITECTURE} STREQUAL arm64 )
                check_cxx_compiler_flag(-fstack-clash-protection HAS_FSTACK_CLASH_PROTECTION)
            endif()
```
to:
```
            if ( NOT APPLE )
                check_cxx_compiler_flag(-fstack-clash-protection HAS_FSTACK_CLASH_PROTECTION)
            endif()
```

**Review by kevinbackhouse — APPROVED** [review]

**Comment by kevinbackhouse** [comment]
I can just do a "squash and merge" if you would like this to be squashed into a single commit.

**Comment by kevinbackhouse** [comment]
I can use mergify to backport #1962 to 0.27-maintenance. Should this PR be backported too?

**Comment by kevinbackhouse** [comment]
@clanmills: ok, thanks. I created #1966 to backport the cmake changes.

@dhoulder: Do you think this should be back-ported to the 0.27-maintenance branch? If so, please could you add a comment like [this one](https://github.com/Exiv2/exiv2/pull/1962#issuecomment-945124986) to this PR? It won't get merged until after v0.27.5 has shipped though.

**Comment by dhoulder** [comment]
Hi @kevinbackhouse , @clanmills :  Thanks for your help. 

> @dhoulder: Do you think this should be back-ported to the 0.27-maintenance branch? If so, please could you add a comment like this one to this PR?

Done. I had "backport to 0.27" on my to-do list, but I'll scrub that now.

> I can just do a "squash and merge" if you would like this to be squashed into a single commit.

Yep, fine by me. Thanks.

For the record I manged to trigger the CI rerun with `git commit -m "retrigger checks" --allow-empty; git push`.

**Comment by clanmills** [comment]
@dhoulder Thank You very much for working on this David.  Very valuable contribution.  I've updated #1893 to ask @paolobenve to build and test with his CR3 files. 

@kevinbackhouse Thank You very much for taking care of the integration, Kev.

**Pull request merged**
