### PR TITLE
Replace DEBUG with EXIV2_DEBUG_MESSAGES

### LINKED ISSUE #926: Please change the behaviour of debug stdout/stderr output.
I have a kind request about the exiv2 sources. I see that debug builds use the define `DEBUG` to print more verbose output messages. These messages are directly written to `std::cout` or `std::cerr`.

This behavior is quite common and there is really nothing wrong with it. However I would slightly prefer more control over the messages, because when I use exiv2 debug builds, they tend to be quite verbose on stdout/stderr.

Would it be acceptable to change the logging behavior? I could think to either add a new define like `EXIV2_DEBUG_MESSAGES` that users can separately control independent of `DEBUG`. Or to leave the messages to be printed only when `DEBUG` is defined, but print via exiv2's existing logging mechanism from `error.hpp` so users can control the verbosity at runtime.

Does any of this sound reasonable? If you find it not worthwhile, please feel free to close this kind request.

### PR DESCRIPTION
**Pull request by piponazo**
Fixes #926

### CODE REVIEW

**Review by clanmills — COMMENTED** [review]
This is a surprise.  I've already tagged and built 0.27.2-RC2.  I would like to avoid code changes between 0.27.2-RC2 and 0.27.2.  We could integrate this tonight, and either:

1) Delete tag 0.27.2-RC2 **and** rebuild/publish/retag on Saturday.
2) Integrate this and tag as 0.27.2-RC3 build/publish/tag on Saturday.
3) Slipstream this into 0.27.2 in a couple of weeks.

What do you think about adding EXIV2_DEBUG_MESSAGES to CMakeLists.txt?

In the past, I've used CXXFLAGS=-DDEBUG to switch on those messages.  I don't want them enabled everywhere because (as the user mentioned) it generate a lot of output from parts of the code that are not being investigate.  So, I prefer to switch it on to rebuild selected files:
```
$ touch ../src/voo.cpp ; make CXXFLAGS=-DDEBUG
```
Or, define it in the code while debugging (and remove before commit).
```
// foo.cpp
#ifndef DEBUG
#define DEBUG
#endif
```

**Review by clanmills — COMMENTED** [review]
I think I'm in favour of this **AND** don't make it an option in CMakeLists.txt.  It makes it very clear that this code is for team/feature debugging.

So, I'm happy to approve this after we've discussed what to do about the tag I've already created for v0.27.2-RC2.

My feeling is that we should go to v0.27.2-RC3 which will require updating release notes.txt and the platform/ReadMe.txt files (almost painless).

**Comment by piponazo** [comment]
I just created the PR because it was something easy to do, but this can wait to be merged. Actually, if we see that this could affect to the ABI as @D4N commented, we can close this PR and just merge #939 into master. 

Keep the RC2 tag, and enjoy your well deserved holidays :wink:

**Comment by clanmills** [comment]
@piponazo Let's not submit this into v0.27.2 which is PR #940.  I'd like to release v0.27.2 today.

I'll approve this tomorrow and pull it into 0.27-maintenance.  It'll be released with v0.27.3 scheduled for 2019-09-30.

**Comment by clanmills** [comment]
@piponazo We've had a change of plan.  https://github.com/Exiv2/exiv2/pull/940#issuecomment-510424424

Can you merge this onto 0.27-maintenance by Sunday afternoon (2019-07-14)?

**Review by clanmills — DISMISSED** [review]

**Comment by piponazo** [comment]
Sure! I'll rebase, push and merge once the CI is green 😉

**Review by D4N — CHANGES_REQUESTED** [review]
Please cherry-pick the commits that went into master, as this still has the original inconsistencies in the docs.

**Comment by clanmills** [comment]
Don't spend time on README.md.  The version of that on 'master' and '0.27-maintenance' have diverged substantially.  I'll make sure that the version on 0.27-maintenance is good.  And fix 'master' when we arrive at 0.28-RC1 (maybe September 2020).

**Review by D4N — APPROVED** [review]
Thanks for backporting this!

**Pull request merged**
