### PR TITLE
Update exiv2.pot

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Use new `update-pot` target contributed by @cjwatson (#1907) to update `exiv2.pot`.

### CODE REVIEW

**Comment by postscript-dev** [comment]
I have no experience of pot files, but maybe the email address for bugs should change? I think that Andreas has no involvement in the project any longer.

*po/CMakeLists.txt*
```
--msgid-bugs-address=ahuggel@gmx.net
```
I understand that @lbschenkel is working on localisation, but there may be a better candidate.

Also, is Andreas still the copyright holder?

*po/CMakeLists.txt*
```
--copyright-holder='Andreas Huggel'
```

**Comment by clanmills** [comment]
Andreas hasn't been involved with Exiv2 since 2017.  I'm not a lawyer, however my understanding is that he does not hold copyright for the open-source version of Exiv2.  See:  https://github.com/Exiv2/exiv2/wiki/Commercial-License

The status of @lbschenkel is unknown.  Earlier this year, he volunteered to work on Exiv2 localisation using Crowdin (about which I know exactly nothing).   @paolobenve offered to work on the Portuguese and asked for Crowdin assistance.  There have been other occasional localisation contributions.  For example, Tony  contributed Catalonian, and Thomas helped with German.  It would be wonderful to have a _**i18n tsar**_ to own and manage localisation.

**Comment by lbschenkel** [comment]
I am still here but I can only take a passive/reactive role in this project: when pinged I can help out, etc. Therefore I am not sure if I qualify, or if it is even a good idea, to be the primary contact person for bugs. I cannot promise any kind of "SLA". I think I could be more suitable as the "second-level support": if the primary maintainer has questions or needs help regarding the translation domain, then I can help them out.

**Comment by kevinbackhouse** [comment]
Thanks @postscript-dev! Good catch on the copyright and bugs address. I have created https://github.com/cjwatson/exiv2/pull/1 to replace those with something more generic.

**Comment by clanmills** [comment]
@lbschenkel Good to hear you're still with us.  I understand your limited availability.  Your help is appreciated.

Can you speak to @paolobenve please?  He offered to get involved with localisation and asked me about a Crowdin Template _(or something like that)_.   Maybe you can get him up-and-running.  Thanks.

**Comment by lbschenkel** [comment]
@paolobenve: feel free to reach me via the e-mail address you can see in this commit: https://github.com/Exiv2/exiv2/commit/c4d18d02e718ee1573e98338756d2b35e7b31f1d.patch

**Comment by kevinbackhouse** [comment]
We updated the copyright and contact details in #1907.

**Review by postscript-dev — CHANGES_REQUESTED** [review]
Maybe the Copyright information could be the same as the `.h`/`.cpp` files, e.g.,
```
 * Copyright (C) 2004-2021 Exiv2 authors
 * This program is part of the Exiv2 distribution.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, 5th Floor, Boston, MA 02110-1301 USA.

```

Also, do we need to update/include the individual language `.po` files with the new copyright and email address?

**Comment by kevinbackhouse** [comment]
@postscript-dev: I couldn't find a way to update the copyright statement by changing the arguments to `xgettext`, so I just edited them manually.

I don't know about the `.po` files. It looks like they all say "This file is distributed under the same license as the exiv2 package", plus the name of the person who did the translation, so that seems ok to me.

**Comment by neheb** [comment]
needs rebasing.

**Comment by bellaperez** [comment]
> ```
> "Report-Msgid-Bugs-To: https://github.com/Exiv2/exiv2/issues\n"
> ```

I suggest this command (tested):

posieve set-header -sfield:"Report-Msgid-Bugs-To:https://github.com/Exiv2/exiv2/issues" po/

**Comment by postscript-dev** [comment]
@bellaperez 
Thanks for your suggestion. As a native English speaker, I haven't needed to investigate `.po` files.

I don't have time to look at this at the moment but will return to the PR in the new year.

**Comment by kmilos** [comment]
Superseded by https://github.com/Exiv2/exiv2/pull/2945?

**Pull request closed without merging**
