### PR TITLE
Release Exiv2 version 0.28.1

### LINKED ISSUE #2813: Let's release version 0.28.1
There are have been a few updates on the [0.28.x](https://github.com/Exiv2/exiv2/commits/0.28.x) branch since we released [v0.28.0](https://github.com/Exiv2/exiv2/releases/tag/v0.28.0). I'd like to release version v0.28.1. Any objections to me going ahead with that? I'll update the 3 same files as #2602 did, and create a new tag.

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Update version numbers for the new release.

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
Note: I will publish and merge https://github.com/Exiv2/exiv2/security/advisories/GHSA-hrw9-ggg3-3r4r immediately before I merge this PR.

**Comment by kevinbackhouse** [comment]
@neheb: the failing FreeBSD check is probably safe to ignore, right?

**Comment by neheb** [comment]
it timed out so yes.

**Comment by 1div0** [comment]
OK

C001!

**Comment by 1div0** [comment]
W0w, 6 hours timeout on my :heart: FreeBSD.?!

That is really weird. Otherwise OK.

Go, release that!

Thank you so much.

**Review by 1div0 — APPROVED** [review]
As an important security release, it should be included in F39 tomorrow.

Will C/C++/Objective-C

:sunglasses:

**Pull request merged**
