### PR TITLE
Fix nls_test(): Check only part of the output

### PR DESCRIPTION
**Pull request by LeoHsiao1**
I used `exiv2 2>&1 | head -n 1` instead of `head -c 20` .

### CODE REVIEW

**Comment by clanmills** [comment]
@LeoHsiao1 Can you update this to ensure test/nls_test.sh has the +x (execute) bit set.  `$ chmod +x test/nls-test.sh`

**Comment by LeoHsiao1** [comment]
Eh, do you mean to change file permissions in tests? Or in the CI process?

**Comment by clanmills** [comment]
It's OK.  I've done it - that's the benefit of working on exiv2/exiv2.  I can modify the PR.  Looks good.  I'm going to approve and merge.

**Review by clanmills — APPROVED** [review]
Thanks for working on this, @LeoHsiao1.

**Comment by LeoHsiao1** [comment]
Ok, it's really convenient. I will now delete this temporary branch to avoid complicating the EXIV2 repository.

**Comment by LeoHsiao1** [comment]
Well, it doesn't exist anymore .Does Github automatically delete temporary branches after a merge?

**Comment by LeoHsiao1** [comment]
I'm guessing you've turned it on:
image

**Comment by clanmills** [comment]
Yes.  When you merge a PR, the robot deletes the branch.  That happened to #1360 (base64 code) earlier this week.  I didn't know I had merged #1360.  I must have pressed the wrong button.  I've discussed #1360 with Luis and he's going to finish it soon, so you don't need to do anything about that.

Are you happy working on Exiv2?

I'd like you to write a unit_test for ini file support.  I'll open an issue about that once we're finished with tests/bash_tests and #1215 is closed.

**Pull request merged**
