### PR TITLE
Add unit tests for XMP types

### PR DESCRIPTION
**Pull request by smr99**
The typedefs XMP_Int8, etc, are clearly intended to provide integers of specific bit-widths.  For exmaple, XMPMeta::Initialize() contains these lines:

	XMP_Assert ( sizeof(XMP_Int8) == 1 );
	XMP_Assert ( sizeof(XMP_Int16) == 2 );
	XMP_Assert ( sizeof(XMP_Int32) == 4 );
	XMP_Assert ( sizeof(XMP_Int64) == 8 );
	XMP_Assert ( sizeof(XMP_Uns8) == 1 );
	XMP_Assert ( sizeof(XMP_Uns16) == 2 );
	XMP_Assert ( sizeof(XMP_Uns32) == 4 );
	XMP_Assert ( sizeof(XMP_Uns64) == 8 );
	
This pull request codifies the above in a simple unit test.  It fails on my 64-bit linux machine.

### CODE REVIEW

**Comment by smr99** [comment]
The Travis builds prove my point: the apple build succeeds because it uses <stdint.h>.  The linux build fails because long is 64 bits (LP64 data model) while windows build succeeds because it uses LLP64 model.   See https://en.wikipedia.org/wiki/64-bit_computing

Note that my other pull request isn't enough because the EXV_HAVE_STDINT_H define isn't used during the test build :-(

**Comment by D4N** [comment]
Although I am usually against testing external dependencies, in this case this is clearly a helpful addition. Thanks for the PR!

I have three requests:
1. Please clean up the git history so that there is only one commit
2. Give the new file a better name, `test_xmp.cpp` is too generic for this case. I would suggest something along the lines of `test_xmp_types.cpp`
3. Please add a `TODO` in a comment into the file to convert the assertions to static assertions once we have C++11

**Comment by piponazo** [comment]
Hi @smr99 , thanks for the contribution. I agree with all the comments made by @D4N and in top of them, I would say that it makes more sense to have the test and the fix in the same Pull Request. Otherwise, we cannot merge this PR since it will turn the CI checks into red, neither we could not merge the other one without knowing if it fixes the problem.

I will take a deeper look to the issue tomorrow, and we can discuss about what to do with the `EXV_HAVE_STDINT_H` definition.

**Comment by clanmills** [comment]
Guys: I'm really impressed by this.  Thank You @smr99 for reporting this.   Thank you @D4N and @piponazo for your comments.

I've known about those 32-bit asserts in the Adobe code, however they've never been triggered.  The XMPsdk code in Exiv2 is elderly and that's why there's a work-in-progress project to (optionally) build with Adobe's 2013/2014/2016 Editions of XMPsdk.  I'd like to link and not embed XMPsdk in Exiv2.

Very good work everybody.  Thank You.

**Comment by smr99** [comment]
Thanks all for the suggestions.   I will implement them.  However,  due to travel, I won't get to it for a week or so.

**Comment by clanmills** [comment]
I'm wondering if we should go down this road.  Exactly how do we reproduce this?  I've installed both gcc-7/g++-7 and gcc-8/g++-8  on Kubuntu 16.04 and Exiv2 builds and passes the test suite.

I believe the exiv2/xmpsdk/ code was released by Adobe more than 10 years ago and intended to be compiled for 32 bits.  I added msvc/xmpsdk projects to build that code with MSVC 2005 (32 bit) when I joined the project in 2008.

I'm not sure why the autotools build (and CMake build) compile and embed that code in Exiv2.   I've tried to avoid changes and it has been building smoothly for years.  It seems strange that we polute/influence the code with EXV_HAVE_STDINT as the strategy has been to build it "out of the box" (more or less as released by Adobe).   

I hope we're not forcing it to compile as 64 bit for we don't know the implications.  I'll check the release notes for Adobe's 2013/14/16 editions and I expect one or more of those will be certified for 64 bit use.  Externally linking Adobe's library with Exiv2 seems the way forward.

**Comment by smr99** [comment]
@clanmills, you ask how to reproduce; a good question.  When I first started with the exiv2 code in early April, I got failures immediately -- with "make tests" in a Debug build.  Now, however, I do not.  The reason is that commit 71ecc44a5e886676bca8182f3f797e0af8a029c1 removed -DDEBUG from the debug builds.  That change disabled the asserts.  So one way to reproduce is revert that commit.  

If -DDEBUG is not desired, another option is to use -DXMP_DebugBuild=1.

**Comment by smr99** [comment]
I think you misunderstand.   The DEBUG define is not for my proposed test,  but rather to enable the assertions in xmp.  I think it would be helpful to have a travis build with those assertions enabled.

I don't know if the xmp works fine or not.  BUT I do know that it is failing its assertions.

I also think it is incorrect to say that #272 fixed the configuration.

**Comment by piponazo** [comment]
@smr99 you are right, your change would help to enable those assertions in XMP. In #272 I focused into fixing the configuration in the Exiv2 code, and I did not consider at that point that it could be affecting to the XMP one. However, in #272 the maintainers of Exiv2 decided to removed the usage of that definition because of other reasons (full history between #272 and #273).

What I would like you to understand is that XMP is not part of Exiv2, it is a dependency of our library. By historical reasons, somebody placed that code in the repository and it persisted until today there. Now we compile it to be used in Exiv2 when the XMP support is enabled. 

We have plans to use **conan** to handle the XMP dependency, so that users can chose which version of XMP they want to use (new ones or the current one at the repository). I am currently working on that.

As @clanmills pointed out, the code has been working for 10 years and nobody complained about this before. It this issue does not affect you directly maybe the best we can do here is to leave the things as they are. But I do not want to have the final word about this issue. If you think that this could have some real benefit in the code and @clanmills or @D4N agree with you, we can proceed with the PR.

By the way, I think you did not rebase correctly the changes in top of master, and now your branch contains some of my commits.

**Comment by smr99** [comment]
@piponazo: I do fully realize XMP is not part of Exiv2 and I do understand the reluctance to do any maintenance work on a 3rd party library that just happens to be in the same source tree.  I support the effort to link against an external build of XMP, though I'm not at all familiar with conan.  I'm coming from the Debian Linux perspective where we have pre-built binary packages of such libraries -- though not for Adobe XMP, sadly.

I haven't looked at the code yet to see whether the assertion failures are important or not.  It may be true that Adobe added assertions that don't matter.  For example, they have XMP_Assert ( sizeof(XMP_Int32) == 4 ), but maybe it is perfectly fine if XMP_Int32 is 8 bytes (as it is on LP64 systems).  On the other hand, maybe it is important that XMP_Int32 is 4 bytes.  I have looked at the latest (CC201607) XMP sources from Adobe and it looks like they have fixed this mistake.

Regarding the "working for 10 years" comments: sure, I get it.  I have not looked, so I have no idea whether XMP support is covered by testing or used in the wild.  It seems conceivable to me that having an 8-byte wide XMP_Int32 makes no difference.  Equally, it is conceivable to me that no-one has exercised that code on linux -- or did not recognize the root cause if they had seen a bug.

In any case: I think this PR can be closed.  I don't think the proposed tests have any value.  What I do think would have value is a Travis build with all assertions enabled.

**Comment by smr99** [comment]
@piponazo  Final thought: the XMP assertions can be enabled using -DXMP_DebugBuild=1, without defining DEBUG.

**Comment by D4N** [comment]
@smr99 Since you closed this, could you open an issue just briefly describing the `XMP_Int32` size problem? That way we won't forget this issue and you'll get the attribution for discovering this.

**Pull request closed without merging**
