### PR TITLE
member init changes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by clanmills** [comment]
I maintain the Exiv2 0.27-maintenance branch.  So, I'm not going to review your efforts yesterday and today.  However I would like to say "Thank You" for what you are doing and both the speed and scope of your efforts.  

I agreed with @piponazo and @D4N in May 2018 that they would take Exiv2 into the future and "modernise" the code into C++11.  When 0.27 shipped in December 2018, we established the 0.27-maintenance branch to which I back-port security fixes and create "dots" releases as necessary.  Exiv2 v0.27.3 shipped on 2020-06-30 and has numerous fixes which should be ported to 'master'.

I hope you're using the test suite to be confident that you're not causing functional damage to the code.  If you need assistance with the test suite or documentation, please ask and I will be happy to help you.

Thank You for your work and contributions.

**Comment by neheb** [comment]
Fixed for GCC4 and 5.

**Comment by piponazo** [comment]
Thanks again for your contributions.

Could you please rebase your branch in top of master? There are some conflicting files at the moment.

**Comment by neheb** [comment]
@piponazo done

@clanmills Interesting that C++11 is considered modern. The only supported OS that only supports C++11 and nothing newer is probably CentOS 7. Then again CentOS gets updates for 10 years.

**Comment by clanmills** [comment]
@neheb The guys wanted to move to C++17 and were asked by KDE to hold back to C++11.  So "modernisation" represents a relative state and doesn't mean "the latest version of C++".  KDE incorporate Exiv2 into the desktop as well as many applications such as digiKam.

With Exiv2 v0.27.3, the code is documented and tested to build with C++11 and C++14 using the cmake options `cmake .. -DCMAKE_CXX_STANDARD=11 -DCMAKE_CXX_FLAGS=-Wno-deprecated`.  The primary impediment to "modernisation" is the replacement of auto-ptr with unique-pair and @piponazo successfully undertook that work on 'master'.  There is no plan (and no compelling reason) to port that to 0.27-maintenance.

I read yesterday, that the C++20 ratification/voting process is now complete.  So the C++20 standard will be "law" by the end of this year.

At this moment, we don't have a schedule 'master' to be released as Exiv2 v0.28 (or possibly v1.0).  If Exiv2 v0.27.4 is required in 2021, I will to undertake that project.  I would prefer to see numerous changes in 0.27-maintenance integrated 'master' to for v0.28 to be released.  There are no known current security issues with 0.27-maintenance.

I will be 70 on 2021-01-18 and want to retire.  I'm writing a book **Image Metadata _and_ Exiv2 Architecture** to document everything I know about this technology and code.  I hope to finish the book in 2020.  Current draft (changes daily) https://clanmills.com/exiv2/book/

**Comment by piponazo** [comment]
@neheb you can find the historic of messages about the C++11 vs C++17 discussion we had approximately 2 years ago here #214. 

Maybe things have evolved enough in these 2 years to consider other options ... but that's the historic reason to stay with C++11 at the moment.

**Comment by neheb** [comment]
@piponazo I would say going to C++14 makes sense at this point. C++17 is interesting but it's really only supported well by GCC8 and above.

Cleaning up the code from its C++98 roots makes more sense right now I think.

**Comment by neheb** [comment]
Redone commits with git clang-format.

**Comment by piponazo** [comment]
@neheb I agree with you. Maybe we could try to force the usage of c++14 and check if all the supported distributions can handle it  ... but first we would need to fix all the issues we are having right now in the CI on master.

Sadly, I did not have too much time to collaborate in the project during the last year. Lately, I am trying to resume my participation on it, at least to review PRs ... I hope to find some more time in the next weeks to at least put the CI again in a good stay and keep collaborating with other small refactorings 😉

**Review by piponazo — APPROVED** [review]

**Comment by clanmills** [comment]
@neheb and @piponazo I would like to "clean up" the CI.  Lots of false negatives cause us to miss the true negatives.

Significant issues:

1 msvc builds that fail to download/build curl
I'd like to stop building web-ready on the Visual Studio CI.  "web-ready" is a marginal feature.  The "every day" build of Exiv2 should be Exiv2 with XMP/Expat/Zlib.

2 CodeCov
Occasionally, code-cov is really clever and useful.  Mostly, he's incomprehensible.

3 MinGW/msys2 and Cygwin64
We don't build those on the CI.

4 We build too many platforms
It's useful to build lots of platforms.  The supported platforms are msvc (2019/17/15), macOS, Ubuntu, MinGW/msys2, Cygwin64, FreeBSD, NetBSD and Solaris 11.4.  I built/test them on my mac-Mini.

However, the CI is building about 50 platforms and this results in lots of errors for which we don't have the band-width to investigate and fix.   In the last 2 weeks, I've made no progress with my book and have been working on python/test code.

I hope to give the CI attention shortly.  Stay Calm.  Everything's going to be fine.

**Comment by piponazo** [comment]
@clanmills FYI: I just created a branch `master_FixCI` where I am trying to fix some of the issues. I will keep you updated about this

**Pull request merged**
