### PR TITLE
Fix 992 Sigma APO MACRO 180mm F3.5 EX DG (Nikon Mount)

### PR DESCRIPTION
**Pull request by clanmills**
This is #992

### CODE REVIEW

**Comment by D4N** [comment]
@clanmills is this a backport of #992 to the 0.27 maintenance branch?

**Comment by clanmills** [comment]
Yes.

**Comment by D4N** [comment]
should be fixed now

**Review by D4N — DISMISSED** [review]

**Review by D4N — APPROVED** [review]

**Review by piponazo — APPROVED** [review]
LGTM. I have re-triggered the travis jobs which failed due to travis issues.

**Pull request merged**
