### PR TITLE
Master fileio cosmetics

### PR DESCRIPTION
**Pull request by piponazo**
As is was suggested in #882, I am splitting that PR in 2 parts:

1. Cosmetic changes
2. Actual work to Reduce system calls in FileIo::eof().

I saw that the 2nd point want to be considered for 0.27.3-RC1: #1154 . I will create 2 PRs one for 0.27 and other for master.

### CODE REVIEW

**Comment by clanmills** [comment]
Thanks for working on this @piponazo.  I see the changes died in the CI.  I'll review this carefully tomorrow when the CI has passed.  I'm very pleased to see you working on this as it's on my TODO list for v0.27.3.

**Comment by piponazo** [comment]
@clanmills problem fixed. I had to update one of the python tests making use of largeiptc-test.

**Comment by clanmills** [comment]
Ah, yes.  That's good.  My first job tomorrow is to review that code.  Last Friday, v0.27.3 was 91% complete and it's now 90% complete.  I discover new things about the same rate as I can fix them!  Schedule isn't in doubt.  RC1 will ship on 2020-04-30.

**Review by clanmills — COMMENTED** [review]
I've made comments about the style here: #1178

I'm not convinced that this has changed the `stat()` call count.  Is there's magic in #1178 that's not in #1178 (basicio.cpp) where you removed the call to size(). `return std::feof(p_->fp_) != 0;`

When I go looking for that (on a clean copy of the code), basicio.cpp is now only 75 lines of code.  I'm puzzled!  I think that code has moved to src/FileIo.cpp and you haven't removed the call to `tell()`

We've been avoiding mixed UpperLower filenames in the code.  Perhaps `src/FileIo.cpp` -> `src/fileio.cpp`

```
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/master/build$ mkdir -p ~/temp
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/master/build$ $ curl http://clanmills.com/Stonehenge.png > ~/temp/Stonehenge.png
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/master/build$ git status
On branch master_fileio_cosmetics
Your branch is up to date with 'origin/master_fileio_cosmetics'.

nothing to commit, working tree clean
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/master/build$ strace -e stat bin/exiv2 ~/temp/Stonehenge.png 2>&1|grep stat|wc -l
3908
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/master/build$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/master/build$ make 2>&1 >/dev/null
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/master/build$ strace -e stat bin/exiv2 ~/temp/Stonehenge.png 2>&1|grep stat|wc -l
3908
rmills@rmillsmbp-ubuntu:~/gnu/github/exiv2/master/build$ 
```

A comment about the compiler output.  On '0.27-maintenance', the command `$ make 2>&1 >/dev/null` generates output.  There's something appearing from CMake and deprecation warnings.  Do you have any comment to make about that?

**Comment by piponazo** [comment]
@clanmills This PR was only about including the cosmetic changes from #882. I will create another PR to include the actual change to reduce the system calls to master (as I did in #1178 for 0.27). 

I also noticed that there are some warnings in the 0.27-maintenance branch. I will try to invest some time on it to clean them.

**Comment by clanmills** [comment]
Ah, right.  You'll change FileIo.cpp in another PR.  That's fine.

Don't worry about the messages from the 0.27-maintenance build.  I was surprised that the behaviour is different on 'master'.  I'll approve this.

**Review by clanmills — APPROVED** [review]

**Pull request merged**
