### PR TITLE
Remove AF designator from Tamron 70-200 G1

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This removes the AF from the name of the lens thus matching the name that lensfun and exiftool determine.

I am a bit unsure about this since exiv2 uses `AF` in all Tamron lenses, whereas I strongly suspect lensfun and exiftool use it in none, but I am happy to hear your thoughts.

The reason I'm opening this is because I am trying to get the lens identification data in darktable (https://github.com/darktable-org/darktable/issues/2886) to match the identifier from lensfun (https://github.com/lensfun/lensfun/issues/957).

### CODE REVIEW

**Comment by clanmills** [comment]
I'm not sure this is a good idea.  The data in those tables was "brought in" from somewhere and we try to avoid touching them.  You're only changing one record which is surrounded by others which are similar.  Should we be modifying them all?

Have you discussed this with lensfun?  Perhaps they could support more than one name for the same lens and support our name and others.

It's possible to change the lens name by including it in the file ~/.exiv2 which always precedes the built-in lens search.  This documented in the Exiv2 man page and here:  https://dev.exiv2.org/projects/exiv2/wiki/Lens_Recognition_in_Exiv2_v026_(and_later)/ 

However, I want to make all the great people at _**darktable**_ happy, so I'm not saying "No".  I'm saying "maybe" if lensfun cannot accommodate us.

**Comment by Leonidas-from-XIV** [comment]
@clanmills I share your concern, absolutely. I agree that this change is probably not the one that makes sense for Exiv2 since it would require to probably change a lot of lens names to match the `exiftool` names (and then, what is the canonical name of a lens anyway).

The underlying issue as far as I understand seems to be that Lensfun uses the `exiftool` names of lenses while darktable uses lensfun correction data while querying for the `Exiv2` names of the lenses which mostly match, but not always, as in the case of this lens and probably all other Tamron AF lenses.

At least  that's what I assume since querying `exiftool my-70-200.nef` I get `Tamron SP 70-200mm f/2.8 Di VC USD (A009)` which is pretty close to the `Tamron SP 70-200mm f/2.8 Di VC USD A009` that is in the lensfun database, whereas if I ask for the equivalent in exiv2 I get `Tamron SP AF 70-200mm F/2.8 Di VC USD` which matches what darktable seems to come up with.

I have filed issues in all these three projects (linked in the description above) hoping to get the developers of the respective systems to chip in and write what they consider the way to go ahead.

**Comment by clanmills** [comment]
Thanks for the update.  Let's hear from lensfun before deciding what to do. 

_**darktable**_ could have a dictionary (`std::map<std::string,std::string>`) to convert Exiv2 lens names to "exiftool/lensfun". 

However, I suspect that lensfun could recognise a lens by more than one name.  This helps all their users who use Exiv2 via dt, digicam and other applications.

**Comment by clanmills** [comment]
Thanks.  I'm going to accept this PR and put something into our test suite to ensure this doesn't regress.  I've extracted the metadata from the 26mb tmp-spider.nef into a 11kb .exv file. 

```
$ dir ~/Downloads/tmp*
-rw-r--r--  1 rmills  staff    11K 26 Aug 19:03 /Users/rmills/Downloads/tmp-spider.exv
-rw-r--r--@ 1 rmills  staff    26M 26 Aug 18:58 /Users/rmills/Downloads/tmp-spider.nef
$ 
``` 

I don't know what lensfun does.  I get quite frequent reports about issues with exiv2/lens -> lensfun.  Lens recognition is painful.  The Exif standard doesn't  deal with lens and various tricks are used within Exiv2 to "guess" the lens by looking at other metadata.

There's also the issue that we have recognised the lens and don't give the name that is expected in lensfun.  Is it possible for lensfun to have multiple names for the same lens?

**Review by clanmills — CHANGES_REQUESTED** [review]
I've submitted PR #991 to deal with this and update the test suite.  I believe this issue with be automatically closed by GitHub when #991 is merged.

I've checked "Request changes" to prevent this PR from moving forward.

**Comment by D4N** [comment]
@clanmills I've cherry picked your fix commit from #991 into this PR, if you give the ok then I'll merge this.

**Review by clanmills — COMMENTED** [review]
I think we're jumping on each other here, Dan.  A user submitted #990.  I submitted the same code as #991 into 0.27-maintenance.

**Review by clanmills — APPROVED** [review]

**Pull request merged**
