### PR TITLE
Tidy/exiv2 app

### PR DESCRIPTION
**Pull request by piponazo**
While I was reading the exiv2 code I realised that we could cleanup few things here and there. This is a pure refactoring, with no changes in behaviour.

### CODE REVIEW

**Comment by D4N** [comment]
I hope my changes make GitLab happy (they work locally). @piponazo Please rebase the fixup commit onto 0a77dae and then I'll approve this as the changes look good to me!

**Comment by piponazo** [comment]
> I hope my changes make GitLab happy (they work locally). @piponazo Please rebase the fixup commit onto 0a77dae and then I'll approve this as the changes look good to me!

Thanks Dan! I did not notice it was failing in gitlab. And I also learned thanks to you about that `fixup` option for rebasing ... I have been squashing and removing the 2nd commit message for years!! 😄

**Review by D4N — APPROVED** [review]
LGTM!

**Comment by clanmills** [comment]
Good job, gentlemen.  In future use the term "remove relics" to "removing useless junk"!

**Pull request merged**
