### PR TITLE
Fix out-of-bounds read in bmffimage.cpp

### LINKED ISSUE #1570: Security Issue in bmffimage.cpp
https://github.com/Exiv2/exiv2/security/advisories/GHSA-6pvh-9j9h-5jcm#advisory

@yuawn.  I'll deal with this on Monday.  I will also inspect the code for other similar weaknesses.  When I wrote the code, I didn't give enough thought to reading outside the buffer.  You're welcome to report more issues after I've submitted the PR with my corrections.

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes #1570

I fixed the main bug that was reported, and also a bunch of other places where the bounds weren't being checked. I think it would also be a good idea to use something like [`readOrThrow`](https://github.com/Exiv2/exiv2/blob/f9cf51ca49e49d2005e034c57b427a77d61c90a9/src/webpimage.cpp#L65), rather than `io_->read()`, but I didn't change that in this pull request.

### CODE REVIEW

**Review by hassec — APPROVED** [review]
LGTM :+1: 

1 optional comment from my side would be to just switch to `static_cast` in the lines you are touching anyways. You already use it in some places, but then leave the C-style cast in other places.

**Comment by kevinbackhouse** [comment]
> 1 optional comment from my side would be to just switch to `static_cast` in the lines you are touching anyways. You already use it in some places, but then leave the C-style cast in other places.

@hassec: do you mean this one? `(const char*)data.pData_`
I hit [this problem](https://stackoverflow.com/questions/10151834/why-cant-i-static-cast-between-char-and-unsigned-char), so I decided to just leave it as a C-style cast. I could change it to a `reinterpret_cast` if you like, but `static_cast` isn't possible.

**Comment by kevinbackhouse** [comment]
@Mergifyio backport main

**Comment by hassec** [comment]
@Mergifyio backport 0.27-maintenance

**Pull request merged**
