### PR TITLE
Use more GNUInstallDirs

### PR DESCRIPTION
**Pull request by dirkmueller**
Conveniently fixes multiarch install dir issues.

(cherry picked from commit aa6374b202bc5b2fbf67c3dded844d994d27246d)

### CODE REVIEW

**Comment by D4N** [comment]
I'll cherry-pick the relevant commits for the CI, so that we'll get a clean build.

Just a side question, do you happen to be the exiv2 maintainer for SUSE?

**Comment by dirkmueller** [comment]
@D4N thanks! yes, I am. how can I help?

**Review by piponazo — APPROVED** [review]
Thanks @dirkmueller for this. The changes look good, but I would like to have also the @clanmills opinion about what we should bring to 0.26. I do not know if the best option is to bring these changes directly to 0.26 or to release a 0.26.1 version with these fixes.

**Comment by D4N** [comment]
@dirkmueller Just asking out of curiosity. And I'd also like to compile
a list of all the package maintainers for the various Linux flavors that
exist, so that we can notify them quickly if a important patches are
available.

I agree with @piponazo that we should get @clanmills opinion before
merging. We should discuss what will be backported to older releases
(only security fixes or general bugfixes or general patches?). There are
many possibilities.

**Comment by a17r** [comment]
thanks @dirkmueller, I'm already using your backport.

**Comment by piponazo** [comment]
Let's merge this into 0.26. @dirkmueller Can you rebase your branch in top of the latest version of 0.26?

**Comment by dirkmueller** [comment]
@piponazo done

**Comment by piponazo** [comment]
Great thanks! I will merge once the travis check passes :)

**Comment by dirkmueller** [comment]
@piponazo hmm, okay, I thought you wanted to cherry pick the changes to fix the Travis.. I added them now here, it passes.

**Pull request merged**
