### PR TITLE
Added several missing Sigma lenses for Canon

### PR DESCRIPTION
**Pull request by czgnp**
Added Sigma lenses with code 368: 50/1.4, 35/1.4 40/1.4, 28/1.4, 14-24/2.8 and 60-600/4.5-6.3.
Configured code 368 to be resolved using focal length and max aperture.
    
Updated the canonEv algorithm since it didn't handle Sigma f/6.3 aperture (the lens reports f/6.2 to camera)
    
Verified all lenses added to 368: My own 35 and 50mm + downloaded Canon cr2 images from dpreview for the other lenses and they all resolve correctly.

### CODE REVIEW

**Comment by clanmills** [comment]
Thank You very much for this PR.  I assume this resolves the issue that you raised in #1446.  Thank You very much for working on this.  I've been contributing to Exiv2 for 12 years and you are one of a handful or engineers who have modified the C++ lens code. 

Can I ask you to submit this PR to 0.27-maintenance and you will be credited for your good work.  Exiv2 v0.27.4 will ship on 2021-05-22:  https://github.com/Exiv2/exiv2/issues/1018#issuecomment-757979745  There is no schedule for the release of 'master' as 0.28

When making changes to the lens code, it's important to update the test suite to ensure future changes will no "forget" your lenses.  There is a wiki page about this and includes an example of a python lens test.  https://github.com/Exiv2/exiv2/wiki/Adding-a-new-lens

**Comment by czgnp** [comment]
Hi, thanks for encouragement. But I messed up the github PR and created yet another one. Can you delete both this one and the 1455 and I will add both the canonmn_int file and testcases again on the 0.27 maintenance branch.
Sorry for the mess, but I can't tame github to clean up after me.

**Comment by hassec** [comment]
@clanmills quick question, If I understand the PR #1429 correctly, would it not be enough of a test to simply add the new lenses to `tests/bugfixes/github/test_canon_lenses.py` which would avoid having to upload new testfiles.

**Comment by clanmills** [comment]
Thank You for your contribution. Please don't call your work a "mess".  Together we'll make everything good.

**Comment by czgnp** [comment]
new to github I finally found the close PR and will reopen a new PR on the 0.27-maitenance branch.

**Pull request closed without merging**
