### PR TITLE
Include a few more BMFF major brands

### PR DESCRIPTION
**Pull request by kmilos**
Partially addresses #1489

### CODE REVIEW

**Review by 1div0 — COMMENTED** [review]
Hvala @kmilos 

I will double check with actual libavif and libheif code and then approve.

**Comment by clanmills** [comment]
Here's what I see:

**With this change:**
```bash
571 rmills@rmillsmm-local:~/gnu/github/exiv2/kmilos/build $ exiv2 ../test/data/*.HIF ../test/data/*.avif ../test/data/*.heic ../test/data/*.CR3 2>/dev/null | grep MIME
../test/data/Canon.HIF MIME type       : image/heic               CHANGED
../test/data/Sony.HIF MIME type       : image/heic                CHANGED
../test/data/avif.avif MIME type       : image/avif
../test/data/avif_exif_xmp.avif MIME type       : image/avif
../test/data/avif_metadata2.avif MIME type       : image/avif
../test/data/2021-02-13-1929.heic MIME type       : image/heic    CHANGED
../test/data/IMG_3578.heic MIME type       : image/heic           CHANGED
../test/data/Stonehenge.heic MIME type       : image/heic         CHANGED
../test/data/heic.heic MIME type       : image/generic
../test/data/1C4A5993.CR3 MIME type       : image/x-canon-cr3
../test/data/1C4A5994.CR3 MIME type       : image/x-canon-cr3
../test/data/1C4A5995.CR3 MIME type       : image/x-canon-cr3
../test/data/1C4A5996.CR3 MIME type       : image/x-canon-cr3
572 rmills@rmillsmm-local:~/gnu/github/exiv2/kmilos/build $ 
```

**Current head:**
```bash
575 rmills@rmillsmm-local:~/gnu/github/exiv2/kmilos/build $ exiv2 ../test/data/*.HIF ../test/data/*.avif ../test/data/*.heic ../test/data/*.CR3 2>/dev/null | grep MIME
../test/data/Canon.HIF MIME type       : image/generic
../test/data/Sony.HIF MIME type       : image/generic
../test/data/avif.avif MIME type       : image/avif
../test/data/avif_exif_xmp.avif MIME type       : image/avif
../test/data/avif_metadata2.avif MIME type       : image/avif
../test/data/2021-02-13-1929.heic MIME type       : image/heif
../test/data/IMG_3578.heic MIME type       : image/heif
../test/data/Stonehenge.heic MIME type       : image/heif
../test/data/heic.heic MIME type       : image/generic
../test/data/1C4A5993.CR3 MIME type       : image/x-canon-cr3
../test/data/1C4A5994.CR3 MIME type       : image/x-canon-cr3
../test/data/1C4A5995.CR3 MIME type       : image/x-canon-cr3
../test/data/1C4A5996.CR3 MIME type       : image/x-canon-cr3
576 rmills@rmillsmm-local:~/gnu/github/exiv2/kmilos/build $ 
```

**Review by clanmills — APPROVED** [review]
I'm going to approve this now.  @kmilos:  If/when @1div0 is also happy, please merge.

**Comment by 1div0** [comment]
So 'avis' file type brand intended for image sequences should map to type "image/avif-sequence".

/usr/share/mime/image/avif-sequence.xml
```
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="image/avif-sequence">
  <!--Created automatically by update-mime-database. DO NOT EDIT!-->
  <comment>AVIF image sequence</comment>
  <glob pattern="*.avifs"/>
</mime-type>
```

**Comment by 1div0** [comment]
Although the AVIF image sequences are still rare, we could add one to the test suite anyway.

**Comment by kmilos** [comment]
> So 'avis' file type brand intended for image sequences should map to type "image/avif-sequence".

That's a bit weird since there is no "image/avif-sequence" [registered w/ IANA](https://www.iana.org/assignments/media-types/media-types.xhtml#image), only "image/avif". From the AVIF spec linked above:

> If any of the brands defined in this document is specified in the major_brand field of the FileTypeBox, the file extension and Internet Media Type should respectively be ".avif" and "image/avif" as defined in § 8 AVIF Media Type Registration.

I've also juts added the check for `mif1` brand, as mentioned in the "image/heif" registration:

> The MIME subtype name may be 'heif' only if the file conforms to 
> the requirements of the 'mif1' brand, and contains that brand as a 
> compatible brand.

**Comment by kmilos** [comment]
See also https://github.com/AOMediaCodec/av1-avif/pull/86

**Comment by 1div0** [comment]
Weird indeed. I will dig deeper. Got that file about half year ago. It seems to be lost in the translation somehow.

**Comment by 1div0** [comment]
OK now, I was not aware of the type removal. Thank you so much. Will approve immediately.

**Review by clanmills — APPROVED** [review]
Good work, everybody.  @kmilos Please merge to show your happiness.

Final state, test/data/heic.heic now reports `image/heif`

**Comment by 1div0** [comment]
Dobro. Hvala.

**Comment by 1div0** [comment]
Wrong button. Too distracted. Sorry.

**Review by 1div0 — APPROVED** [review]
Dobro.

**Comment by kmilos** [comment]
Thanks Robin and dakujem Peter.

**Pull request merged**
