### PR TITLE
Testsuite fails with non-zero exit code if a test does not pass

### PR DESCRIPTION
**Pull request by D4N**
Unfortunately it stops once the first test fails, but this will be fixed by #155 anyway.

### CODE REVIEW

**Review by tbeu — COMMENTED** [review]
Why not simply return `$rc`?

**Comment by piponazo** [comment]
Good point @tbeu . I would also return `$rc`. In some situations the return value could tell us something about the failure reason.

**Comment by piponazo** [comment]
And thanks @D4N for taking care of this. Good catch ;)

**Comment by D4N** [comment]
Done

**Comment by tbeu** [comment]
`rc` or `$rc`?

**Comment by piponazo** [comment]
Interesting ... the mac build actually failed because of this change. It seems that some of the tests is not passing in that platform. Any of you have a Mac to try this branch there ?

**Comment by tbeu** [comment]
@clanmills has got a Mac.

**Comment by D4N** [comment]
> `rc` or `$rc`?

Of course it's `$rc`, sorry, I am not too proficient with bash.

The mac build seems to be failing because the `md5sum` command is not installed, I have tried adding the required package (md5sha1sum) to the install.sh script. Hopefully it will work.

**Review by tbeu — APPROVED** [review]

**Pull request merged**
