### PR TITLE
Add some F mount lenses

### PR DESCRIPTION
**Pull request by kmilos**
Address #2193, #2196 and #2214

### CODE REVIEW

**Comment by kmilos** [comment]
Actually, [one should drop "AF" from the modern OSD Tamrons](https://en.wikipedia.org/wiki/Tamron#List_of_photographic_lenses), so this might just work out...

@tuxfanx Can you please confirm this will be matched by lensfun now?

**Comment by tuxfanx** [comment]
> Not 100% sure for the Tamron string - I followed the pattern of existing Tamrons in the exiv2 Nikon database, but it is included in lensfun under a slightly different name (Canon/exiftool style?) already... @tuxfanx

**for the canon mount, exiv2 outputs the following:** 
Exif.Photo.LensSpecification                 Rational    4  35/1 150/1 0/0 0/0
Exif.Photo.LensModel                         Ascii      41  **TAMRON 35-150mm F/2.8-4.0 Di VC OSD A043**
Exif.Photo.LensSerialNumber                  Ascii      11  0000000000
Exif.Image.LensInfo                          Rational    4  35/1 150/1 0/0 0/0
[you can find some raw pictures taken with the canon mount lens here](https://www.dpreview.com/sample-galleries/0609865725/tamron-35-150mm-f2-8-4-di-vc-osd-sample-gallery/1899233528)

In my opinion, the "AF" does not belong in the model designation because Tamron does not use the "AF" either. If AF is used, it should also be included in the manufacturer's model number.
When using the "AF", 2 separate entries would also have to be listed in the Lensfun DB because of the different canon model designation.

**Comment by tuxfanx** [comment]
> Actually, [one should drop "AF" from the modern OSD Tamrons](https://en.wikipedia.org/wiki/Tamron#List_of_photographic_lenses), so this might just work out...
> 
> @tuxfanx Can you please confirm this will be matched by lensfun now?

"35-150mm F/2.8-4 Di VC OSD" would work, but is it necessary that the entry for Nikon is different from the entry for Canon?

**Comment by kmilos** [comment]
> "35-150mm F/2.8-4 Di VC OSD" would work, but is it necessary that the entry for Nikon is different from the entry for Canon?

Thanks for checking.

One could ask the opposite just as well. It's all a bit arbitrary, isn't it?

I'd prefer to keep the Nikon database scheme consistent. I can also happily remove the Tamron from this PR and let someone else handle it, or just leave users put whatever string they prefer in their ~/.exiv2 config file.

**Review by kevinbackhouse — APPROVED** [review]

**Comment by kmilos** [comment]
@mergifyio backport 0.27-maintenance

**Pull request merged**
