### PR TITLE
Update variable references to avoid expansion warnings

### LINKED ISSUE #1499: make uninstall is issuing warnings
Has to be investigated on all platforms.  It will be investigated and resolved in Exiv2 v0.27.4 RC2.

### PR DESCRIPTION
**Pull request by kmilos**
Fixes #1499

### CODE REVIEW

**Comment by clanmills** [comment]
Wow!  Thank You, @kmilos.

I was just thinking about getting a barf bag before investigating this.  I'll test this out on all the platforms and then approve the fix.

**Comment by kmilos** [comment]
Looks like this is shortcut though, but should be enough if it works...

The "proper" way might be to convert to a exiv2_unistall.cmake.in template instead and parse it w/ `configure_file()` like the FAQ suggests where those variables get replaced instead of the copy we do today:

https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

**Review by clanmills — APPROVED** [review]
This is no longer spewing meaningless messages into the terminal.  However, the uninstall isn't effective (on macOS).

```
# manually clean the standard location 
$ (cd /usr/local ; find . -name "*exiv2*" -depth | xargs sudo rm -rf )
$ (cd /usr/local ; find . -name "*exiv2*")
# install
$ sudo make install 2>&1 >/dev/null ; (cd /usr/local ; find . -name "*exiv2*" -depth)
./bin/exiv2json
./bin/exiv2
./include/exiv2/exiv2lib_export.h
./include/exiv2/xmp_exiv2.hpp
./include/exiv2/exiv2.hpp
./include/exiv2
./lib/libexiv2-xmp.a
./lib/pkgconfig/exiv2.pc
./lib/libexiv2.27.dylib
./lib/cmake/exiv2/exiv2Config-noconfig.cmake
./lib/cmake/exiv2/exiv2ConfigVersion.cmake
./lib/cmake/exiv2/exiv2Config.cmake
./lib/cmake/exiv2
./lib/libexiv2.dylib
./lib/libexiv2.0.27.4.10.dylib
./share/man/man1/exiv2.1
./share/locale/sk/LC_MESSAGES/exiv2.mo
./share/locale/ug/LC_MESSAGES/exiv2.mo
./share/locale/pl/LC_MESSAGES/exiv2.mo
./share/locale/vi/LC_MESSAGES/exiv2.mo
./share/locale/sv/LC_MESSAGES/exiv2.mo
./share/locale/ms/LC_MESSAGES/exiv2.mo
./share/locale/ca/LC_MESSAGES/exiv2.mo
./share/locale/ru/LC_MESSAGES/exiv2.mo
./share/locale/pt/LC_MESSAGES/exiv2.mo
./share/locale/uk/LC_MESSAGES/exiv2.mo
./share/locale/bs/LC_MESSAGES/exiv2.mo
./share/locale/gl/LC_MESSAGES/exiv2.mo
./share/locale/nl/LC_MESSAGES/exiv2.mo
./share/locale/de/LC_MESSAGES/exiv2.mo
./share/locale/fi/LC_MESSAGES/exiv2.mo
./share/locale/fr/LC_MESSAGES/exiv2.mo
./share/locale/es/LC_MESSAGES/exiv2.mo
$ sudo make uninstall ; (cd /usr/local ; find . -name "*exiv2*" -depth)
./include/exiv2
./lib/libexiv2.27.dylib
./lib/cmake/exiv2
./lib/libexiv2.dylib
```
There should be nothing!

I'm happy to accept this PR as it clears up the incompressible messages discussed in #1499.

I'll open a new issue to say "$ make uninstall leaves artefacts in standard locations". #1501

**Comment by clanmills** [comment]
This is no longer spewing meaningless messages into the terminal.  However, the uninstall isn't effective (on macOS).

```
# manually clean the standard location 
$ (cd /usr/local ; find . -name "*exiv2*" -depth | xargs sudo rm -rf )
$ (cd /usr/local ; find . -name "*exiv2*")
# install
$ sudo make install 2>&1 >/dev/null ; (cd /usr/local ; find . -name "*exiv2*" -depth)
./bin/exiv2json
./bin/exiv2
./include/exiv2/exiv2lib_export.h
./include/exiv2/xmp_exiv2.hpp
./include/exiv2/exiv2.hpp
./include/exiv2
./lib/libexiv2-xmp.a
./lib/pkgconfig/exiv2.pc
./lib/libexiv2.27.dylib
./lib/cmake/exiv2/exiv2Config-noconfig.cmake
./lib/cmake/exiv2/exiv2ConfigVersion.cmake
./lib/cmake/exiv2/exiv2Config.cmake
./lib/cmake/exiv2
./lib/libexiv2.dylib
./lib/libexiv2.0.27.4.10.dylib
./share/man/man1/exiv2.1
./share/locale/sk/LC_MESSAGES/exiv2.mo
./share/locale/ug/LC_MESSAGES/exiv2.mo
./share/locale/pl/LC_MESSAGES/exiv2.mo
./share/locale/vi/LC_MESSAGES/exiv2.mo
./share/locale/sv/LC_MESSAGES/exiv2.mo
./share/locale/ms/LC_MESSAGES/exiv2.mo
./share/locale/ca/LC_MESSAGES/exiv2.mo
./share/locale/ru/LC_MESSAGES/exiv2.mo
./share/locale/pt/LC_MESSAGES/exiv2.mo
./share/locale/uk/LC_MESSAGES/exiv2.mo
./share/locale/bs/LC_MESSAGES/exiv2.mo
./share/locale/gl/LC_MESSAGES/exiv2.mo
./share/locale/nl/LC_MESSAGES/exiv2.mo
./share/locale/de/LC_MESSAGES/exiv2.mo
./share/locale/fi/LC_MESSAGES/exiv2.mo
./share/locale/fr/LC_MESSAGES/exiv2.mo
./share/locale/es/LC_MESSAGES/exiv2.mo
$ sudo make uninstall ; (cd /usr/local ; find . -name "*exiv2*" -depth)
./include/exiv2
./lib/libexiv2.27.dylib
./lib/cmake/exiv2
./lib/libexiv2.dylib
```
There should be nothing!

I'm happy to accept this PR as it clears up the incompressible messages discussed in #1499.

I'll open a new issue to say "$ make uninstall leaves artefacts in standard locations".

@kmilos.  It would be more convenient to have this fix in #1498.  I'm sure there a some git magic to transfer https://github.com/Exiv2/exiv2/pull/1500/commits/d71b258b2432fc139b4f2268d22cea42eb6a46f6 into #1498.  So, just update #1498.

**Comment by kmilos** [comment]
OK, I'll deal with this later today.

The two *.dylib could be symlinks which will probably be handled with the updated uninstall template, but don't know why the two (empty?) folders remain...

**Comment by clanmills** [comment]
Correct.  It's leaving two symlinks and two empty directories.

```bash
501 rmills@rmillsm1:/usr/local $ find . -name "*exiv2*"
./include/exiv2
./lib/libexiv2.27.dylib
./lib/cmake/exiv2
./lib/libexiv2.dylib
502 rmills@rmillsm1:/usr/local $ find . -name "*exiv2*" | xargs ls -alt
lrwxr-xr-x  1 root  admin  17 19 Mar 10:30 ./lib/libexiv2.dylib -> libexiv2.27.dylib
lrwxr-xr-x  1 root  admin  24 19 Mar 10:30 ./lib/libexiv2.27.dylib -> libexiv2.0.27.4.10.dylib

./lib/cmake/exiv2:
total 0
drwxr-xr-x  2 root  wheel   64 19 Mar 10:30 .
drwxr-xr-x  7 root  wheel  224 19 Mar 10:30 ..

./include/exiv2:
total 0
drwxr-xr-x     2 root    admin     64 19 Mar 10:30 .
drwxr-xr-x@ 1275 rmills  admin  40800 19 Mar 10:30 ..
503 rmills@rmillsm1:/usr/local $ 
```

I will not delay RC1 because of this.  It's probably been this way for years.

Yesterday I suddenly thought "I've never investigated uninstall.  I've never investigated install with Visual Studio builds.".  In the past, by the time I arrive at this part of the release process, I'm so exhausted I don't want to discover anything else that's broken.

**Comment by kmilos** [comment]
I might not get to update the PR until this eve or tomorrow, so if you don't want to delay RC1 further please go ahead, we'll address this for RC2

**Review by clanmills — CHANGES_REQUESTED** [review]
I'm happy with this, @kmilos.  Can you submit this change into #1498 which is "heading for the door" later today.

Let's deal with #1501 as a different issue.

**Comment by clanmills** [comment]
Right.  I've done that:
```bash
$ cd 0.27-maintenance
$ curl --silent -L https://patch-diff.githubusercontent.com/raw/Exiv2/exiv2/pull/1500.patch | git apply
```

Thank You for doing this.  I'm going for a 10k walk in the forest.  v0.27.4 RC1 goes live at 18:00 UTC.

**Comment by kmilos** [comment]
@clanmills Sorry for the last minute commits, but should still be ok for your 18:00 UTC plan ;)

**Pull request closed without merging**
