### PR TITLE
Fix conan ci luis

### PR DESCRIPTION
**Pull request by piponazo**
Parallel work to #2017 . I just wanted to do some trial & error in a separated branch to Robin's one.

Summary of the actions taken:
- Upgrade to conan 1.43 in all the CI pipelines.
- On Appveyor, where we use the cache feature, make sure we are cleaning up old conan remotes and adding the newer one.
- Use new conan generators that integrate better with CMake.
- Increase minimum required CMake version to 3.7. That version of CMake makes possible to use the CMake targets `GTest::gtest` and `GTest::gtest_main` which automatically propagates the libraries, include directories and definitions needed.
- Remove gitlab & travis pipeline scripts. These were superseded by the Github actions a long time ago.

### CODE REVIEW

**Review by kevinbackhouse — DISMISSED** [review]
Wizardry!

**Review by clanmills — CHANGES_REQUESTED** [review]
Mostly awesome, Luis.

The macOS/CI doesn't use conan and has passed.  I've successful built/tested this on macOS/x64 without conan.  

It doesn't build with conan and I think it's because GTest 1.10 requires C++11.  Can you change conanfile to use gtest/1.8.1 please?

There's a  problem building with conan on the M1 chip because conan has build Expat with arch==x64 and not arm64.  This is OK because that's clearly a conan issue we're not using conan to build with the CI.   

When this builds on macOS/conan (with GTest 1.8.1), let  merge your PR.  This evening I'll use diff to determine why I had linking errors and then close and delete fix_conan_ci.

**Comment by piponazo** [comment]
> It doesn't build with conan and I think it's because GTest 1.10 requires C++11. Can you change conanfile to use gtest/1.8.1 please?

Ha, something new I have learned today. I was not aware that Gtest 1.8.1 was the last release of Gtest working with pre-C++11 compilers.

Sure, I will change that :+1:

**Review by clanmills — APPROVED** [review]
Awesome work, @piponazo.  Build/tests on with/without conan macOS/x64. 

Thanks for simplifying the CI jungle of appveyor/github/gitlab/travis.  Less is usually better.  Well done to retain the appveyor Cygwin/MinGW targets. 

I'm sure @kevinbackhouse, @postscript-dev  and @kmilos will also want to say "Thank You, Luis".

**Comment by kevinbackhouse** [comment]
Will these changes work on `main` too?

**Comment by piponazo** [comment]
> Will these changes work on `main` too?

Most of the changes were already implemented in `main`, but I decided to create a new PR to do the upgrade to the latest conan version as we did here. I think it makes sense to keep the number of differences between `main` and `0.27-maintenance` as small as possible :wink:

**Pull request merged**
