### PR TITLE
More migration to size_t

### PR DESCRIPTION
**Pull request by piponazo**
Continuation of the work done to avoid some of the static_casts we have around the code base. See other recent PRs: #2118 #2109 #2062

### CODE REVIEW

**Comment by neheb** [comment]
Seems good at first glance. I do wonder whether or not static_cast is needlessly verbose. In my code I prefer to use functional casts, eg. size_t(x).

**Comment by piponazo** [comment]
> Seems good at first glance. I do wonder whether or not static_cast is needlessly verbose. In my code I prefer to use functional casts, eg. size_t(x).

Whenever you use C++ it is better to use the C++ casts because they just do what you specify. The usage of C-style casts can be actually dangerous in some cases, because they try to do different kind of casts in a determined order. You can find more information here:
https://stackoverflow.com/questions/332030/when-should-static-cast-dynamic-cast-const-cast-and-reinterpret-cast-be-used

Anyways, as I mentioned in this PR and in others, the intention is to remove as many static_casts as possible from the codebase. They are normally a code smell indicating that a better data model could reduce the need of them.

**Comment by clanmills** [comment]
I like Rosen's idea to use function casts.  The static cast syntax is ugly and the C cast is hackery.

**Comment by neheb** [comment]
Well, the function cast is the same as a C cast. Just looks less ugly and avoids the C cast clang-tidy warning.

I like using it for simple types like size_t where the compiler's not really going to do anything strange.

**Comment by clanmills** [comment]
The equivalent of a cast in Pascal was `size_t(...)`.  When I started to work in C, I was shocked by the cast.  I couldn't believe that a language designer would use anything so hideous.   My first program did something with argv, and I had a function with the signature `something(char*** args)`.  It was my first program for "The IBM PC".  After being used the multi-window Apollo workstation, it was quite a shock.  The C tradition of vulgar syntax continued with the `static_cast<voodoo> ...`.  C with all its *'s and ->'s looks like Custer at the Little Bighorn.

I read an interview with Stroudstup and he said something like "C++20 is the language I set out the make in the first place". I wonder if it will be as nice as Pascal.

**Comment by piponazo** [comment]
The PR is now ready for review after I fixed problems reported by the CI jobs.

@neheb & @clanmills , IMHO I think that the discussion about the casting style is offtopic (This PR is probably not the best place to discuss such things. I am actually mostly removing casts here). Feel free to open another issue or trigger this conversation in the team chat.

**Comment by clanmills** [comment]
You're quite right, @piponazo.  Apologies for the noise.

**Comment by piponazo** [comment]
> You're quite right, @piponazo. Apologies for the noise.

No worries, I appreciate interesting discussions in the right channels 😁

**Review by neheb — APPROVED** [review]

**Pull request merged**
