### PR TITLE
Add characterisation tests for the XmpKey class

### PR DESCRIPTION
**Pull request by piponazo**
While studying the code **XmpKey** I decided to:

- Add characterisation unit tests for the current behavior.
- clang-format the code for which I have added tests.

I will probably dedicate more time to add characterisation tests to the existing code, since it provides a proper safety net to address refactorings.

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
This is not an easy subject.  The syntax of keys in Exiv2 began life as:  Family.Group.Tag and that's fine for Exif and IPTC data:
```
646 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pe ~/Stonehenge.jpg | cut -d. -f 1 | cut -d' ' -f 1 | sort | uniq
Exif
647 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2 $ exiv2 -pe ~/Stonehenge.jpg | cut -d. -f 2 | cut -d' ' -f 1 | sort | uniq
GPSInfo
Image
Iop
MakerNote
Nikon3
NikonAf2
NikonCb2b
NikonFi
NikonIi
NikonLd3
NikonMe
NikonPc
NikonVr
NikonWt
Photo
Thumbnail
```

However Xmp is more complex.  I think, in effect, Xmp is XMP.adobeXmpSyntax.  So you can have stuff such as `XMP.xmp.MP.RegionInfo/MPRI:Regions[1]/MPReg:Rectangle`

There's a recursive parser in samples/exiv2json that understands the syntax and converts this into JSON.

I found it hard to discover Adobe's documentation about the syntax.  If you want me to search more, I'll look at this evening.

If we ever support multi-page tiff, the Exif.Group.TagName syntax will have to be enhanced to deal with pages.

**Comment by clanmills** [comment]
Here's a discussion I had with a user last year about XMP syntax:
http://dev.exiv2.org/boards/3/topics/2808?r=2818#message-2818

**Comment by piponazo** [comment]
Cool, thanks for all this information. The good thing about these characterisation tests is that they are also useful as documentation, and help you to get a glance of the code behaviour very quickly. I tried first to use a key ID such as `Exif.Group.TagName` and XmpKey class throws an exception unless you use something like the example used in the tests `Xmp.prefix.TagName`. 

I will try extend a bit those tests in the future with the new information you have provided 😉

**Comment by clanmills** [comment]
As always, Luis, you (and Dan) delight me with your ingenious way of looking at everything.  Very good work. Thanks very much.

**Pull request merged**
