### PR TITLE
Initial support for OM System MakerNote

### PR DESCRIPTION
**Pull request by kmilos**
Addresses #2126 in a "dumb" way by duplicating the header class.

### CODE REVIEW

**Comment by piponazo** [comment]
@kmilos In #2126 there is a sample image provide by the reporter of the issue. Is there any chance to extract the metadata from that image into an .exv file and add a new test in this branch to make sure that we are solving the issue?

**Comment by kmilos** [comment]
> Is there any chance to extract the metadata from that image into an .exv file and add a new test in this branch to make sure that we are solving the issue?

Will do when I find some time again @piponazo

**Comment by sarunasb** [comment]
> @kmilos In #2126 there is a sample image provide by the reporter of the issue. Is there any chance to extract the metadata from that image into an .exv file and add a new test in this branch to make sure that we are solving the issue?

Glad to provide any .exv files, but would need to know if any other switches beside -ex should be used.

**Comment by clanmills** [comment]
I think we had a discussion about how to manually create the .EXV when a segment (XMP or Exif) > 64k.  https://github.com/Exiv2/exiv2/issues/2126#issuecomment-1060233289

In the first instance, use `$exiv2 -ea --force --verbose path` to create a .EXV and you'll probably be happy with the result.  If however the XMP or Exif metadata exceeds one JPEG segment (of 64k max), you'll have to apply some effort to create a suitable .EXV.  You can inspect the structure of an image with the command `$ exiv2 -pS path`.

**Comment by sarunasb** [comment]
`
$ exiv2 -ea --force --verbose OM100015.ORF
File 1/1: OM100015.ORF
Writing Exif data from OM100015.ORF to ./OM100015.exv
Writing XMP data from OM100015.ORF to ./OM100015.exv
Warning: No image data to encode Exif.OlympusCs.PreviewImageStart.
Warning: Exif tag Exif.Olympus2.ThumbnailImage not encoded
Warning: Exif tag Exif.OlympusCs.PreviewImageLength not encoded
Warning: Exif tag Exif.OlympusCs.PreviewImageStart not encoded
Warning: Exif tag Exif.OlympusCs.PreviewImageValid not encoded
Warning: Exif tag Exif.Photo.MakerNote not encoded
Warning: Exif tag Exif.OlympusIp.0x0635 not encoded
Warning: Exif tag Exif.OlympusIp.0x0636 not encoded
Warning: Exif tag Exif.OlympusIp.0x063a not encoded
Warning: Exif tag Exif.OlympusIp.0x063b not encoded
Warning: Exif tag Exif.OlympusIp.0x1103 not encoded
Warning: Exif tag Exif.OlympusIp.0x1104 not encoded
`
OM100015.exv is here:
https://math.dartmouth.edu/nextcloud/s/mBPbcPNsJAY8tQW

**Comment by clanmills** [comment]
Gosh, I don't want to get sucked into this.  Where's the "original" file OM100015.ORF?

Sometimes, when you're up to your neck in alligators, it's hard to remember that this mission was to drain the swamp!  All we want is a small file that contains the metadata in which you are interested.  We prefer to add small files to the test suite.

Can you get ExifTool to create a .EXV from OM100015.ORF?

**Comment by piponazo** [comment]
I thought it might convenient to bring here the topic about the usage of Git LFS. If we move on with the proposal I presented in #2159 we could eventually upload large binary files for testing.

**Comment by sarunasb** [comment]
Here is the original RAW OM100015.ORF (19MB), from which the .exv was created:
https://math.dartmouth.edu/nextcloud/s/n4S2WtaRWRXpoMw

I have also created .exv from the JPEG sample attached in #Support for files from OM System cameras #2126:
https://math.dartmouth.edu/nextcloud/s/tya7CdrTb8Neb2Q

I do have a local version of ExifTool, modified to read OM System MakerNote. Here is an .EXV created with 
`exiftool -tagsfromfile OM100015.ORF OM100015_exiftool.EXV`:
https://math.dartmouth.edu/nextcloud/s/DpYAxCqQoPEyd4N

**Comment by kmilos** [comment]
Good to go I think, unless @clanmills or @hassec figure out a more compact/elegant way of implementing this.

**Review by clanmills — APPROVED** [review]
Thanks for working on this, @kmilos.

I'm going to approve this because it works and fits the existing architecture.  It's amazing that we need 100+ lines of additional boiler plate code when tvisitor does the same job in 2 lines (which I suspect I can reduce to 1 line!).

The inflexibility of the `__MnHeader::__Signature()` methods is because they are baked into the code.  I feel we have failed to discover how this can be detected and fixed by read().  Having created the class with confidence and proceeded to read the metadata, we should not need rigid static strings and size_t variables in different classes.

The other architectural issue is the makernote classes.  tvisitor.cpp has no maker note classes at all.  None.  I never discovered a need for any.  However the effort and risk involved in removing the makernote classes from Exiv2 cannot be justified.  So, let's leave alone.  If anybody ever rewrites Exiv2, I hope they will appreciate the simpler (and more robust and consistent) approach used by tvisitor to deal with makernotes, ICC, IPTC and format specific metadata such as PNG/textual-information.  Less can be more!

None-the-less, the code is correct and does its job.  Thank You to @kmilos for putting in the effort to add this to Exiv2.

**Review by piponazo — APPROVED** [review]

**Comment by hassec** [comment]
Should we maybe just create a small follow-up issue to look into cleaning up the duplication? Just so that it doesn't get forgotten? 

Otherwise, I'm happy for this to go in :+1:

**Comment by clanmills** [comment]
@hassec The duplication?  Are you referring to the boiler plate class code being mostly duplicated in the _MnHeader classes?  If that's what you're thinking, my inclination is to allow it as the effort/risk to re-engineer these classes is considerable.

**Comment by kmilos** [comment]
> Should we maybe just create a small follow-up issue to look into cleaning up the duplication? Just so that it doesn't get forgotten?

Sure, feel free!

**Pull request merged**
