### PR TITLE
Update security process

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Suggested update to our security process.
Note: I removed the "Reported CVEs" section because it is incomplete and will become obsolete with this new process.

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
This is really good.  Thank You very much for working on this.

I'm so happy that you have volunteered.  I would have liked to have done more in this area (and localisation).    I hope more contributors will make Exiv2 better and stronger.

I'm delighted by the emerging cooperation with Yaun.  I am concerned that his enthusiasm for security drowns our development efforts and undermines Exiv2 credibility and good reputation.

**Review by clanmills — DISMISSED** [review]
I thought you had already removed that.  I added that in enthusiasm last year and never had time to investigate and create that table.  I'm glad this information is now provided by some other mechanism.  Good Work.

**Comment by kevinbackhouse** [comment]
I added an extra paragraph to clarify that bugs found on the main branch aren't security bugs, unless they are reproducible on an official release, such as [v0.27.3](https://github.com/Exiv2/exiv2/releases/tag/v0.27.3).

**Review by hassec — APPROVED** [review]

**Review by piponazo — APPROVED** [review]
LGTM! Thanks :+1:

**Pull request merged**
