### PR TITLE
Main drop deprecated stuff

### PR DESCRIPTION
**Pull request by piponazo**
Rescue from `old-master` the changes in which we removed things that are marked as DEPRECATED in 0.27-maintenance:

https://github.com/Exiv2/exiv2/pull/694

### CODE REVIEW

**Comment by piponazo** [comment]
Something weird is happening with the reporting on AppVeyor ... in this PR it looks like it is failing but navigating in AppVeyor I can see that the build is passing:
https://ci.appveyor.com/project/piponazo/exiv2-wutfp/builds/38740840

The error reported by Gitlab seems to be legit:
https://gitlab.com/D4N/exiv2/-/jobs/1187120660

But I would try to fix it in a different PR.

**Comment by clanmills** [comment]
@piponazo We're dancing on each other's toes. 

I removed the video code in #1560.  I'd like to stop work on #1560 and let's work together to get this PR ready to merge.

I have the Cygwin64 build running (locally and CI).  https://github.com/Exiv2/exiv2/pull/1560/commits/19c50aee88799027278da63b22903be518a9c259

I fixed the MinGW/msys2 build on my machine (yet it fails on the CI).
https://github.com/Exiv2/exiv2/pull/1560/commits/53d65f2c4064b386c9485a41f6266fe28fc7fc52

And I've increase the python timeout in suite.conf to avoid a false test failure:
https://github.com/Exiv2/exiv2/pull/1560/commits/7e971ba17f1554e67a6d2ad0fcdf61d2610d1ee4

I'm not going to close #1560 yet.  I will try to get MinGW/msys2 to build on the CI.

**Comment by clanmills** [comment]
> Something weird is happening with the reporting on AppVeyor ... in this PR it looks like it is failing but navigating in AppVeyor I can see that the build is passing:
> https://ci.appveyor.com/project/piponazo/exiv2-wutfp/builds/38740840
> 
> The error reported by Gitlab seems to be legit:
> https://gitlab.com/D4N/exiv2/-/jobs/1187120660
> 
> But I would try to fix it in a different PR.

I added Cygwin and MinGW/msys2 Appveyor/CI builds a few months ago.  The Visual Studio builds are fine.

The MinGW "localtime"  issue is fixed on my machine with https://github.com/Exiv2/exiv2/commit/53d65f2c4064b386c9485a41f6266fe28fc7fc52  It's strange that fix doesn't work on the CI.  I'm going to look at the configuration of the CI.  Maybe we need a different version of GCC or something. 

I'm confident we'll have this fixed in a couple of hours.

**Comment by clanmills** [comment]
My machine and the CI are using GCC 10.2.0. 

Time to use the heavy artillery.  Retain and inspect the code generated by the pre-processor.

**Comment by clanmills** [comment]
@piponazo I've got this almost fixed in #1560.  The C++ is failing to compile something in the ImageFactory on Fedora/MinGW. https://gitlab.com/D4N/exiv2/-/jobs/1188620228

Kind weird that it compiles that code elsewhere.  There's not much wrong here.  Let's fix and merge this PR because you've taken care of the EPS and other stuff I haven't look at yet in #1560.

**Comment by clanmills** [comment]
You'll have to fix Cygwin/64.  It's using the 2019 Image, however the CI script in appveyor_mingw_cygwin.yml sets up Cygwin/64 environment and builds using gcc.

Your build is failing to compile:
```
/cygdrive/c/projects/exiv2/include/exiv2/rwlock.hpp: In constructor 'Exiv2::RWLock::RWLock(__pthread_rwlockattr_t* const*)':
644/cygdrive/c/projects/exiv2/include/exiv2/rwlock.hpp:95:17: error: 'pthread_rwlock_init' was not declared in this scope; did you mean 'pthread_rwlock_t'?
645   95 |                 pthread_rwlock_init(&rwlock_, attr);
646      |                 ^~~~~~~~~~~~~~~~~~~
647      |                 pthread_rwlock_t
```

Its caused by building with -std=c++11.  We need to use -std=gnu++11 on Cygwin/64.  The fix is here:  https://github.com/Exiv2/exiv2/pull/1560/commits/19c50aee88799027278da63b22903be518a9c259

After the build has failled, the test suite powers up and goes crazy because executables such as exiv2(.exe) have not been built.  We should add something to the system_tests.py to instantly terminate if the executables do not exist.  I'll open an issue about this and ask @1div0 to investigate.  Fixing that is not urgent.

**Review by clanmills — APPROVED** [review]
Very good.  Team-work works.  I don't know why nobody uses it at work.

**Comment by sridharb1** [comment]
I am removing myself from the reviewer list. Sorry, but don't want to be a roadblock on this. However, I approve what is being done in this issue.

**Pull request merged**
