### PR TITLE
Switch Cygwin CI to GHA

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by kmilos** [comment]
Duh, there is no other shell for Cygwin action other than PowerShell, trying its multi-line break...

Also, not sure why AppVeyor is still attempting to run when the recipe has been removed?

**Review by clanmills — COMMENTED** [review]
That looks about right. Let's see how/if it works out on the CI.

You're using the correct approach to install the dependencies and build with CMake without using conan.  I've never succeeded in building with conan on Cygwin.

The code in appveyor_mingw_cygwin.yml use apt-cyg to install the dependencies and builds with cmake.  Appveyor runs the cmd shell.

**Comment by kmilos** [comment]
Yeah, and had to turn unit test off (same on AppVeyor) as there is not gtest on Cygwin available ootb.

**Comment by kmilos** [comment]
Almost there, now juts a couple of test fail, presumably because of line ending difference: `ctest` is run from PowerShell and not from bash like it was on AppVeyor...

**Comment by clanmills** [comment]
Here are the notes I made when I created this last year:  https://help.appveyor.com/discussions/questions/51961-building-on-mingw-64-and-cygwin64

When this PR flies, we don't need appveyor to run appveyor_mingw_cygwin.yml at all.  I can't remember how this is triggered.  I'm fairly sure I had to register something on the appveyor web-site.

**Comment by clanmills** [comment]
@kmilos Appveyor is running the cmd.exe (DOS console) and I execute bash to run the bash build script.  I build the bash build script line-by-line with `;` command separators.  The bash build script is a one-liner.

```
set CMD=mkdir build
set CMD=CMD=%CMD%; cd build
...
C:\cygwin64\bin\bash -c "%CMD%"
```

**Comment by clanmills** [comment]
I'm fairly sure the build is failing in Appveyor because you've deleted appveyor_mingw_cygwin.yml.  I think I had to register something with appveyor to tell him to use that file.  

I remember thinking "this will only work on 0.27-maintenance".  Ummm.  I can't remember how it works and I can't find anything on appveyor.  @kevinbackhouse Do you know how appveyor knows to read the file appveyor_mingw_cygwin.yml?

**Comment by kmilos** [comment]
Thanks Robin, I was well aware of that. The problem was that the default bash launcher suggested by the action author changes the working directory to $HOME even w/ `--norc`, so I had to remove the `--login` option.

But we're back to square one (same as PowerShell), there are still a couple of failing tests...

**Comment by clanmills** [comment]
@kmilos.  

I haven't understood what you are saying about the shell.  Most of the tests pass, so it's mostly working fine.  This looks like a solid/repeatable error.  I'll try this after lunch on Windows.

At the moment, I'm giving README.md a thorough overhaul to deal with ctest.

**Comment by clanmills** [comment]
I've found the appveyor settings.  https://ci.appveyor.com/project/clanmills/exiv2/settings.  I will delete the project.

Later today, I'll investigate the other build failures on Windows.  There can't be much wrong.

**Comment by kmilos** [comment]
> I've found the appveyor settings. https://ci.appveyor.com/project/clanmills/exiv2/settings. I will delete the project.

Please wait until we get this working ;)

The suggested workaround to check out Unix line endings also doesn't work currently... I'm taking a break from this one...

**Comment by clanmills** [comment]
Whoops.  I've already deleted it.

I asked in a review for that code concerning the line-endings to be changed and the engineer refused.  He's the only contributor I have ever fired.

**Comment by kmilos** [comment]
Ok, figured out why the git config wasn't working (executed in the wrong shell), so this is my last attempt before touching tests.

**Comment by kmilos** [comment]
Bingo!

**Review by piponazo — APPROVED** [review]
Great! Finally all the pipelines running on GHA! :confetti_ball:

**Comment by clanmills** [comment]
You're almost as smart as I used to be!

Do you know the Country Song "As Good As I One Was"?  https://www.youtube.com/watch?v=ldQrapQ4d0Y

**Comment by kmilos** [comment]
Can't say I did :D

**Comment by clanmills** [comment]
_"I'm not as good as I once was.
But I'm as good once, as I ever was!"_

**Pull request merged**
