### PR TITLE
Explicitly include stdint

### LINKED ISSUE #2557: Code in main does not compile on F38
I dared to upgrade to Fedora Linux 38 β. However, Exiv2 code in main branch does not compile cleanly neither w/ GNU Compiler nor w/ LLVM based Clang++.

Please see the logs.
[Exiv2 GCC 13 F38.log](https://github.com/Exiv2/exiv2/files/11028322/Exiv2.GCC.13.F38.log)
[Exiv2 LLVM 15.0.7 F38.log](https://github.com/Exiv2/exiv2/files/11028323/Exiv2.LLVM.15.0.7.F38.log)

On F37 it was OK.

[RFC] Anyone experienced the same issue?

### PR DESCRIPTION
**Pull request by kmilos**
Fixes https://github.com/Exiv2/exiv2/issues/2557

### CODE REVIEW

**Review by kevinbackhouse — APPROVED** [review]

**Comment by neheb** [comment]
Google search shows https://github.com/marketplace/actions/install-llvm-and-clang for testing newer versions.

**Comment by kmilos** [comment]
Don't think we need/want a new action per se, just better coverage of toolchains in already existing images (e.g. CLANG64 in MSYS2 and llvm-toolchain-15 in ubuntu-latest) instead of all the insane combinations of release/debug/shared/static...

**Comment by kmilos** [comment]
@neheb If I enable `EXIV2_TEAM_WARNINGS_AS_ERRORS` on CLANGARM64, I get these errors for a Debug build:
```
C:/msys64/home/kmilos/exiv2/src/helper_functions.cpp:23:30: error: 'codecvt_utf8<wchar_t, 1114111,
 0>' is deprecated [-Werror,-Wdeprecated-declarations]
  using convert_typeX = std::codecvt_utf8<wchar_t>;
                             ^
C:/msys64/clang64/include/c++/v1/codecvt:199:28: note: 'codecvt_utf8<wchar_t, 1114111, 0>' has been
explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 codecvt_utf8
                           ^
C:/msys64/clang64/include/c++/v1/__config:800:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_C
XX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                        ^
C:/msys64/clang64/include/c++/v1/__config:773:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#      define _LIBCPP_DEPRECATED __attribute__((deprecated))
                                                ^
C:/msys64/home/kmilos/exiv2/src/helper_functions.cpp:24:24: error: 'convert_typeX' is deprecated [
-Werror,-Wdeprecated-declarations]
  std::wstring_convert<convert_typeX, wchar_t> converterX;
                       ^
C:/msys64/clang64/include/c++/v1/codecvt:199:28: note: 'codecvt_utf8<wchar_t, 1114111, 0>' has been
explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 codecvt_utf8
                           ^
C:/msys64/clang64/include/c++/v1/__config:800:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_C
XX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                        ^
C:/msys64/clang64/include/c++/v1/__config:773:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#      define _LIBCPP_DEPRECATED __attribute__((deprecated))
                                                ^
C:/msys64/home/kmilos/exiv2/src/helper_functions.cpp:24:8: error: 'wstring_convert<std::codecvt_ut
f8<wchar_t, 1114111, 0>>' is deprecated [-Werror,-Wdeprecated-declarations]
  std::wstring_convert<convert_typeX, wchar_t> converterX;
       ^
C:/msys64/clang64/include/c++/v1/locale:3621:28: note: 'wstring_convert<std::codecvt_utf8<wchar_t, 1
114111, 0>>' has been explicitly marked deprecated here
class _LIBCPP_TEMPLATE_VIS _LIBCPP_DEPRECATED_IN_CXX17 wstring_convert
                           ^
C:/msys64/clang64/include/c++/v1/__config:800:41: note: expanded from macro '_LIBCPP_DEPRECATED_IN_C
XX17'
#    define _LIBCPP_DEPRECATED_IN_CXX17 _LIBCPP_DEPRECATED
                                        ^
C:/msys64/clang64/include/c++/v1/__config:773:49: note: expanded from macro '_LIBCPP_DEPRECATED'
#      define _LIBCPP_DEPRECATED __attribute__((deprecated))
                                                ^
3 errors generated.
```

This is even before trying to fix this header issue.

**Comment by kmilos** [comment]
@neheb If I turn that off, but tuen samples on, CLANG64 fails w/
```
C:/msys64/home/milos/exiv2/samples/easyaccess-test.cpp:11:23: error: constexpr variable 'easyAcce
ss' must be initialized by a constant expression
static constexpr auto easyAccess = std::array{
                      ^            ~~~~~~~~~~~
1 error generated.
```

**Comment by neheb** [comment]
Codecvt being deprecated is a C++17 thing.

I tested the meson build, which does not have samples yet. I'll look into it.

**Comment by neheb** [comment]
I just looked at that code. I have no idea why it wouldn't be constexpr friendly.

**Comment by kmilos** [comment]
@neheb Thanks for looking into it.

> my first guess is a CMake bug where samples are not being compiled as C++17

Nope, `-std=gnu++17` is in there...

```
[118/208] Building CXX object samples/CMakeFiles/easyaccess-test.dir/easyaccess-test.cpp.obj
FAILED: samples/CMakeFiles/easyaccess-test.dir/easyaccess-test.cpp.obj
C:\msys64\clang64\bin\c++.exe -DEXV_LOCALEDIR=\"../share/locale\" -DWIN32_LEAN_AND_MEAN -IC:/msys64/
home/kmilos/exiv2/build -IC:/msys64/home/kmilos/exiv2/src -IC:/msys64/home/kmilos/exiv2/includ
e/exiv2 -IC:/msys64/home/kmilos/exiv2/include -g3 -gstrict-dwarf -O0 -std=gnu++17 -fvisibility=hid
den -fvisibility-inlines-hidden -Wp,-D_GLIBCXX_ASSERTIONS -Wall -Wcast-align -Wpointer-arith -Wforma
t-security -Wmissing-format-attribute -Woverloaded-virtual -W -Wno-error=format-nonliteral -municode
 -MD -MT samples/CMakeFiles/easyaccess-test.dir/easyaccess-test.cpp.obj -MF samples\CMakeFiles\easya
ccess-test.dir\easyaccess-test.cpp.obj.d -o samples/CMakeFiles/easyaccess-test.dir/easyaccess-test.c
pp.obj -c C:/msys64/home/kmilos/exiv2/samples/easyaccess-test.cpp
C:/msys64/home/kmilos/exiv2/samples/easyaccess-test.cpp:11:23: error: constexpr variable 'easyAcce
ss' must be initialized by a constant expression
static constexpr auto easyAccess = std::array{
                      ^            ~~~~~~~~~~~
1 error generated.
```

**Comment by kmilos** [comment]
> I looked into codecvt. Seems to do the same as iconv. Maybe we should make iconv required on non Windows. Thoughts?

Definitely worth exploring.

**Comment by neheb** [comment]
https://github.com/Exiv2/exiv2/pull/2553 is a small fix for MSYS2. Well, less compiled code.

**Pull request merged**
