### PR TITLE
Fix branch names in CONTRIBUTING.md (master was renamed to main)

### PR DESCRIPTION
**Pull request by Sturmflut**

### CODE REVIEW

**Review by piponazo — APPROVED** [review]
Thanks a lot for fixing these notes (and for all your new contributions 👍 )

**Comment by postscript-dev** [comment]
@Sturmflut: Thanks for contributing this.

If you have the time, would you be interested in also updating [GIT_GUIDELINES.md](https://github.com/Exiv2/exiv2/blob/46c329081f147d68ba38e7256481d8e432cac64c/GIT_GUIDELINES.md)? This has the same `master`/`main` problem.

**Comment by Sturmflut** [comment]
> @Sturmflut: Thanks for contributing this.
> 
> If you have the time, would you be interested in also updating [GIT_GUIDELINES.md](https://github.com/Exiv2/exiv2/blob/46c329081f147d68ba38e7256481d8e432cac64c/GIT_GUIDELINES.md)? This has the same `master`/`main` problem.

Sure, see #2075.

**Comment by postscript-dev** [comment]
@Sturmflut: Great, thanks for working on that.

**Pull request merged**
