### PR TITLE
New folders layout

### PR DESCRIPTION
**Pull request by piponazo**
In this PR I am proposing to change slightly the folders structure of the project.

The old folder layout was:
- **src** folder: Inside we had the **exiv2lib** sources and private headers. But not only that, we also had the code for the **exiv2** application there.
- **include** folder: Just the public headers belonging to exiv2lib.
- **unitTests** folder: unit tests for **exiv2lib**.

The new layout is:
- **exiv2lib** folder: Inside we had the exiv2lib sources. Inside we have the **include** folder with the public headers and the **unitTests** folder with exactly the same content than before.
- **exiv2app** folder: exiv2 application code.

This simple change revealed some problems:

- It was not clear in some cases if some sources were belonging to the library or to the application. Now each source file is where it belongs.
- The **exiv2** application was accessing some private code of **exiv2lib**. I had to consider some of these headers as public headers of **exiv2lib** so that the application and the samples can use them.
- There seems to be a convoluted situation with the `timegm.h` file. I think things can be simplified there, and I have created an issue (#334) to investigate the situation later.
- There were few header files that were not added to the CMake code. This was causing that some IDEs could not handle those files properly. 

This is the first of a series of changes I want to carry on to improve different aspects of the project configuration. As we have been discussing during the last months, I will only perform these changes to the CMake code, and the autotools & msvc configuration systems will stop working. If you accept these changes, I will propose to remove the autools & msvc configuration code from the repository.

### CODE REVIEW

**Comment by piponazo** [comment]
Note that I left the different commits just to document the different steps I had to do. If the PR gets approved I will squash them.

**Review by clanmills — COMMENTED** [review]
I'm a little nervous about this.  With the website under DDoS attack, I've recommended to somebody to use `$ make doc` to generate the documentation.  I wonder how the documentation has been disturbed by this.

The other matter that bothers me is making the release.  There's stuff in the exiv2/Makefile which is involved in this.  I can recover/refactor those scripts and commands to be executed in a different way from SVN as they haven't been touched since releasing v0.26.

So, let me have a night's sleep on this in case I think of another reason to hesitate.

**Comment by piponazo** [comment]
Let's create tasks to generate the documentation and the releases with CMake. I've done these things in the past with CMake, and it should be relatively simple to implement them in Exiv2. I will address those tasks before merging this branch. 

For the documentation, I think I do not need much more information. But I would like to know what we exactly need for the release. Could you give more details about it in a different issue?

**Comment by clanmills** [comment]
There isn't a whole lot to building the documentation.  It's built with Doxygen.  I don't remember much about it.  I don't remember it being difficult.  I'm sure it can be made into a simple script to be executed by CMake.

I agree with what you're saying about the release process.  There's quite a lot to be thought about there.

Can you open two issues (one for the release and one for the docs) and we can discuss this there.

Incidentally, I've discovered why I've been encountering problems with cmake/msvc setting EXV_HAVE_STDINT_H  It's because I sometime build with Cygwin in the same source tree that I use to build for msvc.  Cygwin correctly finds unistd.h and writes the file include/exiv2/exv_conf.h with that symbol.  The CMake/msvc files are reading the wrong exv_conf.h.

I'm going to approve this change and removing the autotools and msvc/ code.  (sniff, sad to see the end of msvc/).  However this is a solid change.  Thank You for working on this and persuading me to accept this direction.

**Review by clanmills — APPROVED** [review]

**Comment by piponazo** [comment]
Sure, I'll create the two issues and then we can discuss more about those topics in each issue.

Let's fix these things as soon as possible (and before merging these changes). I would not like to remove any functionality without a replacement already in place for the CMake configuration.

**Comment by D4N** [comment]
Oh, I think I broke this PR by merging #153... Sorry :(

Anyway, concerning the new folder layout:
- this will make the backporting off changes on 0.26 a lot harder, I would therefore suggest to introduce this shortly before the 0.27 release
- What's the issue with the exiv2 binary including private headers? Just bad style?
- (Just my personal opinion: can we call `exiv2app` just `exiv2` or something without app in the name?)

**Comment by piponazo** [comment]
> this will make the backporting off changes on 0.26 a lot harder, I would therefore suggest to introduce this shortly before the 0.27 release.

Are we still interested in doing that? I thought we were interested in backporting more things from master to 0.26 (after what it was said in #336). If that is not the case, then I'm fine with waiting to introduce these changes after 0.27. 

> What's the issue with the exiv2 binary including private headers? Just bad style?
Yes. Ideally exiv2 and the sample applications should only access the public headers. If we find ourselves having applications that need internal parts of the library, I would classify this as a code/design smell. Those should be implementation details of the library, not stuff which need to be accessed by the consumers.

> (Just my personal opinion: can we call exiv2app just exiv2 or something without app in the name?)
Sure. Then I think I would call the folders: **lib** for the library and **exiv2** for the terminal application.

**Comment by piponazo** [comment]
I agree with you guys, let's wait a bit more for addressing these kind of changes. I'm closing this PR.

**Comment by clanmills** [comment]
I like the idea of renaming `src/exiv2.cpp` as `src/exiv2app.cpp`

**Comment by D4N** [comment]
> Question is, should we do this in RCx, v0.27 or introduce it when we begin v0.28?

I think a RC of v0.27 would be the best point in time. At that point we will probably no longer have to backport a lot of stuff, so the additional work will be minimal. But at the same time everyone downstream will see the change and we'll have the new layout in 0.27 from the start (so that backporting from 0.28 to 0.27 will be easy).

**Pull request closed without merging**
