### PR TITLE
Support Canon M100

### PR DESCRIPTION
**Pull request by danileo**
Adds the support of the Canon M100 camera ModelID.
Before:
> exiv2 -pt testimg.jpg | grep -ai model
Exif.Image.Model Ascii 15 Canon EOS M100
Exif.Canon.ModelID Long 1 (60293120)
Exif.Photo.LensModel Ascii 29 EF-M15-45mm f/3.5-6.3 IS STM
After:
> exiv2 -pt testimg.jpg | grep -ai model
Exif.Image.Model Ascii 15 Canon EOS M100
Exif.Canon.ModelID Long 1 EOS M100
Exif.Photo.LensModel Ascii 29 EF-M15-45mm f/3.5-6.3 IS STM

### CODE REVIEW

**Comment by D4N** [comment]
@danileo Thanks for your contribution! Since we like to have tests for new lenses, could you either write one (see the directory `tests/`) or upload a sample image and I'll write the test (provided you allowed edits by maintainers)?

**Comment by clanmills** [comment]
@D4N This issue was reported with a test file yesterday on Redmine: http://dev.exiv2.org/issues/1352

I've copied Daniel's file 
```
$ curl http://dev.exiv2.org/attachments/download/1226/testimg.jpg > test/data/exiv2-bug317.jpg
```

And written the following test in tests/bugfixes/github/test_issue_317.py
```
# -*- coding: utf-8 -*-

import system_tests
class NikonLensId227(metaclass=system_tests.CaseMeta):

    filename = "$data_path/exiv2-bug317.jpg"
    commands = ["$exiv2 -pa --grep model/i $filename"]

    stdout = ["""Exif.Image.Model                             Ascii      15  Canon EOS M100
Exif.Canon.ModelID                           Long        1  EOS M100
Exif.Photo.LensModel                         Ascii      29  EF-M15-45mm f/3.5-6.3 IS STM
"""
	]
    stderr = [""]
    retval = [0]
```

When I run test test suite, I see at the end of the test report:
```
...
test_run (bugfixes.github.test_issue_317.NikonLensId227) ... ok
test_run (bugfixes.github.test_issue_45.Sigma24_105mmRecognization) ... ok
test_run (bugfixes.github.test_regression_issue_201.ShadowingError) ... ok
test_run (bugfixes.redmine.test_1305.Issue1305Test) ... ok
test_run (bugfixes.redmine.test_issue_1348.NikonLensId227) ... ok
test_run (tiff_test.test_tag_compare.OutputTagExtract) ... ok
test_run (tiff_test.test_tiff_test_program.TestTiffTestProg) ... ok

----------------------------------------------------------------------
Ran 44 tests in 1.033s
```

My git skills are totally insufficient to modify Daniel's PR.  Daniel: Can you update your PR?

**Comment by danileo** [comment]
I amended the PR with the changes described by @clanmills

**Comment by clanmills** [comment]
Thank you, Daniel for doing this.  I'm going to leave @D4N (Dan) to review and integrate this.  Dan is super smart and always thinks of "gotcha's" that I'm not clever enough to spot!

**Comment by D4N** [comment]
@danileo I stripped your test image from its image data & pushed the changes to this PR's branch in your fork.

Thanks for your work! I am going to merge this once the CI is green.

**Review by D4N — APPROVED** [review]

**Pull request merged**
