### PR TITLE
exiv2_v0.27.5RC3

### LINKED ISSUE #1935: Exiv2 v0.27.5 RC3
I've updated the v0.27.5 release notes https://github.com/Exiv2/exiv2/issues/1018#issuecomment-895425552 with an additional prolog.  The release note tables for RC1/RC2/RC3.  will be merged for GM.

**Exiv2 v0.27.5 RC3 2021-09-30**

Changes since RC2.

| Group    | PR     | Topic                                                       | Issue  | 
|:-        |:-      |:-                                                           |:-      |
| Withdrawn| #1858  | Fix compiler warning on Apple/M1/Clang                      | https://github.com/Exiv2/exiv2/pull/1915#pullrequestreview-758174005  |
| Withdrawn |  | Reading HEIC from iPhone images |  #1928 |
| Build    | TBD    | Fix linking libiconv on macOS with M1                       | #1903  |
| Security | TBD    | Fix out of range access                                     | #1918  |

We intend to release Exiv2 v0.27.5 RC3 and v0.27.5 on 2021-10-22.

---------------------------------

Please let me know of other changes.  Here are PRs which have been closed on 'main'.  I believe only #1918 and #1915 will be in RC3.   I'm sure @kevinbackhouse will know about other issues.

fix out of range access, minor performance improvement  bug
#1918 by rabauke was merged 5 days ago

Pass -fstack-protector-strong to linker  build  CMake
#1915 by evanmiller was merged 9 days ago

Fix quadratic loops in pentaxmn_int.cpp  bug  OSS-Fuzz
#1910 by kevinbackhouse was merged 10 days ago

Comment out bogus code in XMPUtils.cpp  bug  OSS-Fuzz
#1902 by kevinbackhouse was merged 10 days ago

Lock conan version on Windows.  forward-to-main
#1897 by kevinbackhouse was merged 20 days ago

### PR DESCRIPTION
**Pull request by clanmills**

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
I must have missed one of the conan invocations.

**Comment by clanmills** [comment]
Bollocks.  git refuses my fix:  _0.27-maintenance -> 0.27-maintenance (refusing to allow an OAuth App to create or update workflow `.github/workflows/on_PR_windows_matrix.yml` without `workflow` scope)_

I think the change is here:
```
      - name: Run Conan
        run: |
          md build
          cd build
          conan config install https://github.com/conan-io/conanclientcert.git
          conan profile list
          conan install .. --build missing
          dir ..
          tree /f ../conanCache
```

**Comment by kevinbackhouse** [comment]
Hang on. I was looking at this from my phone before, but I am at my desk now. I'll see if I can fix it.

**Comment by kevinbackhouse** [comment]
It looks like it wasn't running with the latest version of the CI, so I have tried rebasing the commits onto the latest 0.27-maintenance.

**Review by kevinbackhouse — APPROVED** [review]

**Comment by clanmills** [comment]
Thanks @kevinbackhouse For me, git is mostly a mystery.  I know about 6 commands and that's it.

**Comment by kevinbackhouse** [comment]
@clanmills: that's me with cmake! It seems like a bunch of magic incantations that I have very little interest in learning.

**Comment by clanmills** [comment]
Luis's the cmake man.  He actually likes it!  I confess to liking Windows.

**Comment by clanmills** [comment]
Well done, @kevinbackhouse.  Now I have to figure out how to remove two dead commits from my branch.  Probably easier to pull down a fresh copy from GitHub.  I believe that's the fix for about 90% of git troubles.

**Comment by kevinbackhouse** [comment]
Do you mean you want to squash this into a single commit? I think you might be able to do that from the dropdown on the "merge" button.

**Comment by kevinbackhouse** [comment]
@clanmills: I just had another look at this. Do you just want to get rid of the two "build trigger" commits? I can do that if you like. Or you can do it like this:

```bash
git checkout exiv2_v0.27.5RC3
git reset --hard exiv2_v0.27.5RC3~2
git push --force
```

**Comment by clanmills** [comment]
I got rid of the build triggers using the SmartGit GUI.  That was straightforward.  I deleted the local branch and pulled a mint copy from GitHub.  Rather scared of a command such as `git push --force` which might push the house down!

Less nervous about `git reset --hard exiv2_v0.27.5RC3~2` which only hits the local repos.

**Comment by kevinbackhouse** [comment]
@clanmills: The easiest solution is to push another commit to edit the files to how you want them, then use the "squash and merge option":
Screenshot from 2021-10-01 18-15-10

**Comment by clanmills** [comment]
I heard Dan talking about squashing.  I thought squash was something to drink on a hot summer's day!  Ah, yes.  That makes sense.  More questions:

1. How did you get your code from #1939 into the base of this branch? 
2. The difference between `git pull` and `git pull --rebase` and what's fast forward and what's merge?

I'm going to merge this PR, tag 0.27-maintenance and publish the RC3 on GitHub.  You've done a great job on v0.27.5.  This is "Kev's Release".

**Comment by kevinbackhouse** [comment]
The answer to 1 is that I did a rebase. I.e. I took your 3 commits and reapplied them to the latest version of 0.27-maintenance. The sequence of commands was something like this:

```bash
git checkout exiv2_v0.27.5RC3
git rebase origin/0.27-maintenance
git push --force
```

To be honest, I have never heard of `git pull --rebase`. I'll have to go and look that up.

I often use the `gitk` tool to view the commit graph and check that the correct thing happened when I do something potentially destructive like a rebase.

**Comment by clanmills** [comment]
Ah!! Right.  Now I know what rebase is.  Thanks for the explanation.

**Pull request merged**
