### PR TITLE
Output of -PV was not suitable for inputting to -m-, key was missing.

### LINKED ISSUE #1969: -PV option doesn't print the key
Using an image from the test suite, you get:

```
$ exiv2 -PV -K Exif.Image.ImageDescription test/data/smiley1.jpg
set  Well it is a smiley that happens to be green
```

while according to the man page, `-PV` is supposed to:

```
V : plain data value AND the word 'set ' (for use with exiv2 -m-)
```

But the above output is unsuitable for the `-m` flag since it's missing the key.

### PR DESCRIPTION
**Pull request by facundofc**
Fix #1969

### CODE REVIEW

**Review by postscript-dev — CHANGES_REQUESTED** [review]
Can you also make a very small change to section [11 'MODIFY' COMMANDS](https://github.com/Exiv2/exiv2/blob/main/exiv2.md#11-modify-commands) in the manpage.
Please change 2 references:
'--Print Vkyv' to '--Print V'

**Comment by kevinbackhouse** [comment]
@postscript-dev: is this one ready to merge except for the issue with the Mac tests?
@facundofc: I wasn't able to rerun the tests. Normally, there's a button that I can click but it's missing for some reason. Please could you add a commit with a trivial change, like adding an empty line, just to trigger the tests?

**Review by kevinbackhouse — APPROVED** [review]

**Comment by kevinbackhouse** [comment]
@postscript-dev: This looks ready to me. Ok to merge?

**Comment by postscript-dev** [comment]
@kevinbackhouse: Yes, let's go ahead with this.
________________________________

**Review by postscript-dev — APPROVED** [review]

**Pull request merged**
