### PR TITLE
Fix test_pr_1905.py for native 2019msvc64 (#2108)

### LINKED ISSUE #2108: test_pr_1905.TestExifTagsInTaglist depends on cut command
##### **Describe the bug**
The test file `tests/bash_tests/test_pr_1905.py` depends on the `cut` command available on bash shells. Therefore, when one tries to run all the project tests with `ctest` on windows with CMD or PowerShell, that test fails:

````
1: ======================================================================
1: FAIL: test_run (test_pr_1905.TestExifTagsInTaglist)
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "F:\projects\exiv2\tests\system_tests.py", line 652, in test_run
1:     self.compare_stderr(i, command, processed_stderr, stderr)
1:   File "F:\projects\exiv2\tests\system_tests.py", line 773, in compare_stderr
1:     self._compare_output(
1:   File "F:\projects\exiv2\tests\system_tests.py", line 745, in _compare_output
1:     self.assertMultiLineEqual(
1: AssertionError: "'cut' is not recognized as an internal o[50 chars]e.\n" != ''
1: - 'cut' is not recognized as an internal or external command,
1: - operable program or batch file.
1:  : Standard error does not match
1:
1: ----------------------------------------------------------------------
1: Ran 33 tests in 11.707s
```
##### **To Reproduce**
Steps to reproduce the behavior:
1. Compile the projedt under windows
2. Run `ctest` on a CMD or Powershell. You should not have in your `PATH` any directory that might containg the cut command.

##### **Expected behavior**
All tests pass correctly.

##### **Desktop (please complete the following information):**
- OS and version: (Windows 11)
- Compiler and version: (MSVC 2022)
- Compilation mode and/or compiler flags: Release. No special flags.

##### **Additional context**
Even though the `windows-2022` github instances seems to use by default PowerShell, I guess that they include in their `PATH` the directories in which the bash terminals are installed. Therefore, the problem is not visible in our CI infrastructure.

### PR DESCRIPTION
**Pull request by postscript-dev**
Closes #2108.

### CODE REVIEW

**Review by piponazo — DISMISSED** [review]
Tested on my Windows PC and it works 👏

**Review by clanmills — COMMENTED** [review]
Beautiful fix, @postscript-dev.

**Comment by postscript-dev** [comment]
@piponazo:
Thanks for the quick response!

Last year, I noticed a problem related to this issue that I think is worth mentioning.

The Exiv2 mechanism to create tag webpages from the source code is [only run when we publish the website](https://github.com/Exiv2/team/blob/abf9dcb871ecc5b18207c8b8dc88ee0abf95d10f/.github/workflows/exiv2.org.yml#L48). This means that when we make changes, the CI will not catch any errors for us. To create the webpages is simple.
1. Set the `EXIV2HOME` environment variable (e.g., `/home/postscript-dev/exiv2_postscript-dev`)
2. In the `doc/templates` directory, run `make`

The build instructions are missing from [README.md](https://github.com/Exiv2/exiv2/blob/main/README.md) but I plan to add them.

If you have the time, could you look at the CI?

**Review by hassec — CHANGES_REQUESTED** [review]
Can we keep `test/data` for input data and use `test/data/test_reference_files` for reference output?

**Review by piponazo — APPROVED** [review]

**Comment by piponazo** [comment]
> Can we keep `test/data` for input data and use `test/data/test_reference_files` for reference output?

I think it would be a good idea to write this down in the wiki or in the test/README document to give instructions to people about some of the practices we have been discussing lately about writting tests. 

> The Exiv2 mechanism to create tag webpages from the source code is [only run when we publish the website](https://github.com/Exiv2/team/blob/abf9dcb871ecc5b18207c8b8dc88ee0abf95d10f/.github/workflows/exiv2.org.yml#L48). This means that when we make changes, the CI will not catch any errors for us. To create the webpages is simple.

@postscript-dev whenever you create the PR with the instructions, please do it in the main repository and I'll happily try to adapt our CI jobs to make this run on every PR.

**Review by hassec — APPROVED** [review]

**Pull request merged**
