### PR TITLE
Fixes #1014 Two Nikon lenses still not detected

### LINKED ISSUE #1014: Two Nikon lenses still not detected
**Describe the bug**
I have some pictures using two lenses I had some years back and they seems to be still missing from the exiv2. I used the following `.exiv2`:
```
[nikon]
164=AF-S Nikkor 70-200mm f/2.8E FL ED VR
170=AF-S Nikkor 24-70mm f/2.8E ED VR
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Run exiv2 on the existing photos 
2. Lenses are not detected

The metadata from pictures:
```
$ exiv2 -pv --grep Lens DSC_0003.JPG
0x0083 Nikon3       LensType                    Byte        1  78
0x0084 Nikon3       Lens                        Rational    4  240/10 700/10 28/10 28/10
0x008b Nikon3       LensFStops                  Undefined   4  72 1 12 0
0x000c NikonLd3     LensIDNumber                Byte        1  170
0x000d NikonLd3     LensFStops                  Byte        1  72
```
and
```
$ exiv2 -pv --grep Lens DSC_0170.NEF
0x0083 Nikon3       LensType                    Byte        1  78
0x0084 Nikon3       Lens                        Rational    4  240/10 700/10 28/10 28/10
0x008b Nikon3       LensFStops                  Undefined   4  72 1 12 0
0x000c NikonLd3     LensIDNumber                Byte        1  170
0x000d NikonLd3     LensFStops                  Byte        1  72
```

**Expected behavior**
The lens should be detected.

**Desktop (please complete the following information):**
 - OS: Linux
 - Compiler & Version [Gcc 7.3, Clang-6, MSVC 2017]
 - Compilation mode and/or compiler flags

**Additional context**
I would be able to contribute the code, but it is not particularly clear to me how and what all values I am supposed to use in the `src/nikonmn_int.cpp` to get the correct behavior. So either point me how I should do or feel free to add the data. I can also provide images if necessary.

### PR DESCRIPTION
**Pull request by layderv**

### CODE REVIEW

**Comment by Jakuje** [comment]
@layderv thank you for the help. I unfortunately did not manage to get back to the original issue during last week, but I will check if it works for me in the evening.

I would be also for removing the AAA BBB CCC DDD, since I think they were used only for the differentiation of the different identification of the same lens and nothing that should get to the resulting code.

**Comment by layderv** [comment]
@D4N sure, done. @Jakuje @clanmills ok so the file doesn't change from the one now in `master`; should I update the tests to reflect the current output?

**Comment by Jakuje** [comment]
I am sorry it took me time to come back to this issue and to figure out what is going on here.

I got a bit confused with the ordering of the lens records and by the fact that this information is not in the default output of exiv2 command. Indeed, with master, I am getting correct results with master now.

Now, we have two same lines with different LensType value and same name. I did not find the second bit of this value described anywhere and I see that there are similar "duplicates" in other Nikon lenses. I will check tomorrow what is the real name of the lenses that I had borrowed and I will come back to see whether they need to be updated or we are fine.

**Comment by layderv** [comment]
Ok, in the meantime I'm leaving the tests

**Comment by Jakuje** [comment]
I checked the lenses and I am pretty sure that both of them are VR, but I do not see a difference in the different `LensType`:

    Nikon 24-70/2,8 VR
    Nikon 70-200/2,8 VR E FL

so I think we are fine this way. Thank you.

**Comment by piponazo** [comment]
Hi guys! Thanks for the contribution.

If I understood correctly, at the end we do not have a defect on master, and this is just about adding a new test validating lens recognition for a specific case, right?. I'm approving now and once we get a confirmation about this we can merge it.

**Review by piponazo — APPROVED** [review]

**Comment by Jakuje** [comment]
> Hi guys! Thanks for the contribution.
> 
> If I understood correctly, at the end we do not have a defect on master, and this is just about adding a new test validating lens recognition for a specific case, right?. I'm approving now and once we get a confirmation about this we can merge it.

Yes.

**Comment by D4N** [comment]
@Jakuje I'm a little confused, didn't you write in #1014 that changes are required on master too?

**Comment by Jakuje** [comment]
> @Jakuje I'm a little confused, didn't you write in #1014 that changes are required on master too?

Yes, but after I wrote the changes, we figured out that the record is already there.

**Pull request merged**
