### PR TITLE
several keys added to easyaccess

### PR DESCRIPTION
**Pull request by norbertwg**
Related to issue https://github.com/Exiv2/exiv2/issues/2338
For lensmodel the call of findMetadatum is replaced by code based on findMetadatum.
Reason: In all samples I analysed, an image containing Exif.NikonLd4.LensIDNumber also contains Exif.NikonLd4.LensID and vice versa. One of them (sometimes both) has the integer value zero, whereas the other can have a reasonable value. So when looping through the tags, a NikonLd4-tag is skipped, when it's value is zero.

Sample easyaccess-test enhanced with additional optional arguments "category" for easier definition of some tests.

Following keys are added:
Exif.Canon.LensModel
Exif.CanonCs.MaxAperture
Exif.CanonSi.ApertureValue
Exif.MinoltaCs5D.ExposureManualBias
Exif.MinoltaCs5D.MeteringMode
Exif.MinoltaCsNew.MinoltaModel
Exif.MinoltaCsOld.MeteringMode
Exif.MinoltaCsOld.MinoltaModel
Exif.Nikon3.ISOSettings
Exif.NikonLd4.LensID
Exif.NikonLd4.LensIDNumber
Exif.NikonLd4.MaxAperture
Exif.NikonPc.Saturation
Exif.NikonSiD300a.ISO
Exif.Olympus2.Macro
Exif.Olympus2.Quality
Exif.OlympusCs.ExposureMode
Exif.OlympusCs.MeteringMode
Exif.OlympusEq.SerialNumber
Exif.OlympusRd.ExposureBiasValue
Exif.OlympusRd2.ExposureBiasValue
Exif.PanasonicRaw.Make
Exif.PanasonicRaw.Model
Exif.PanasonicRaw.Orientation
Exif.Pentax.ExposureTime
Exif.Pentax.FNumber
Exif.Pentax.Flash
Exif.Pentax.MeteringMode
Exif.Pentax.ModelID
Exif.Pentax.Quality
Exif.Pentax.SerialNumber
Exif.Pentax.WhiteBalance
Exif.PentaxDng.ExposureTime
Exif.PentaxDng.FNumber
Exif.PentaxDng.Flash
Exif.PentaxDng.MeteringMode
Exif.PentaxDng.ModelID
Exif.PentaxDng.Quality
Exif.PentaxDng.SerialNumber
Exif.PentaxDng.WhiteBalance
Exif.Photo.BodySerialNumber
Exif.Sigma.MeteringMode
Exif.Sony1Cs.MeteringMode
Exif.Sony1Cs2.ExposureProgram
Exif.Sony1Cs2.MeteringMode
Exif.Sony2Cs.MeteringMode
Exif.SonyMinolta.Quality
Exif.SonyMisc2b.ExposureProgram
Exif.SonyMisc3c.Quality2

### CODE REVIEW

**Comment by norbertwg** [comment]
Sorry, again need some help. As you see, some jobs failed. Looking into the log, I should have added test reference files for the new exv-files I added for testing. I have created them locally and committed. What shall I do to get it included in this pull request, just a push?

**Comment by postscript-dev** [comment]
@norbertwg 
> What shall I do to get it included in this pull request, just a push?

Yes, pushing locally will update your fork at github.com/norbertwg/exiv2 and here. This link was created when you requested a PR with exiv2.

**Comment by postscript-dev** [comment]
@norbertwg 
Is your PR ready for review?

**Comment by norbertwg** [comment]
@postscript-dev 
Yes, PR is ready for review.

**Review by kevinbackhouse — APPROVED** [review]

**Comment by kevinbackhouse** [comment]
@postscript-dev: is this ok to merge?

**Comment by postscript-dev** [comment]
@kevinbackhouse 
> @postscript-dev: is this ok to merge?

Yes, the changes look good.

@norbertwg 
Thanks for taking the time to contributing this, the easyaccess API hadn't been updated for a while and needed work. In the future, when we add new tags to exiv2, we can try to also update the easyaccess arrays.

After reviewing a PR, we usually leave the contributor to perform the merge. You can select squash and merge and then click to add this to the `main` branch.

**Comment by kevinbackhouse** [comment]
Not sure if @norbertwg has permission to merge, so I'll do it.

**Pull request merged**
