### PR TITLE
Do not check functions existence

### PR DESCRIPTION
**Pull request by piponazo**
I noticed that we are checking in the CMake code for the existence of some functions and headers that are guaranteed to exist in C++98. Since we are using the ` -std=c++98` compiler flag, we will always have those functionalities. 

Those checks apart of being useless (IMO) increase considerably the configuration times on CMake.

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
That's interesting, Luis.  These things have been there forever.  Presumably memset (and the others) are in C++11/14/17.

There's something wrong with CMake/msvc HAVE_UNISTD_H in config/generateConfigFile.cmake  I'm not sure how/why he thinks unistd.h is visible to the CL compiler.  The file is in the cygwin and mingw trees which should be invisible to msvc.  I don't believe any version of msvc has ever provided unistd.h. 

I have the following hack in include/exiv2/config.h, however it'd be better to fix this in generateConfigFile.cmake

```
#include "exv_conf.h"

// CMake mistakenly finds unistd.h
#ifdef  _MSC_VER
# ifdef  EXV_HAVE_UNISTD_H
#  undef EXV_HAVE_UNISTD_H
# endif
#endif
```

**Comment by piponazo** [comment]
Hi Robin, I am not sure I understood what you are saying. Efectively we have this line of code in `config/generateConfigFile.cmake`:

```
check_include_file( "unistd.h"  EXV_HAVE_UNISTD_H )
```
I did not touch this one because I knew that it is not provided by MSVC. When we run cmake on windows, cmake detects correctly that the file is not there. These lines come from our [AppVeyor CI job](https://ci.appveyor.com/project/piponazo/exiv2-wutfp/build/1.0.554):

```
-- Looking for unistd.h
-- Looking for unistd.h - not found
```
I did not try to run it with MinGW, but the CMake code seems to be doing the work correcly in the CI node. 

Since this point about `EXV_HAVE_UNISTD_H` is a different topic to which I was fixing here, I propose you to create an issue with more details about it and then I can check it out.

**Comment by clanmills** [comment]
My code in config.h is 100% wrong and will not be submitted.  I think we need to exclude check_include_file( "unistd.h"  EXV_HAVE_UNISTD_H ) for MSVC in generateConfigFile.cmake  I'll investigate this after lunch.

Let's not spend time on this during the weekend as we easily fix this by email.  Together we should discuss big/interesting things that aren't so easy by email.

**Comment by clanmills** [comment]
This change in config/generateConfigFile.cmake appears to work OK.
```
# TODO : Do something about EXV_STRERROR_R_CHAR_P

# TODO: This check should be removed and rely on the check done in findDependencies.cmake
check_include_file( "libintl.h" EXV_HAVE_LIBINTL_H )

if(NOT MSVC)
check_include_file( "unistd.h"  EXV_HAVE_UNISTD_H )
endif()

check_include_file( "memory.h"  EXV_HAVE_MEMORY_H )
check_include_file( "process.h" EXV_HAVE_PROCESS_H )
```

**Comment by piponazo** [comment]
You do not need to do that @clanmills. The point of the `check_include_file` cmake function is that it will look into your system for those headers and later create the file `exv_conf.h` in the build directory with a definition or not of `EXV_HAVE_UNISTD_H`.

I noticed that there is a mess right now around all these configuration files. Some of them are generated by CMake, others by the autotools, we even have some files in the source tree with mixed responsibilities:

```
include/exiv2/config.h
include/exiv2/exv_msvc.h
include/exiv2/exv_msvc-webready.h
```
I really want to clean all these things if we finally take the step of removing the autotools/msvc files and we just support CMake as configuration system.

**Comment by clanmills** [comment]
check_include_file appears to be making an error on the buildserver and finding unistd.h.  Curiously, it behaves correctly on my laptop!  The files exv_msvc.h and exv_msvc-webready.h are essential for the msvc/ build.

Let's discuss the decision to drop support for msvc/ and autotools/

**Pull request merged**
