### PR TITLE
fix_1076_0.27 2 sigmas lenses on Canon body

### LINKED ISSUE #1076: Update of 2 sigmas lenses on Canon body AND way to differentiate lenses with same ID
Hello,

In the array: canonCsLensType of the file canonmn_int.cpp, please could you add these 2 lenses:

        { 231, "Sigma 12-24mm f/4 DG HSM | A"                               }
        { 495, "Sigma 24-70mm f/2.8 DG OS HSM | A"                       }

For the number 495, there is already one canon lens with same focal and aperture so not possible to differentiate with actual code.
{ 495, "Canon EF 24-70mm f/2.8L II USM"                             }

It is nevertheless possible to differentiate by using the tag: 0x0095, "LensModel" of CanonMakerNote which is:

"12-24mm F4 DG HSM | Art 016"
"24-70mm F2.8 DG OS HSM | Art 017"

Maybe it would be a good idea when the match has 2 possible solutions to use this tag.
Either by finding exactly the same substring "24-70mm F2.8 DG OS HSM | Art 017" to differentiate with the canon lens or using the distinctive "Art" which has a high probability to be specific to sigma lenses.

I can provide images if needed.

Kind regards,
Fabien

### PR DESCRIPTION
**Pull request by clanmills**
Fix #1076 @fabeng07 Please provide test files and I will update the test suite.

### CODE REVIEW

**Review by piponazo — DISMISSED** [review]
It looks fine, but it would be nice to have the representative metadata in order to create a test case for these lenses.

**Comment by clanmills** [comment]
Thanks @piponazo.  I will update and merge when I get test files from @fabeng07.  In #1076, he offered test files and when Dan asked for them, nothing happened!  I'm sure he'll send them and we'll get finished on this one.

**Comment by clanmills** [comment]
Thanks @piponazo.  I will update and merge when I get test files from @fabeng07.  In #1076, he offered test files and when Dan asked for them, nothing happened!  I'm sure he'll send them and we'll get finished on this one.

**Comment by clanmills** [comment]
@fabeng07  Please provide test images so I can finish this for Exiv2 v0.27.3 RC1.

**Comment by clanmills** [comment]
Without test images, this fix will not be submitted to the code base.

**Pull request closed without merging**
