### PR TITLE
Optional compiler flags for detecting more warnings

### PR DESCRIPTION
**Pull request by piponazo**
In this PR I am adding 2 new CMake variables (disabled by default) that are useful for the Exiv2 developers to detect some issues in the code thanks to the compiler flags.

The objective of these flags is to enable some useful flags I found in this [post](https://kristerw.blogspot.ch/2017/09/useful-gcc-warning-options-not-enabled.html)  to detect issues in the code. Note that some of these flags can be aggressive and detect false positives. The developers should use them wisely and comment/un-comment those ones that the find useful.

Apart of adding these options, I have been fixing some of the issues detected in the code thanks to these flags. Maybe I went too far applying changes, so if some of the reviewers think that the changes that I did in the c++ code are not appropriate I am happy to modify the PR to just include the CMake code and then submit other PRs with the changes in the C++ code.

You will notice that now that the output in Travis-ci and AppVeyor are much more clean :)

### CODE REVIEW

**Comment by Kicer86** [comment]
As in case of ccache I'm against such changes.
It adds extra efford for cmake maintenance.
Also it is imho against cmake idea to be cross platform (now only gcc is supported).
My personal point of view is to keep CMakeLists as simple as possible. The less ifs the better.
It is easy to set these flags by developer himself.

**Comment by Kicer86** [comment]
One more comment: I'd rather enabled all possible warnings on travis or appveyor.

**Comment by D4N** [comment]
I am a little torn whether to add these flags to CMake. Imho they can be a useful addition, nevertheless you can achieve the same with `CXXFLAGS=-Wextra -Werror -Wlogical-op cmake ..` (just as an example) for which you needn't write any cmake code, you only need a shell. However, CMake can add/remove flags depending on your compiler version, which is very useful. I'll have to think a little bit more about that.

**Review by clanmills — APPROVED** [review]
I'm not sure what is "best" here.  I want to agree with both of you, so let me propose a way to move forward.

Let's have a team meeting on Sunday 12 November when I'm home in England.  I only do this about once per year on Google+.  13:00UTC (14:00 CET).  I'll open a GooglePlus event about 12:45 and you'll receive an invitation.

I'll prepare a slide presentation/agenda for the meeting and circulate it a few days before the meeting.  I aim to keep team meetings to 60 minutes or less.

If Luis wants to submit this code, I'm happy.  We can remove it later when we talk together.  And this will give Dan and Michal time to experience the impact.  Keep the code or remove it?  I think we'll all agree when we've had some time to use those changes.

I have a few of observations:
1) Please use throw `error(Exiv2::kerSomething)` and not `throw("english string")` (to ensure localisation).  AND it encourages us to use generic throws conditions.
2) Let's keep the "straight build" simple.  Let's not overwhelm the user with build choices that she/he cannot understand.  To help with that, let's try to keep options in families.  Eg EXIV2_ENABLE...., EXIV2_BUILD..., EXIV2_TEAM... for options that are of limited public use.
3) I think we need to have EXIV2_options to "mask" some CMake options.  Perhaps it's good to have EXIV2_BUILD_SHARED_LIBS and BUILD_SHARED_LIBS. 
4) Can you test these new option on clang and GCC.  A day will arrive when CLANG is our preferred compiler (which it is already on MacOS-X).
5) Can we "atomise" this commit?  There's a lot of changes here.  It's probably best to keep CMake options and C++ changes in different commits - especially if we decide to back port to release branches.

I'm sure I'll have more comments to add concerning the code changes in the next few days when I find time on my own to work.

I am so happy with the effort Luis, Dan, Michal and (the new Andreas S) are making on Exiv2.  Thank You so much for your hard work and commitment.

At the meeting in November, let's discuss leadership of the project.  As you know, I would like leadership taken off my back.  I'm happy to volunteer for a less stressful role such as "release engineer" and/or "user support".

**Comment by D4N** [comment]
This is a big PR, I'll need some time to get work through the diff.

**Comment by piponazo** [comment]
Hi guys!

Thanks for all your useful reviews. I understand all the points that you have made and they made me think. For the moment I am going to close this PR since it is true that I went too far here and it is difficult to review all the changes.

I will open another PR only with the CMake changes and I will also explore if they are compatible with clang. If not, I will investigate about other useful clang compiler flags to detect these kind of issues.

I think that the changes in the CMake are mostly isolated in the file `config/compilerOptions.cmake` and do not affect much to other parts of the CMake configuration. Although any developer can pass those flags through the command line to CMake, many will forget about that, or they even might not know about these compiler flags at all. I see this as some help utilities to the developers, that would help them to toggle these options easily by just enabling a CMake option.

**Comment by D4N** [comment]
Please re-submit the code patches too. There were lots of useful changes (for instance the float vs double) that we should consider.

**Comment by piponazo** [comment]
I will do it! 😉

**Pull request closed without merging**
