### PR TITLE
sridharb1_contrib_msvc3_0.27

### PR DESCRIPTION
**Pull request by clanmills**
`contrib\msvc` renamed `contrib\msvc2019`
`contrib\msvc\build` renamed `contrib\msvc2019\solution`

### CODE REVIEW

**Comment by clanmills** [comment]
Visual Studio 2013 build is failing while conan is building zlib.  It's using python27 to run conan and I think we should be using python37.

The CI for VS2013 has been stable.  Perhaps the CI is running on a clean machine that is failing to build zlib.  On earlier builds, perhaps the CI already had zlib pre-built, or downloaded a built version.

The MacMini is able to build VS 2013 without issues.

I will ignore the CI and merge this change.

**Comment by piponazo** [comment]
I think zlib is being built and the problem is with OpenSSL:

```
ERROR: OpenSSL/1.1.1c@conan/stable: Error in source() method, line 170
	tools.get(url, sha256=sha256[self.version])
	NotFoundException: Not found: https://www.openssl.org/source/old/1.1.1openssl-1.1.1c.tar.gz
Command exited with code 1
```

But you are right on your analysis. The conan guys said months ago that the support for python2 would be dropped. I will take a look into this, and check if we can use python3 in the windows machines provided by AppVeyor. (I'll work in other branch, so fell free to merge this one).

**Comment by clanmills** [comment]
Thank you, @piponazo You are such a helpful person.

**Comment by clanmills** [comment]
Ah, yes it's openssl.  When I build on the MacMini, by default I don't build web-ready.  The build.sh script has an option to build web-ready.

**Comment by sridharb1** [comment]
> 
> 
> Ah, yes it's openssl. When I build on the MacMini, by default I don't build web-ready. The build.sh script has an option to build web-ready.

I am guessing that with all these comments, it is the "built-in" build script that has some issues.

However, is the new projects/solution working or not yet? Are you still waiting for me to change the paths to the new ones? As I said, I will do it, but unfortunately I have a crashing disk emergency that simply sucked up the last two days. I may be able to work on it tomorrow.

**Comment by clanmills** [comment]
The issue is coming from AppVeyor which GitHub invokes to build the code on various editions of Visual Studio.  I'm not experiencing problem on my build server at home.  We can safely ignore this.

When you've done the relative paths and any other changes, let me know and we'll get them into 0.27-maintenance.  There's no hurry.  RC1 is not due for another 4 weeks.

**Comment by clanmills** [comment]
The problem in AppVeyor is after compiling zlib, it does:
```
function 'conans.client.tools.files.unzip'
701  warnings.warn("Provide the output argument explicitly{}".format(fn_str))
702WARN: minizip.patch: error: absolute paths are not allowed - file no.1
703WARN: minizip.patch: stripping absolute path from source name '/dev/null'
704WARN: minizip.patch: error: absolute paths are not allowed - file no.2
705WARN: minizip.patch: stripping absolute path from source name '/dev/null'
706zlib/1.2.11@conan/stable: WARN: Didn't find crypt.h at path: c:\Users\appveyor\conanCache\zlib\1.2.11\conan\stable\package\4c07c57fb6551a5dcaf87b7d4f715de1120ade0a\include\crypt.h
707ERROR: OpenSSL/1.1.1c@conan/stable: Error in source() method, line 170
708	tools.get(url, sha256=sha256[self.version])
709	NotFoundException: Not found: https://www.openssl.org/source/old/1.1.1openssl-1.1.1c.tar.gz
710Command exited with code 1
```
When I run on rmillsmm-w10, I get:
```
conan install .. --profile msvc2013Release64 --options webready=True --build missing  2>&1 | c:\msys64\usr\bin\tee -a logs\build.txt
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=12
os=Windows
os_build=Windows
[options]
webready=True
[build_requires]
[env]

conanfile.py: Installing package
Requirements
    Expat/2.2.6@pix4d/stable from 'conan-center' - Cache
    OpenSSL/1.1.1c@conan/stable from 'conan-center' - Cache
    gtest/1.8.0@bincrafters/stable from 'conan-center' - Cache
    libcurl/7.61.1@bincrafters/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    Expat/2.2.6@pix4d/stable:58e0aa01cb58b4d743f9d9a3484424eff9ac0056 - Cache
    OpenSSL/1.1.1c@conan/stable:71216f8a3ce0e621eed5c053c417fdcab8134684 - Cache
    gtest/1.8.0@bincrafters/stable:1579b76058fd3f3284ad47a8d6c712af83876129 - Cache
    libcurl/7.61.1@bincrafters/stable:a189ae2e2043d26f522b07d1385dc8a21c0054a2 - Cache
    zlib/1.2.11@conan/stable:e0a02d496bbb652b6295152dfce0d3937acc0b56 - Cache
```
It used existing builds in the conan cache.  So, I removed the `~/.conan/data` directory and repeated the build.  This time, conan downloaded the dependencies.  It didn't build anything.
```
conan install .. --profile msvc2013Release64 --options webready=True --build missing  2>&1 | c:\msys64\usr\bin\tee -a logs\build.txt
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=12
os=Windows
os_build=Windows
[options]
webready=True
[build_requires]
[env]

zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
zlib/1.2.11@conan/stable: Downloaded recipe revision 0
gtest/1.8.0@bincrafters/stable: Not found in local cache, looking in remotes...
gtest/1.8.0@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
gtest/1.8.0@bincrafters/stable: Downloaded recipe revision 0
libcurl/7.61.1@bincrafters/stable: Not found in local cache, looking in remotes...
libcurl/7.61.1@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libcurl/7.61.1@bincrafters/stable: Downloaded recipe revision 0
OpenSSL/1.1.1c@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.1.1c@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
OpenSSL/1.1.1c@conan/stable: Downloaded recipe revision 0
Expat/2.2.6@pix4d/stable: Not found in local cache, looking in remotes...
Expat/2.2.6@pix4d/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Expat/2.2.6@pix4d/stable: Downloaded recipe revision 0
conanfile.py: Installing package
Requirements
    Expat/2.2.6@pix4d/stable from 'conan-center' - Downloaded
    OpenSSL/1.1.1c@conan/stable from 'conan-center' - Downloaded
    gtest/1.8.0@bincrafters/stable from 'conan-center' - Downloaded
    libcurl/7.61.1@bincrafters/stable from 'conan-center' - Downloaded
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    Expat/2.2.6@pix4d/stable:58e0aa01cb58b4d743f9d9a3484424eff9ac0056 - Download
    OpenSSL/1.1.1c@conan/stable:71216f8a3ce0e621eed5c053c417fdcab8134684 - Download
    gtest/1.8.0@bincrafters/stable:1579b76058fd3f3284ad47a8d6c712af83876129 - Download
    libcurl/7.61.1@bincrafters/stable:a189ae2e2043d26f522b07d1385dc8a21c0054a2 - Download
    zlib/1.2.11@conan/stable:e0a02d496bbb652b6295152dfce0d3937acc0b56 - Download
```
Why does AppVeyor compile those libraries instead of downloading them?  No idea!!

I'm quite certain that this can be ignored as an AppVeyor panic attack.

**Comment by piponazo** [comment]
I did not spend time checking but I am pretty sure that the problem is that those binaries are available for certain configurations in the conan servers, but the specific configuration that we are using is not there, and we have to compile it by our selves. 

In this link you can check the available pre-compiled binaries for libcurl:
https://conan.io/center/libcurl/7.69.1/?user=_&channel=_&revision=&os=Windows&tab=config

The fact that they do not have all possible combinations is reasonable, specially for old compiler versions. Think about the amount of space they would require to have all the supported libraries compiled for all the compiler versions and possible configurations 😅

**Comment by sridharb1** [comment]
> However, is the new projects/solution working or not yet? Are you still waiting for me to change the paths to the new ones? As I said, I will do it, but unfortunately I have a crashing disk emergency that simply sucked up the last two days. I may be able to work on it tomorrow.

I have updated my exiv2-x86_x64 (https://github.com/sridharb1/exiv2-x86_x64) to use the new directory structure. Please note that I have changed it to contrib/vs2019/solution instead of msvc2019 as I feel the former fits better. Please let me know how this goes.

**Comment by clanmills** [comment]
@sridharb1 I've submitted a PR #1136

We've "lost" my change in README.md.  I've submitted that in the PR.  Can you update your code, please.

```
514 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ git diff contrib/vs2019/LICENSE 
diff --git a/contrib/vs2019/LICENSE b/contrib/vs2019/LICENSE
index a58147e8..81fe56ef 100644
--- a/contrib/vs2019/LICENSE
+++ b/contrib/vs2019/LICENSE
@@ -1,6 +1,6 @@
 MIT License
 
-Copyright (c) 2020 Sridhar Boovaraghavan
+Copyright (c) 2020 Sridhar Boovaraghavan GitHub Handle: sridharb1
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
515 rmills@rmillsmm-local:~/gnu/github/exiv2/0.27-maintenance $ 
```

**Comment by sridharb1** [comment]
> I remain uneasy about the effort required to get the dependencies into the tree.

Yes, it is not easy. However, you doing it independently, albeit with provided instructions, is a good test. I would love to see this go through.
> 
> We've "lost" my change in README.md. I've submitted that in the PR. Can you update your code, please.

Done.

**Comment by clanmills** [comment]
I'll get the dependencies and 100% build this before RC1.  I'll do it in a couple of weeks.  I'd like to work on the ISOBMFF code this week and to continue to sweep changes from master into 0.27-maintenance.  The project's going smoothly.  _He who travels alone, travels quickest._ https://screenfish.net/1917-down-to-gehenna-or-up-to-the-throne/

**Comment by sridharb1** [comment]
@clanmills just to let you know, I have updated my [https://github.com/sridharb1/exiv2-x86_x64.git](url) to add a dependency to brotli because now my curl depends on it.

**Comment by clanmills** [comment]
Thanks for letting me know.  I'll sync your changes into #1136 today.

I won't merge #1136 until I do the work to pull in and test and build the whole tree - and run the test suite on the resulting build.

By the way, you have write access to #1136.  If you feel "git happy", you're welcome to update it.

**Comment by clanmills** [comment]
8b6c70e

**Pull request merged**
