### PR TITLE
Fix_1372_env_vars_0.27

### LINKED ISSUE #1372: Support EXIV2 Environment Strings in tests/bash_tests
The following environment strings are documented in README.md and should be support in test/bash_tests/*

| Variable        | Default | Platforms | Purpose |
|:--                 |:--        |:--     |:-- |
| EXIV2_BINDIR       | **\<exiv2dir\>/build/bin** | All Platforms | Path of built binaries (exiv2.exe) |
| EXIV2_PORT         | **12762**<br>**12671**<br>**12760**  | Cygwin<br>MinGW/msys2<br>Other Platforms | Test TCP/IP Port   |
| EXIV2_HTTP         | **http://localhost**  | All Platforms | Test http server   |
| EXIV2_ECHO         | _**not set**_ | All Platforms | For debugging Bash scripts |
| VALGRIND           | _**not set**_ | All Platforms | For debugging Bash scripts |
| VERBOSE            | _**not set**_ | All Platforms | Causes make to report its actions |
| PATH<br>DYLD\_LIBRARY\_PATH<br>LD\_LIBRARY\_PATH    | $EXIV2\_BINDIR/../lib | Windows<br>macOS<br>Other platforms | Path of dynamic libraries |

The Variable EXIV2\_PORT or EXIV2\_HTTP can be set to None to skip http tests.  The http server is started with the command `python3 -m http.server $port`.  On Windows, you will need to run this manually _**once**_ to authorise the firewall to permit python to use the port.

### PR DESCRIPTION
**Pull request by LeoHsiao1**
This PR is a response to #1372.

### CODE REVIEW

**Comment by LeoHsiao1** [comment]
This is the effect of the variable EXIV2_ECHO:
```sh
leo@Leo:/mnt/d/1/exiv2/tests$ export EXIV2_ECHO=True
leo@Leo:/mnt/d/1/exiv2/tests$ python3 runner.py -v bash_tests/
addmoddel_test (testcases.TestCases) ... ++ /mnt/d/1/exiv2/build/bin/addmoddel exiv2-empty.jpg
++ /mnt/d/1/exiv2/build/bin/exiv2 -pv exiv2-empty.jpg
ok
```

I still don't know how the variable `VERBOSE` works.
And since you already have the variable `EXIV2_ECHO`, do you need a variable `VERBOSE`?

**Comment by clanmills** [comment]
VERBOSE is part of the world of `make`.  So when a user does `$ make tests VERBOSE=1` then expect the tests to run and report lots of information.  In particular the argument --verbose should be assumed by `python3 runner.py`.

EXIV2_ECHO is probably a 10 year old mistake by me.  Perhaps I should have used VERBOSE.  I didn't think of doing that when I added EXIV2_ECHO.

EXIV2_ECHO should cause the test suite to echo every command (whether VERBOSE is set or not).  It's should be very easy to implement.  In tests, it's respected in functions.source runTest().  You can do something similar in BT.Executer().

**Comment by LeoHsiao1** [comment]
When executing `make python_tests VERBOSE=1`, the variable `EXIV2_ECHO` is enabled. The operation effect is as follows:
```sh
leo@Leo:/mnt/d/1/exiv2/build$ make python_tests VERBOSE=1
...
addmoddel_test (bash_tests.testcases.TestCases) ... 
++ /mnt/d/1/exiv2/build/bin/addmoddel exiv2-empty.jpg
++ /mnt/d/1/exiv2/build/bin/exiv2 -pv exiv2-empty.jpg
ok
...
```

**Comment by clanmills** [comment]
@LeoHsiao1 Can you set --verbose in runner.py when VERBOSE is in the environment.  It's something like (about line 65):

```python
    args          = parser.parse_args()
    args.verbose |=  "VERBOSE" in os.environ
    conf_file     = args.config_file[0]
    DEFAULT_ROOT  = os.path.abspath(os.path.dirname(conf_file))
    system_tests.set_debug_mode(args.debug)
    system_tests.configure_suite(conf_file)
```

Then we can simplify test/Makefile:

```make
python_tests:
	@echo
	@echo ---- Running python_tests ----
	@echo
	@echo bash -c ' . functions.source ; cd ../tests ; if [ ! -z $$VERBOSE ]; then verbose=--verbose ;fi ; python3 runner.py $$verbose '
	@bash -c ' . functions.source ; cd ../tests ; if [ ! -z $$VERBOSE ]; then verbose=--verbose ;fi ; python3 runner.py $$verbose '
```

to be:
```make
python_tests:
	@echo
	@echo ---- Running python_tests ----
	@echo
	@echo    'cd ../tests ; python3 runner.py'
	@bash -c 'cd ../tests ; python3 runner.py'
```

When you've update the PR with those changes working, I'll review the other changes in the PR.

**Comment by LeoHsiao1** [comment]
I've simplified the makefile.
The variables EXIV2_ECHO and VERBOSE seem to need to be kept only one.

**Comment by clanmills** [comment]
Oh, Gosh.  This isn't your best work.  I can see you haven't understood what I want here.  I've fixed makefile and VERBOSE.  However, every existing tests fails.  It has something to do with the '++ ' that you're adding to every command.  VALGRIND is hardly ever set.

```
======================================================================
ERROR: test_run (bugfixes.github.test_CVE_2017_1000126.TestCvePoC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rmills/gnu/github/exiv2/0.27-maintenance/tests/system_tests.py", line 588, in test_run
    proc = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '++'
```



Have you built and run the tests on 0.27-maintenance.  It behaves something like this:

```bash
$ cd build
$ make python_tests
.........s.......s.............................................s................................................ss...................
171 tests run in 3.02 seconds (5 skipped)
```
When VERBOSE is set:
```bash
$ cd build
$ make python_tests VERBOSE=1
addmoddel_test (bash_tests.testcases.TestCases) ... ok
conversions_test (bash_tests.testcases.TestCases) ... ok
....
171 tests run in 3.02 seconds (5 skipped)
```

When VERBOSE and EXIV2_ECHO are set:

```bash
$ cd build
$ make python_tests VERBOSE=1
addmoddel_test (bash_tests.testcases.TestCases) ...
/Users/rmills/gnu/github/exiv2/0.27-maintenance/build/bin/addmoddel exiv2-empty.jpg
ok
conversions_test (bash_tests.testcases.TestCases) ... 
/Users/rmills/gnu/github/exiv2/0.27-maintenance/build/bin/exiv2 -pv exiv2-empty.jpg
ok
....
171 tests run in 3.02 seconds (5 skipped)
```

**Comment by LeoHsiao1** [comment]
Eh, my last commit [e0486ec063](https://github.com/Exiv2/exiv2/pull/1377/commits/e0486ec063172d955ae6884c121f27fb6f58122b) yesterday has already achieved this effect.
I thought you wanted to go to verbose mode by default when `make tests`, so I changed the code today.

**Comment by LeoHsiao1** [comment]
Anyway, the variables EXIV2_ECHO and VERBOSE are now supported, you just need to modify the Makefile.

**Comment by LeoHsiao1** [comment]
For now you can use these commands:
```sh
leo@Leo:/mnt/d/1/exiv2/tests$ python3 runner.py 
.
```

```sh
leo@Leo:/mnt/d/1/exiv2/tests$ python3 runner.py -v
addmoddel_test (bash_tests.testcases.TestCases) ... ok
```

```sh
leo@Leo:/mnt/d/1/exiv2/tests$ VERBOSE=1 python3 runner.py -v
addmoddel_test (bash_tests.testcases.TestCases) ... 
++ /mnt/d/1/exiv2/build/bin/addmoddel exiv2-empty.jpg
++ /mnt/d/1/exiv2/build/bin/exiv2 -pv exiv2-empty.jpg
ok
```

```sh
leo@Leo:/mnt/d/1/exiv2/tests$ EXIV2_ECHO=1 python3 runner.py -v
addmoddel_test (bash_tests.testcases.TestCases) ...
++ /mnt/d/1/exiv2/build/bin/addmoddel exiv2-empty.jpg
++ /mnt/d/1/exiv2/build/bin/exiv2 -pv exiv2-empty.jpg
ok
```

**Comment by clanmills** [comment]
@LeoHsiao1 There's something very broken here.  Can you take a fresh copy of the code and run python_tests.

Every test in bugfixes fails with `FileNotFoundError: [Errno 2] No such file or directory: '++'`

```bash
520 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/build $ make python_tests

---- Running python_tests ----

bash -c cd ../tests; python3 runner.py --verbose
addmoddel_test (bash_tests.testcases.TestCases) ... ok
conversions_test (bash_tests.testcases.TestCases) ... ok
crw_test (bash_tests.testcases.TestCases) ... ok
exifdata_test (bash_tests.testcases.TestCases) ... ok
exiv2_test (bash_tests.testcases.TestCases) ... ok
geotag_test (bash_tests.testcases.TestCases) ... ok
icc_test (bash_tests.testcases.TestCases) ... ok
image_test (bash_tests.testcases.TestCases) ... ok
io_test (bash_tests.testcases.TestCases) ... Serving HTTP on 127.0.0.1 port 12760 (http://127.0.0.1:12760/) ...
127.0.0.1 - - [22/Oct/2020 14:57:51] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "GET /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "GET /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "HEAD /Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "GET /Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "HEAD /Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "GET /Reagan.tiff HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "HEAD /exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:51] "GET /exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:52] "HEAD /exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:52] "GET /exiv2-bug922a.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:52] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:52] "GET /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:52] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:52] "GET /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:52] "HEAD /table.jpg HTTP/1.0" 200 -
127.0.0.1 - - [22/Oct/2020 14:57:52] "GET /table.jpg HTTP/1.0" 200 -
ok
iptc_test (bash_tests.testcases.TestCases) ... ok
iso65k_test (bash_tests.testcases.TestCases) ... ok
modify_test (bash_tests.testcases.TestCases) ... ok
nls_test (bash_tests.testcases.TestCases) ... ok
path_test (bash_tests.testcases.TestCases) ... ok
png_test (bash_tests.testcases.TestCases) ... ok
preview_test (bash_tests.testcases.TestCases) ... ok
stdin_test (bash_tests.testcases.TestCases) ... ok
stringto_test (bash_tests.testcases.TestCases) ... ok
tiff_test (bash_tests.testcases.TestCases) ... ok
version_test (bash_tests.testcases.TestCases) ... ok
webp_test (bash_tests.testcases.TestCases) ... ok
write2_test (bash_tests.testcases.TestCases) ... ok
write_test (bash_tests.testcases.TestCases) ... ok
xmpparser_test (bash_tests.testcases.TestCases) ... ok
test_run (bugfixes.github.test_CVE_2017_1000126.TestCvePoC) ... ERROR
test_run (bugfixes.github.test_CVE_2017_1000127.TestPoC) ... ERROR
test_run (bugfixes.github.test_CVE_2017_11336.TestCvePoC) ... ERROR
....

======================================================================
ERROR: test_run (bugfixes.github.test_CVE_2017_1000126.TestCvePoC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rmills/gnu/github/exiv2/0.27-maintenance/tests/system_tests.py", line 588, in test_run
    proc = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '++'
```

**Comment by LeoHsiao1** [comment]
This is because I set the default value of the variable VALGRIN incorrectly.
I thought it was the prefix symbol displayed before each command. Now it looks like a debugging tool.

**Comment by clanmills** [comment]
Thanks.  That's a lot better.  It's still nor right (but closer).

1.  Don't use --verbose in the makefile **(fix submitted)**
- tests/runner.py detects VERBOSE in the environment.
- so `$ make python_tests` runs in 'quiet' mode.
- so `$ make python_tests VERBOSE=1` runs in 'verbose` mode

2. Don't treat EXIV2_ECHO == VERBOSE **(fix submitted)**

3. I've broken something in the print/echo code
```
535 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance/tests $ env VERBOSE=1 python3 runner.py 

.     
.
. <---- it's putting dots of separate lines.  Somebody's wrongly outputting a `\n`  
.
```

Questions. 
1 Have you dealt with ALL the environment strings.  I don't see anything to set **EXIV2_PORT** correctly on Cygwin or MinGW.  This is very important.  When the build server is builds/tests every platform, it's very important to use different ports for the python web-server.

2 I don't understand your difficulty with **EXIV2_ECHO**.  Can you explain what you think it should do and I'll explain it again.

3 **VALGRIND** is a process wrapper.  It's like gdb.  Don't confuse it with **EXIV2_ECHO**.

4 **UPPERCASE** and **lowercase**.  The config code setting exiv2_echo is **lowercase**.  Is it case insensitive?

**Comment by LeoHsiao1** [comment]
- I thought `EXIV2_ECHO` did the same thing as `VERBOSE`, displaying each command executed as long as the variable were enabled. So my code is as follows:
    ```py
    def run(self):
        # Whether to display the command to execute
        if Config.exiv2_echo or Config.verbose:
            print('++', ' '.join(self.args))

    ```

- I believe these environment variables are already supported across platforms, based on the compatibility of python code.

- All environment variables must be capitalized. However, `tests/suite.conf` stores the value of an environment variable in a lowercase variable, which I follow:
    ```sh
    [ENV]
    exiv2_path: EXIV2_BINDIR
    dyld_library_path: DYLD_LIBRARY_PATH
    ld_library_path: LD_LIBRARY_PATH
    exiv2_http: EXIV2_HTTP
    exiv2_port: EXIV2_PORT
    exiv2_echo: EXIV2_ECHO
    verbose: VERBOSE
    valgrind: VALGRIND
    ```

**Comment by clanmills** [comment]
Ah, right.  We'll get this finished and merged tomorrow.  Good way to finish the week.

Thanks for fixing the mysterious '\n' output.

Dan's config magic:

```
[ENV]
exiv2_http: EXIV2_HTTP
```
is about equivalent to config['exiv2_http'] = os.environ['EXIV2_HTTP'].  Ingenious.  Very elegant.

Several puzzles to discuss:

1. VERBOSE seems to be broken again!

```
$ cd tests
$ python3 runner.py --verbose # works!
$ env VERBOSE=1 python3 runner.py # doesn't
```

2. I'm not convinced you've understood EXIV2_ECHO.  Please run `$ make bash_tests` and `$ make bash_tests EXIV2_ECHO=1` to see what it does.

3. Where are the defaults for EXIV2_PORT for MinGW and Cygwin in your code?

4. Are you updating PATH with EXIV2_BINDIR?

**Comment by clanmills** [comment]
I've fixed VERBOSE. args.verbose==1 when not set and ==2 when set (eh?)  So, puzzles 2), 3), 4) above and we're done!

**Comment by clanmills** [comment]
Let's forget about EXIV2_ECHO.  I've found that very useful for debugging bash scripts.  We now have Visual Code to debug the python scripts.  So let's forget about EXIV2_ECHO.  I'll remove it from README.md at release time.

However you need to fix HTTP_PORT on cygwin and mingw.  Here's the relevant code from test/functions.source.

```base
##
# startHttpServer - power up the python web server
startHttpServer() {
    cd "${testdir}/.."                   # testdir is the tmp output directory
    
    if    [ "$platform" == "cygwin" ]; then dport=12762
    elif  [ "$platform" == "mingw"  ]; then dport=12761
    else                                    dport=12760
    fi

    if [ ! -z $EXIV2_PORT ]; then port=$EXIV2_PORT ; else port=$dport          ; fi
    if [ ! -z $EXIV2_HTTP ]; then http=$EXIV2_HTTP ; else http=http://localhost; fi
    exiv2_url=$http:$port
    python3 -m http.server $port &       # start a background local HTTP server in the "real" test directory
    sleep 2                              # wait for it to init or die!
    exiv2_httpServer=$!
    # ask the server to reply
    echo $exiv2_url status = $(python3 -c "import urllib.request;print(urllib.request.urlopen('$exiv2_url/').status)")
}
```

The variable platform is set as follows:

```bash
        platform=$(runTest exiv2 -vV 2>/dev/null | grep platform=)
```

The command `$ exiv2 -vV` == `$ exiv2 --verbose --version` outputs loads of build information including the `platform=XXX` where XXX==cygwin or mingw on those platforms.

I'm sure there are lots of other ways to detect this.  I chose to use `$ exiv2 -vV`, however it's not the only way.  The benefit of using `$ exiv2 -vV` is that you can debug this without using Windows.

EXIV2_BINDIR is only a question.  I hope it doesn't need any more work.

I hope we can finish this today.  We still have to deal with #1274.  Let's get done on this.  Let's have a week off the python tests and deal with #1274 and #1215 in November.  I want to get on with the book.

**Comment by clanmills** [comment]
I've just realised that HTTP_PORT isn't working correctly on MinGW/msys2 and successfully using 12760.  The bash code to set platform isn't correct.

You don't need to do anything about HTTP_PORT.  Leave it at 12760.  I'll fix README.md at release time.

**Comment by LeoHsiao1** [comment]
- If you remove `EXIV2_ECHO`, how do you control each command that is displayed? Does it also depend on `VERBOSE`?
- I'm going to leave `EXIV2_PORT: 12760` by default, regardless of platform differences.

**Comment by clanmills** [comment]
Please forget about EXIV2_ECHO.  It was useful when the scripts were written in bash because echo is about the only debugging tool we have in bash!

We can't echo the commands in the python scripts.  It doesn't matter.  We can debug python with Visual Code.  

I'm fixing the bash scripts to respect EXIV2_PORT on mingw and cygwin.  

The CI is complaining about something which I'll investigate after lunch.  And then I will approve and merge the PR.  Thank you for working on this.

**Review by clanmills — APPROVED** [review]

**Comment by LeoHsiao1** [comment]
It seems like you start work at 6 a.m.
Haven't had breakfast yet?

**Comment by clanmills** [comment]
I'm often up about 6am.  Do some work and have breakfast about 8.  Alison doesn't like me awake in bed because I read the news on the phone and it wakes her up!  I went back to bed this morning and slept until 10:30!

I usually approach projects by doing big items first and little tasks later.  There are 16 parts of the book "To be written".  I hope to deal with most of them in the next two weeks.  Then complete the 6 big unfinished tasks (image formats, XMP, lens recognition, previews, I/O and updating files).   The whole book has be polished.  I think we're having a week's vacation 4-11 November.   It looks unlikely to be finished this year.

**Pull request merged**
