### PR TITLE
Fix #604 (0.27)

### LINKED ISSUE #604: samples/conntest.cpp and -DEXIV2_ENABLE_CURL=1 is broken
There are several issues with this:

1) We need to use #include <curl/curl.h> when EXIV2_ENABLE_CURL is set
2) We need to link CURL_LIBRARIES to conntest when EXIV2_ENABLE_CURL is set
3) There's a typo in the comment at the top of samples/conntest.cpp

The work-around is to not use CURL and we'll fix this in v0.27.1.

```
605 rmills@rmillsmm:~/gnu/github/exiv2/exiv2/build $ git diff
diff --git a/samples/CMakeLists.txt b/samples/CMakeLists.txt
index a3e491e..46aaa53 100644
--- a/samples/CMakeLists.txt
+++ b/samples/CMakeLists.txt
@@ -90,6 +90,9 @@ endif()
 # ******************************************************************************
 # connection test application
 add_executable(conntest conntest.cpp)
+if ( EXIV2_ENABLE_CURL )
+target_link_libraries( conntest PRIVATE ${CURL_LIBRARIES} )
+endif()
 list(APPEND APPLICATIONS conntest)
 
 # ******************************************************************************
diff --git a/samples/conntest.cpp b/samples/conntest.cpp
index 22fce2c..bcef8d1 100644
--- a/samples/conntest.cpp
+++ b/samples/conntest.cpp
@@ -1,5 +1,5 @@
 // ***************************************************************** -*- C++ -*-
-// con-test.cpp
+// conntest.cpp
 // Tester application for testing the http/https/ftp/ssh/sftp connection
 
 #include <exiv2/exiv2.hpp>
@@ -7,6 +7,10 @@
 #include <iostream>
 #include <cstdlib>
 
+#ifdef EXV_USE_CURL
+#include <curl/curl.h>
+#endif
+
 void httpcon(const std::string& url, bool useHttp1_0 = false) {
     Exiv2::Dictionary response;
     Exiv2::Dictionary request;
606 rmills@rmillsmm:~/gnu/github/exiv2/exiv2/build $ 
```

### PR DESCRIPTION
**Pull request by piponazo**
Same than #656 for 0.27.

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
Thanks for working on this.  For sure, I'm glad you know your way around the conan magic.

I thought you said that curl should be installed with platform tools (apt, source, etc).  However it appears that you have updated conan and cmake to operate correctly concerning curl.

**Comment by piponazo** [comment]
For the dependencies we always have the option to bring them as system pacakges, with conan or compile them manually. Conan should be the easiest option, but there are still some corner cases that are difficult to deal with. In this particular case, it seems that the travis Mac OSX images already provided the system curl libraries, and if we also bring curl with conan we end up having these linking errors:

```
AssertionError: 'dyld: Library not loaded: libcurl.4.dylib[198 chars].0\n' != ''

- dyld: Library not loaded: libcurl.4.dylib

-   Referenced from: /Users/travis/build/Exiv2/exiv2/build/bin/tiff-test

-   Reason: Incompatible library version: tiff-test requires version 10.0.0 or later, but libcurl.4.dylib provides version 7.0.0

 : Standard error does not match
```
That's why I decided to rely on the system package for OSX.

**Comment by piponazo** [comment]
In case you see me playing a bit more in this branch, it is because the linking started to fail in the Linux-clang case due to some gtest stuff. I'm upgrading the travis images to make them more similar to master. I will only merge once everything is green.

**Comment by clanmills** [comment]
Good Morning.  Good Luck with clang/linux.

That's curious about curl 7 and 10 on Travis.

The version in /usr/lib/libcurl is 9 (compatible with 7).  I believe Apple put that on the machine.

```
940 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ otool -L /usr/lib/libcurl.dylib | grep curl
/usr/lib/libcurl.dylib:
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
941 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/build $ 
```

It feels as though you've built with 10 (courtesy of conan) and trying to use 7 (courtesy of Apple) at run-time.   Perhaps you need to set DYLD_LIBRARY_PATH to be certain that you use Conan's libcurl.dylib at run-time.

I'll build this on the Mac with conan.

**Pull request merged**
