### PR TITLE
optimize toAscii

### PR DESCRIPTION
**Pull request by neheb**
Construct string in lambda to help the compiler optimize the generated code. Also replace transform with normal loop.

### CODE REVIEW

**Comment by neheb** [comment]
so uhhh, this is funny.

With this for loop, the else if branch is never hit. The reason it's optimized now is because GCC gets rid of it while the tests don't fail here.

@kevinbackhouse

**Comment by neheb** [comment]
oh uhhhh, I didn't need to get rid of std::transform. GCC handles it just fine.

https://godbolt.org/z/4cvrfr6hh
https://godbolt.org/z/Go9bzac9P

The important part is c == 0 is not tested for.

**Comment by neheb** [comment]
now notice if you remove the first std::replace, tests still pass.

**Review by kmilos — APPROVED** [review]
LGTM

**Pull request merged**
