### PR TITLE
Adapted README.md to better render on Github

### PR DESCRIPTION
**Pull request by D4N**
With #113 I realized that the README.md file does not render very well on Github. E.g. some links were not rendered as links and the tables had all content in just in one line.

I have also added explicit references to files & directories as links. Unfortunately, I had to hardcode the urls for that to the master branch on Github. This could lead to surprises when clicking on links in forks or other branches. To my knowledge there is no solution to this other than not linking, as Github does not handle links between directories & files at all (README.md is also shown in a 'directory' when simply opening the repository).

The proposed state can be seen [here](https://github.com/D4N/exiv2/tree/readme_improvements).

### CODE REVIEW

**Review by piponazo — APPROVED** [review]
Thanks for updating this!

The file was not a markdown file before (I think I was the one changing the extension few weeks ago), and that's why there were so many things to fix here :+1:

**Comment by D4N** [comment]
No problem. Whats your opinion on the links? I am a little torn here, since it might cause surprises for people who view the Readme in another branch or fork. But then again, I think the odds of that actually happening are pretty low.

**Comment by piponazo** [comment]
Did you check if you can use relative paths in those links? 

If it does not work, I do not think it is a big issue. The files should always be on Exiv2/Exiv2/master  :)

**Comment by D4N** [comment]
Yes, I tried it. Github's markdown supports relative links from files to
files and from directories to directories but not from files to
directories (and vice-versa). The problem here is, that README.md can be
viewed as a file or as a directory (when you open the repository) and
thus with relative links, only half of them would work at different
times (which I think would be extremely confusing).

**Comment by D4N** [comment]
Any objections to merging this?

**Review by clanmills — APPROVED** [review]
Looks good to me.  Don't forget to add Dan, Luis and Michal to the credits in the mast-head.  We could remove Marco, Gilles and Volker as we seldom hear from them.  In fact, I don't even know who Marco is!

**Pull request merged**
