### PR TITLE
conversions to make_unique

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by piponazo** [comment]
I cannot explain why but I tried to run this locally and it is also failing on my Windows setup.

**Comment by neheb** [comment]
seems to be some type problem. No clue.

**Comment by neheb** [comment]
Early speculation: the MSVC 7.1 bug comment might be a hint as to what's going wrong. I notice only one of the TiffBinaryArray functions uses it.

**Review by piponazo — APPROVED** [review]
CI is happy now 👍

**Comment by neheb** [comment]
Yeah. TiffBinaryArray can be handled later.

**Pull request merged**
