### PR TITLE
027 update conan

### PR DESCRIPTION
**Pull request by piponazo**
Trying to update conan to 1.17 on appveyor. This should fix automatically the cache corruption issues observed in the last appveyor builds.

### CODE REVIEW

**Comment by piponazo** [comment]
@D4N @clanmills I was trying to update conan in appveyor, but the builds keep failing ... Maybe if you observe the changes here you can see something I am missing ... I have no clue why the recipe is not found:

```
ERROR: Failed requirement 'zlib/1.2.11@conan/stable' from 'conanfile.py'
ERROR: Recipe not found: 'zlib/1.2.11@conan/stable'
Command exited with code 1
```
The conan remotes seem to be correctly configured, and locally the things work 😑

**Comment by clanmills** [comment]
I'll run builds on my machines with conan 1.17 and give you an update.

**Comment by clanmills** [comment]
Looks OK on rmillsmm-w7:
```
C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\build>conan --version
Conan version 1.17.2

C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\build>cd ..

C:\Users\rmills\gnu\github\exiv2\0.27-maintenance>mkdir another_build

C:\Users\rmills\gnu\github\exiv2\0.27-maintenance>cd another_build

C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\another_build>conan install .. -o webready=True --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
webready=True
[build_requires]
[env]

libcurl/7.64.1@bincrafters/stable: Not found in local cache, looking in remotes...
libcurl/7.64.1@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 234/234 [00:00<00:00, 7.41kB/s]
Downloading conanfile.py: 100%|##########| 18.1k/18.1k [00:00<00:00, 398kB/s]
Downloading conan_export.tgz: 100%|##########| 764/764 [00:00<?, ?B/s]
Decompressing conan_export.tgz: 100%|##########| 764/764 [00:00<00:00, 49.8kB/s]
libcurl/7.64.1@bincrafters/stable: Downloaded recipe revision 0
OpenSSL/1.1.1b@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.1.1b@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 58.0/58.0 [00:00<00:00, 3.77kB/s]
Downloading conanfile.py: 100%|##########| 26.0k/26.0k [00:00<00:00, 1.70MB/s]
OpenSSL/1.1.1b@conan/stable: Downloaded recipe revision 0
conanfile.py: Installing package
Requirements
    Expat/2.2.6@pix4d/stable from 'conan-center' - Cache
    OpenSSL/1.1.1b@conan/stable from 'conan-center' - Downloaded
    gtest/1.8.1@bincrafters/stable from 'conan-center' - Cache
    libcurl/7.64.1@bincrafters/stable from 'conan-center' - Downloaded
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    Expat/2.2.6@pix4d/stable:ceec4f117b6216dfc9504a7d161aedbdd5bd53ac - Cache
    OpenSSL/1.1.1b@conan/stable:606fdb601e335c2001bdf31d478826b644747077 - Download
    gtest/1.8.1@bincrafters/stable:a35f8fa327837a5f1466eaf165e1b6347f6e1e51 - Cache
    libcurl/7.64.1@bincrafters/stable:ae6191bc1194317ff7cdbc84d4d302ab49975618 - Download
    zlib/1.2.11@conan/stable:6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7 - Cache

Expat/2.2.6@pix4d/stable: Already installed!
gtest/1.8.1@bincrafters/stable: Already installed!
zlib/1.2.11@conan/stable: Already installed!
OpenSSL/1.1.1b@conan/stable: Retrieving package 606fdb601e335c2001bdf31d478826b644747077 from remote 'conan-center'
Downloading conanmanifest.txt: 100%|##########| 6.38k/6.38k [00:00<?, ?B/s]
Downloading conaninfo.txt: 100%|##########| 1.35k/1.35k [00:00<?, ?B/s]
Downloading conan_package.tgz: 100%|##########| 8.79M/8.79M [00:03<00:00, 2.96MB/s]
Decompressing conan_package.tgz: 100%|##########| 8.79M/8.79M [00:01<00:00, 7.86MB/s]
OpenSSL/1.1.1b@conan/stable: Package installed 606fdb601e335c2001bdf31d478826b644747077
OpenSSL/1.1.1b@conan/stable: Downloaded package revision 0
libcurl/7.64.1@bincrafters/stable: Retrieving package ae6191bc1194317ff7cdbc84d4d302ab49975618 from remote 'conan-center'
Downloading conanmanifest.txt: 100%|##########| 1.08k/1.08k [00:00<00:00, 73.2kB/s]
Downloading conaninfo.txt: 100%|##########| 1.81k/1.81k [00:00<?, ?B/s]
Downloading conan_package.tgz: 100%|##########| 715k/715k [00:00<00:00, 1.06MB/s]
Decompressing conan_package.tgz: 100%|##########| 715k/715k [00:00<00:00, 4.26MB/s]
libcurl/7.64.1@bincrafters/stable: Package installed ae6191bc1194317ff7cdbc84d4d302ab49975618
libcurl/7.64.1@bincrafters/stable: Downloaded package revision 0
conanfile.py: Generator cmake created conanbuildinfo.cmake
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
conanfile.py imports(): Copied 4 '.dll' files: gmock_main.dll, gtest_main.dll, gtest.dll, gmock.dll

C:\Users\rmills\gnu\github\exiv2\0.27-maintenance\another_build>
```

**Comment by piponazo** [comment]
It seems that I found the root of the issues, and it is again a mix of corner cases between some erroneous binary builds in the conan-server for the versions we are using in Appveyor and Travis CI. After some trial-and-error commits I could find a configuration that works for all the platforms. I squashed all the commits, and I expect to see all the CI checks green in few hours.

**Comment by clanmills** [comment]
Well done, Luis.  I know you've worked hard to get to the bottom of this.  Thanks for digging in.

Do we have to do anything to get #967 into the mix?  I will ship 0.27.2 this week.  Then work on the book in August.  "dot 3" in September.  Life is good!

BTW, I might have recruited a technical writer to work on our documentation.  He's a retired engineer and did courses on English at the University of Arkansas after he retired.   This is the person with whom I have cooperated on the libintl/mac horror which is caused by installing Microsoft Visual Studio for Mac.  It installs a framework which includes libintl which interferes with our build.  Everyday we learn new things.

**Comment by piponazo** [comment]
I already rebased #967, but appveyor keeps complaining about other things now ... I'll keep investigating

**Pull request merged**
