### PR TITLE
[Backport 0.28] Fix building for ios

### PR DESCRIPTION
**Pull request by m-kuhn**
Backport of https://github.com/Exiv2/exiv2/pull/2761

### CODE REVIEW

**Review by kmilos — APPROVED** [review]
Thanks

**Comment by m-kuhn** [comment]
Is there an ETA for 0.28.1?

**Comment by kmilos** [comment]
> Is there an ETA for 0.28.1?

@Exiv2/exiv2

**Comment by stevendinggang** [comment]
> @Exiv2/exiv2

Hi, I would like to ask, does this branch do iOS compatibility changes? Can you test it locally?

**Comment by nehaljwani** [comment]
> > Is there an ETA for 0.28.1?
> 
> @Exiv2/exiv2

I can on work on it. ETA: this weekend (hopefully, 😅)

**Pull request merged**
