### PR TITLE
Strip XMP raw packet before decoding (backport #2133)

### PR DESCRIPTION
**Pull request by kmilos**
(cherry picked from commit eb49d66caf485cd165bc5647289928aa8386261f)

### CODE REVIEW

**Comment by piponazo** [comment]
Hum, there are some jobs failing here ... I wonder if the CI configuration has changed a lot between `main` and `0.27`. Give me some time (days) to take a look there and check the status of CI on 0.27. Probably with some minor effort I can bring it back to a normal state.

**Comment by kmilos** [comment]
Yeah, only the Windows jobs fail, seems to be conan related, again 😕

**Comment by clanmills** [comment]
Let me look at this.  I confess that I like Windows.  Visual Studio + MFC are awesome.  Well, in the 90s they were.  I haven't used them for 20 years.

I'm gonna buy a Mac Studio with the M1-Max (the less expensive version).

**Comment by piponazo** [comment]
@clanmills I am already working at it. I hope that by updating the CI workflows with the latest changes done in `main` I can solve the situation easily.

**Comment by piponazo** [comment]
@kmilos try to rebase your branch and hopefully the CI will turn green after we merged #2140

**Review by piponazo — APPROVED** [review]
LGTM!

**Comment by clanmills** [comment]
Thank You: @kmilos and @piponazo.

**Pull request merged**
