### PR TITLE
Check bounds of month and day

### LINKED ISSUE #851: Denial of service in XMPUtils AdjustTimeOverflow()
There is a denial of service bug in the loop at [XMPUtils.cpp:245](https://github.com/Exiv2/exiv2/blob/c0ecc2ae36f34462be98623deb85ba1747ae2175/xmpsdk/src/XMPUtils.cpp#L245) because `time->day` can be very large. This loop adjusts out-of-bounds days by subtracting one month at a time. Since the type of `time->day` is `long`, this can take a very long time.

issue_851_poc

Reproducible on the 0.27-maintenance branch ([c0ecc2a](https://github.com/Exiv2/exiv2/commit/c0ecc2ae36f34462be98623deb85ba1747ae2175)):

```
exiv2 issue_851_poc.jpg
```

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes #851.

It looks like somebody wanted to add this check before, but they couldn't due to "bug 1269463" (see comments in the code). None of the tests fail, so I am assuming that "bug 1269463" is no longer a problem.

### CODE REVIEW

**Comment by D4N** [comment]
Uh, guys, this is a bug in the xmpsdk, we shouldn't be fixing that. Instead we should upgrade to the latest edition. Or at least this shouldn't propagate into master.

@piponazo You did manage to build exiv2 with the latest xmpsdk, right?

**Comment by piponazo** [comment]
That's a good point @D4N . Yes, I even think we have some instructions in the README or README-CONAN to build with the latest version of xmpsdk, although it was marked as experimental. 

Although in principle I agree with your comment, @kevinbackhouse has already done the work (probably because he was not aware about XMPSDK being a 3rd party library) and I think we do not loose anything for accepting his contribution.

I do not see ourselves dropping the XMPSDK embedded version and using the external dependency in short-mid terms. So I would welcome any security fix in that area.

**Comment by D4N** [comment]
We can patch it for 0.27, but we should really upgrade xmpsdk on master too.

**Comment by kevinbackhouse** [comment]
Where does XMPSDK come from? I might need to file an issue with them if they haven't already fixed it.

**Comment by D4N** [comment]
Xmpsdk comes from adobe: https://www.adobe.com/devnet/xmp.html

But upgrading it is quite a piece of work, as it will require fixing all the tests that  depend on the output from the xmpsdk, as that changes with each version.

**Review by piponazo — APPROVED** [review]

**Pull request merged**
