### PR TITLE
Added new fujifilm tags

### PR DESCRIPTION
**Pull request by joef42**
+ Shadow Tone
+ Highlight Tone
+ D Range Priority
+ D Range Priority Auto
+ D Range Priority Fixed
+ Rating

### CODE REVIEW

**Comment by D4N** [comment]
Hi @joggelxx, thanks for this PR! The changes look good to me, however I'd like to add some regression tests. Could you either add these yourself or provide us with some images which utilize these newly added tags? I'd add a regression test myself then.

**Comment by joggelxx** [comment]
Hi D4N,
I can take care of that. Could you point me to an example how to write this test?

**Comment by D4N** [comment]
> Hi D4N,
> I can take care of that. Could you point me to an example how to write this test?

Sorry for the long radio silence. You can find some examples in the `tests/` subdirectory, for example `tests/bugfixes/github/test_pr_992.py`. The documentation of the test syntax & API is written down in `tests/doc.md`.

**Comment by joggelxx** [comment]
Hi @D4N,
here are the tests and some fixes that came up along the way ;). Please have a look and let me know if there is something else I can improve.

**Review by piponazo — APPROVED** [review]
The changes and tests look good. Thanks for the contribution!

**Comment by clanmills** [comment]
@joggelxx Thank You for your contribution.

I have merged this into the 0.27-maintenance branch and they will ship in Exiv2 v0.27.3 which is scheduled for 2020-06-30.  They will be included in Exiv2 v0.27.3 RC1 which will ship on 2020-04.30.  https://github.com/Exiv2/exiv2/issues/1018#issuecomment-604539346

**Pull request merged**
