### PR TITLE
correct identification for Tamron SP 24-70mm G2 A032

### PR DESCRIPTION
**Pull request by nulllinie**
SP 24-70mm F/2.8 Di VC USD G2 has a different identcode
from exiftool: Composite:LensID CE 47 37 5C 25 25 DF 0E
example image (Nikon raw) with this lens:
[exampleImage.zip](https://github.com/Exiv2/exiv2/files/6604378/exampleImage.zip)

### CODE REVIEW

**Comment by hassec** [comment]
Hi @nulllinie, thanks a lot for the report! :+1: 

If you look at the supported lenses in exiftool [here](https://exiftool.org/TagNames/Nikon.html), you'll actually see that exiftool has the following line on that site:
```
'CE 47 37 5C 25 25 DF 4E'  = Tamron SP 24-70mm f/2.8 Di VC USD G2 (A032)
```
So exiv2 and exiftool both expect a "4E" instead of a "0E".   
This value corresponds to the raw hex value for the `LensType`.   

I've found a sample picture from a review of the Lens shot with a nikon camera where exiftool and exiv2 report a `LensType` of "4E".   

So something must have changed, because your picture definitely has a value of "0E" for `LensType`.     
Could you post the model of your camera, and also maybe the firmware version of camera and lens?   

But the above means, that we can't just change the old entry to reflect the new value because it would break exiv2 for existing pictures. 
You can see in the list you changed, that many lenses already have duplicated entries with slightly different values. 
Could you modify your PR, and just duplicate the existing line and make your change to the new entry?

**Comment by nulllinie** [comment]
Hi @hassec , 
thanks for your quick response. i will do the duplicate entry and testcase, but this will take some days, weekend is over ;-)
The info you asked for:
Nikon D7000
Firmware: A 1.04, B 1.05, L 2.016
Lens: No info about firmeware, but bought 3 weeks ago, according [Tamron website](https://www.tamron.jp/en/support/popup/a032.html#NI)  the lens firmware should be the current one - unless the lense is older than three years ...

**Comment by nulllinie** [comment]
Hi @hassec 
can u send me / port an link to the sample picture from a review you found? Then i will try to make a testcase for this too, then both lenses are covered.

**Comment by hassec** [comment]
Hi @nulllinie for now don't worry about the image I mentioned, as I'm not sure if we can simply include it in the test images. (Copyright and all...)

**Review by hassec — APPROVED** [review]
LGTM! 

Thanks a lot  @nulllinie  for taking the time to provide the fix + testcase :+1:

**Pull request merged**
