### PR TITLE
Remove non CMake configuration code

### LINKED ISSUE #182: Too many options for building for MSVC
Hi there!
  I've finally managed to build exiv2 under windows 8 and MSVC 2017, by simply using the `CMakeLists.txt` located in the project root directory. But before trying this, I spent some time reading the [CMake readme file](https://github.com/Exiv2/exiv2/blob/master/README-CMAKE) which instead of clarifying the situation made it all more confused. :-)
I tried the `contrib/cmake/msvc` and the `contrib/build/msvc` solutions, which were just a waste of time as I couldn't get them to work.

Since the `CMakeLists.txt` from the project root directory works like a charm, why are these other solutions needed? If they have their reason to exist, I would anyway suggest to update the readme file to recomment the MSVC users to use the main `CMakeLists.txt`, and clearly specify under which cases the other two methods must be used instead.

### PR DESCRIPTION
**Pull request by piponazo**
As discussed during the team meeting, the idea for 0.27 RC1 would be to remove the autotools and msvc files and just rely in CMake + Conan for building the project in all the platforms.

In #335 I am doing a first big change to the project that will break the configuration/compilation of Exiv2 with the autotools and msvc scripts. Therefore I think it is the right moment to take this step.

Note that this PR will fix #182

### CODE REVIEW

**Review by clanmills — APPROVED** [review]

**Comment by D4N** [comment]
Could you also update the Readme? Currently it explains how to use autotools and not cmake.

**Comment by clanmills** [comment]
I'll look at README.md and all the documentation.  I've been very busy with README-CONAN.md for the last couple of days.  We have a lot of family/home stuff this weekend.  I'll get it submitted on Monday.

**Comment by clanmills** [comment]
I'll start looking at README.md later today (Monday).  @piponazo has done good work with CMake/doxygen.

I'm wondering what (if anything) will remain in the config/ directory.  Perhaps `config/` should only contain subdirectories such as `config/cmake/` and `config/doxygen/`  In ancient times, autotools, CMake and  doxygen files were submitted to a single `config/` directory.  Is now a good time to rationalise?

**Comment by piponazo** [comment]
@clanmills I also thought about that. Right now the `config` folder contains things about: autotools, CMake and doxygen. Once we remove the autotools stuff, I would actually propose to rename the `config` folder to `cmake`, since more of the files there will be used by CMake to configure the project or perform different tasks related with documentation, consumption of the library (.pc files), etc.

I noticed in the last years that many open source projects are following this convention of having a CMake folder where to put all the files processed by CMake. Just two examples:

https://github.com/opencv/opencv
https://github.com/danmar/cppcheck

**Comment by clanmills** [comment]
We agree.

If everything in `config/` relates to CMake, let's rename it `cmake/`.  If there are several tools to be configured, let's have `config/cmake`, `config/doxygen` or whatever.  Let's keep down the number of "top level" directories small.  Examples: `src/`, `include/`, `xmpsdk/`, `samples/`

I'm updating README.md and then I will look at other documents.  I'm wondering if we should put all documentation into doxygen.  Over the years we've accumulated different sources of information such as Redmine, GitHub, REAME-this-and-that.  And different formats (text files, mark-down, generated HTML, possibly others).   Perhaps we focus on a single source of documentation.  Doxygen -> HTML

**Comment by piponazo** [comment]
@clanmills I also have the feeling that we have too many sources of information. However for the quick introduction documents I still think it's a good idea to have them in a simple Markdown documents that can be read with any text editor. 

At some point we could move more documentation to Doxygen, but in order to take that step, we should find a reliable way of generating & publishing the Doxygen documentation so that it can be easily accessible from a website. Otherwise the users would need to configure the project and generate the documentation by themselves.

**Comment by D4N** [comment]
> At some point we could move more documentation to Doxygen, but in order to take that step, we should find a reliable way of generating & publishing the Doxygen documentation so that it can be easily accessible from a website.

GitLab pushes the current documentation from the master branch to https://d4n.gitlab.io/exiv2/.

**Comment by piponazo** [comment]
@D4N Cool! That's what I was looking for. However there is something wrong there ... the main page should contain more information. Something like this:

screenshot_2018-06-08_13-14-59

**Review by D4N — APPROVED** [review]
42k slocs less!

**Pull request merged**
