### PR TITLE
constructor fixes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
Seems MSVC's pragma once is totally broken.

**Comment by piponazo** [comment]
> Seems MSVC's pragma once is totally broken.

I guess you were looking at something else, right? I never had problems with `#pragma once` in any of the main compilers (gcc, clang, msvc)

**Review by piponazo — APPROVED** [review]
Thanks!

**Comment by neheb** [comment]
I moved the default line from the cpp file to hpp file for the AnyError stuff and got a linker error under MSVC. AppVeyor’s history has the details.

**Pull request merged**
