### PR TITLE
Fix wrong make test

### PR DESCRIPTION
**Pull request by a4865g**

### CODE REVIEW

**Review by kevinbackhouse — APPROVED** [review]

**Comment by clanmills** [comment]
The test code in both 'main' and 0.27-maintenance has been changed substantially since I last revised README.md for 0.27.4.  Changing "make tests" to "make test" is a valid change, however I think a more thorough review should be conducted.

I was very surprised this morning to discover that the test code has been changed on 0.27-maintenance.  I can only assume/guess that has migrated to 0.27-maintenance into on the back of the recent CI changes.

I'll investigate this today.  I think we should hold off merging this change until I have studied this.

**Review by clanmills — CHANGES_REQUESTED** [review]
The test code has been quite substantially changed since README.md was written.  I think there are many more changes required to bring the code and documentation into alignment.  I'll look at this today (Thursday 2021-12-16).

**Review by clanmills — APPROVED** [review]
The test code on 'main' uses CTest.    The correct way to execute ctest is `$ cmake --build . --target test`  (test singular).  The change in this PR is correct.

The test code in 0.27.5 and earlier uses custom targets such as tests, bash_tests, python_tests, unit_test and version_test to execute the test code.  While working on fix_conan_ci_luis afee6cc58, Luis has introduced CTest on the 0.27-maintenance branch.

Tomorrow, I will update README.md on branch 0.27-maintenance to discuss CTest.  I will ask Luis to review my changes.

At some future date, main/README.md should be synced with changes I submit to 0.27-maintenance.  It makes sense to accept this small change at this time, although README.md will require further maintenance in future.

**Review by clanmills — CHANGES_REQUESTED** [review]
The change here is too simple.  The table in _4 Running the test suite_ has the code `$ make tests` and `cmake –build . –target tests` which should also be changed.

My primary concern here is that the documentation discusses the 0.27-maintenance targets tests, bash_tests, python_tests, unit_test and version_test.  These targets are no longer in this branch as the test scripts are now executed by ctest.

As the ctest code was submitted to branch 0.27-maintenance last week, I will submit a PR to 0.27-maintenance with changes to README.md.

The documentation in README.md should be comprehensively updated.  This one line change is correct and insufficient.

**Comment by clanmills** [comment]
Thank You @a4865g for bringing up this subject.

I'm going to close this PR because I've overhauled the documentation relating to test in #2034 (on main) and #2033 (on 0.27-maintenance).

**Pull request closed without merging**
