### PR TITLE
Robin changes

### PR DESCRIPTION
**Pull request by piponazo**
Hi Robin,

I took your changes in robinmills/exiv2/master and created a Pull Request from my private fork as we discussed. 

Let's see if the code build in all the platforms and I will review later the changes introduced.

Cheers!

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
Well, as I wrote this code, I have to approve it.  I will fix my mistakes.   Luis is "the man" for CMake and has final say about CMake support. (CMakeLists.txt .cmake files).

**Comment by piponazo** [comment]
There has been failures on the continuous integration tools. I have to check the problems and made some additional work to fix them.

Later I will review the changes. I will do that during the weekend

**Comment by clanmills** [comment]
Luis

I'm going to integrate this to exiv2/exiv2 'master' and build it locally.  I hope to get Jenkins working again before I go the airport today.  I can't tell you how happy I will be to get Jenkins running smoothly again.

**Comment by piponazo** [comment]
With that action the master branch of the main repository will become unstable.

**Comment by clanmills** [comment]
Yes.  I'm aware of that.  I'm investigating.  For sure there's something wrong with Expat/MSVC.  If the worst comes to the worst, we've have to revert 7fa8d313

**Comment by clanmills** [comment]
The code is building OK with the msvc/solution/project files.  It's Expat that's failing in CMake:

```
---------- EXPAT building with cmake -----------------

++++++++++++++++++++++++++++++++++++++++++++++++++++++++
CD = C:\Users\rmills\gnu\github\exiv2\exiv2\contrib\cmake\msvc\work_Release\expat-2.1.0
cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release expat-2.1.0 -DCMAKE_INSTALL_PREFIX=C:\Users\rmills\gnu\github\exiv2\exiv2\contrib\cmake\msvc\dist\2015\x64\dll\Release -DBUILD_examples=0 -DBUILD_tests=0 ..\..\expat-2.1.0
Press any key to continue . . .
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:38 (include):
  include could not find load file:

    ConfigureChecks.cmake


CMake Error: File C:/Users/rmills/gnu/github/exiv2/exiv2/contrib/cmake/msvc/expat-2.1.0/expat.pc.in does not exist.
CMake Error at CMakeLists.txt:73 (configure_file):
  configure_file Problem configuring file


-- Configuring incomplete, errors occurred!
See also "C:/Users/rmills/gnu/github/exiv2/exiv2/contrib/cmake/msvc/work_Release/expat-2.1.0/CMakeFiles/CMakeOutput.log".
```

I'll get some coffee and think about this.  I've never seen it complain and I believe it's using "vanilla" expat-2.1.0  It's possible that expat.pc.in does not exist and ConfigureChecks.cmake is confused.  Ummmmm.  We'll find/fix this - we always do.

**Comment by clanmills** [comment]
I've fixed it:
1) Something wrong with my local copy of Expat (indeed, he had lost that file!).  I deleted the bad one and cmakeBuild.cmd copied in a nice clean version.  Expat builds.

2) xmpsdk/CMakeLists.txt has lost an `endif()` at line 72.

I'll submit and do more testing.  I'm looking forward to G&T on VS11 this evening, it's been a tough week.

**Comment by clanmills** [comment]
Everything looks fine here, except the CMake/Xcode magic - so I've raised an issue on you.  Travis is happy. AppVeyor is not.  I think you should ease the pressure on the Windows build and only depend on libz and expat.  Don't bother with --webready on Windows.

The best feature in "webready" is support for HTTP.  There is a default http implementation (which I wrote).  So all builds of exiv2 support http.

The option -DEXIV2_ENABLE_WEBREADY=1 drags in curl/libssh/openssl.  A lot of baggage and compiling for a few users.  The script contrib/cmake/msvc/cmakeBuild.cmd copies prebuilt binaries of openssl to save time and builds libssh and curl from source. msvc/exiv2+webready.sln builds everything include openssl.  It's a monster.

I'm really excited that conan could let us stop worrying about this stuff.  Now you know why I wanted to give you encouragement the moment I met you.

**Comment by piponazo** [comment]
Great I will take care of that during the weekend ;)

**Pull request merged**
