### PR TITLE
meson backports for 0.28.x

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by neheb** [comment]
[meson: basic cmake conf](https://github.com/Exiv2/exiv2/pull/2815/commits/9b04d769d4609c8a6496be74463048de8c6aeef2) is questionable. It's incomplete and errors on missing cmake.

**Comment by kevinbackhouse** [comment]
Do you want to include this in v0.28.1?

**Comment by neheb** [comment]
yeah

**Comment by kevinbackhouse** [comment]
> yeah

If you rebase it then hopefully the tests will all pass.

**Review by kevinbackhouse — APPROVED** [review]

**Pull request merged**
