### PR TITLE
Translation Exiv2 in Dutch (nl)

### PR DESCRIPTION
**Pull request by pmatth2**
Hello, attached is a (partial) translation of Exiv2 in Dutch, nl.po.

As this is the first time I upload a file to GitHub, I hope I followed the proper procedure.
Regards, Paul.

### CODE REVIEW

**Comment by clanmills** [comment]
Thanks very much for submitting this.  The procedure for localisation is documented in README.md __*2.8 Localisation*__.  If you have discovered errors in that documentation, please let me know.

I will have your file reviewed by a Dutch user and hope to get it into the code-base later this week.  We hope to release Exiv2 v0.27.2-RC2 at the end of this week.

Thank You very much taking the trouble to work on this.  A user (called Toni) added Catalonian last year, and now you've contributed Dutch.  Thanks very much.

**Comment by pmatth2** [comment]
Hello, I indeed followed the guide in the README.md, section Localisation. 

Three remarks. 

1. The following:

> Running exiv2 in a foreign language

> $ env LANG=fr_FR exiv2    # env LANGUAGE=fr_FR exiv2 on Linux!
exiv2: Une action doit être spécifié
exiv2: Au moins un fichier est nécessaire
Utilisation : exiv2  [ options ] [ action ] fichier ...

does not work on my system (Xubuntu 18.04):

$ env LANG=fr_FR exiv2     # gives the following output:
exiv2: An action must be specified
exiv2: At least one file is required
Usage: exiv2 [ options ] [ action ] file ...

No French there! I tried de_DE and nl_NL as well, but it stays in English.
I compiled with the cmake option -DEXIV2_BUILD_PO=On

2. 

> 2.4) Install and test your messages:

> You have to install your messages to test them. It's not possible to test a message file from the build/bin directory.

> $ sudo cp -R  po/xy /usr/local/share/locale/xy

Didn't work for me neither. To test my translated strings, I had to take the nl.mo file (generated by poedit from the nl.po) and rename that to exiv2.mo. Then copy this one to .../share/locale/nl/**LC_MESSAGES/**, like so:

$ sudo cp exiv2/po/nl.mo /usr/local/share/locale/nl/LC_MESSAGES/exiv2.mo

3. 
> 2.5) Submitting your new language file for inclusion in future versions of Exiv2:

> Open a new issue on https://github.com/exiv2/exiv2 and attach the file po/xy/exiv2.po

I opened a new issue but could not attach my file nl.po: unsupported file type! ;)

Perhaps my little problems stem from the fact that I am not a programmer, just a translator (Gimp 2.10.x + libs, gThumb 3.8...). My motivation to translate exiv2 was that I wanted gThumb to be 100% in Dutch. I'm curious to see if this works!

Regards, Paul.

**Comment by clanmills** [comment]
That's really good feedback, Paul.  Thanks very much.

I'm surprised that you've encountered all this "doesn't work for me" stuff.  I'm wondering if you've build NLS (natural language support).  Can you try this:
```
$ exiv2 -vVg nls
exiv2 0.27.2.1
enable_nls=1
$ 
```

Explanation: -vVg == --verbose --version --grep

--verbose --version reveals a lot of information about the build of the library (date, time, compiler and lots of other stuff).   --grep says "only match" the argument.  So instead of getting about 200 lines you only see enable_nls.  You can enable/disable NLS in the build with the option EXIV2_ENABLE_NLS={On|Off}.  The default is On, however it will disable itself if you don't have gettext and libintl.h installed.  I'm sure you have gettext because you've used the localisation tools.

The notes in README.md were developed with Ubuntu Unix and tested on MacOS-X, Cygwin and MinGW.  I'll install Xubuntu 18.04 on a VM this morning and investigate.

**Comment by clanmills** [comment]
About attaching a .po file.  GitHub restricts the types of file.  If you rename the file nl.txt, I believe it's OK.  You could also zip or tar the file and it'll probably be accepted.  Your git patch appears to have arrived safely.  Here's nl.pl.zip
[nl.po.zip](https://github.com/Exiv2/exiv2/files/3324072/nl.po.zip)

```
2117 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ zip nl.po.zip po/nl.po 
  adding: po/nl.po (deflated 80%)
2118 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ ls -l nl.po.zip
-rw-r--r--+ 1 rmills  staff  121012 25 Jun 08:40 nl.po.zip
2119 rmills@rmillsmbp:~/gnu/github/exiv2/0.27-maintenance $ 
```

**Comment by pmatth2** [comment]
paul@graveyron:~$ exiv2 -vVg nls
exiv2 0.27.99.0
enable_nls=1

So nls is enabled. 

If GitHub wants a zip, just mention that in the documentation. Now it says "Upload your xy.po". 

Regards, Paul.

**Comment by clanmills** [comment]
I'll fix the documentation.  I didn't test uploading the .po file.  Everything that's not tested is invariably wrong.  Everything that's tested can even be wrong!  Software is a tough adversary.

I'll review all the documentation on X-Ubuntu (and MacOS-X) after breakfast.

**Comment by clanmills** [comment]
@pmatth2 I've submitted a PR #928.  I expect when this is merged, you'll get the credit for nl.po and your name will appear as a contributor here:  https://www.openhub.net/p/exiv2

I've fixed the documentation about the "messages" file.  It's a puzzle that the documentation is incorrect.  README.md was a new file with Exiv2 v0.27 and deals with localisation, debugging, running the test suite and other development topics that were vaguely documented in the past.  Getting the localisation information together was painful!  With your help, we've fixed some of the fiction.

I installed a new VM with XUbuntu 18.04.  I had to use `$ env LANGUAGE=nl exiv2` to see your file in action.  Why would this work differently on Ubuntu and XUbuntu?  Nobody knows!

Thank You very much for getting involved.  If you'd like to help Exiv2 with your localisation skills, the Team would be delighted to have somebody "own" localisation.  I believe there are tools to submit po files for update/translation.  Team Exiv2 is a small, happy and enthusiastic band of C++ Warriors.  We'd be delighted to welcome you on board.

**Comment by clanmills** [comment]
I'll leave this open for now as you may wish to update nl.po.

I don't understand git.  I've put a copy of po/nl.po into #928 to ensure it's available with my change to po/CMakeLists.txt.  Ummmn.  There's a little collision here.  @piponazo and @D4N are git gurus and will deal with this.

Perhaps I should have asked you to change po/CMakeLists.txt in the PR and then only submitted the changes to README.md in #928.

Something will work out fine, you'll see.

**Comment by clanmills** [comment]
I'll close this.  Let shift focus to #928.

**Comment by clanmills** [comment]
I'm going to reopen this and assign it to 0.27.3 (scheduled for 2019-09-30).  Both the reviewers on Pixls have commented the translation is good, however there is quite a lot to be done.

So, I'd like to see you complete the task AND make the change to po/CMakeLists.txt.  I'm going to  reduce the scope of #928 to be the documentation change.  The cut-off for 0.27.2 is this Saturday June 29 (and that requires review and merging).  If that's too much for this week, it'll go into v0.27.3.

**Comment by clanmills** [comment]
I've reopened #927 and set the target to Exiv2 v0.27.3.  I've also requested that he makes the change to po/CMakeLists.txt.  #927 translation is good, however it's incomplete.

Let's get the changes on README.md into Exiv2 v0.27.2.

**Comment by D4N** [comment]
@pmatth2 Could you add this file to `po/CMakeLists.txt` into the `GETTEXT_CREATE_TRANSLATIONS` list? And could you please change the header of `nl.po` to this (please insert your name & email):
```
# Dutch translation of Exiv2
# Copyright (C) 2019 INSERT_YOURNAME_HERE
# This file is distributed under the same license as the Exiv2 package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
```
Then I'd be more than happy to merge this.

**Comment by pmatth2** [comment]
As asked,

Please rename nl.po.txt to nl.po

Reagrds, Paul. 
[CMakeLists.txt](https://github.com/Exiv2/exiv2/files/3336391/CMakeLists.txt)
[nl.po.txt](https://github.com/Exiv2/exiv2/files/3336394/nl.po.txt)

**Comment by D4N** [comment]
@pmatth2 I somehow managed to close your pull request, I'm very sorry about that, no clue how that happened. I'll submit your changes via a second PR.

**Pull request closed without merging**
