### PR TITLE
Update localization files

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by neheb** [comment]
```
po/meson.build:8:5: ERROR: File en@quot.po does not exist.
```

**Comment by kmilos** [comment]
Hm... [The gettext manual gives the impression these are to be generated on the fly](https://www.gnu.org/software/gettext/manual/html_node/po_002fLINGUAS.html)? So either we consider this a meson bug and try to follow it through, or simply drop en@quot and en@boldquot for the time being?

**Comment by neheb** [comment]
ping @eli-schwartz

**Comment by eli-schwartz** [comment]
> Hm... [The gettext manual gives the impression these are to be generated on the fly](https://www.gnu.org/software/gettext/manual/html_node/po_002fLINGUAS.html)? So either we consider this a meson bug and try to follow it through, or simply drop en@quot and en@boldquot for the time being?

The gettext manual unfortunately makes some very significant assumptions. In particular it assumes that the only build system people will ever use is GNU autotools in combination with the gettext project's own support for gettext.

Hence it heavily documents how to do what works in autotools, and doesn't pay much heed to either meson or cmake.

In particular, these LINGUAS entries that are generated in the fly are generated by gettext Makefile rules and sed scripts implemented by neither meson nor cmake.

In theory meson could add support for these variants, although I've never actually seen anyone who found them useful. If you do want them, then please open a meson ticket asking for them and I can look into adding support.

**Comment by eli-schwartz** [comment]
Ok, great :) happy to be of service.

**Review by neheb — APPROVED** [review]

**Pull request merged**
