### PR TITLE
Issue 841: replace assert with enforce.

### LINKED ISSUE #841: Invalid data location in CRW image causes exiv2 to crash
The attached file causes an assertion failure in `exiv2`.

issue_841_poc

Reproducible on the 0.27-maintenance branch ([f4a37c6](https://github.com/Exiv2/exiv2/commit/f4a37c63f2f890c16ff7192fc89a75a7c34ae82b)):

```
exiv2 issue_841_poc.jpg
```

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes #841.

### CODE REVIEW

**Review by clanmills — COMMENTED** [review]
I'm going to leave it to Dan and Luis to approve.  Dan brought enforce() into the code-base.

I believe you're in Oxford.  You're very welcome to come to Camberley for a BBQ during the summer.  We're going to Scotland and other short trips in the next couple of months.  After that, it'd be nice to meet up.

**Comment by D4N** [comment]
I've grep'ed the source code for invocations of `dataLocation()` and it is only used in very few places. What's your guys opinion on simply making it throw if it should find an invalid location?

**Comment by kevinbackhouse** [comment]
@D4N: that sounds fine to me. Would you like me to add that to this PR?

**Comment by piponazo** [comment]
I think @D4N 's idea is very nice. If you could try to throw inside `CiffComponent::dataLocation(uint16_t tag)` then we could remove all the checks from where `dataLocation()` is used. Could you try to do it in this PR? If we observe complications because of that we can always postpone it.

**Review by piponazo — DISMISSED** [review]

**Review by D4N — DISMISSED** [review]
Thanks for fixing this!

**Comment by D4N** [comment]
@kevinbackhouse Could you rebase the commints on top of 0.27-maintenance and squast them into one?

**Review by piponazo — APPROVED** [review]

**Pull request merged**
