### PR TITLE
fix_Sony2010e_0.27 Thanks to @sridharb1

### PR DESCRIPTION
**Pull request by clanmills**
Thanks You @sridharb1  Please approve.  I'll merge this after the CI build checks have passed.

### CODE REVIEW

**Review by sridharb1 — APPROVED** [review]
Looks good

**Comment by piponazo** [comment]
Has been this included also into mater ? I can see that @D4N added the label but I did not see any PR emerging from this one.

**Comment by clanmills** [comment]
Thanks for powering up, Luis.  Hope everything's OK with you and your family in Spain.

I don't think this has arrived in.  When @D4N sets the "to-Master" label, I believe that causes an additional rule to be executed:
```
Rule: forward-port patches to master (backport) No backport have been created
```
For sure this failed last night on PR #1130
https://github.com/Exiv2/exiv2/runs/545847173

It might be better not to use the "to-master" magic and wait for Exiv2 v0.27.3 to be released. Then I'll take the action to review every change in 0.27-maintenance and open new PRs to integrate changes in master.  We'll have more control, and you'll be able to review/modify changes destined for master.

**Comment by piponazo** [comment]
It is fine for me to proceed as you suggested ;).

**Pull request merged**
