### PR TITLE
IO read/write functions with size_t

### PR DESCRIPTION
**Pull request by beutlich**
Sorry, the automatic clang-formating disguises the real changes.

### CODE REVIEW

**Comment by D4N** [comment]
Please fix the Travis build and please split the commits into smaller chunks (especially the clang format), currently each commit includes many distinct changes.

**Comment by tbeu** [comment]
> especially the clang format

This would be a tedious work. VS reformats from time to time and if I do not dectect it immediatly I am lost.

**Comment by piponazo** [comment]
Thanks for the contribution!

For me everything looks fine, so I'll be happy to approve once the windows x64 builds are fixed.

Normally we put a lot of care to split the changes in different commits. But since this is a huge work and all the changes are related (excepting the clang-format changes) I would be permissive in this case.

**Comment by tbeu** [comment]
> so I'll be happy to approve once the windows x64 builds are fixed

That is the problem, where I gave up. I put this on hold for now.

**Pull request closed without merging**
