### PR TITLE
Add Sigma 14mm and 24mm Art lenses for Nikon F-mount to lens db

### PR DESCRIPTION
**Pull request by mallman**
Add Sigma 14mm and 24mm Art lenses for Nikon F-mount to lens db.

The specifications for these lenses, including model numbers, can be found at

https://www.sigma-global.com/en/lenses/a017_14_18/

and 

https://www.sigma-global.com/en/lenses/a015_24_14/

I've attached sample camera jpegs as requested in the contributing documentation.

Cheers.

_DSC2133
_DSC2134

### CODE REVIEW

**Comment by kmilos** [comment]
Thanks for your contribution and welcome.

I just recently found out we have [somewhat of a problem when it comes to Sigma lenses](https://github.com/lensfun/lensfun/pull/1588#issuecomment-1029090715)... The same lens is named differently (both by exiftool and exiv2) depending on whether it is in Canon translation tables or Nikon translation tables, so e.g. lensfun would work for a Canon user, but not for a Nikon one, and vice-versa. This is also the case for one of the lenses you submitted; exiv2 and exiftool have it in the Canon table as "Sigma 14mm f/1.8 DG HSM | A"

Not sure how to proceed to be honest.

**Comment by mallman** [comment]
I don't know if I'm brave enough to make this claim in https://github.com/lensfun/lensfun/pull/1588, but in my opinion the problem lies with lensfuns's data architecture. The "key" lensfun uses for lookup is a description, not a specification. Using some string description as a fuzzy lookup key is just flat-out bad design that's bound to lead to grief. They should be using something like exiv's approach where the lookup is based on actual metadata that's almost 100% prescriptive, i.e. _this_ should be the lookup key:

```
{0x26,0x58,0x31,0x31,0x14,0x14,0x1C,0x02,0x00,0x00,0x00, "Sigma"}
```

Maybe include the manufacturer's model number, too. Where there's ambiguity, the description can be used as a _fallback_.

Granted, this doesn't cover teleconverters or lens adapters like FTZ or FTZ 2, but that's a smaller problem to solve than reverse matching some arbitrary string description.

If anyone with some time on their hands is looking to make a valuable community contribution, they could merge the data from exiv and lensfun and patch lensfun or create a new tool.

Ha ha. That's my controversial (possibly misinformed) and triggering comment for the ~day~ hour. (The day is young.)

**Comment by mallman** [comment]
> Not sure how to proceed to be honest.

I don't either. But I'll take a closer look to see what can be done.

**Comment by mallman** [comment]
I haven't heard of your M2Lscript proposal, no. What would be the output of M2Lscript?

**Comment by clanmills** [comment]
The lens name needed by Lens Fun.  The proposal is in my book:  https://exiv2.org/book/index.html#future and discussed on GitHub.

By the way, about the only part of Exiv2 that isn't documented in my book are the convertors.  It was about the final thing to be investigated and documented.  I gave up in exhaustion.  I also thought "This convertor stuff is insane.  We should report exactly what is in the file.  The truth and nothing but the truth.".   Sssshsh.

**Pull request closed without merging**
