### PR TITLE
Add remaining DNG 1.3 tag values (0.27->master)

### PR DESCRIPTION
**Pull request by kmilos**
Addendum to #1391

### CODE REVIEW

**Comment by clanmills** [comment]
I'll sit on this for a couple of days as you may think of something to add.

**Comment by kmilos** [comment]
It was a good idea, I leafed through the spec some more and found the light sources could be pretty printed as well easily.

There are maybe a couple of more tags where the values could be decoded to something more human readable, but I'd leave those for the eventual DNG support overhaul:

MakerNoteSafety (False/True)
ColorimetricReference (Scene-referred/Output-referred)
ProfileEmbedPolicy
PreviewColorSpace

DNG 1.4 & 1.5 (not implemented ATM anyway):

DefaultBlackRender
ProfileLookTableEncoding
ProfileHueSatMapEncoding
DepthFormat
DepthUnits
DepthMeasureType

**Comment by kmilos** [comment]
A-ha, we actually do have test cases for those light sources, great! I'll update later today, sorry.

**Comment by kmilos** [comment]
Should be passing now. Let me know if you prefer to extend the pretty-printing to the existing 4 DNG 1.3 tags, otherwise I think this is now good to go.

**Comment by kmilos** [comment]
Ok, this now (sort of) completes DNG 1.3 support level, so please merge after review.

What's still potentially missing is parsing the extra CameraProfile IFDs if present; we just print the offsets in ExtraCameraProfiles to indicate something is there. I haven't come across a sample DNG file that has actually has these...

**Review by clanmills — DISMISSED** [review]
This looks fine.  Thank You for working on this.  I don't have an opinion about ExtraCameraProfiles.  Something I could discuss in the book if we had a suitable test file.  Presumably it's an array of IFDs and each on has the same collection of tags as the main file (BaselineExposureOffset, CalibrationIlluminant1 and so on).

I've approved this.  Four comments (which you can action or ignore)

1. Do we need print0x9208?  Can we use EXV_PRINT_TAG(exifLightSource)?

We'll need to leave print0x9208 in the code because it's in the API:

```
505 rmills@rmillsmm-local:~/gnu/github/exiv2/dng_tag_values_cfa/src $ nm -g --demangle ../build/lib/libexiv2.dylib | grep 9208
00000000001f2f90 T Exiv2::Internal::print0x9208(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, Exiv2::Value const&, Exiv2::ExifData const*)
506 rmills@rmillsmm-local:~/gnu/github/exiv2/dng_tag_values_cfa/src $ 
```

2.  The comment `// DNG tag`, could that be `// DNG 1.3 tag` 

3.  Do you have test files for any tags other than CalibrationIlluminant{1|2}?

4. What aren't we upgrading to DNG 1.4?

**Comment by kmilos** [comment]
> I don't have an opinion about ExtraCameraProfiles. Something I could discuss in the book if we had a suitable test file. Presumably it's an array of IFDs and each on has the same collection of tags as the main file (BaselineExposureOffset, CalibrationIlluminant1 and so on).

Precisely. Tons of standalone DCP (DNG Camera Profile) files are shipped w/ the Adobe DNG Converter, people also make/tweak them using the [dcpTool](http://dcptool.sourceforge.net/) and [DCamProf](http://rawtherapee.com/mirror/dcamprof/dcamprof.html), and they're also shipped by other OSS like https://github.com/Beep6581/RawTherapee/tree/dev/rtdata/dcpprofiles 

As standalone, a DCP is just a minimal TIFF w/ a single Camera Profile IFD with the fixed collection of tags (list is indeed in the DNG spec). Otherwise, it's just a list of extra IFDs inside the DNG file: "The format of a camera profile begins with a 16-bit byte order mark (MM or II) followed by a 16-bit "magic" number equal to 0x4352 (CR), a 32-bit IFD offset, and then a standard TIFF format IFD. All offsets are relative to the start of the byte order mark."

> 1. Do we need print0x9208?  Can we use EXV_PRINT_TAG(exifLightSource)?

No, not really. I just used it since it's there and also used for the equivalent ExifIFD LightSource tag 0x9208... I'll replace it w/ the macro, so it's consistent across all DNG tags.

> 2. The comment `// DNG tag`, could that be `// DNG 1.3 tag`

I just went with what's in the rest of the DNG TagInfo array list, none of them are identified by version so far... If you think that's useful, I can add the version for all existing DNG tags?

> 3. Do you have test files for any tags other than CalibrationIlluminant{1|2}?

Unfortunately not, we'd have to cook those. Using actual DNG samples from e.g. https://raw.pixls.us/ is also an option, but the files are huge...

> 4. What aren't we upgrading to DNG 1.4?

I left out 1.4 and 1.5 on purpose as part of the #1161 discussion and future work, all of those tags are missing. One step at a time ;)

**Comment by clanmills** [comment]
Right.  That's fine.  Gosh, I'm having another very busy day.  A user reported an issue yesterday concerning the machine generated documentation on the web-site, and today somebody has asked me to revise README-CONAN.md for Visual Studio 2019 which didn't exist when I wrote it in 2018.  Tuesday lunch-time and no progress with the book.

I'd like you to change print0x9208 to EXV_PRINT_TAG(exifLightSource) for the new tags (and keep it where it was in use before).  Then I'll merge.

Can you push the "Merge pull request" button, or does that only appear for me?

**Comment by clanmills** [comment]
Oh about the comment `// DNG 1.3`.  Yes I think we should put that comment on all new tags which we add.  However I'm not asking for that to be done to existing code.

**Comment by kmilos** [comment]
Ok, I'll make those two small changes hopefully later tonight, and merge after check pass (I do see the merge button now).

**Comment by clanmills** [comment]
Thank You very much.  You are very cooperative and helpful.  I appreciate your contributions.  Please push that "Merge" button and we'll live to unpuzzle the next challenge.

**Review by clanmills — APPROVED** [review]
Thank You for dealing with this.

**Comment by clanmills** [comment]
@kmilos I've discovered that the latest DNG Spec is 1.5.  I think I'll open a new issue: "Support for DNG 1.5".  I won't assign it a milestone.  It's a "well, we need to do this eventually" kind of thing.

I've added code to tvisitor.cpp to support DNG tags, .DCP files and added a paragraph about those files.

I go to run in the forest on Wednesday mornings with my friend Steve and his dog Banjo.  This afternoon, I will focus on the book and straighten out the confusion in my brain concerning Tiff6.0, Tiff/EF, DNG in IFD0.  Exif (and its children GPS etc have their own IFD).

My aim is to update the PR concerning Exif 2.31 and 2.32, however the intermediate step is for me to really understand how those cleanly work together.

**Comment by kmilos** [comment]
> I think I'll open a new issue: "Support for DNG 1.5". I won't assign it a milestone. It's a "well, we need to do this eventually" kind of thing.

Agreed, it's good to have this self-contained Feature Request rather than use the existing PR as a catch-all... Enjoy your run, hope the weather is good.

**Comment by piponazo** [comment]
Hi @kmilos , thanks for this excellent contribution. I am sorry to arrive late to the discussion. Have you considered to include these changes to master? We should try to keep **master** aligned with the new features arriving to **0.27-maintenance**.  Let me know if you are interested in forwarding those changes, otherwise I can do it.

**Comment by clanmills** [comment]
@piponazo I've been modifying the titles of PRs to end with `(master only)`, or `(0.27 only)` or `(0.27->master)` to make it easy for the release engineer to know what needs to be "promoted" when we want to release v0.28.

As you know, my current priority is to finish my book in 2020 and enjoy my 70th birthday on 2021-01-18.

I'm hoping that several things will happen in 2021.

1. C-19 will begin to fade and LGM will happen in Rennes in late May.
2. Somebody agrees to take on the role of 'maintainer' for Exiv2.
3. I'm willing to release master as v0.28 before Rennes.  Although, if @LeoHsiao1 or @kmilos volunteered, that would be even better.

And when I leave Rennes, I want the weight of Exiv2 off my back.  We hope to attend a wedding in the States in July.  I want to pass a music exam on the Euphonium (probably November 2021).  And the usual stuff like gardening, running, travelling and exploring.

**Comment by piponazo** [comment]
Great @clanmills , thanks for the info. So, If I understood correctly, (0.27 -> master) means that the work done here still needs to be merged into master, right? I'll keep it in mind and do this work when I find some spare time (this end of the year is being pretty busy for me at work).

I am looking forward to find the time to read your book, I am sure the community will really appretiate it.

**Pull request merged**
