### PR TITLE
Add Unit tests with Google Test

### PR DESCRIPTION
**Pull request by piponazo**
In this PR I introduce the support to add unit tests with the Google Test and Google Mock frameworks.

By default the compilation of the unit tests is disabled. One can enable it toggling the CMake Option  **EXIV2_BUILD_UNIT_TESTS**. Once that variable is enabled, CMake will try to find GTest and GMock in your system. I also added these dependencies to conan, so if you use conan it should be automatic to bring those dependencies to your system.

I just added few simple unit tests as example of how to use the framework and how to add new tests into the project.

The tests are running correctly on travis-ci for Linux and Mac. On Windows I am having a problem (they crash when AppVeyor execute them) and I disabled their execution temporarily.

Let me known about your thoughts.

### CODE REVIEW

**Comment by D4N** [comment]
Good job bringing unit tests to exiv2!

However, I have some trouble getting them to run on Fedora 26. Executing `CC=gcc CXX=g++ cmake -DEXIV2_BUILD_UNIT_TESTS=ON ..` in `exiv2/build` leads to the usual CMake output with a new error:
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GTest (missing: GMOCK_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  config/FindGTest.cmake:297 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  config/findDependencies.cmake:69 (find_package)
  CMakeLists.txt:63 (include)

```
I have installed gmock and gtest via dnf, so maybe some paths are different or something else is missing? Can I provide you with some information that would help us both to debug this? Since I am currently lost with CMake's config files.

Although it should not be a problem, I'd like to point out, that the `FindGTest.cmake` file is licensed under the BSD license. So please also add the file `Copyright.txt` which is mentioned in the comments of `FindGTest.cmake` (or just paste it into the comments) for completeness. If it is actually licensed under the 3 or 2 clause BSD license, then there is no problem as both are GPL-compatible. As licensing is potentially a minefield, we should be extra cautious.

**Review by clanmills — APPROVED** [review]
This all looks fine, Luis.  Several questions:

1) Do we need to add some user documentation?

2) Should FindGTest.cmake be send to Kitware for consideration to be included in their supported modules?

3) You're hard wired for Visual Studio 14/64 bit.  Can you look at contrib/cmake/msvc/vcvars.bat which supports VS 2005/8/10/12/13/15/17 32/64.  I put that together a few years ago as a "neutral" way of invoking Microsoft's vcvars.bat script which moves about with different editions of Visual Studio.

**Comment by piponazo** [comment]
Hi @D4N, let's try to fix your case. Can you give me the folder layout where gtest and gmock are installed ? I would like to know where the headers and libraries are installed in your system (The linux command **tree** can give a very nice output for this purpose). I will also take a look to the license thing.

@clanmills here you can find my answer to the 3 questions:

1. More than user documentation, I would say "Developer documentation". Remember that this is something that is only interesting for the Exiv2 developers/contributors. The final user should not care about this.
2. Actually there is already an official FindGTest.cmake that comes with the official distribution. The problem is that this one does not find GMock. Actually, we could just survive with GTest for the moment and bring the GMock support later ... I will think about this.
3. What do you want me to do exactly there ? I do not see the relationship between GTest and that file.

**Comment by D4N** [comment]
DNF installs the packages in various places so here are the contents of the rpm packages:
```
$ dnf repoquery -l gtest
/usr/lib/libgtest.so.0
/usr/lib/libgtest.so.0.0.0
/usr/lib/libgtest_main.so.0
/usr/lib/libgtest_main.so.0.0.0
/usr/share/doc/gtest
/usr/share/doc/gtest/CHANGES
/usr/share/doc/gtest/CONTRIBUTORS
/usr/share/doc/gtest/LICENSE
/usr/share/doc/gtest/README
/usr/lib64/libgtest.so.0
/usr/lib64/libgtest.so.0.0.0
/usr/lib64/libgtest_main.so.0
/usr/lib64/libgtest_main.so.0.0.0
/usr/share/doc/gtest
/usr/share/doc/gtest/CHANGES
/usr/share/doc/gtest/CONTRIBUTORS
/usr/share/doc/gtest/LICENSE
/usr/share/doc/gtest/README
```
```
$ dnf repoquery -l gmock
/usr/share/doc/gmock
/usr/share/doc/gmock/CHANGES
/usr/share/doc/gmock/CONTRIBUTORS
/usr/share/doc/gmock/LICENSE
/usr/share/doc/gmock/README
```
```
$dnf repoquery -l gtest-devel
/usr/bin/gtest-config
/usr/include/gtest
/usr/include/gtest/gtest-death-test.h
/usr/include/gtest/gtest-message.h
/usr/include/gtest/gtest-param-test.h
/usr/include/gtest/gtest-printers.h
/usr/include/gtest/gtest-spi.h
/usr/include/gtest/gtest-test-part.h
/usr/include/gtest/gtest-typed-test.h
/usr/include/gtest/gtest.h
/usr/include/gtest/gtest_pred_impl.h
/usr/include/gtest/gtest_prod.h
/usr/include/gtest/internal
/usr/include/gtest/internal/gtest-death-test-internal.h
/usr/include/gtest/internal/gtest-filepath.h
/usr/include/gtest/internal/gtest-internal.h
/usr/include/gtest/internal/gtest-linked_ptr.h
/usr/include/gtest/internal/gtest-param-util-generated.h
/usr/include/gtest/internal/gtest-param-util.h
/usr/include/gtest/internal/gtest-port.h
/usr/include/gtest/internal/gtest-string.h
/usr/include/gtest/internal/gtest-tuple.h
/usr/include/gtest/internal/gtest-type-util.h
/usr/lib/libgtest.so
/usr/lib/libgtest_main.so
/usr/share/aclocal/gtest.m4
/usr/share/doc/gtest-devel
/usr/share/doc/gtest-devel/samples
/usr/share/doc/gtest-devel/samples/prime_tables.h
/usr/share/doc/gtest-devel/samples/sample1.cc
/usr/share/doc/gtest-devel/samples/sample1.h
/usr/share/doc/gtest-devel/samples/sample10_unittest.cc
/usr/share/doc/gtest-devel/samples/sample1_unittest.cc
/usr/share/doc/gtest-devel/samples/sample2.cc
/usr/share/doc/gtest-devel/samples/sample2.h
/usr/share/doc/gtest-devel/samples/sample2_unittest.cc
/usr/share/doc/gtest-devel/samples/sample3-inl.h
/usr/share/doc/gtest-devel/samples/sample3_unittest.cc
/usr/share/doc/gtest-devel/samples/sample4.cc
/usr/share/doc/gtest-devel/samples/sample4.h
/usr/share/doc/gtest-devel/samples/sample4_unittest.cc
/usr/share/doc/gtest-devel/samples/sample5_unittest.cc
/usr/share/doc/gtest-devel/samples/sample6_unittest.cc
/usr/share/doc/gtest-devel/samples/sample7_unittest.cc
/usr/share/doc/gtest-devel/samples/sample8_unittest.cc
/usr/share/doc/gtest-devel/samples/sample9_unittest.cc
/usr/bin/gtest-config
/usr/include/gtest
/usr/include/gtest/gtest-death-test.h
/usr/include/gtest/gtest-message.h
/usr/include/gtest/gtest-param-test.h
/usr/include/gtest/gtest-printers.h
/usr/include/gtest/gtest-spi.h
/usr/include/gtest/gtest-test-part.h
/usr/include/gtest/gtest-typed-test.h
/usr/include/gtest/gtest.h
/usr/include/gtest/gtest_pred_impl.h
/usr/include/gtest/gtest_prod.h
/usr/include/gtest/internal
/usr/include/gtest/internal/gtest-death-test-internal.h
/usr/include/gtest/internal/gtest-filepath.h
/usr/include/gtest/internal/gtest-internal.h
/usr/include/gtest/internal/gtest-linked_ptr.h
/usr/include/gtest/internal/gtest-param-util-generated.h
/usr/include/gtest/internal/gtest-param-util.h
/usr/include/gtest/internal/gtest-port.h
/usr/include/gtest/internal/gtest-string.h
/usr/include/gtest/internal/gtest-tuple.h
/usr/include/gtest/internal/gtest-type-util.h
/usr/lib64/libgtest.so
/usr/lib64/libgtest_main.so
/usr/share/aclocal/gtest.m4
/usr/share/doc/gtest-devel
/usr/share/doc/gtest-devel/samples
/usr/share/doc/gtest-devel/samples/prime_tables.h
/usr/share/doc/gtest-devel/samples/sample1.cc
/usr/share/doc/gtest-devel/samples/sample1.h
/usr/share/doc/gtest-devel/samples/sample10_unittest.cc
/usr/share/doc/gtest-devel/samples/sample1_unittest.cc
/usr/share/doc/gtest-devel/samples/sample2.cc
/usr/share/doc/gtest-devel/samples/sample2.h
/usr/share/doc/gtest-devel/samples/sample2_unittest.cc
/usr/share/doc/gtest-devel/samples/sample3-inl.h
/usr/share/doc/gtest-devel/samples/sample3_unittest.cc
/usr/share/doc/gtest-devel/samples/sample4.cc
/usr/share/doc/gtest-devel/samples/sample4.h
/usr/share/doc/gtest-devel/samples/sample4_unittest.cc
/usr/share/doc/gtest-devel/samples/sample5_unittest.cc
/usr/share/doc/gtest-devel/samples/sample6_unittest.cc
/usr/share/doc/gtest-devel/samples/sample7_unittest.cc
/usr/share/doc/gtest-devel/samples/sample8_unittest.cc
/usr/share/doc/gtest-devel/samples/sample9_unittest.cc
```
and:
```
$ dnf repoquery -l gmock-devel
/usr/bin/gmock-config
/usr/include/gmock
/usr/include/gmock/gmock-actions.h
/usr/include/gmock/gmock-cardinalities.h
/usr/include/gmock/gmock-generated-actions.h
/usr/include/gmock/gmock-generated-function-mockers.h
/usr/include/gmock/gmock-generated-matchers.h
/usr/include/gmock/gmock-generated-nice-strict.h
/usr/include/gmock/gmock-matchers.h
/usr/include/gmock/gmock-more-actions.h
/usr/include/gmock/gmock-more-matchers.h
/usr/include/gmock/gmock-spec-builders.h
/usr/include/gmock/gmock.h
/usr/include/gmock/internal
/usr/include/gmock/internal/gmock-generated-internal-utils.h
/usr/include/gmock/internal/gmock-internal-utils.h
/usr/include/gmock/internal/gmock-port.h
/usr/share/gmock/generator
/usr/share/gmock/generator/LICENSE
/usr/share/gmock/generator/README
/usr/share/gmock/generator/README.cppclean
/usr/share/gmock/generator/cpp
/usr/share/gmock/generator/cpp/__init__.py
/usr/share/gmock/generator/cpp/__init__.pyc
/usr/share/gmock/generator/cpp/__init__.pyo
/usr/share/gmock/generator/cpp/ast.py
/usr/share/gmock/generator/cpp/ast.pyc
/usr/share/gmock/generator/cpp/ast.pyo
/usr/share/gmock/generator/cpp/gmock_class.py
/usr/share/gmock/generator/cpp/gmock_class.pyc
/usr/share/gmock/generator/cpp/gmock_class.pyo
/usr/share/gmock/generator/cpp/keywords.py
/usr/share/gmock/generator/cpp/keywords.pyc
/usr/share/gmock/generator/cpp/keywords.pyo
/usr/share/gmock/generator/cpp/tokenize.py
/usr/share/gmock/generator/cpp/tokenize.pyc
/usr/share/gmock/generator/cpp/tokenize.pyo
/usr/share/gmock/generator/cpp/utils.py
/usr/share/gmock/generator/cpp/utils.pyc
/usr/share/gmock/generator/cpp/utils.pyo
/usr/share/gmock/generator/gmock_gen.py
/usr/share/gmock/generator/gmock_gen.pyc
/usr/share/gmock/generator/gmock_gen.pyo
/usr/share/pkgconfig/gmock.pc
/usr/src/gmock
/usr/src/gmock/gmock-all.cc
/usr/src/gmock/gmock-cardinalities.cc
/usr/src/gmock/gmock-internal-utils.cc
/usr/src/gmock/gmock-matchers.cc
/usr/src/gmock/gmock-spec-builders.cc
/usr/src/gmock/gmock.cc
/usr/src/gmock/gmock_main.cc
```

**Comment by piponazo** [comment]
Umh! So you actually do not have libraries for GMock (there are only .so files for gtest). That is probably the problem. Can you check why it does not install the libgmock.so files ?

Anyways, I would also appretiate if you try to use conan to bring the dependencies and tell me if it works in that way for you :)

**Comment by D4N** [comment]
Yeah, you are right, apparently `libgmock.so` didn't make it into the rpm package :-(

I have therefore updated rpm builds and when libgmock.so is present, everything works just fine. I hope that my proposed changes will be propagated soon to the Fedora repositories, otherwise Fedora users won't be able to run the unit tests (here the according [bugzilla entry](https://bugzilla.redhat.com/show_bug.cgi?id=1314927)).

Do we require gmock for the unit tests? If not, I would advocate to not depend on it for now (at least not until we have integrated Jenkins with github).

Concerning Conan, I have not tried and would prefer not having to rely on it on Linux, since it just does the job that the system's package manager does. Also, imho exiv2 should be package-able on all major distributions, which all forbid the usage of external package managers for building packages (basically like in with python, if you build a python rpm package, you must not build it using pip). Relying on Conan for retrieving & building dependencies could make packaging unnecessarily hard, if it retrieves different versions than the distribution ships.

**Comment by clanmills** [comment]
I am enthusiastic to see conan work with Visual Studio.  At present, we download and build dependencies with my script: contrib/cmake/msvc/cmakeBuild.cmd.  I will be happy to find a "standard" alternative such as conan.

Microsoft added a package manager and CMake support to Visual Studio 2017.  I understand that Jason and Luis have that working.  That's wonderful.  I doubt if that back-ports to earlier versions of Visual Studio.  So, although it's good news going forward, it doesn't deal with legacy Visual Studio support.

I will continue to support the msvc/ solution+project files with do not rely on package mangers at all.  You are expected to install "vanilla" source code directories of expat, zlib etc "parallel" to exiv2.  No special tools are required and everything is built by Visual Studio (2005/8/10/12/13/15/17).

I haven't looked at the unit tests on any platform yet.

**Comment by piponazo** [comment]
@D4N Thanks for your help, it is good to hear that after you managed to include the .so library the CMake finder did its job. I think we can get rid of the GMock dependency for the moment, since it would be only useful when we do advance unit testing. Although I do not think this would be a problem for distributions (because it is not a dependency for the library itself, but for the Exiv2 developers) , I am happy to relax the conditions for the moment and bring new features incrementally :).

Regarding conan, I agree that it is something that distributions will never use, but for normal users it's wonderful ... they will not need to care about installing packages in the system anymore. But as I always say, that's something optional. 

Alright, I will remove the customised `FindGTest.cmake` file, rely in the official one and remove any mention to GMock for the moment ;)

**Comment by clanmills** [comment]
I'm happy to increase the minimum version of CMake.  The current value of 3.1.0 was set a couple of years ago to support threads.  There hasn't been a reason to update it since.  Now we have a good reason, so let's update it appropriately.

**Comment by piponazo** [comment]
@clanmills If you do not mind, I would prefer to discuss that decision in other thread. I think we have to also be a bit conservative with the CMake version choice.  Some Linux distributions are quite conservative with the CMake version they use. If we choose a very high version for CMake we will oblige users to install a never version of CMake just to compile Exiv2. 

I think I could prepare a list of benefits that newer versions will give us, but please, let's discuss it in other thread :)

**Review by Kicer86 — COMMENTED** [review]
looks fine

**Comment by D4N** [comment]
I agree with Luis. The version of cmake that we require is already too recent for all  versions of CentOS/RHEL (at least it was a week ago when I tried to build master on CentOS 7). I would even advocate to lower the required cmake version if that is somehow possible (don't know enough about cmake to tell).

**Comment by piponazo** [comment]
It's something that we could investigate, but there are many points to consider. For example, for supporting modern XCode or Visual Studio versions we will need to require recent versions of CMake. I would have that discussion in order place :)

**Comment by D4N** [comment]
Is it possible to add different minimum required versions depending on the target? So that we could require an older version of cmake for Linux when building via makefiles and a more recent one when building via xcode/visual studio.

**Comment by piponazo** [comment]
I have never tried that ... it would be interesting but then it would also complicate the maintenance of the CMake code. I do not want to imagine how difficult it would be to maintain different paths of the CMake code ^_^u

**Comment by clanmills** [comment]
I don't think you can do this.  The generator is passed on the command-line arguments (e.g. -G Xcode).  I don't think CMake can change the generator after it has been invoked.

However if you pass an unknown generator such as "Visual Studio 16 2019", he produces a clear message.
```
559 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/b $ cmake .. -G "Visual Studio 16 2019"
CMake Error: Could not create named generator Visual Studio 16 2019

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Xcode                        = Generate Xcode project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  KDevelop3                    = Generates KDevelop 3 project files.
  KDevelop3 - Unix Makefiles   = Generates KDevelop 3 project files.

560 rmills@rmillsmbp:~/gnu/github/exiv2/exiv2/b $ 
```
My suspicion is that cmake loads a DLL for every generator and can't change the generator after he starts parsing his scripts.

If the only reason for us to say "You need 3.8.2 or greater" is to support VS2017,  we shouldn't require that in CMakeLists.txt.  We can put a line in the documentation and leave/expect the user to upgrade the CMake installation on the build machine.

**Comment by D4N** [comment]
> If the only reason for us to say "You need 3.8.2 or greater" is to support VS2017, we shouldn't require that in CMakeLists.txt. We can put a line in the documentation and leave/expect the user to upgrade the CMake installation on the build machine.

If we would only need a newer version for newer generators, then lowering it and documenting the requirement seems reasonable to me. Provided everything still works of course.

**Pull request merged**
