### PR TITLE
add support for gcc and clang 7

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by kmilos** [comment]
Any particular reason to support these old compilers on main?

**Comment by neheb** [comment]
No. It's just real easy to do. There might be super LTS systems out there that could benefit.

**Comment by kmilos** [comment]
It's more code... and I doubt super LTS systems would go for main/next version...

**Review by piponazo — APPROVED** [review]
I love it 💯 

As @neheb stated, the more compilers we can support out there the better. 

However, I do not think we have CI jobs checking that clang-7 or old gcc versions can actually compile the project, right? If we want to be sure that we support these compilers we should add some additional jobs in our pipelines (we can create another ticket for that)

**Comment by neheb** [comment]
> It's more code... and I doubt super LTS systems would go for main/next version...

not that much. It's just preprocessor stuff,

**Pull request merged**
