### PR TITLE
Use time.h instead of ctime

### LINKED ISSUE #1304: Master - Fedora_MinGW CI build broken
**Describe the bug**
Currently the Fedora_MinGW build on Gitlab is broken:

```
In file included from /builds/D4N/exiv2/src/localtime.c:7:
/builds/D4N/exiv2/src/timegm.h:6:10: fatal error: ctime: No such file or directory
    6 | #include <ctime>
      |          ^~~~~~~
```
https://gitlab.com/D4N/exiv2/-/jobs/740703401

**Expected behavior**
We should make the needed changes to have all the CI jobs passing.

**Additional context**
The root of this problem is probably the changes done at 
https://github.com/Exiv2/exiv2/pull/1299/commits/226066635e2329fe83ed8f2addf889bc7dcc83d8

### PR DESCRIPTION
**Pull request by piponazo**
Should fix #1304 

@neheb I am just pinging you to make you aware of the situation 😉

### CODE REVIEW

**Comment by clanmills** [comment]
There's a comment that this in only used localtime.c.  I removed localtime.c in v0.27.3  https://github.com/Exiv2/exiv2/pull/1225

**Comment by piponazo** [comment]
> There's a comment that this in only used localtime.c. I removed localtime.c in v0.27.3 #1225

Thanks for letting me know! I will propagate that change to master 😉

**Comment by piponazo** [comment]
> > There's a comment that this in only used localtime.c. I removed localtime.c in v0.27.3 #1225
> 
> Thanks for letting me know! I will propagate that change to master 😉

Actually, after removing the `localtime.c` file, the Fedora_MinGW build failed in GitLab. This is weird ... in `0.27-maintenance` we also have a Fedora_MinGW build which is passing. I must be missing something.

**Comment by clanmills** [comment]
Well done, Luis.  Great Team Work Here.  As you said to @neheb.  He's on fire.  We're smokin!

**Comment by neheb** [comment]
Sounds weird. ctime is a standard C++ header. The problem is elsewhere.

**Comment by piponazo** [comment]
> Sounds weird. ctime is a standard C++ header. The problem is elsewhere.

It was my first thought too ...  Actually after you said that I think I have realized what was the problem ... I just noticed about the following errors in the failing CI job:

```
[ 24%] Building C object src/CMakeFiles/exiv2lib_int.dir/localtime.c.obj
cc1: warning: command line option '-Woverloaded-virtual' is valid for C++/ObjC++ but not for C
In file included from /builds/D4N/exiv2/src/localtime.c:7:
/builds/D4N/exiv2/src/timegm.h:6:10: fatal error: ctime: No such file or directory
    6 | #include <ctime>
```

Of course, `locatime.c` was being compiled with **gcc** and not **g++** and therefore it was not finding `ctime`.

Now that we have removed `locatime.c` it should be fine to come back to the `ctime` header. I'll create another branch for that.

**Pull request merged**
