### PR TITLE
fix format strings

### PR DESCRIPTION
**Pull request by neheb**
Found with lgtm.com

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Wonder if libexiv2 should use fmtlib.

**Comment by piponazo** [comment]
> Wonder if libexiv2 should use fmtlib.

I think this has been discussed in the past. Note that we mostly care about implementing the library **libexiv2** that is consumed by many open source projects. We also have the **exiv2** command line application that is used to print the information decoded by the library, but I think some distributions do not include that application in their system packages.

We try to minimize the number of dependencies in the project and just include dependencies if they are strictly needed to read some image metadata formats. 

However, it we see that it brings a considerable benefit to bring a library like that we could consider it. The code that you touched here is part of `printIFD` which I think it is used for debugging. Opinions about this @clanmills ?

**Comment by clanmills** [comment]
Dependent libraries caused pain in the past before we used conan.  It might be OK to statically link something into libexiv2.

Let's not change this while 0.27-maintenance is active.  If you discover format issues on 'master', porting them to 0.27-maintenance is probably easy.  Once you introduce another library, 'master' and 0.27-maintenance diverge even more.  I don't want to change dependencies in 0.27-maintenance.

**Comment by neheb** [comment]
OK. I take it this PR is fine as is?

**Comment by clanmills** [comment]
I am delighted by your contributions.  Thank You very much for getting involved with Exiv2.

I don't know if this is _"fine as it is"_ because you have used formatting that I don't understand.  Such as:

```
                                    << Internal::stringFormat("%8" PRIu64 " | %#06x %-25s |%10s |%9" PRIu64 " |",
```

This formatting code has been in Exiv2 for a few years.  Can you explain:
1  Why it should be changed.
2 Why your code addresses the deficiencies in the existing implementation.
3 Can your change back-port to C++98 (and therefore 0.27-maintenance).

If this is C++11 only (and therefore 'master'), we should ask @piponazo to approve.

**Comment by neheb** [comment]
1. The code as is uses wrong formats. The variables in bigtiffimage are uint64_t, which is either unsigned long int or unsigned long long int depending on the platform.
3. Mostly. cinttypes is a C++11 header. inttypes.h can be used for C++98 conformance.

**Comment by clanmills** [comment]
I want to approve your change.  Please help me to understand it.  Is PRIu64 a macro? 

We should remove BigTiff from the code base.  I could say much more, however it's off topic when discussing formats.  The BigTiff project stalled #1259.

**Comment by neheb** [comment]
PRIu64 is indeed a macro. It evaluates to either lu or llu.

**Comment by clanmills** [comment]
Thanks for your confirmation about my suspicion.  It's 23:04 in England - time for bed.  I'll review this on Saturday.

**Review by clanmills — COMMENTED** [review]
I'm happy with the changes to src/rafimage.cpp and will port them to 0.27-maintenance.

I'm unhappy with the changes to src/bigtiffimage.cpp for two reasons:
1. We should remove bigtiffimage.cpp from the code-base in support of #1259.  I have opened a new issue about this: #1329

2. I'm unhappy with PRIu64  I don't even know where it's defined.

So, here's my proposal.

On 0.27-maintenance:
1 I will back-port your changes to rafimage.cpp
2 I will remove bigtiffimage.cpp from the code-base

I leave it to @piponazo to comment or approve this PR for the 'master' branch.

**Comment by piponazo** [comment]
Hi all,

I’m not sure you will this reply. I’m on holidays, and replying directly
with my phone with the email app 🤞.

For me the changes are good for master, but I’m not sure if they can be
applied to 0.27. If I understood it correctly, the new macro used is only
available since c/c++11.

We can always remove the bigtiff stuff from master after this PR is merged.

**Comment by clanmills** [comment]
Enjoy your vacation.

I have removed src/bigtiffimage.cpp from 0.27-maintenance and recommend that you do the same on 'master' #1331

**Review by piponazo — APPROVED** [review]

**Pull request merged**
