### PR TITLE
fix_1558_cmake_build_type

### PR DESCRIPTION
**Pull request by clanmills**
See: #1558.

### CODE REVIEW

**Review by kmilos — APPROVED** [review]

**Comment by piponazo** [comment]
Hi Robin. In essence, this addition is good to have. 

Nonetheless, I would propose to do something similar to what it is discussed in this blog post from kitware (the creators of CMake):
https://blog.kitware.com/cmake-and-the-default-build-type/

I also have one question: Do you have plans to include this in 0.27-maintenance, or that branch is freeze?

**Comment by kmilos** [comment]
There's also some [more in the CMake  FAQ](https://gitlab.kitware.com/cmake/community/-/wikis/FAQ?version_id=d523de26dec5420d27012a3795d127ced7446c6c#how-can-i-change-the-default-build-mode-and-see-it-reflected-in-the-gui), but I'm ok with this just minimal change, i.e. I don't know CMake well enough to say what's the best approach is and what all the extra modifiers do...

**Comment by heckflosse** [comment]
@cryptomilk is a cmake specialist. Perhaps he can have a look...

**Comment by clanmills** [comment]
0.27-maintenance is frozen for now.

The code in both that CMake blog and FAQ makes me nervous.  I think "When you're in a hole, stop digging.".  I've brought the code into alignment with the documentation.

The error in the documentation is entirely mine.  I believed that the default was Release - and now my guess has been shown to be wrong.  As I mentioned on the chat server, I've never actually thought about this because CMAKE_BUILD_TYPE doesn't do anything on Visual Studio, CLion or Xcode.

It seems very unlikely that the build would default to Debug.  I suspect another invisible agent is at work somewhere.

I notice that the person who opened the issue has made no comment about the resolution and not shown any appreciation for the amazing team response to his ticket.

**Comment by kmilos** [comment]
@mergify backport 0.27-maintenance

**Pull request merged**
