### PR TITLE
More cleanup

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by D4N** [comment]
@clanmills Could you take a look at the proposed changes to `include/exiv2/tiffimage.hpp`? You have set the default value for `depth` in `printStructure` to `-1` in fd5e983746c336336039e91cb6b656cf8eeccdea, so I guess that was intentional or should it be changed to `0`?

**Review by piponazo — APPROVED** [review]
The changes look good! 👍

**Comment by D4N** [comment]
I have no objections to these changes, although I would like to @clanmills to take a look at the changes proposed in `include/exiv2/tiffimage.hpp`. Albeit it is a tiny detail, it could break client code.

**Comment by piponazo** [comment]
Since we are mentioning in #180 that we should mark the function `printStructure` as deprecated or even remove it, I would not continue blocking this PR . 

@tbeu if you fix the conflicts I will be happy to merge this branch.

**Comment by D4N** [comment]
@tbeu Could you rebase your changes on top of master & repush them? I think we can merge this PR then.

**Comment by D4N** [comment]
@piponazo I have rebased & repushed the changes, could you take a look at them again (just so I didn't screw up anything)?

Also travis is consistently failing on ubuntu, I'll take a look at that.

**Pull request merged**
