### PR TITLE
Trivial PR to see if I understand the process

### PR DESCRIPTION
**Pull request by clanmills**
I’m trying to submit a PR with a trivial change to msvc/ReadMe.txt  I want to understand how to make this github/git beast work.  I’ve:
1) 656 rmills@rmillsmbp:~/gnu/github/clanmills/exiv2 $ git fetch --all
2) Made the changes with the editor
3) Committed the change to github.com/clanmills/exiv2

I'm trying to follow this:  https://help.github.com/articles/creating-a-pull-request-from-a-fork/

base-fork: exiv2/exiv2  base:master <- head-fork: clanmills/exiv2 compare:master

### CODE REVIEW

**Comment by clanmills** [comment]
What does "This branch is out-of-date with the base branch" mean?

**Comment by D4N** [comment]
I see that there are some commits from PR #213 in here. I'll try to explain the process of a PR in more detail and then hopefully the "branch out of date" will be a little more clear.

The basic process behind a PR is just the following: person A wants to implement feature X, so they clone the repository, create a new branch where they develop feature X. Once the development is finished, they request that their development branch is merged into the master branch. This used to be done (and is also still done) via patches send around on mailings lists. However, GitHub is centered around the idea that you create a development branch for each PR (which is then merged into master) and it works a ton easier if you stick to that.

Git branches are different from branches that you know from subversion. Afaik branches in svn are more or less copies of the entire tree. In git branches are nothing more than "pointers" to a commit (the idea behind that is that you can have thousands of branches alongside each other). The git book shows this quite detailed with some pictures: https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell#_create_new_branch

With that out of the way, back to the PR. The idea is that you create a new branch that will start at the `HEAD` of the branch that you want to merge into (that is usually master). Assuming your repository is setup so that the remote `origin` points to `github.com/Exiv2/exiv2`, you can achieve it like this:
``` Bash
git fetch
git branch my_meaningful_branch_name origin/master
```
With the first command you update all remote branches, with the second you create a new branch starting at origin/master (that is the current state of exiv2/master). Now you can switch to the new branch and start working:
``` Bash
git checkout my_meaningful_branch_name
# do some work now
git commit
# more work
git commit
```
Now you have 2 additional commits in your **local** branch `my_meaningful_branch_name`, i.e. this branch exists only on your machine. You can create a new branch on Github via:
``` Bash
git push -u origin name_of_my_branch_on_origin
```
There are a few things to note here:
1. `name_of_my_branch_on_origin` is the name of `my_meaningful_branch_name` on the remote origin (that would be github). Those two don't have to be the same, but it is a good idea
2. the `-u` flag sets `name_of_my_branch_on_origin` as the upstream branch, i.e. next time you commit something and push it, you won't have to specify to which branch to push (most times you want it that way)

Now the commits are on github and you can create the PR via the web UI.

Concerning the "branch out of date" message and the additional commits from #213, this is probably caused by you only working on the master branch of your fork and submitting PRs from it. That is possible, but it makes things unnecessarily complicated (on my private fork of exiv2 I don't use the master branch at all, I create new branches from origin/master).

Consider the following initial commit situation:
```
a -> b -> c (master)
```
(a, b, c are commits)

You create a new branch starting at c, and create the commit d while someone pushes commit e to master. Now the situation looks like this:
```
           /-> d (your branch)
a -> b -> c -> e  (master)
```
This is now the "branch out of date" situation. The issue is, that now you might not be able to cleanly merge `your branch` on top of master. That's what github is trying to tell you.

The leftover commits from #213 are caused by something similar. You were working in your master branch and added some commits:
```
      /-> c -> d -> e (your master branch)
a -> b (master)
```
I then squashed all commits c, d & e from your master branch, creating commit f and pushed it to master (that sounds complicated, but I just clicked the button on github). The situation now looks like this:
```
      /-> c -> d -> e (your master branch)
a -> b -> f (master)
```
Then you want to make another PR and start working on your master branch again adding a commit g:
```
      /-> c -> d -> e -> g (your master branch)
a -> b -> f (master)
```
Now github takes a look when your master branch branched of from master. That happened before you started working on the first PR (#213) and so it happily puts all commits since that point into the PR. The branch is also out of date, because it does not contain commit f (which is actually a combination of c, d and e, thus you could easily merge them).

How can you avoid these issues:
1. Every time you start a PR, fetch everything & create a new branch starting at origin/master
2. Push the branches to exiv2/ and not to clanmills/. Conceptually there is no difference, but the other devs can write branches on exiv2/ but not on clanmills/. So we could help you in case something breaks.
3. If the branch should become "out of date" due to pushes to master, please run a `git pull --rebase origin master` in your PR branch. While this runs a scary rebase, it keeps the commit history linear in contrast to frequent merges (run `git log --oneline --graph` on your own master branch and you'll see what I mean). You have to do that only once before finally merging a PR (or ask someone else to do it, if the commits are on exiv2/).

If you'll have some time, I would recommend reading the first 3 chapters of the [git book](https://git-scm.com/book/en/v2/).

**Comment by clanmills** [comment]
Dan:  Thanks for all those notes.  Wow.  You've taken the time to explain this. Thank You.  I have the "Pro Git" book on my desk.  I couldn't understand it when I got it in September.  I'll read it again and in view of a little experience with git, I will be able to understand the book.

I'm off today and tomorrow training in the Hills.  It's likely to be Monday before I can tackle this.

I've no idea how that stuff relating to #213 **_MemIo::reserve()_** ended up in the PR.  I thought that was submitted.

**Comment by clanmills** [comment]
I'm going to study Dan's advice and start this effort again from the beginning.  I'm not going to "Close" this PR at the moment because it's convenient to have it in the "current PRs".  However I will close this in a day or two and start again.  My goodness, I have been warning by several folks that git is hard to understand.

**Comment by clanmills** [comment]
Dan:  Right.  I shouldn't be working with the fork clanmills/exiv2 - that has complicated matters.  I think Luis said I should be using a fork.  What I should do is to work on exiv2/exiv2 and create a branch, commit it and create a PR.  You review/approve the change.  I assume somebody will remove stale branches.

**Comment by D4N** [comment]
Whether you work on your fork or on exiv2/ does not make a huge difference: the only one is that I and the other devs have write access to branches on exiv2. The takeaway point is: when you start a PR, create a new branch starting at origin/master, not on your local copy of master (as they can differ).

**Comment by clanmills** [comment]
Thanks, Dan.  I dealt with the code last night.  I'll submit it this morning.

**Comment by clanmills** [comment]
I'm going to close this.  Dan's notes are very useful indeed and I've copied them to the Redmine Wiki.  http://dev.exiv2.org/projects/exiv2/wiki/Creating_a_PR_on_GitHub   I'll study and update those notes in the next few days.

**Pull request closed without merging**
