### PR TITLE
clang-tidy: pass by value

### PR DESCRIPTION
**Pull request by neheb**
Found with modernize-pass-by-value

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Only codecov fails. No idea about that.

**Review by FUCKher24 — CHANGES_REQUESTED** [review]
-   [vv__]()

**Comment by FUCKher24** [comment]
> Only codecov fails. No idea about that.

**Review by piponazo — APPROVED** [review]
I was not very convinced initially about this change, but after reading the clang dedicated page, I see its value:

https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html

Thanks!

**Pull request merged**
