### PR TITLE
Cppcheck issues

### PR DESCRIPTION
**Pull request by piponazo**
In this PR I am fixing more issues reported by cppcheck in the 0.27 branch (related with #474). 

Please, consider to review the changes commit by commit, so that you can be focus on one issue at time. 

If approved, I will also propagate these changes to master.

### CODE REVIEW

**Comment by clanmills** [comment]
This is "heavy duty" stuff.  Thousands of changes, mostly cosmetic.   The build passes the test suite, so we haven't knowingly damaged the code.

Doing this to the 0.28 branch makes sense as I believe you're going to reformat all the code with clang-tidy.  Sweeping 0.28 aggressively makes sense.

Should we do this to the 0.27 code base?  I'm not sure.  For sure, we'll have trouble when users submit patches.  I hoped "the dots" would be minor code changes (a few lines here and there, and mostly for security).  Perhaps we should leave this for a while months and do this for 0.27.3 (September 2019).

I'm going to ask Dan to be "tie breaker".  @D4N what do you think about cppchecks and 0.27 
1) Do this for v0.27.1
2) Do this later v0.27.3
3) Never do this to the the v0.27 code base.
4) Another other suggestion?

I'm sure Gilles would say we should have done this immediately he talked about this after RC1.  I would have resisted because we were already fully loaded with work.

**Comment by piponazo** [comment]
I completely agree with your analysis. However I thought we could benefit from some of these small improvements in the code in 0.27, and this will make our life easier when porting other changes from 0.27 to master (in case we apply the cppcheck fixes only in master and not in 0.27).

Since most of the changes are mostly cosmetics, I think there is not much risk of breaking something here, and therefore I would vote for applying the changes to both branches. However if you and @D4N think that it is safer to just apply them in master, I will accept it ;).

What I would not like to do is to wait to much to apply the changes to either of the branches. Otherwise I will need to fix synchronisation issues, etc.

**Comment by clanmills** [comment]
I think we should delay this until after 0.27.1  If we change so many files in "dot one", we're sending a very negative message to users.  Let's get "dot one" out and I'll document our "deprecation policy" and say we're going to give the code a "massive spring clean" for "dot two" to for better alignment with "0.28".

The schedule for "dot one" is March 31.   I will aim for March 15.  It can't be sooner because we're going the States January 23-February 22.

**Comment by piponazo** [comment]
Alright, I'll apply them to master then.

**Pull request closed without merging**
