### PR TITLE
Use double type to improve floating point accuracy

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Attempt to fix this: https://github.com/Exiv2/exiv2/pull/2514#issuecomment-1441013736

@neheb

### CODE REVIEW

**Comment by neheb** [comment]
if you want to test this locally, create a Dockerfile file with

```
FROM i386/debian

RUN apt update; apt install -y cmake g++ clang make libexpat1-dev zlib1g-dev libbrotli-dev libssh-dev libcurl4-openssl-dev libgtest-dev libxml2-utils libinih-dev python3-dev git gettext libgmock-dev libgtest-dev neovim vim nano && \
  git clone -b print0x0007-float https://github.com/kevinbackhouse/exiv2 && \
  cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DEXIV2_ENABLE_NLS=TRUE -DEXIV2_BUILD_SAMPLES=TRUE -DEXIV2_ENABLE_WEBREADY=ON -DEXIV2_ENABLE_CURL=ON -DEXIV2_ENABLE_VIDEO=ON -DEXIV2_BUILD_SAMPLES=ON -DEXIV2_BUILD_UNIT_TESTS=ON -DEXIV2_TEAM_EXTRA_WARNINGS=ON && \
  cmake --build . --parallel && \
  ctest . -VV
```

run
```
docker build -t test-image -f Dockerfile
```

and see what the issues are. Alternatively get rid of the cmake stuff and just do

```
docker run -it test-image
```

to experiment.

AFAIK the reason 32-bit tests are disabled in CI has to do with an old version of Python being unreliable on Windows.

**Comment by neheb** [comment]
```
6: ======================================================================
6: ERROR: issue_1912_poc.jpg_test (test_regression_allfiles.TestAllFiles)
6: ----------------------------------------------------------------------
6: Traceback (most recent call last):
6:   File "/exiv2/tests/regression_tests/test_regression_allfiles.py", line 191, in test_func
6:     BT.reportTest(os.path.basename(filename), out)
6:   File "/exiv2/tests/bash_tests/utils.py", line 567, in reportTest
6:     raise RuntimeError('\n' + log.to_str())
6: RuntimeError: 
6: [ERROR] The output of the testcase mismatch the reference
6: [INFO] The output has been saved to file /exiv2/test/tmp/issue_1912_poc.jpg.out
6: [INFO] simply_diff:
6: /exiv2/test/data/test_reference_files/issue_1912_poc.jpg.out: 53 lines
6: /exiv2/test/tmp/issue_1912_poc.jpg.out: 53 lines
6: The first mismatch is in line 49:
6: < Exif.GPSInfo.GPSTimeStamp                    Rational    3  1131375984/1869505902 1950679091/1 18/1  05:56:36.6
6: > Exif.GPSInfo.GPSTimeStamp                    Rational    3  1131375984/1869505902 1950679091/1 18/1  06:47:36.6
6: 
6: ----------------------------------------------------------------------
6: Ran 321 tests in 23.678s
6: 
6: FAILED (errors=1)
```

**Comment by kevinbackhouse** [comment]
@neheb: I think this is caused by a compiler optimization on x86 not bothering to cast down to float. The test passes on a debug build, but not on a release build. I've added a second commit which I think will fix it.

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
Fixed. 4 other failures remain.

**Pull request merged**
