### PR TITLE
Fix 220

### PR DESCRIPTION
**Pull request by clanmills**
Dan:  I hope I've finally got this correct.  There are three things is the PR:
1) The changes for #220 (including test harness fix)
2) I've modified test/Makefile to report errors without exiting (I know this test/bugfixes.sh will soon be history)
3) I've "thrown in" changes to msvc/ReadMe.txt (fixes to trivial typos)

### CODE REVIEW

**Comment by D4N** [comment]
Uhm, I do not think it is a good idea to ignore the errors from the current test suite. Although the bugfixes-test.sh is going to disappear, the other tests are probably not, at least not soon. It already happened twice that regressions made it into the code base, because the CI passed although the testsuite failed.

Also, why are you adding the error silencing with this PR? The build on travis reports that it is fine.

**Comment by D4N** [comment]
Otherwise this looks very good. Very good that you found a workaround so that we do not have to touch `bugfixes-test.out`!

**Comment by clanmills** [comment]
There's a misunderstanding about "ignoring errors".  I mean that test harness does not terminate on the first error.  It will run every test and take the error exit if any errors have been found.  I have a modified version of test/Makefile that implements this concept:
```
test:
	mkdir -p tmp
	rm -rf tmp/test-failed
	@list='$(TESTS)'; for p in $$list; do \
	    echo Running $$p ...; \
	    ./$$p;  \
	    rc=$$?; \
	    if [ $$rc -ne 0 ]; then echo '***' ; echo '***' $$p result = $$rc ; echo '***'       ; fi ; \
	    if [ $$rc -ne 0 ]; then              echo '***' $$p result = $$rc >> tmp/test-failed ; fi ; \
	done
	make newtests
	@if [ -e tmp/test-failed ]; then echo '***' FAILED ; cat tmp/test-failed ; echo '***' ; exit 911; fi

newtests:
	( if [ -e bin/exiv2 ]; then PATH=$$PWD/bin/build ; fi ; cd ../tests ; env EXIV2_PATH=$$(dirname $$(which exiv2)) python3 runner.py --verbose )
```

**Comment by D4N** [comment]
Ah, I see. Can you push the new snippet too, so that the whole thing is complete?

Btw, love the `exit 911` :-D (unfortunately POSIX dictates that return values are between 0 and 255, so it gets wrapped to 146, you could include the European emergency number 112, that'll work^^ )

**Comment by clanmills** [comment]
OK Let's return 255. 

Can you submit the code with the little patch above.  It's a really wet day in England, so I won't be going out for a run.  I'm going to do some work on the test harness to use mcdamo's test files.  I'll ask you to review it and we can discuss what I'm thinking.

I'm going to raise a new issue concerning the Exiv2 Developer's Meeting.  It looks as though we've lost Luis and that's a great pity because he's a nice guy and outstanding engineer.  Moreover, I believe learning more about metadata could be hugely beneficial to his career.

**Comment by D4N** [comment]
Robin Mills <notifications@github.com> writes:

> OK Let's return 255. 
>
> Can you submit the code with the little patch above.  It's a really wet day in England, so I won't be going out for a run.  I'm going to do some work on the test harness to use mcdamo's test files.  I'll ask you to review it and we can discuss what I'm thinking.
>

I have just checked Travis and it is currently running the new tests
twice, as I have added them to .travis/run.sh.

Also Travis reports :
~~~~~~~~~~~~~~~~~
dirname: missing operand
Try 'dirname --help' for more information.
~~~~~~~~~~~~~~~~~
in the output just before the new tests are being run (for Linux).

I tried the makefile locally on my machine and it is not working
there. The issue is, that I have installed exiv2 via the package
manager, so dirname $(which exiv2) returns /usr/bin for me (and nothing
on travis, as exiv2 is not installed there).

However, I don't think you need to set EXIV2_PATH for runner.py on
Linux/Unix, as the default is already correct.

> I'm going to raise a new issue concerning the Exiv2 Developer's Meeting.  It looks as though we've lost Luis and that's a great pity because he's a nice guy and outstanding engineer.  Moreover, I believe learning more about metadata could be hugely beneficial to his career.
>

That's a pity :(

**Pull request merged**
