### PR TITLE
fix_1353_mingw_toolchain_0.27 (0.27->master)

### PR DESCRIPTION
**Pull request by clanmills**
See #1353.  Thank You to @gaaned92 for an insight into the twilight zone where mingw meets msys.

### CODE REVIEW

**Comment by clanmills** [comment]
I've screwed up.  I should not have merged the PSD changes into 0.27-maintenance #1342 without updating tests/bash_tests/testcases.py  I will disable function exiv2-test() in testcases.py for the moment.

**Comment by clanmills** [comment]
WTF!  What's going on?  This shouldn't be merged until the CI goes great.  I'm tired and making mistakes.  I'll deal with this tomorrow.

**Comment by piponazo** [comment]
Do not worry about this PR being merged by accident. Most of the changes were documentation changes, and the ones in `http.cpp` are harmless. I will test this directly on 0.27-maintenance and if something is not accurate we can change it in other PR.

**Comment by clanmills** [comment]
Everything is OK.  0.27-maintenance passes the test suite.  I'm open a new issue about exiv2-test() in tests/bash_tests/testcases.py.   We are running both the "old/genuine" bash_tests in test/*.sh and the new pythonic tests/bash_test.  Exiv2 is good, it's the new pythonic tests that are not up-to-date with #1342.

**Comment by piponazo** [comment]
I validated the documentation changes in this PR. I could build 0.27-maintenance with MSYS2 without issues 👍

**Comment by clanmills** [comment]
I've been tried unsuccessfully to build cmake with the mingw toolchain.  ./bootstrap takes about 15 minutes to say _**wrongly**_ that cc can't compile and link a simple program.  What is  ./boostrap?  It might be a wrapper for auto tools ./configure!  What doesn't cmake use cmake to build itself?

I've made a little progress with conan on MinGW/msys2.   I've discovered that it uses $USERPROFILE to locate the profiles (USERPROFILE is a Windows env string).    conan doesn't like GCC 10.2 (he's OK with 10.1).  `$ conan install .. --build missing` attempts to build expat and dies with a meaningless error message.  I'll update #1224 with those findings.  I don't think we'll be able to get conan to build on MinGW/msys2 or Cygwin64.

**Pull request merged**
