### PR TITLE
Cmake cleanups

### PR DESCRIPTION
**Pull request by piponazo**
In this PR I made a final pass over the CMake code before the 0.27 release. For more details, check each commit individually.

### CODE REVIEW

**Review by clanmills — APPROVED** [review]
This all seems very good and tidy.  And I like how you have eliminated mysterious stuff such as the FREEBSD variable.

I'm unsure about the curl related code.  http.cpp can be implement HttpIo in two ways.  When curl is available, it uses it.  When it's not available, it has a simple HTTP handler.  This enables every version of exiv2 to use the HttpIo object.   When you build with __webready__, you link libcurl and get http, https, ftp and other remote protocols.  Without __webready__, you still get http support.

A tiny comment.  When you're listing two files on a single line, can you lay the code out in columns for easy reading.  Example:
```
     foo.cpp           foo.hpp
     something.cpp     something.hpp
```

I dealt with the documentation this morning and am working in the garden this afternoon.  I only have Gilles XMP/Region #521 to investigate and I'm ready for RC2 tomorrow.

Can you merge (or whatever you do) so that I can `git pull --rebase` (on 0.27-RC2).  I'll build and test everything.

I'll put the code fix for XMP/Region #521 into the issue report.  I don't care if the fix gets into RC2 or not as I believe that bug's been in the code for about 10 years!

**Comment by piponazo** [comment]
Thanks @clanmills for your feedback. I did the alignment in the CMakeLists.txt file, it is a good idea.

Regarding the CURL changes, the most relevant thing I did was to remove this block:

```
#ifdef EXV_USE_CURL	
#include <curl/curl.h>	
#endif
```
from `include/exiv2/http.hpp`. I think there is no reason to expose that header in a public header, since CURL is just used internally in the library. Or am I missing something?

**Comment by clanmills** [comment]
I can't remember why that's there.  It's been there since 2013.  Undoubtably needed at the time.  My only concern was that we can build with/without curl.  I've just tested this and it's working on ubuntu 18.04 and MacOS-X.

Localisation appears broken on Ubuntu (OK on MacOS-X).  I'll keep investigating.

I think we're done on this PR.  Can you close it when  you're ready, please?

**Comment by piponazo** [comment]
Sure, I'll merge it once the CI turns green. 

About the localisation stuff, it is working on my side under Ubuntu 18.04. Feel free to tell me what is happening to you (via Slack)

**Pull request merged**
