### PR TITLE
Improve printing of GPS info

### PR DESCRIPTION
**Pull request by kmilos**
Addresses #1541

### CODE REVIEW

**Review by clanmills — DISMISSED** [review]
Thanks, Milos.  That looks fine.  Thank You for dealing with this.

**Review by clanmills — APPROVED** [review]
This looks good.  A few comments:

1 Converting rationalToFloat()

I'm a little surprised that so much code is necessary in printDegrees().  Is there a lesson to be learned here.  There is a API:

```cpp
EXIV2API Rational floatToRationalCast(float f);
```

I thought there are one to convert rationalToFloat(), or Long, or Double.  I can't find it. Is there something special and unusual about degrees() such as doing arithmetic on several values.

2.  Is the result the same as ExifTool?

3. Well spotted that I put "knots" in the man page.  It should of course be nautical miles.

**Comment by kmilos** [comment]
> Is there something special and unusual about degrees() such as doing arithmetic on several values.

There are two ways of lat/lon encoding w/ 3 RATIONALs according to Exif spec: integer degrees and minutes and then anything goes for seconds (integer or fractional) like [ DD/1, MM/1, SS/1 or SSSS/frac], or fractional minutes with seconds "unused" [ DD/1, MMMM/frac, 0/1 ]. We need to convert the second case (I chose to make it fit the first one), and then print consistently in the usual degree/minute/second format...

> Is the result the same as ExifTool?

One exception: ExifTool prints `.00"` even when seconds are integers...

**Comment by clanmills** [comment]
Right.  You've got your head round this one.  That cosmetic difference with ExifTool seems OK to me.  I'm happy for you to merge.

**Comment by clanmills** [comment]
Let's agree on a team convention.   The person who opens a PR also does the merge.  Why?  Because if you suddenly think of a modification to the PR, you can update it before merging.

**Comment by kmilos** [comment]
Thanks. Fine by me.

**Pull request merged**
