### PR TITLE
Check if the metadata is NULL

### LINKED ISSUE #2638: Seg. fault - Geeqie with 0.28.0 and certain .nef files
#### **Describe the bug**
When Geeqie is compiled with exiv2 0.28.0, viewing the exif data of certain files cause a crash. This occurs with .nef files from my camera, but not with downloaded test .nef files.
The fault does not occur with earlier versions of exiv2.
#### **To Reproduce**

Compile Geeqie with exiv2 0.28.0. Run and load the attached .nef file. Open the Exif Window.

Attached is a sample image from my camera (copyright free)
The stack trace after the seg. fault which includes some debug output prior to the crash
The source code of the two Geeqie files involved.

#### **Desktop (please complete the following information):**
Ubuntu 23.04
Exiv2 0.28.0 via `meson wrap install exiv2`
gcc version 12.2.0 (Ubuntu 12.2.0-17ubuntu1)
meson warning level 3

[2019-12-23-11:21:44-DSC_3328.NEF.gz](https://github.com/Exiv2/exiv2/files/11584579/2019-12-23-11.21.44-DSC_3328.NEF.gz)
[exiv2.cc.gz](https://github.com/Exiv2/exiv2/files/11584580/exiv2.cc.gz)
[advanced-exif.cc.gz](https://github.com/Exiv2/exiv2/files/11584581/advanced-exif.cc.gz)
[exiv2-028-1-log.txt.gz](https://github.com/Exiv2/exiv2/files/11584582/exiv2-028-1-log.txt.gz)

### LINKED ISSUE #2649: Gwenview crashes in Exiv2::Internal::Nikon3MakerNote::printFlashMasterDataFl7 when opening .nef image
#### **Describe the bug**
See https://bugs.kde.org/show_bug.cgi?id=470880 

```
#0  0x00007ffff653c87b in std::__cxx11::list<Exiv2::Exifdatum, std::allocator<Exiv2::Exifdatum> >::begin (this=0x0) at /usr/include/c++/13/bits/stl_list.h:1033
#1  0x00007ffff666be18 in Exiv2::ExifData::findKey (this=0x0, key=...) at /home/nico/workspace/exiv2/src/exif.cpp:457
#2  0x00007ffff6567d73 in Exiv2::Internal::Nikon3MakerNote::printFlashMasterDataFl7 (os=..., value=..., metadata=0x0) at /home/nico/workspace/exiv2/src/nikonmn_int.cpp:3423
#3  0x00007ffff6669d3d in Exiv2::Exifdatum::write (this=0x7fff9809d8c0, os=..., pMetadata=0x0) at /home/nico/workspace/exiv2/src/exif.cpp:187
#4  0x00007ffff7d10e91 in Exiv2::operator<< (os=..., md=...) at /home/nico/kde/usr/include/exiv2/metadatum.hpp:277
#5  0x00007ffff7d12ab2 in Gwenview::ImageMetaInfoModelPrivate::fillExivGroup<Exiv2::ExifData, std::_List_const_iterator<Exiv2::Exifdatum> > (this=0xcba4d0, parent=..., group=0xcba4b0, container=...)
    at /home/nico/kde/src/gwenview/lib/imagemetainfomodel.cpp:282
#6  0x00007ffff7d10136 in Gwenview::ImageMetaInfoModel::setExiv2Image (this=0x7fffdc0022d0, image=0x7fff98001960) at /home/nico/kde/src/gwenview/lib/imagemetainfomodel.cpp:441
#7  0x00007ffff7cbfc49 in Gwenview::Document::setExiv2Image (this=0xcba9e0, image=std::unique_ptr<Exiv2::Image> = {...}) at /home/nico/kde/src/gwenview/lib/document/document.cpp:388
#8  0x00007ffff7cbce1d in Gwenview::AbstractDocumentImpl::setDocumentExiv2Image (this=0xcbaa90, image=std::unique_ptr<Exiv2::Image> = {...})
    at /home/nico/kde/src/gwenview/lib/document/abstractdocumentimpl.cpp:81
#9  0x00007ffff7cc9665 in Gwenview::LoadingDocumentImpl::slotMetaInfoLoaded (this=0xcbaa90) at /home/nico/kde/src/gwenview/lib/document/loadingdocumentimpl.cpp:497
#10 0x00007ffff7cce7ce in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gwenview::LoadingDocumentImpl::*)()>::call(void (Gwenview::LoadingDocumentImpl::*)(), Gwenview::LoadingDocumentImpl*, void**) (f=(void (Gwenview::LoadingDocumentImpl::*)(Gwenview::LoadingDocumentImpl * const)) 0x7ffff7cc94f2 <Gwenview::LoadingDocumentImpl::slotMetaInfoLoaded()>, o=0xcbaa90, arg=0x7fffffffcc50)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:152
#11 0x00007ffff7cce050 in QtPrivate::FunctionPointer<void (Gwenview::LoadingDocumentImpl::*)()>::call<QtPrivate::List<>, void>(void (Gwenview::LoadingDocumentImpl::*)(), Gwenview::LoadingDocumentImpl*, void**)
    (f=(void (Gwenview::LoadingDocumentImpl::*)(Gwenview::LoadingDocumentImpl * const)) 0x7ffff7cc94f2 <Gwenview::LoadingDocumentImpl::slotMetaInfoLoaded()>, o=0xcbaa90, arg=0x7fffffffcc50)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:185
#12 0x00007ffff7ccd955 in QtPrivate::QSlotObject<void (Gwenview::LoadingDocumentImpl::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0xcbe880, 
    r=0xcbaa90, a=0x7fffffffcc50, ret=0x0) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:418
#13 0x00007ffff44e8651 in QtPrivate::QSlotObjectBase::call (a=0x7fffffffcc50, r=<optimized out>, this=0xcbe880) at ../../include/QtCore/../../src/corelib/kernel/qobjectdefs_impl.h:398
#14 doActivate<false> (sender=0xcb55c8, signal_index=4, argv=0x7fffffffcc50) at kernel/qobject.cpp:3923
#15 0x00007ffff44e34d7 in QMetaObject::activate (sender=<optimized out>, m=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3983
#16 0x00007ffff42ff5d5 in QFutureWatcherBase::event (this=<optimized out>, event=0x7fff980a5460) at thread/qfuturewatcher.cpp:334
#17 0x00007ffff53aeb75 in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0xcb55c8, e=0x7fff980a5460) at kernel/qapplication.cpp:3640
#18 0x00007ffff44b3d48 in QCoreApplication::notifyInternal2 (receiver=0xcb55c8, event=0x7fff980a5460) at kernel/qcoreapplication.cpp:1064
#19 0x00007ffff44b3f62 in QCoreApplication::sendEvent (receiver=<optimized out>, event=<optimized out>) at kernel/qcoreapplication.cpp:1462
#20 0x00007ffff44b71f5 in QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0x4fd480) at kernel/qcoreapplication.cpp:1821
#21 0x00007ffff44b74ad in QCoreApplication::sendPostedEvents (receiver=<optimized out>, event_type=<optimized out>) at kernel/qcoreapplication.cpp:1680
#22 0x00007ffff4506e2f in postEventSourceDispatch (s=0x5664a0) at kernel/qeventdispatcher_glib.cpp:277
#23 0x00007ffff318b39c in g_main_dispatch (context=0x7fffdc000ee0) at ../glib/gmain.c:3460
#24 g_main_context_dispatch (context=0x7fffdc000ee0) at ../glib/gmain.c:4200
#25 0x00007ffff31e9438 in g_main_context_iterate.isra.0 (context=0x7fffdc000ee0, block=1, dispatch=1, self=<optimized out>) at ../glib/gmain.c:4276
#26 0x00007ffff3188a23 in g_main_context_iteration (context=0x7fffdc000ee0, may_block=1) at ../glib/gmain.c:4343
#27 0x00007ffff4506919 in QEventDispatcherGlib::processEvents (this=0x5669e0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#28 0x00007ffff44b270b in QEventLoop::exec (this=this@entry=0x7fffffffd0c0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:69
#29 0x00007ffff44ba99b in QCoreApplication::exec () at ../../include/QtCore/../../src/corelib/global/qflags.h:121
#30 0x000000000047a3b1 in main (argc=2, argv=0x7fffffffd3d8) at /home/nico/kde/src/gwenview/app/main.cpp:213
```

#### **To Reproduce**
Open this image in Gwenview: https://mega.nz/file/j3RGELSa#wMs5nJ-HlrMZrjytiC9NkESXF6TRIIVzPDlZsa-uI3E

A short description of what you expected to happen.

#### **Desktop (please complete the following information):**
- OS and version: Fedora 38
- Exiv2 version and source: 0.28.0, master
- Compiler and version: GCC 13.1.1
- Compilation mode and/or compiler flags: Debug

#### **Additional context**
0.27.7 works fine

### PR DESCRIPTION
**Pull request by kevinbackhouse**
Fixes: #2638, #2649

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
I've converted this to draft because I'd like to merge #2664 first.

**Comment by kevinbackhouse** [comment]
@Mergifyio backport 0.28.x

**Review by postscript-dev — CHANGES_REQUESTED** [review]
@kevinbackhouse 
Thanks for creating this PR. I started to look at this but your work saves me some time!

I reviewed all the tags and, as far as I could see, the only guards needed were in [src/nikonmn_int.cpp](https://github.com/Exiv2/exiv2/blob/6b186a4cd276ac11b3ea69951c2112f4c4814b9a/src/nikonmn_int.cpp#L1C1-L1C1) and [src/sonymn_int.cpp](https://github.com/Exiv2/exiv2/blob/6b186a4cd276ac11b3ea69951c2112f4c4814b9a/src/sonymn_int.cpp#L1C1-L1C1). 

For your PR, in [src/sonymn_int.cpp](https://github.com/Exiv2/exiv2/blob/6b186a4cd276ac11b3ea69951c2112f4c4814b9a/src/sonymn_int.cpp#L1C1-L1C1), I would also add `|| !metadata` guards for functions that use:
1. [static auto getModel(const ExifData* metadata, std::string& val)](https://github.com/Exiv2/exiv2/blob/6b186a4cd276ac11b3ea69951c2112f4c4814b9a/src/sonymn_int.cpp#L640)
2. [static auto getAFAreaModeSetting(const ExifData* metadata, uint32_t& val)](https://github.com/Exiv2/exiv2/blob/6b186a4cd276ac11b3ea69951c2112f4c4814b9a/src/sonymn_int.cpp#L671)
3. [static auto getMetaVersion(const ExifData* metadata, std::string& val)](https://github.com/Exiv2/exiv2/blob/6b186a4cd276ac11b3ea69951c2112f4c4814b9a/src/sonymn_int.cpp#L701)
4. [static auto getFocusMode2(const ExifData* metadata, uint32_t& val)](https://github.com/Exiv2/exiv2/blob/6b186a4cd276ac11b3ea69951c2112f4c4814b9a/src/sonymn_int.cpp#L715)

**Comment by kevinbackhouse** [comment]
Good catch @postscript-dev! I've updated #2664 to catch those cases too. And I've added a second commit here with the extra fixes.

**Review by postscript-dev — APPROVED** [review]

**Review by neheb — APPROVED** [review]

**Pull request merged**
