### PR TITLE
a couple of clang-tidy fixes

### PR DESCRIPTION
**Pull request by neheb**
For the second one I added some manual changes. clang-format did the rest.

### CODE REVIEW

**Comment by hassec** [comment]
Hi @neheb, 

This is quite a large PR mixing a few things.   
IMHO, it would be better to not mix code changes + clang tidy + clang format.      
Having them in separate PRs if possible or at least separate commits makes review much easier.   

Then re the formatting, AFAIK there isn't really an agreed formatting convention. I think this is one of the ToDo's.  
So it's probably better to not right now apply formatting to lines you otherwise don't touch. It only adds noise to the review.   

Also, it probably makes sense to do separate PRs for each clang-tidy modernization.     
Again, that makes it easier to review, and also easier to decide which ones we want to keep.

**Comment by neheb** [comment]
The formatting thing is necessary as clang-tidy does the transformations in a weird way.

**Comment by hassec** [comment]
There are multiple places where something is only formatted that isn't changed by clang-tidy.

**Comment by neheb** [comment]
Split into separate PR.

**Pull request closed without merging**
