### PR TITLE
clang-tidy: use uppercase numeric literals

### PR DESCRIPTION
**Pull request by neheb**
Found with readability-uppercase-literal-suffix

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by hassec** [comment]
Hey @neheb, thanks for taking the time to create all these clang-tidy fixes :)   

I'm not sure that I'm convinced yet that this specific one is necessary.   
Does this really improve anything for people working on the codebase? I'd argue, probably not.  
Additionally, how are we going to enforce this in the future?     
We'd have to run clang-tidy as a check for this, which seems overkill... 
just my 2 cents, WDYT @piponazo

**Comment by neheb** [comment]
well, it's a style thing. no need to enforce I think.

**Comment by hassec** [comment]
Well if we don't enforce it, then let's stick with the lowercase, as I think that's what most people use.  
Otherwise we just end up with a mix of upper and lower case which is even worse...

**Review by piponazo — APPROVED** [review]

**Comment by piponazo** [comment]
I do not have a strong preference over one or another, but normally all these clang-tidy rules are created when there are good reasons for them. In this case:

https://reviews.llvm.org/D52670

```
References:

CERT DCL16-C
MISRA C:2012, 7.3 - The lowercase character "l" shall not be used in a literal suffix
MISRA C++:2008, 2-13-4 - Literal suffixes shall be upper case
```

Probably we could enforce such things by having a CI job checking if certain clang-format options are satisfied. But I am not sure if there would be certain clang-format option enforcing this specific rule.

For me, it is fine to proceed with this change, but let's give some time so that others can give their opinions/thoughts about this.

**Pull request merged**
