### PR TITLE
Add missing dependency to expat in export set

### PR DESCRIPTION
**Pull request by Ryanf55**
Solves #2726

Once approved, please backport to `0.28.x`

Note: This work was done on behalf of[ AeroVironment Inc.](https://www.avinc.com/)

### CODE REVIEW

**Comment by neheb** [comment]
none of this cmake config stuff makes any sense to me:

```
$ cat ./meson-private/exiv2.pc
prefix=/usr/local
includedir=${prefix}/include
libdir=${prefix}/lib/arm-linux-gnueabihf

Name: exiv2
Description: Exif/IPTC/Xmp C++ metadata library and tools plus ICC Profiles, Previews and more.
URL: https://exiv2.org
Version: 1.0.0
Requires.private: libbrotlidec, libcurl, expat, INIReader, zlib
Libs: -L${libdir} -lexiv2
Cflags: -I${includedir}
```

at least pkgconfig is clear.

**Comment by Ryanf55** [comment]
> none of this cmake config stuff makes any sense to me:
> 
> ```
> $ cat ./meson-private/exiv2.pc
> prefix=/usr/local
> includedir=${prefix}/include
> libdir=${prefix}/lib/arm-linux-gnueabihf
> 
> Name: exiv2
> Description: Exif/IPTC/Xmp C++ metadata library and tools plus ICC Profiles, Previews and more.
> URL: https://exiv2.org
> Version: 1.0.0
> Requires.private: libbrotlidec, libcurl, expat, INIReader, zlib
> Libs: -L${libdir} -lexiv2
> Cflags: -I${includedir}
> ```
> 
> at least pkgconfig is clear.

CMake does the same things, but separates build and usage requirements. Because most of the exiv2 deps are configurable to be used and part of the build, you get the extra complication, which doesn't see to be supported by the pkgconfig build. 

Also, isn't that why it's open source 😎

**Comment by neheb** [comment]
not sure I understand. Your PRs have made zlib and expat external dependencies of expat when they're really internal ones.

@eli-schwartz am i missing something here?

**Comment by eli-schwartz** [comment]
> CMake does the same things, but separates build and usage requirements. Because most of the exiv2 deps are configurable to be used and part of the build, you get the extra complication, which doesn't see to be supported by the pkgconfig build.
.,
Sounds like you are unaware of the meaning of the `Requires.private` keyword for pkgconfig. To be clear, a private dependency in pkgconfig is private linkage.

Since pkgconfig, when exporting an "imported interface library", exports both static and shared versions, the private linkage of expat is thus only used for the static version of exiv2. This is important, because if exiv2 is configured to make use of expat, linking to:
- libexiv2.so *does not* require linking with `-lexpat`
- libexiv2.a *does* require linking with `-lexpat`

There's really no way to get around this. But for cmake it "doesn't matter" since for cmake, installing both static and shared libraries "doesn't matter", so it is the expectation of the cmake build system that projects write their fooConfig.cmake.in files to be handcrafted to only make sense for static builds (or shared builds, as the case may be). This is a solvable problem, of course, because even though cmake decided that pkgconfig is NIH and they want to cast shade on it and tell people not to use it and use fooConfig.cmake files instead, you can just ignore that advice and use working technology, namely, cmake's `include(FindPkgConfig)` and `pkg_check_modules()`.

Regarding you latest push:

You mentioned in the linked ticket a few cmake-related resources discussing the topic, which all more or less boiled down to saying "yes, those are actually needed because you are statically linking, so you have to have them". But in this PR it seems you've switched approaches based on feedback, from always linking to expat even for shared builds, to trying to stop linking to expat *at all*. How is this supposed to work? Where will your static exiv2 library get its `XML_*` symbols from?

Always looking up expat is technically wrong, but simply looking up the library isn't going to result in incorrect linkage. *Never* looking up the library is definitely going to result in incorrect linkage.

**Comment by Ryanf55** [comment]
> > CMake does the same things, but separates build and usage requirements. Because most of the exiv2 deps are configurable to be used and part of the build, you get the extra complication, which doesn't see to be supported by the pkgconfig build.
> > .,
> > Sounds like you are unaware of the meaning of the `Requires.private` keyword for pkgconfig. To be clear, a private dependency in pkgconfig is private linkage.
> 
> Since pkgconfig, when exporting an "imported interface library", exports both static and shared versions, the private linkage of expat is thus only used for the static version of exiv2. This is important, because if exiv2 is configured to make use of expat, linking to:
> 
> * libexiv2.so _does not_ require linking with `-lexpat`
> * libexiv2.a _does_ require linking with `-lexpat`
> 
> There's really no way to get around this. But for cmake it "doesn't matter" since for cmake, installing both static and shared libraries "doesn't matter", so it is the expectation of the cmake build system that projects write their fooConfig.cmake.in files to be handcrafted to only make sense for static builds (or shared builds, as the case may be). This is a solvable problem, of course, because even though cmake decided that pkgconfig is NIH and they want to cast shade on it and tell people not to use it and use fooConfig.cmake files instead, you can just ignore that advice and use working technology, namely, cmake's `include(FindPkgConfig)` and `pkg_check_modules()`.
> 
> Regarding you latest push:
> 
> You mentioned in the linked ticket a few cmake-related resources discussing the topic, which all more or less boiled down to saying "yes, those are actually needed because you are statically linking, so you have to have them". But in this PR it seems you've switched approaches based on feedback, from always linking to expat even for shared builds, to trying to stop linking to expat _at all_. How is this supposed to work? Where will your static exiv2 library get its `XML_*` symbols from?
> 
> Always looking up expat is technically wrong, but simply looking up the library isn't going to result in incorrect linkage. _Never_ looking up the library is definitely going to result in incorrect linkage.

Thanks for the notes. I'll create a simple test executable that calls that indirectly calls the `XML_*` symbols. Then there won't be guesswork, and we can test both approaches recommended on the CMake issue.

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
aaaand this is why friend don't let friends use cmake.

**Comment by neheb** [comment]
@mergifyio backport 0.28.x

**Pull request merged**
