### PR TITLE
Update Sony(1|2) tags

### PR DESCRIPTION
**Pull request by postscript-dev**
Transcribe all tags (except for `LensID`) from main ExifTool Sony group into Exiv2.
Changes include:
- Rename `ColorReproduction` -> `CreativeStyle` and `LongExposureNoiseReduction` -> `FocusMode3` to reflect use.
- Rename `0x*` tagnames to equivalent ExifTool tags (e.g., `0x2006` -> `Sharpness`)
- Rename duplicate tagnames (e.g., `DynamicRangeOptimizer` (0xb04f) to `DynamicRangeOptimizer2`)
- Remove tag entries that are Groups (e.g., `ShotInfo`).
- Separate some common Sony/Minolta data as the camera types use different values (e.g., `Quality`)
- All `exiv2-Sony*.exv` and some `exiv2_pr2323-coverage*.exv` test files are from ExifTool Sony samples (https://exiftool.org/Sony.tar.gz).

ExifTool Sony tags sources:
https://www.exiftool.org/TagNames/Sony.html
https://github.com/exiftool/exiftool/blob/1e17485cbb372a502e5b9d052d01303db735e6fa/lib/Image/ExifTool/Sony.pm

### CODE REVIEW

**Comment by postscript-dev** [comment]
One tag in this PR that may be of interest to darktable developers is [ExifTool's Sony LensSpec tag (0xb02a)](https://www.exiftool.org/TagNames/Sony.html). This is set by compatible lenses and the translated output contains the focal length, aperture and some additional information (e.g., `SAM`, `Fish-eye`, etc). Incompatible lenses are translated as `Unknown`.

To test my PR, I have been using [ExifTool's Sony JPEG samples](https://exiftool.org/Sony.tar.gz) which contain examples of the many different Sony camera types. This sample set includes lots of different lens examples, most of which, exiv2 can read. If I process the files with

```bash
$ exiv2 -Pxkvt -K Exif.Sony1.LensID -K Exif.Sony1.LensSpec *.jpg 2>/dev/null > exiv2-LensID_LensSpec_tags.txt
```

the [exiv2-LensID_LensSpec_tags.txt](https://github.com/Exiv2/exiv2/files/9310694/exiv2-LensID_LensSpec_tags.txt) file demonstrates the new tag.

The file shows that `LensSpec` produces output in circumstances where we don't have translations for `LensID`. In addition, `LensSpec` includes values for cameras which have a fixed lens and therefore don't have a `LensID` tag. For example, my fixed lens `Sony DSC-HX60V` camera has a `LensSpec` value of `24-720mm F3.5-6.3` which is also listed as the lens in Sony's PlayMemories Home software.

I wasn't planning to backport everything in this PR but I am willing to work on the `LensSpec` tag.

**Comment by postscript-dev** [comment]
Recently it was decided that we can add lenses to exiv2 without a corroborating image, so I looked at adding the ExifTool Sony/Minolta lenses. I formatted the ExifTool lenses into an exiv2 array and can now see that there are lots of differences.

As I don't have enough experience with lenses I don't plan to finish this task. If someone else wants to work on this, the formatted array is available in [exiftool_SonyMinolta-lens-in-exiv2-format.txt](https://github.com/Exiv2/exiv2/files/9328706/exiftool_SonyMinolta-lens-in-exiv2-format.txt). You can do a diff with the array in

https://github.com/Exiv2/exiv2/blob/3ac7608282ee28c87e1ee4cfb2f40d6945d389f3/src/minoltamn_int.cpp#L1027-L1030

to find the problems.

**Comment by kevinbackhouse** [comment]
@postscript-dev: I made one final suggestion in https://github.com/postscript-dev/exiv2/pull/6 and then I am happy with the code changes. (I'm not qualified to comment on the tag changes because I don't know anything about cameras!)

**Comment by postscript-dev** [comment]
@kevinbackhouse:
Thanks for the suggestion, I have made the changes.

**Review by kevinbackhouse — APPROVED** [review]

**Comment by postscript-dev** [comment]
@kevinbackhouse 
Thanks for taking the time to reviewing this, it was a big PR. As you are not confident about cameras tags, I will leave this for a couple of days to see if anyone else has comments. After that I plan to merge.

**Pull request merged**
