### PR TITLE
fix1001_rename_AFPrimaryPoint

### LINKED ISSUE #1001: Rename tag Exif.Canon.AFPrimaryPoint
#981 adds recognition for Canon AutoFocus Metadata.  The tag "Exif.Canon.AFPrimaryPoint" records points that should be ignored by the AutoFocus.

The name AFPrimaryPoint was chosen to align with ExifTool Documentation.  https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Canon.html

Suggestions (from @derselbst) for alternative names are "AFPointsDisabled" and "AFPointsUnusable"  If we agree on a change of tag name, this will be released in Exiv2 v0.27.4.  I don't want to delay Exiv2 v0.27.3 while this is discussed.

@boardhead Can you give us your opinion about this, please?

Here are Tom's notes about Canon AutoFocus Metadata.  https://github.com/Exiv2/exiv2/issues/981#issuecomment-524564157

### PR DESCRIPTION
**Pull request by clanmills**
Fix #1001

### CODE REVIEW

**Comment by clanmills** [comment]
@derselbst  I've invited you to join Team Exiv2 on Github.  I'd appreciate you reviewing both #1010 and #1001 and we can get them merged for release.

If you could review any of the other open PRs, I would appreciate your help.  v0.27.3 was scheduled to be released today and it has been stalled while waiting for reviews by team members.

**Review by derselbst — DISMISSED** [review]
Thx for the invitation. I had a look at this and it seems an appropriate fix for #1001. 

Unfortunately I cannot review the other open PRs as I'm on vacation this week, sry.

**Comment by clanmills** [comment]
Thanks Tom (@derselbst).  Enjoy your vacation.

This PR is effectively a correction to #988.  So I will have to wait for #988 to be approved.

**Comment by clanmills** [comment]
Tom

I know you're on vacation and I don't expect you to do anything this week about this message.  However, I've sent similar messages to some other folks, and it's convenient for me to send this now.

1) Approving Open PRs
I’d like to get Exiv2 v0.27.3 released (it was due on 2019-09-30). I’ve assigned you to review a couple of PRs.
https://github.com/Exiv2/exiv2/pulls?utf8=✓&q=is%3Apr+is%3Aopen+milestone%3Av0.27.3+review-requested%3Aderselbst

Dan’s busy moving house. When I last spoke to Luis (about 2 weeks ago), he said “hope to have more time for open-source later this year”.

Can you “review and approve” your PRs. I’d really like Dan and/or Luis to do this as they always think of something smart and clever. However, it’s more important to get this stuff released.

2) Team Exiv2 Riot/Matrix Chat Server
Can you send me your email address and I will invite you to join the Team Exiv2 Chat Server on Riot/Matrix. That’s how the team discusses stuff “off-line”. It will take up very little of your time, however you can speak directly to the Team or to a team member. You’ll find this useful. You won’t find it intrusive.

Enjoy your vacation.

**Comment by piponazo** [comment]
As I commented in #1015, I consider the test failing here:

```
FAIL: test_run (bugfixes.github.test_issue_987.tagListTest)
```

brittle and it will give us more headaches in the future ... I propose to remove it from `0.27-maintenance` and not merging it into master. If we agree on this I will take care of the changes.

**Comment by derselbst** [comment]
>I propose to remove it from 0.27-maintenance and not merging it into master. 

Agreed. I don't see a need for the tagList test either.

**Comment by derselbst** [comment]
@clanmills Thanks!

**Comment by clanmills** [comment]
I'm working on Exiv2 v0.27.3 which will include this fix. I'm aiming for a release candidate in early June and GM at the end of June 2020. This is a maintenance release of Exiv2 v0.27. The current version is v0.27.2 which was released on 2019-07-29.

**Pull request merged**
