### PR TITLE
Differentiate between public and private of the library

### PR DESCRIPTION
**Pull request by piponazo**
Note: please do not review the first two commits, these are part of another existing PR (#173). This branch is based on the other one.

This PR proposes two important changes to the code base:

1. Makes more explicit the private files of the library. The initial idea was to create an OBJECT library (CMake concept) with the private source code of **exiv2lib** so that I could reuse those objects in the **unit_tests** target to test the private code. However this change is also interesting just to have a more readable code. In the commit 69c0858 you could see that I renamed some files and I move some code from some file to other ones, in such a way that now all the files `xxx_int.hpp` have a match with `.cpp` extension. This helps to identify in a better way where the implementation code is, and also it improve the code navigation experience in most of the editors/IDEs. I am still thinking if I should remove the OBJECT library approach (afcdd6b) ... opinions ?
2. The second important change is about exporting all the library symbols when we enable the compilation of the unit tests. This seems to be the only way we have to test the internal code of the **exiv2lib**. You can find more details about the problem that I found when I was trying to use the OBJECT library in the details of the latest commit: 916b454. This change would make us require the usage of CMake 3.3 for running the unit tests.

### CODE REVIEW

**Comment by D4N** [comment]
You can drop the first two commits with `git rebase -i HEAD~5`, see [stackoverflow](https://stackoverflow.com/questions/1338728/delete-commits-from-a-branch-in-git/1338758#1338758) for a more detailed explanation.

Now to the actual changes:
- I am against increasing the minimum required CMake version again. It is already impossible to build the master branch of exiv2 or 0.26 on CentOS 7, this PR makes it impossible to build on the Ubuntu version that Travis is using. These distributions are going to stick around for a long time (at least CentOS7 until 2025), so I wouldn't require it on Linux as we do not need most of the features anyway of CMake.
- I don't understand why you are moving the files around, beside making it more obvious what implements a public interface and what a private one. But everything that belongs to the public interface goes under `include/exiv2/` so that distinction is pretty clear to be honest.

Maybe this does not work with CMake, but wouldn't it be an option to compile the unit tests and link them with all the object files that got created during the compilation of `libexiv2`? Then we wouldn't have to worry about exporting all symbols on Windows and we could keep the cmake version lower. Also, as long as link time optimization is disabled and the object files are build with `-fPIC` the result should be the same as if the unit tests were linked against libexiv2.

**Comment by piponazo** [comment]
I did not want to update the CMake version either but I found the **CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS** new CMake feature very convenient and I decided to give it a try. 

I agree with you in which we should not update the CMake requirements often. I will try to find another solution to this issue. However I have been lately thinking about this ... maybe we could still support the **autotools** configuration system for compiling the library and application in old platforms. Then, we (developers) could use all the nice new CMake features for the development of the library. I will create an issue for discussing about this. 

I want to make clear that it is easy to make this to work on Linux/Mac, but I am having problems with Visual Studio on Windows. I tried to use directly the private **OBJECT** library (exiv2lib_int) in the **unit_tests** targets, but the private objects have dependencies on the public symbols (circular dependency) and therefore it is impossible to test the private code with that approach with the current design of the library (I can paste here the linker error messages that I am getting later). Apparently the `-fPIC` option only exists for gcc/clang. 

Maybe I can reuse all the object files of **exiv2lib** for the **unit_tests**, but then I need to duplicate a lot of CMake code to handle all the directories inclusions and libraries dependencies.

**Comment by D4N** [comment]
I see, we have basically an impossible problem: we need a newer cmake for windows but cannot have the new version because that would drop support for many Linux distributions. I also don't think that we should keep autotools around, I don't know anything about autotools and the config files are beyond me (also it uses libtool, which I neither know anything about), thus I don't want to maintain them.

I have an insane suggestion: how about we create a build system for our build system? It sounds dirty and wrong, but I don't see another way. We could keep a few very small files with platform specific configs (that would be the minimum required cmake version) around and the rest which is independent which we would the concatenate. That could be done with a simple invocation of 'cat' or with Python if Windows doesn't have something similar to cat.

It sounds terrible but I think some distros are currently doing this with our source anyway. They basically patch the cmake files so that a lower version is required, which would be comparable to my suggestion. We can of course also provide patch files for each platform.

What do you think?

**Comment by clanmills** [comment]
I'm happy to maintain ./configure and MSVC during 2018.

I'm rather concerned about the talk about removing the ./configure and MSVC build environments and replacing them with only CMake (and now we are discussing modified/special CMake).  We've been successfully building the code with ./configure and MSVC for years.  CMake/Visual Studio has required a lot of support and effort, however it does work.  We're now saying "kill the old" and "script our way" around the new.  It doesn't feel right.

**Comment by piponazo** [comment]
In my case I have some experience with autotools, and even when I would like to completely drop it support to just maintain one configuration system (CMake), I think that if we drop it, we might affect to some users or linux distributions.

I want to take a look to the current autotools code, maybe it is not very difficult to maintain for the changes that we want to address in the C++ code. I would prefer to maintain for some time the autotools code rather than inventing our own build system. 

Maybe we should ask ourselves : what are the real user scenarios we want to cover with the build system ? These are some of the thoughts I had about it: 

- In **windows** it is difficult or impossible to use the autotools. There we have to rely on CMake or in the existing Visual Studio solutions (that I will not maintain either). Since windows does not provide CMake in the default installation, users will need to install it manually. Therefore, it should not be a big topic to require a higher version of CMake here.
- **Old linux distributions**: They are currently providing old versions of Exiv2 that were probably built using the autotools or the CMake version use until now. I do not think these distros will update to the future versions of Exiv2. I think we do not need to worry about that.
- **Modern/future linux distributions**: Most of them provide recent versions of CMake (example: Ubuntu 16.04 has CMake 3.5.1). In the case, they do not have a recent enough version, they can always fall back to the autotools system for building the library and application. And anyways, users/developers can always install more recent versions of CMake living together with the cmake system package. 

Maybe I am missing something. Honestly I do not know how the linux distributions compile the different packages. But I think that if we keep working the autotools code for the basic stuff, we can make our lives easier using modern CMake stuff.

**Comment by clanmills** [comment]
I'm agreeing with everything you have said.  And I am offering to continue to support ./configure and MSVC during 2018.   We should be 100% certain that CMake is a total replacement for the older build systems.

**Comment by D4N** [comment]
My 2cents concerning the build system:

I agree in most points. Windows users have to install cmake manually or use the vcproj files (which I will neither maintain, as I have no Windows machine), same goes for Mac users. Modern Linux distributions have a recent enough cmake for that not being a problem.

I disagree concerning the old Linux distros. Yes, most are probably not going to upgrade, but RHEL 7 for instance wants to update exiv2 from 0.23 to 0.26. RHEL 7 is also going to stay around until 2025 and they are using cmake to build exiv2.

Also, it'll be harder for devs who are rolling out a more recent version of exiv2 on a server with an older distro (debian, RHEL, Ubuntu LTS), since installing cmake manually can range from complicated to impossible (it depends on curl, expat, jsoncpp, libc, libc++, zlib, ... imagine one of these is too old on your target system). It's already impossible to build an unpatched exiv2 on CentOS7 with cmake.

Personally, I have mainly two problems with this:
1. We drop support for a platform I care about & that I want to use for development.
2. We decided to not move to C++11 yet as that would drop support for old compilers still in use, but now we drop support for platforms still in use.

I think we can get out of this mess by simply keeping the new version requirements confined to the Windows & Mac platform and providing a `old_cmake.patch` that will remove all these requirements. This would also make life easier for the Linux package maintainers.

**Comment by D4N** [comment]
I have though a little bit more about the matter and reconsidered the matter. I think we can bump the cmake version as a) you are right that we probably won't cut off many devs and b) windows builds will be extremely tedious without it. Clinging to the old cmake version will probably cause more harm than good.

However, I'd like to propose that we try to keep the "core" (= everything required to build libexiv2.so & exiv2) of the build system as backwards compatible as possible, so that a package maintainer could easily patch the "new stuff" away but will still use essentially the same build system as we do.

**Review by Kicer86 — APPROVED** [review]

**Review by Kicer86 — APPROVED** [review]

**Comment by piponazo** [comment]
@D4N Thanks for your feedback. I think what you proposed is a good approach. We can keep the minimum required version as low as possible so that the **exiv2lib** and **exiv2** app can be compiled. Then, if a developer (or CI machines) has a higher version of CMake, they can use the the "advanced" stuff :+1: 

I will fix try to fix the problems in this branch.

**Pull request merged**
